### ISSUE TITLE
Can't access web ui

### ISSUE THREAD

**Issue by 6MH89F3j** [hoobs-org/HOOBS#1028]
**Description**
I messed up my Hoobs install by trying to update node. Now I can't access the web ui. I am able to SSH in.

**Version**
3.3.2 I think. I just updated to the latest yesterday (1/13/21).

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

I upgraded from 3.3.1 to 3.3.2, but I don't think that caused my issue.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes, I was using version 2, and regularly upgrade to the latest releases
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

ring
sony audio
robot roomba
dummy switches
lg webos

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
Started HOOBS.
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js',
'/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js',
'/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js',
'/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js',
'/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js',
'/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
]
}
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
throw outerError;
^
Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 105.
Stopped HOOBS.
```

**Additional context**
I know I screwed up the box. I have plenty of backups. I just want a way to reset it so I can start over.

I tried the following command to reset it, but doesn't seem to be working:
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset`

I just get the following

Reseting device

Connection to hoobs.local closed by remote host.
Connection to hoobs.local closed.

And when I try to log back in, I still see the same issue as above when running 'sudo hoobs service log'

**Comment by 6MH89F3j** [comment]
Oops, just noticed Im having the same issue as: #1025

**Comment by 6MH89F3j** [comment]
Ahh, I should have kept reading through the issues before posting. I ended up finding this and it worked for me. SSH in and run the following commands one after another:

sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
