### ISSUE TITLE
HOOBS Shutting down due to SIGTERM error in Harmony plugin

### ISSUE THREAD

**Issue by andresmakesgames** [hoobs-org/HOOBS#1031]
**Description**
I'm seeing HOOBS call out a SIGTERM error and unexpectedly shutting down the service on a regular basis, due to our Harmony Hub's socket getting disconnected.

**Expected behavour**
I expect it to, at the very least, gracefully recover from Harmony's socket disconnecting and try to periodically reconnect on an interval, instead of shutting down the HOOBS service entirely.

**Plugin name**
homebridge-harmony

**Please report the issue to the plugin developer**
It is noted on the developer's Github that they don't support HOOBS compatibility, and a rep from HOOBS directs people to this Github page instead.

**Version**
HOOBS 3.3.1, homebridge-harmony 1.4.1 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
I'm not entirely sure what version we started on, but I believe the issue has been present since we installed the plugin.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
- [ X] No

**What device are you using?**
- [X ] HOOBS Box

**If this is a custom install, what's your operating system?**
N/A

**Post your config**
* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 60,
        "home_setup_id": "X-HM://0023ISYWYB7K1",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "78727"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "REDACTED",
        "username": "REDACTED"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "TVAccessory": true,
            "publishAllTVAsExternalAccessory": false,
            "mainActivity": "Watch TV",
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": false,
            "name": "Harmony Hub",
            "hubName": "Harmony Hub",
            "cleanCache": true,
            "showTurnOffActivity": "0",
            "showCommandsAtStartup": false,
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "linkVolumeControlToTV": true
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "access_token": "REDACTED"
        },
        {
            "platform": "NeatoVacuumRobot",
            "plugin_map": {
                "plugin_name": "homebridge-neato"
            },
            "email": "REDACTED",
            "password": "REDACTED"
        },
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "name": "Home Alarm",
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "auth": {
                "username": "REDACTED",
                "password": "REDACTED"
            },
            "cameraOptions": {
                "enableHwaccelRpi": true
            }
        }
    ]
}
```

**Post your log**

```
1/15/2021, 6:36:35 PM [Harmony Hub] (Harmony Hub)WARNING - socket closed
1/15/2021, 6:36:45 PM [Harmony Hub] INFO - starting hub discovery
1/15/2021, 6:36:46 PM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running at healthCheck (dgram.js:902:11) at Socket.send (dgram.js:627:3) at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)
1/15/2021, 6:36:46 PM Got SIGTERM, shutting down Bridge...
1/15/2021, 6:36:46 PM [Harmony Hub] INFO - shutdown
1/15/2021, 6:36:46 PM [Harmony Hub] INFO - shutdown
1/15/2021, 6:36:47 PM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running at healthCheck (dgram.js:902:11) at Socket.send (dgram.js:627:3) at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)
1/15/2021, 6:36:48 PM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running at healthCheck (dgram.js:902:11) at Socket.send (dgram.js:627:3) at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)
1/15/2021, 6:36:49 PM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running at healthCheck (dgram.js:902:11) at Socket.send (dgram.js:627:3) at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)
```

**Additional context**
I am not sure why Harmony keeps losing its socket connection. It may be related to our router, which I believe is one of the allegedly undesirable Puma chipsets provided by Spectrum. That said, it should not be causing HOOBS to shut down the HOOBS service. The Harmony hub getting periodically disconnected is a minor inconvenience. The entire HOOBS service shutting down is a very aggravating experience.

**Comment by andresmakesgames** [comment]
This is still happening on latest. Is anyone maintaining this repo?
