### ISSUE TITLE
Trouble accessing Hoobs browser interface

### ISSUE THREAD

**Issue by runningfool20** [hoobs-org/HOOBS#1033]
Complete noob here.

Having difficulty accessing Hoobs web interface. hoobs.local and local IP address only lead to "This site can't be reached" error pages. Was having difficulty with the Ring plugin, someone somewhere suggested updating a "node". So I think I tried that, but after reboot of the Hoobs box, things no longer work. Am I completely out of luck?

I am able to run commands in MacOS terminal and ran a command for a service log.

Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 148.
Stopped HOOBS.
Started HOOBS.

**Comment by bwp91** [comment]
https://github.com/hoobs-org/HOOBS/issues/1019#issuecomment-759297684
