### ISSUE TITLE
Unable to login to the UI, also doesn't show anymore in Homekit

### ISSUE THREAD

**Issue by AmeMeEternamen** [hoobs-org/HOOBS#1045]
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
 Mac
**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

MyQ, Ring

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```
hoobs@hoobs:/$ SSH cat ~/.hoobs/etc/config.json
-bash: SSH: command not found
hoobs@hoobs:/$ SSH `cat ~/.hoobs/etc/config.json
**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```
*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://10.95.1.62
* http://10.95.1.86

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Jan 22 14:08:46 2021 from fe80::1c33:a765:b172:a2f7%eth0
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$ sudo hoobs service log
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 104.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 105.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 106.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 107.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 108.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 109.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 110.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 111.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 112.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 113.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 114.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 115.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 116.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 117.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 118.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 119.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 120.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 121.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 122.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 123.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 124.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.

**Additional context**

**Comment by EddieDSuza** [comment]
Login via ssh with user: hoobs and password: hoobsadmin
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local
Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin
On Windows, use Putty with the same credentials as above.

Then run this command to reset the HOOBS Box:
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset
