### ISSUE TITLE
Trouble installing Hoobs on Mac mini

### ISSUE THREAD

**Issue by hermsdad** [hoobs-org/HOOBS#1093]
I have an old mac mini with High Sierra. I was able to get the old Xcode (10.1) from the developer site. Got it installed and then installed Node.JS LTS. And then installed Hoobs. But I can't seem to get Hoobs to run. I tried the following at the command line: hoobs -p 'my user pwd' with that obviously being the user's pwd that I'm logged into on the mac (admin). I also edited sudoers so I wouldn't need a pwd using sudo visudo and adding NOPASSWD: to the %admin line. I then try just hoobs at the command line. I get the following error:
Calvin:~ calvin$ hoobs
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.

It seems to be installed but there seems to be some configuration messed up somewhere. Anybody have any idea? Any help is greatly appreciated. I am just comfortable enough with coding but i am no expert. As in I need explicit command line help. 
Thanks.

**Comment by hermsdad** [comment]
I figured out the problem for those of you interested. the initial start for hoobs wants to start on port 80. port 80 is locked to non-root users. My solution was to log into the root user on mac and start hoobs. Others have mentioned changing the hoobs config file through the terminal. Because obviously you can't use the GUI because you can't get hoobs to start. You can't use any port below 1024 unless its with root user. 

Also wanted to point out that the install instructions can be dangerous. if you are going to edit sudoer make sure to type in "sudo visudo" That is it. Don't type "sudo nano /etc/sudoers" that will screw up sudoer and make it useless. visudo is not the most intuitive editor. Look up instructions on how to use it or to even change it to the nano editor but under visudo. visudo will make sure you don't end up with broken sudoer file. 

Somebody should probably update the wiki to reflect these important install notes for a Mac Os X install.

I now have Hoobs working no problem. Wish I had known this from the beginning. I'm sure a more skilled programmer would have spotted this issue right away. But for us noobs it's not so obvious.
