### ISSUE TITLE
Error at installing the plugin Fritz Platform

### ISSUE THREAD

**Issue by MasterofKungfu9999** [hoobs-org/HOOBS#1110]
**Description**
The Fritz Platform Plugin provides the data of the FRITZ!Box Router
**Expected behavoir**
Please let us know what the plugin is supposed to do.

**Plugin name**
Fritz Platform

**Please report the issue to the plugin developer**
The Developer says its an issue of hoobs 

**Version**
3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
ERR! notarget No matching version found for homebridge-fritz-platform@5.0.21.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
26.2.2021, 12:40:49 -
26.2.2021, 12:40:49 - npm ERR! A complete log of this run can be found in:
npm ERR! /home/hoobs/.npm/_logs/2021-02-26T11_40_49_152Z-debug.log

Here ist the log:

0 verbose cli [
0 verbose cli '/usr/local/bin/node',
0 verbose cli '/usr/local/bin/npm',
0 verbose cli 'install',
0 verbose cli '--prefer-offline',
0 verbose cli '--no-audit',
0 verbose cli '--unsafe-perm',
0 verbose cli '--progress=true',
0 verbose cli 'homebridge-fritz-platform@5.0.21'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v14.15.5
3 timing config:load:defaults Completed in 4ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 6ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/hoobs/.hoobs/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/hoobs/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 2ms
13 timing config:load:global Completed in 2ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 24ms
19 verbose npm-session 96238d5ded1aed04
20 timing npm:load Completed in 42ms
21 timing arborist:ctor Completed in 2ms
22 timing idealTree:init Completed in 446ms
23 timing idealTree:userRequests Completed in 6ms
24 silly idealTree buildDeps
25 silly fetch manifest homebridge-fritz-platform@5.0.21
26 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
27 http fetch GET 200 https://registry.npmjs.org/homebridge-fritz-platform 52ms (from cache)
28 silly placeDep ROOT homebridge-fritz-platform@ OK for: @hoobs/hoobs@3.3.2 want: 5.0.21
29 timing idealTree:#root Completed in 76ms
30 timing idealTree:node_modules/homebridge-fritz-platform Completed in 0ms
31 timing idealTree:buildDeps Completed in 79ms
32 timing idealTree:fixDepFlags Completed in 9ms
33 timing idealTree Completed in 544ms
34 timing command:install Completed in 558ms
35 verbose type version
36 verbose stack homebridge-fritz-platform: No matching version found for homebridge-fritz-platform@5.0.21.
36 verbose stack at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:207:23)
36 verbose stack at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:26
36 verbose stack at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:888:19)
36 verbose stack at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:836:11)
36 verbose stack at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
36 verbose stack at async Promise.all (index 1)
36 verbose stack at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
36 verbose stack at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
37 verbose cwd /home/hoobs/.hoobs
38 verbose Linux 4.19.75-v7l+
39 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-fritz-platform@5.0.21"
40 verbose node v14.15.5
41 verbose npm v7.6.0
42 error code ETARGET
43 error notarget No matching version found for homebridge-fritz-platform@5.0.21.
44 error notarget In most cases you or one of your dependencies are requesting
44 error notarget a package version that doesn't exist.
45 verbose exit 1


```

**Additional context**

**Comment by askovi** [comment]
I just installed the plugin and it works fine (v5.0.25). How are you trying to install the plugin? Make sure to use the UI.

**Comment by MasterofKungfu9999** [comment]
I'm using the UI.

But my node Version is 14.15.5. Is there an issue with this version?

**Comment by MasterofKungfu9999** [comment]
Updating hoobs to version 3.3.3 brings no improvement
