### ISSUE TITLE
Can't access UI 

### ISSUE THREAD

**Issue by ghofmann1** [hoobs-org/HOOBS#1115]
**Description**

UI serves up 'cant connect to server" always. 

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [X ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE


```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
Last login: Mon Mar  1 10:22:13 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Georginas-MacBook-Pro:~ georginahofmann$ ssh hoobs@hoobs.local
hoobs@hoobs.local's password: 
Permission denied, please try again.
hoobs@hoobs.local's password: 
Linux hoobs 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l
Raspberry Pi 3 Model B Rev 1.2


*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://10.0.1.70


HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
hoobs@hoobs:~ $ sudo hoobs service log
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 166.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:307
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs/backups'
    at Object.mkdirSync (fs.js:987:3)
    at Object.module.exports.makeDirSync (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/fs-extra/lib/mkdirs/make-dir.js:101:15)
    at checksum (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:180:10)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:40:68)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs/backups'```

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
What version of Node are you running?
Run this command
```
node -v
```
