### ISSUE TITLE
Unable to access Hoobs 

### ISSUE THREAD

**Issue by AmeMeEternamen** [hoobs-org/HOOBS#1136]
Hello,

I am unable to access my Hoobs, via the 192.162.1.1, or either hoops.local. I have been able to access it thru SSH login

I am unable to use the hoobs device for anything at all

Help

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Franklins-MBP:~ franklindowning-seldon$ ssh hoobs@hoobs.local
hoobs@hoobs.local's password: 
Linux hoobs 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l
Raspberry Pi 3 Model B Plus Rev 1.3

*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.1.62
* http://10.0.0.105
* http://[2601:703:105:bc40::5006]
* http://[2601:703:105:bc40:86b0:80b4:f84b:ca09]

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Mar 12 10:19:19 2021 from 192.168.1.138
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$ sudo npm install -g --unsafe-perm @hoobs/hoobs
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> @hoobs/hoobs@3.3.3 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

+ @hoobs/hoobs@3.3.3
added 7 packages from 8 contributors, removed 1 package and updated 27 packages in 58.471s
hoobs@hoobs:/$ 

Service Log

Last login: Fri Mar 12 12:19:03 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Franklins-MBP:~ franklindowning-seldon$ ssh hoobs@hoobs.local
hoobs@hoobs.local's password: 
Linux hoobs 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l
Raspberry Pi 3 Model B Plus Rev 1.3

*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.1.62
* http://10.0.0.105
* http://[2601:703:105:bc40::5006]
* http://[2601:703:105:bc40:86b0:80b4:f84b:ca09]

HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Mar 12 10:19:19 2021 from 192.168.1.138
Could not chdir to home directory /home/hoobs: No such file or directory
hoobs@hoobs:/$ sudo npm install -g --unsafe-perm @hoobs/hoobs
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs

> @hoobs/hoobs@3.3.3 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

+ @hoobs/hoobs@3.3.3
added 7 packages from 8 contributors, removed 1 package and updated 27 packages in 58.471s
hoobs@hoobs:/$ sudo hoobs service log
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 93.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 94.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 95.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 96.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 97.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 98.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 99.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 100.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 101.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 102.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 103.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 104.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 105.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 106.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 107.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 108.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 109.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 110.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 111.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 112.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 113.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 114.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs'
    at Object.mkdirSync (fs.js:987:3)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:35:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.

**Comment by mkellsy** [comment]
Run this and see if it comes back
```
sudo npm uninstall @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

After that complets
```
sudo systemctl restart hoobs.service
```

**Comment by mkellsy** [comment]
The last command simply restarts the hoobs service. There shouldn't be any output. It only shows errors.

**Comment by AmeMeEternamen** [comment]
issue is still nor resolved

**Comment by mkellsy** [comment]
Node isn't finding main.js. you may have corruption on the card. We tried to reinstall HOOBS and that worked. So I think you may have to re-flash the sd card with a fresh image.
