### ISSUE TITLE
HOOBS 3.3.5

### ISSUE THREAD

**Issue by Stewart06** [hoobs-org/HOOBS#1154]
15/03/2021 à 22:40:16 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 9329f589-c80c-4d49-bc93-d5e12eb4cabd
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
15/03/2021 à 22:40:16 Got SIGTERM, shutting down Bridge...
15/03/2021 à 22:40:16 [Apple TV Platform] Shutting down Apple TV clients...

**Comment by Stewart06** [comment]
La version 3.3.4 fonctionné, j'ai voulu mettre à jour vers la version 3.3.5 et maintenant l'instance s'arrête après le démarrage du service HOOBS !

**Comment by Stewart06** [comment]
Vite un correctif s'il vous plait !!!

**Comment by mkellsy** [comment]
Delete the accessory cache.
```
rm -fR ~/.hoobs/etc/accessories
```

Version 3.3.4 caused corruption in the accessory cache.
Fixed in 3.3.5.

Sorry for the inconvenience.

**Comment by e1l52** [comment]
I was able to fix the 3.3.4 issues with upgrading to 3.3.5 and deleting the accessory cache.
Thanks a lot for the help.
Unfortunately I lost again most device names, room settings etc. and had to re-setup my HomeKit installation again.
But now it survives a HOOBS reboot.
