### ISSUE TITLE
Bridge Service Fails to Start after updating to 3.3.5

### ISSUE THREAD

**Issue by krakenbait** [hoobs-org/HOOBS#1155]
**Description**
I recently updated my hoobs in a box from 3.3.4 to 3.3.5 and I can't seem to get the bridge service to start running again. I updated node.js to be sure as well. I'm fairly inexperienced with code so if there's something glaringly obvious I apologize. I just can't seem to figure it out on my own. 

**Version**
Please include the version of HOOBS you are using.
3.3.5
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.3.4
**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

I'm not really sure how to answer this question. 

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Dyson PureCool
myQ
Pihole
Simplisafe3
Xiaomi Roborock Vacuum

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYN78J",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "xxxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxx-xx-xxx",
        "username": "xxxxxxxxxxx"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-dyson-pure-cool",
        "homebridge-myq",
        "homebridge-simplisafe3",
        "homebridge-pihole",
        "homebridge-xiaomi-roborock-vacuum"
    ],
    "accessories": [
        {
            "accessory": "Pihole",
            "plugin_map": {
                "plugin_name": "homebridge-pihole",
                "index": 0
            },
            "name": "Pihole",
            "ssl": false,
            "rejectUnauthorized": true,
            "host": "localhost",
            "port": 80,
            "baseDirectory": "/admin/",
            "time": 0,
            "reversed": false,
            "logLevel": 1,
            "auth": "xxxxxxxxxxxxxx"
        },
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "homebridge-xiaomi-roborock-vacuum",
                "index": 0
            },
            "name": "Roborock S5",
            "waterBox": false,
            "silent": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": true,
            "delay": false,
            "cleanword": "clean",
            "roomTimeout": 0,
            "autoroom": false,
            "token": "xxxxxxxxxxxxxxxxxx",
            "ip": "192.168.7.30"
        }
    ],
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-dyson-pure-cool"
            },
            "username": "xxxxxxxxxx",
            "password": "xxxxxxxxxxx",
            "countryCode": "US",
            "devices": [
                {
                    "ipAddress": "192.168.7.28",
                    "serialNumber": "VS7-US-KNA0379A",
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false
                }
            ]
        },
        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "email": "xxxxxxxxx",
            "password": "xxxxxxxxxx"
        },
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "name": "Home Alarm",
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "auth": {
                "username": "xxxxxxxxx",
                "password": "xxxxxxx"
            },
            "cameraOptions": {
                "enableHwaccelRpi": true
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
3/15/2021, 5:38:11 PM HOOBS listening on port 80.
3/15/2021, 5:38:15 PM Initializing HAP-NodeJS v0.9.3...
3/15/2021, 5:38:20 PM Loaded plugin 'homebridge-dyson-pure-cool'
3/15/2021, 5:38:21 PM [3/15/2021, 5:38:20 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
3/15/2021, 5:38:21 PM Loaded plugin 'homebridge-myq'
3/15/2021, 5:38:21 PM [3/15/2021, 5:38:21 PM] Registering platform 'homebridge-myq.myQ'
3/15/2021, 5:38:21 PM Loaded plugin 'homebridge-pihole'
3/15/2021, 5:38:21 PM [3/15/2021, 5:38:21 PM] Registering accessory 'homebridge-pihole.Pihole'
3/15/2021, 5:38:22 PM Loaded plugin 'homebridge-simplisafe3'
3/15/2021, 5:38:22 PM [3/15/2021, 5:38:22 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
3/15/2021, 5:38:24 PM Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
3/15/2021, 5:38:24 PM Loading 3 platforms...
3/15/2021, 5:38:24 PM [3/15/2021, 5:38:24 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
3/15/2021, 5:38:24 PM [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
3/15/2021, 5:38:24 PM [myQ] Initializing myQ platform...
3/15/2021, 5:38:24 PM [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
3/15/2021, 5:38:25 PM Loading 2 accessories...
3/15/2021, 5:38:25 PM [Pihole] Initializing Pihole accessory...
3/15/2021, 5:38:25 PM [Roborock S5]] Initializing XiaomiRoborockVacuum accessory...
3/15/2021, 5:38:25 PM Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c53fc86d-07b6-4952-9a90-7c2506882e05
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
3/15/2021, 5:38:25 PM Got SIGTERM, shutting down Bridge...
3/15/2021, 5:38:26 PM [Roborock S5] STA getDevice | Connected to: 192.168.7.18
3/15/2021, 5:38:26 PM [Roborock S5] STA getDevice | Model: roborock.vacuum.s5
3/15/2021, 5:38:26 PM [Roborock S5] STA getDevice | State: charging
3/15/2021, 5:38:26 PM [Roborock S5] STA getDevice | FanSpeed: 104
3/15/2021, 5:38:26 PM [Roborock S5] STA getDevice | BatteryLevel: 100
3/15/2021, 5:38:26 PM [Roborock S5] INF getSerialNumber | roborock.vacuum.s5 | Serial Number is R0028S76503425
3/15/2021, 5:38:26 PM [Roborock S5] STA getDevice | Serialnumber: R0028S76503425
3/15/2021, 5:38:26 PM [Roborock S5] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.8_002034
3/15/2021, 5:38:26 PM [Roborock S5] STA getDevice | Firmwareversion: 3.5.8_002034
3/15/2021, 5:38:26 PM [Roborock S5] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
3/15/2021, 5:38:26 PM [Roborock S5] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
3/15/2021, 5:38:26 PM [Roborock S5] INF changedCharging | roborock.vacuum.s5 | Charging is active
3/15/2021, 5:38:26 PM [Roborock S5] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
3/15/2021, 5:38:26 PM [Roborock S5] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 104%
3/15/2021, 5:38:26 PM [Roborock S5] INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 104% (Max), for HomeKit 100%
3/15/2021, 5:39:00 PM Initializing HAP-NodeJS v0.9.3...
3/15/2021, 5:39:04 PM Loaded plugin 'homebridge-dyson-pure-cool'
3/15/2021, 5:39:05 PM [3/15/2021, 5:39:04 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
3/15/2021, 5:39:05 PM Loaded plugin 'homebridge-myq'
3/15/2021, 5:39:05 PM [3/15/2021, 5:39:05 PM] Registering platform 'homebridge-myq.myQ'
3/15/2021, 5:39:05 PM Loaded plugin 'homebridge-pihole'
3/15/2021, 5:39:05 PM [3/15/2021, 5:39:05 PM] Registering accessory 'homebridge-pihole.Pihole'
3/15/2021, 5:39:06 PM Loaded plugin 'homebridge-simplisafe3'
3/15/2021, 5:39:06 PM [3/15/2021, 5:39:06 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
3/15/2021, 5:39:07 PM Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
3/15/2021, 5:39:07 PM Loading 3 platforms...
3/15/2021, 5:39:07 PM [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
3/15/2021, 5:39:07 PM [3/15/2021, 5:39:07 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
3/15/2021, 5:39:07 PM [myQ] Initializing myQ platform...
3/15/2021, 5:39:07 PM [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
3/15/2021, 5:39:07 PM Loading 2 accessories...
3/15/2021, 5:39:07 PM [Pihole] Initializing Pihole accessory...
3/15/2021, 5:39:07 PM [Roborock S5]] Initializing XiaomiRoborockVacuum accessory...
3/15/2021, 5:39:08 PM Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c53fc86d-07b6-4952-9a90-7c2506882e05
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
3/15/2021, 5:39:08 PM Got SIGTERM, shutting down Bridge...
3/15/2021, 5:39:10 PM [Roborock S5] STA getDevice | Connected to: 192.168.7.18
3/15/2021, 5:39:10 PM [Roborock S5] STA getDevice | Model: roborock.vacuum.s5
3/15/2021, 5:39:10 PM [Roborock S5] STA getDevice | State: charging
3/15/2021, 5:39:10 PM [Roborock S5] STA getDevice | FanSpeed: 104
3/15/2021, 5:39:10 PM [Roborock S5] STA getDevice | BatteryLevel: 100
3/15/2021, 5:39:10 PM [Roborock S5] INF getSerialNumber | roborock.vacuum.s5 | Serial Number is R0028S76503425
3/15/2021, 5:39:10 PM [Roborock S5] STA getDevice | Serialnumber: R0028S76503425
3/15/2021, 5:39:10 PM [Roborock S5] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.8_002034
3/15/2021, 5:39:10 PM [Roborock S5] STA getDevice | Firmwareversion: 3.5.8_002034
3/15/2021, 5:39:10 PM [Roborock S5] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
3/15/2021, 5:39:10 PM [Roborock S5] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
3/15/2021, 5:39:10 PM [Roborock S5] INF changedCharging | roborock.vacuum.s5 | Charging is active
3/15/2021, 5:39:10 PM [Roborock S5] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
3/15/2021, 5:39:10 PM [Roborock S5] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 104%
3/15/2021, 5:39:10 PM [Roborock S5] INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 104% (Max), for HomeKit 100%
3/15/2021, 5:39:32 PM Initializing HAP-NodeJS v0.9.3...
3/15/2021, 5:39:35 PM Loaded plugin 'homebridge-dyson-pure-cool'
3/15/2021, 5:39:36 PM [3/15/2021, 5:39:35 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
3/15/2021, 5:39:36 PM Loaded plugin 'homebridge-myq'
3/15/2021, 5:39:36 PM [3/15/2021, 5:39:36 PM] Registering platform 'homebridge-myq.myQ'
3/15/2021, 5:39:36 PM Loaded plugin 'homebridge-pihole'
3/15/2021, 5:39:36 PM [3/15/2021, 5:39:36 PM] Registering accessory 'homebridge-pihole.Pihole'
3/15/2021, 5:39:37 PM Loaded plugin 'homebridge-simplisafe3'
3/15/2021, 5:39:37 PM [3/15/2021, 5:39:37 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
3/15/2021, 5:39:38 PM Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
3/15/2021, 5:39:38 PM Loading 3 platforms...
3/15/2021, 5:39:38 PM [3/15/2021, 5:39:38 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
3/15/2021, 5:39:38 PM [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
3/15/2021, 5:39:38 PM [myQ] Initializing myQ platform...
3/15/2021, 5:39:38 PM [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
3/15/2021, 5:39:38 PM Loading 2 accessories...
3/15/2021, 5:39:38 PM [Pihole] Initializing Pihole accessory...
3/15/2021, 5:39:38 PM [Roborock S5] Initializing XiaomiRoborockVacuum accessory...
3/15/2021, 5:39:39 PM Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c53fc86d-07b6-4952-9a90-7c2506882e05
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
3/15/2021, 5:39:39 PM Got SIGTERM, shutting down Bridge...
3/15/2021, 5:39:43 PM [Roborock S5] STA getDevice | Connected to: 192.168.7.18
3/15/2021, 5:39:43 PM [Roborock S5] STA getDevice | Model: roborock.vacuum.s5
3/15/2021, 5:39:43 PM [Roborock S5] STA getDevice | State: charging
3/15/2021, 5:39:43 PM [Roborock S5] STA getDevice | FanSpeed: 104
3/15/2021, 5:39:43 PM [Roborock S5] STA getDevice | BatteryLevel: 100
3/15/2021, 5:39:43 PM [Roborock S5] INF getSerialNumber | roborock.vacuum.s5 | Serial Number is R0028S76503425
3/15/2021, 5:39:43 PM [Roborock S5] STA getDevice | Serialnumber: R0028S76503425
3/15/2021, 5:39:43 PM [Roborock S5] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.8_002034
3/15/2021, 5:39:43 PM [Roborock S5] STA getDevice | Firmwareversion: 3.5.8_002034
3/15/2021, 5:39:43 PM [Roborock S5] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
3/15/2021, 5:39:43 PM [Roborock S5] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
3/15/2021, 5:39:43 PM [Roborock S5] INF changedCharging | roborock.vacuum.s5 | Charging is active
3/15/2021, 5:39:43 PM [Roborock S5] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
3/15/2021, 5:39:43 PM [Roborock S5] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 104%
3/15/2021, 5:39:43 PM [Roborock S5] INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 104% (Max), for HomeKit 100%
3/15/2021, 5:49:27 PM Initializing HAP-NodeJS v0.9.3...
3/15/2021, 5:49:31 PM Loaded plugin 'homebridge-dyson-pure-cool'
3/15/2021, 5:49:31 PM [3/15/2021, 5:49:31 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
3/15/2021, 5:49:32 PM Loaded plugin 'homebridge-myq'
3/15/2021, 5:49:32 PM [3/15/2021, 5:49:32 PM] Registering platform 'homebridge-myq.myQ'
3/15/2021, 5:49:32 PM Loaded plugin 'homebridge-pihole'
3/15/2021, 5:49:32 PM [3/15/2021, 5:49:32 PM] Registering accessory 'homebridge-pihole.Pihole'
3/15/2021, 5:49:33 PM Loaded plugin 'homebridge-simplisafe3'
3/15/2021, 5:49:33 PM [3/15/2021, 5:49:33 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
3/15/2021, 5:49:34 PM Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
3/15/2021, 5:49:34 PM Loading 3 platforms...
3/15/2021, 5:49:34 PM [3/15/2021, 5:49:34 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
3/15/2021, 5:49:34 PM [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
3/15/2021, 5:49:34 PM [myQ] Initializing myQ platform...
3/15/2021, 5:49:34 PM [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
3/15/2021, 5:49:34 PM Loading 2 accessories...
3/15/2021, 5:49:34 PM [Pihole] Initializing Pihole accessory...
3/15/2021, 5:49:34 PM [Roborock S5] Initializing XiaomiRoborockVacuum accessory...
3/15/2021, 5:49:35 PM Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c53fc86d-07b6-4952-9a90-7c2506882e05
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
3/15/2021, 5:49:35 PM Got SIGTERM, shutting down Bridge...

```

**Additional context**

**Comment by mkellsy** [comment]
Please see https://github.com/hoobs-org/HOOBS/issues/1154

**Comment by krakenbait** [comment]
> Please see #1154

Thanks! I'll close it out.
