### ISSUE TITLE
Major incident after update to 3.3.5 - Service does not start

### ISSUE THREAD

**Issue by dibimuc** [hoobs-org/HOOBS#1160]
**Description**
I just updated to 3.3.5 and Hoobs service will not start. All plug-ins are up-to-date.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
16.3.2021, 12:33:44 HOOBS listening on port 8080.
16.3.2021, 12:33:50 Initializing HAP-NodeJS v0.9.3...
16.3.2021, 12:33:52 Loaded plugin 'homebridge-dummy'
16.3.2021, 12:33:52 [3/16/2021, 5:33:52 AM] Registering accessory 'homebridge-dummy.DummySwitch'
16.3.2021, 12:34:07 Loaded plugin 'homebridge-harmony'
16.3.2021, 12:34:07 [3/16/2021, 5:34:07 AM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
16.3.2021, 12:34:07 [3/16/2021, 5:34:07 AM] The plugin "homebridge-hue" requires Node.js version of ^14.16.0 which does not satisfy the current Node.js version of v12.14.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
16.3.2021, 12:34:12 Loaded plugin 'homebridge-hue'
16.3.2021, 12:34:12 [3/16/2021, 5:34:12 AM] Registering platform 'homebridge-hue.Hue'
16.3.2021, 12:34:12 Loaded plugin 'homebridge-shelly'
16.3.2021, 12:34:14 [3/16/2021, 5:34:14 AM] Registering platform 'homebridge-shelly.Shelly'
16.3.2021, 12:34:15 Loaded plugin 'homebridge-tahoma'
16.3.2021, 12:34:15 homebridge-tahoma API version: 2.7
16.3.2021, 12:34:15 [3/16/2021, 5:34:15 AM] Registering platform 'homebridge-tahoma.Tahoma'
16.3.2021, 12:34:16 Loaded plugin 'homebridge-weather-plus'
16.3.2021, 12:34:16 [3/16/2021, 5:34:16 AM] Registering platform 'homebridge-weather-plus.WeatherPlus'
16.3.2021, 12:34:16 Loading 5 platforms...
16.3.2021, 12:34:16 [Wohnzimmer] Initializing HarmonyHubWebSocket platform...
16.3.2021, 12:34:16 [Wohnzimmer] HarmonyPlatform Init
16.3.2021, 12:34:16 [WeatherPlus] Initializing WeatherPlus platform...
16.3.2021, 12:34:16 [WeatherPlus] Adding station with weather service Dark Sky named 'Now'
16.3.2021, 12:34:16 Initializing platform accessory 'Now'...
16.3.2021, 12:34:16 [My TaHoma Box] Initializing Tahoma platform...
16.3.2021, 12:34:16 [My TaHoma Box] Fetch accessories...
16.3.2021, 12:34:16 [My TaHoma Box] Login TaHoma server...
16.3.2021, 12:34:17 [Shelly] Initializing Shelly platform...
16.3.2021, 12:34:17 [Hue] Initializing Hue platform...
16.3.2021, 12:34:17 [Hue] homebridge-hue v0.13.2, node v12.14.1, homebridge v1.3.3
16.3.2021, 12:34:17 [Hue] config.json: plugin_map: invalid key
16.3.2021, 12:34:17 [Hue] config.json: nupnp: invalid key
16.3.2021, 12:34:17 [Hue] config.json: parallelRequests: invalid key
16.3.2021, 12:34:17 Loading 4 accessories...
16.3.2021, 12:34:17 [Abendessen-Szene] Initializing DummySwitch accessory...
16.3.2021, 12:34:17 [Abendessen-Szene] Setting switch to false
16.3.2021, 12:34:17 [Homeoffice] Initializing DummySwitch accessory...
16.3.2021, 12:34:17 [Homeoffice] Setting switch to false
16.3.2021, 12:34:17 [Chillen-Szene] Initializing DummySwitch accessory...
16.3.2021, 12:34:17 [Chillen-Szene] Setting switch to false
16.3.2021, 12:34:17 [Espressomaschine] Initializing DummySwitch accessory...
16.3.2021, 12:34:17 [Espressomaschine] Setting switch to false
16.3.2021, 12:34:17 [Wohnzimmer] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
16.3.2021, 12:34:19 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7faa2501-af2d-4a67-8770-f696cdc12cc8
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
16.3.2021, 12:34:19 [My TaHoma Box] Unable to refresh states (not logged in)
16.3.2021, 12:34:19 Got SIGTERM, shutting down Bridge...
16.3.2021, 12:34:19 [Wohnzimmer] INFO - shutdown
16.3.2021, 12:34:19 [Wohnzimmer] INFO - shutdown
16.3.2021, 12:34:20 [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
16.3.2021, 12:34:20 [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.42.0
16.3.2021, 12:34:20 [Hue] Philips hue: 17 accessories
16.3.2021, 12:34:20 Initializing platform accessory 'Philips hue'...
16.3.2021, 12:34:20 [Hue] Philips hue: 3 services
16.3.2021, 12:34:20 Initializing platform accessory 'Iris'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Leuchte'...
16.3.2021, 12:34:20 Initializing platform accessory 'Spiegel'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Golden Globe'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Spot'...
16.3.2021, 12:34:20 Initializing platform accessory 'LED Licht'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Strahler'...
16.3.2021, 12:34:20 Initializing platform accessory 'Mond'...
16.3.2021, 12:34:20 [My TaHoma Box] [Alarm] type: Alarm > TSKAlarmController, protocol: internal
16.3.2021, 12:34:20 [My TaHoma Box] Device Alarm ignored
16.3.2021, 12:34:20 [My TaHoma Box] [Box] type: Pod > Pod, protocol: internal
16.3.2021, 12:34:20 [My TaHoma Box] No definition found for Pod > Pod in mapping.json file
16.3.2021, 12:34:20 [My TaHoma Box] [Markise] type: Awning > PositionableHorizontalAwning, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Instanciate Markise as WindowCovering with config {}
16.3.2021, 12:34:20 [My TaHoma Box] [IO (10920801)] type: ProtocolGateway > IOStack, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] No definition found for ProtocolGateway > IOStack in mapping.json file
16.3.2021, 12:34:20 [My TaHoma Box] [Schlafen Gaube] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Device Schlafen Gaube ignored
16.3.2021, 12:34:20 [My TaHoma Box] [Kontor] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Device Kontor ignored
16.3.2021, 12:34:20 [My TaHoma Box] [Wohnzimmer] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Device Wohnzimmer ignored
16.3.2021, 12:34:20 [My TaHoma Box] [Küche] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Device Küche ignored
16.3.2021, 12:34:20 [My TaHoma Box] [Schlafen] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Device Schlafen ignored
16.3.2021, 12:34:20 [My TaHoma Box] [Balkon] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Device Balkon ignored
16.3.2021, 12:34:20 [My TaHoma Box] [Bad] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:34:20 [My TaHoma Box] Device Bad ignored
16.3.2021, 12:34:20 Initializing platform accessory 'Markise'...
16.3.2021, 12:34:21 [HOOBS@Now@Now@Air Pressure] Characteristic not in required or optional characteristic section for service TemperatureSensor. Adding anyway.
16.3.2021, 12:34:24 [Hue] goodbye
16.3.2021, 12:35:45 Initializing HAP-NodeJS v0.9.3...
16.3.2021, 12:35:47 Loaded plugin 'homebridge-dummy'
16.3.2021, 12:35:47 [3/16/2021, 5:35:47 AM] Registering accessory 'homebridge-dummy.DummySwitch'
16.3.2021, 12:35:47 Loaded plugin 'homebridge-harmony'
16.3.2021, 12:35:47 [3/16/2021, 5:35:47 AM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
16.3.2021, 12:35:47 [3/16/2021, 5:35:47 AM] The plugin "homebridge-hue" requires Node.js version of ^14.16.0 which does not satisfy the current Node.js version of v12.14.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
16.3.2021, 12:35:51 Loaded plugin 'homebridge-hue'
16.3.2021, 12:35:51 [3/16/2021, 5:35:51 AM] Registering platform 'homebridge-hue.Hue'
16.3.2021, 12:35:51 Loaded plugin 'homebridge-shelly'
16.3.2021, 12:35:52 [3/16/2021, 5:35:52 AM] Registering platform 'homebridge-shelly.Shelly'
16.3.2021, 12:35:53 Loaded plugin 'homebridge-tahoma'
16.3.2021, 12:35:53 homebridge-tahoma API version: 2.7
16.3.2021, 12:35:53 [3/16/2021, 5:35:53 AM] Registering platform 'homebridge-tahoma.Tahoma'
16.3.2021, 12:35:53 Loaded plugin 'homebridge-weather-plus'
16.3.2021, 12:35:53 [3/16/2021, 5:35:53 AM] Registering platform 'homebridge-weather-plus.WeatherPlus'
16.3.2021, 12:35:53 Loading 5 platforms...
16.3.2021, 12:35:53 [Wohnzimmer] Initializing HarmonyHubWebSocket platform...
16.3.2021, 12:35:53 [Wohnzimmer] HarmonyPlatform Init
16.3.2021, 12:35:53 [WeatherPlus] Initializing WeatherPlus platform...
16.3.2021, 12:35:54 [WeatherPlus] Adding station with weather service Dark Sky named 'Now'
16.3.2021, 12:35:54 Initializing platform accessory 'Now'...
16.3.2021, 12:35:54 [My TaHoma Box] Initializing Tahoma platform...
16.3.2021, 12:35:54 [My TaHoma Box] Fetch accessories...
16.3.2021, 12:35:54 [My TaHoma Box] Login TaHoma server...
16.3.2021, 12:35:54 [Shelly] Initializing Shelly platform...
16.3.2021, 12:35:54 [Hue] Initializing Hue platform...
16.3.2021, 12:35:54 [Hue] homebridge-hue v0.13.2, node v12.14.1, homebridge v1.3.3
16.3.2021, 12:35:54 [Hue] config.json: plugin_map: invalid key
16.3.2021, 12:35:54 [Hue] config.json: nupnp: invalid key
16.3.2021, 12:35:54 [Hue] config.json: parallelRequests: invalid key
16.3.2021, 12:35:54 Loading 4 accessories...
16.3.2021, 12:35:54 [Abendessen-Szene] Initializing DummySwitch accessory...
16.3.2021, 12:35:54 [Abendessen-Szene] Setting switch to false
16.3.2021, 12:35:54 [Homeoffice] Initializing DummySwitch accessory...
16.3.2021, 12:35:54 [Homeoffice] Setting switch to false
16.3.2021, 12:35:54 [Chillen-Szene] Initializing DummySwitch accessory...
16.3.2021, 12:35:55 [Chillen-Szene] Setting switch to false
16.3.2021, 12:35:55 [Espressomaschine] Initializing DummySwitch accessory...
16.3.2021, 12:35:55 [Espressomaschine] Setting switch to false
16.3.2021, 12:35:55 [Wohnzimmer] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
16.3.2021, 12:35:55 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7faa2501-af2d-4a67-8770-f696cdc12cc8
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
16.3.2021, 12:35:55 [My TaHoma Box] Unable to refresh states (not logged in)
16.3.2021, 12:35:55 Got SIGTERM, shutting down Bridge...
16.3.2021, 12:35:55 [Wohnzimmer] INFO - shutdown
16.3.2021, 12:35:55 [Wohnzimmer] INFO - shutdown
16.3.2021, 12:35:56 [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
16.3.2021, 12:35:56 [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.42.0
16.3.2021, 12:35:56 [Hue] Philips hue: 17 accessories
16.3.2021, 12:35:56 [My TaHoma Box] [Alarm] type: Alarm > TSKAlarmController, protocol: internal
16.3.2021, 12:35:56 [My TaHoma Box] Device Alarm ignored
16.3.2021, 12:35:56 [My TaHoma Box] [Box] type: Pod > Pod, protocol: internal
16.3.2021, 12:35:56 [My TaHoma Box] No definition found for Pod > Pod in mapping.json file
16.3.2021, 12:35:56 [My TaHoma Box] [Markise] type: Awning > PositionableHorizontalAwning, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Instanciate Markise as WindowCovering with config {}
16.3.2021, 12:35:56 [My TaHoma Box] [IO (10920801)] type: ProtocolGateway > IOStack, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] No definition found for ProtocolGateway > IOStack in mapping.json file
16.3.2021, 12:35:56 [My TaHoma Box] [Schlafen Gaube] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Device Schlafen Gaube ignored
16.3.2021, 12:35:56 [My TaHoma Box] [Kontor] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Device Kontor ignored
16.3.2021, 12:35:56 [My TaHoma Box] [Wohnzimmer] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Device Wohnzimmer ignored
16.3.2021, 12:35:56 [My TaHoma Box] [Küche] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Device Küche ignored
16.3.2021, 12:35:56 [My TaHoma Box] [Schlafen] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Device Schlafen ignored
16.3.2021, 12:35:56 [My TaHoma Box] [Balkon] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Device Balkon ignored
16.3.2021, 12:35:56 [My TaHoma Box] [Bad] type: RollerShutter > PositionableRollerShutter, protocol: io
16.3.2021, 12:35:56 [My TaHoma Box] Device Bad ignored
16.3.2021, 12:35:56 Initializing platform accessory 'Markise'...
16.3.2021, 12:35:57 [HOOBS@Now@Now@Air Pressure] Characteristic not in required or optional characteristic section for service TemperatureSensor. Adding anyway.
16.3.2021, 12:35:57 Initializing platform accessory 'Philips hue'...
16.3.2021, 12:35:57 [Hue] Philips hue: 3 services
16.3.2021, 12:35:57 Initializing platform accessory 'Iris'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Leuchte'...
16.3.2021, 12:35:57 Initializing platform accessory 'Spiegel'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Golden Globe'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Spot'...
16.3.2021, 12:35:57 Initializing platform accessory 'LED Licht'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Strahler'...
16.3.2021, 12:35:57 Initializing platform accessory 'Mond'...
16.3.2021, 12:36:00 [Hue] goodbye ```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Add any other context about the problem here.

**Comment by bwp91** [comment]
I believe I just replied to you on reddit :)

See https://github.com/hoobs-org/HOOBS/issues/1154#issuecomment-799800839

**Comment by dibimuc** [comment]
Thanks didn’t know where to post my issue. Great and thank you very much!!

**Comment by Jedih** [comment]
Yeah, count me in. Just updated from 3.3.4 to 3.3.5 on my Raspberry Pi 4 and the service won't start now. All my plugins are up-to-date (Harmony 1.5.1 and Telldus 1.0.7 and Twinkly 0.4.0).

**Comment by dibimuc** [comment]
See #1154 (comment)

**Comment by Jedih** [comment]
Tried `rm -fR ~/.hoobs/etc/accessories` and then reboot but still doesn't start bridge service.

**Comment by LA0068** [comment]
Service won't restart after upgrade from 3.3.4 to 3.3.5.  All plugins up to date (TPLink KASA, WEMO, Bond, Nest, Nest Cam).  HOOBS SDCard, Raspberry Pi4

**Comment by Praktiker** [comment]
I have the same problem. Deleting switchbot plugin still gives error: 17.3.2021, 19:41:42 [SwitchBot] Loading accessory from cache: Gartentür zu Bot
17.3.2021, 19:41:42 [SwitchBot] Loading accessory from cache: Gartentür auf Bot
17.3.2021, 19:41:42 [SwitchBot] Loading accessory from cache: Temp Küche  Meter
17.3.2021, 19:41:42 [SwitchBot] Loading accessory from cache: Kaffee Bot
17.3.2021, 19:41:42 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 98b536ef-e3de-4a59-989d-55554782d620
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

As you can see it still sees the accessory though it is uninstalled (and server restarted).
Regards...

**Comment by philippgerard** [comment]
> Tried `rm -fR ~/.hoobs/etc/accessories` and then reboot but still doesn't start bridge service.

Worked for me and solved the problem.

**Comment by Jedih** [comment]
Removed all my plugins and then the bridge service starts. But every time I install a new plugin, it stops again. 

`rm -fR ~/.hoobs/etc/accessories` doesn't work for me at all.

**Comment by bwp91** [comment]
@Praktiker i assume you tried running the command posted here?

@Jedih any errors in the logs when you install a plugin and the bridge doesn’t run?

**Comment by Praktiker** [comment]
@bwp91 thank you just saw it and it worked.

**Comment by Jedih** [comment]
> @Jedih any errors in the logs when you install a plugin and the bridge doesn’t run?

Here's the log when I install the Telldus plugin:

2021-03-18 16:47:53 + homebridge-telldus@1.0.7
added 7 packages from 7 contributors in 0.789s
2021-03-18 16:47:53 Plugin "homebridge-telldus" installed.
2021-03-18 16:47:54 Got SIGINT, shutting down Bridge...
2021-03-18 16:48:00 Initializing HAP-NodeJS v0.9.3...
2021-03-18 16:48:01 Loaded plugin 'homebridge-telldus'
2021-03-18 16:48:01 [3/18/2021, 9:48:01 AM] Registering platform 'homebridge-telldus.Telldus'
2021-03-18 16:48:01 Loading 1 platforms...
2021-03-18 16:48:01 [Telldus] Initializing Telldus platform...
2021-03-18 16:48:01 [Telldus] isLocal: false

**Comment by Jedih** [comment]
It seems to be the Telldus and Twinkly plugins which are shutting down the service. Hoobs are still running after I install the Harmony plugin, but shuts down when I install the Telldus and Twinkly plugins.

**Comment by RichDias** [comment]
> Removed all my plugins and then the bridge service starts. But every time I install a new plugin, it stops again.
> 
> `rm -fR ~/.hoobs/etc/accessories` doesn't work for me at all.

Exactly the same issue here.  It works, without plugins

**Comment by Jedih** [comment]
Yeah, it seems to me that v. 3.3.5 doesn't play together with a lot of plugins :-(

**Comment by bwp91** [comment]
> > @Jedih any errors in the logs when you install a plugin and the bridge doesn’t run?
> 
> Here's the log when I install the Telldus plugin:
> 
> 2021-03-18 16:47:53 + homebridge-telldus@1.0.7
> added 7 packages from 7 contributors in 0.789s
> 2021-03-18 16:47:53 Plugin "homebridge-telldus" installed.
> 2021-03-18 16:47:54 Got SIGINT, shutting down Bridge...
> 2021-03-18 16:48:00 Initializing HAP-NodeJS v0.9.3...
> 2021-03-18 16:48:01 Loaded plugin 'homebridge-telldus'
> 2021-03-18 16:48:01 [3/18/2021, 9:48:01 AM] Registering platform 'homebridge-telldus.Telldus'
> 2021-03-18 16:48:01 Loading 1 platforms...
> 2021-03-18 16:48:01 [Telldus] Initializing Telldus platform...
> 2021-03-18 16:48:01 [Telldus] isLocal: false

Unfortunately these logs don't offer any help with pinpointing the issue :/

**Comment by Jedih** [comment]
Re-installed HOOBS 3.3.3 and now my plugins work again. Tried to update to 3.3.5 twice but ran into the same problem. Had to flash the SD to go back to 3.3.3. Gonna stay on 3.3.3 for now!

**Comment by WIMWG** [comment]
I had this to. Restored system with system backup and magically it works again. Hoobs still show 3.3.5 as version.
