### ISSUE TITLE
Livolo plugin error - HOOBS

### ISSUE THREAD

**Issue by iznaf** [hoobs-org/HOOBS#1179]
**Description**
Livolo plugin not working - error 

**Expected behavoir**
Ligts control

**Plugin name**
Livolo

**Version**
3.3.3

**Did you upgrade**
 No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
No

**What device are you using?**
Raspberry Pi 4 and HOOBS SD Card

**Post your config**
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYTR1S",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "5A:DF:2E:29:8C:60"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-livolo-switches"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "livolo-switches",
            "plugin_map": {
                "plugin_name": "homebridge-livolo-switches",
                "login": "%mymail@gmail.com%",
                "password": "%mypassword%"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
3/24/2021, 12:11:12 PM Got SIGINT, shutting down Bridge...
3/24/2021, 12:11:16 PM Initializing HAP-NodeJS v0.9.2...
3/24/2021, 12:11:16 PM Loaded plugin 'homebridge-livolo-switches'
3/24/2021, 12:11:16 PM [3/24/2021, 4:11:16 AM] Registering platform 'homebridge-livolo-switches.livolo-switches'
3/24/2021, 12:11:16 PM Loading 1 platforms...
3/24/2021, 12:11:16 PM [livolo-switches] Initializing livolo-switches platform...
3/24/2021, 12:11:16 PM [livolo-switches] Livolo Init
3/24/2021, 12:11:16 PM [livolo-switches] DidFinishLaunching
3/24/2021, 12:11:16 PM Preparing Advertiser for 'HOOBS F41A' using bonjour-hap backend!
3/24/2021, 12:11:16 PM Starting to advertise 'HOOBS F41A' using bonjour-hap backend!
3/24/2021, 12:11:16 PM Bridge is running on port 51826.
3/24/2021, 12:11:16 PM (node:3260) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
3/24/2021, 12:11:16 PM at Hash.update (internal/crypto/hash.js:84:11)
3/24/2021, 12:11:16 PM at new LivoloApi (/home/hoobs/.hoobs/node_modules/homebridge-livolo-switches/lib/livolo-api.js:19:6)
3/24/2021, 12:11:16 PM at LivoloSwitches.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-livolo-switches/index.js:39:33)
3/24/2021, 12:11:16 PM at HomebridgeAPI.emit (events.js:315:20)
3/24/2021, 12:11:16 PM at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/src/api.ts:275:10)
3/24/2021, 12:11:16 PM at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:161:18)
3/24/2021, 12:11:16 PM at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
3/24/2021, 12:11:16 PM at processTicksAndRejections (internal/process/task_queues.js:93:5)
3/24/2021, 12:11:16 PM (Use `node --trace-warnings ...` to show where the warning was created)
3/24/2021, 12:11:16 PM (node:3260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
3/24/2021, 12:11:16 PM (node:3260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Additional context**
Thanks

**Comment by iznaf** [comment]
Tried this, din't help:

        {
            "platform": "livolo-switches",
            "login": "mymail@gmail.com",
            "password": "mypwd",
            "plugin_map": {
                "plugin_name": "homebridge-livolo-switches"
            }
        }

Same issue:

3/26/2021, 12:07:37 PM (node:8756) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'gatewayId' of undefined
3/26/2021, 12:07:37 PM at LivoloApi._reloadSwitchesData (/home/hoobs/.hoobs/node_modules/homebridge-livolo-switches/lib/livolo-api.js:160:51)
3/26/2021, 12:07:37 PM at processTicksAndRejections (internal/process/task_queues.js:93:5)
3/26/2021, 12:07:37 PM at LivoloApi.connect (/home/hoobs/.hoobs/node_modules/homebridge-livolo-switches/lib/livolo-api.js:43:23)
3/26/2021, 12:07:37 PM (Use `node --trace-warnings ...` to show where the warning was created)
3/26/2021, 12:07:37 PM (node:8756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
3/26/2021, 12:07:37 PM (node:8756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
