### ISSUE TITLE
HOOBS Cluster error

### ISSUE THREAD

**Issue by wills721** [hoobs-org/HOOBS#1196]
**Description**
Hoobs Server giving 'Serial Number' not found error.

3/29/2021, 3:52:27 PM HOOBS listening on port 8081.
3/29/2021, 3:52:28 PM Initializing HAP-NodeJS v0.9.3...
3/29/2021, 3:52:29 PM No plugins installed.
3/29/2021, 3:52:29 PM [HOOBS All-Devices@@Serial Number] characteristic value expected string and received undefined
3/29/2021, 3:52:29 PM TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:1118:10)
    at Server.publishBridge (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:189:21)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:158:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:158:9)

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry PI arm721

**List your plugins**
None right now. 

**Post your config**
{
    "server": {
        "port": 8081,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS All-Devices",
        "port": 51827,
        "pin": "031-45-154"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm"
}

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by wills721** [comment]
This is a log from a 'hoobs server -instance 'All-Devices'
