### ISSUE TITLE
Got SIGTERM, shutting down Bridge...

### ISSUE THREAD

**Issue by isaleem-mi6** [hoobs-org/HOOBS#1255]
Hi, 
I have removed a lot of my plugin's to try an dresolve this issue but I still cant get the server to start and remain running.
Please help with resolving this issue I am facing.

Logs

10/05/2021, 23:58:31 HOOBS listening on port 80.10/05/2021, 23:58:52 Initializing HAP-NodeJS v0.9.3...10/05/2021, 23:58:56 Loaded plugin 'homebridge-evohome'10/05/2021, 23:59:07 [5/10/2021, 4:59:06 PM] Registering platform 'homebridge-evohome.Evohome'10/05/2021, 23:59:07 Loaded plugin 'homebridge-gsh'10/05/2021, 23:59:07 [5/10/2021, 4:59:07 PM] Registering platform 'homebridge-gsh.google-smarthome'10/05/2021, 23:59:09 Loaded plugin 'homebridge-roomba-stv'10/05/2021, 23:59:09 [5/10/2021, 4:59:09 PM] Registering accessory 'homebridge-roomba-stv.Roomba'10/05/2021, 23:59:09 Loading 2 platforms...10/05/2021, 23:59:09 [Evohome] Initializing Evohome platform...10/05/2021, 23:59:09 [Evohome] Logging into Evohome...10/05/2021, 23:59:09 [Google Smart Home] Initializing google-smarthome platform...10/05/2021, 23:59:09 Loading 1 accessories...10/05/2021, 23:59:09 [Roomba] Initializing Roomba accessory...10/05/2021, 23:59:09 [Roomba] Enabling keepAlive10/05/2021, 23:59:10 Failed to find plugin to handle accessory Front Door10/05/2021, 23:59:10 Failed to find plugin to handle accessory Downstairs10/05/2021, 23:59:10 Failed to find plugin to handle accessory Upstairs10/05/2021, 23:59:10 Failed to find plugin to handle accessory Google-Home-ce9097b60035cf846adf53cd2308b0ba10/05/2021, 23:59:10 Failed to find plugin to handle accessory Google-Home-ce9097b60035cf846adf53cd2308b0ba10/05/2021, 23:59:14 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 84f9056a-361f-40b1-bc58-3382d0c65067
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)10/05/2021, 23:59:14 Got SIGTERM, shutting down Bridge...10/05/2021, 23:59:15 [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu10/05/2021, 23:59:15 [Evohome] Logged into Evohome!10/05/2021, 23:59:15 [Evohome] You have 1 location(s). This instance will be using Index No 010/05/2021, 23:59:15 [Evohome] You have 9 device(s).10/05/2021, 23:59:16 [Evohome] 0: Living room (22°)10/05/2021, 23:59:16 [Evohome] 1: Kitchen floor (23.5°)10/05/2021, 23:59:16 [Evohome] 2: M.bed (21°)10/05/2021, 23:59:16 [Evohome] 3: Front room (20°)10/05/2021, 23:59:16 [Evohome] 4: Mustafa (21.5°)10/05/2021, 23:59:16 [Evohome] 5: Ibrahim (21°)10/05/2021, 23:59:16 [Evohome] 6: Guest (20°)10/05/2021, 23:59:16 [Evohome] 7: Lobby (20.5°)10/05/2021, 23:59:16 [Evohome] 8: Office (20.5°)10/05/2021, 23:59:16 Initializing platform accessory 'Living room Thermostat'...10/05/2021, 23:59:16 Initializing platform accessory 'Kitchen floor Thermostat'...10/05/2021, 23:59:16 Initializing platform accessory 'M.bed Thermostat'...10/05/2021, 23:59:16 Initializing platform accessory 'Front room Thermostat'...10/05/2021, 23:59:17 Initializing platform accessory 'Mustafa Thermostat'...10/05/2021, 23:59:17 Initializing platform accessory 'Ibrahim Thermostat'...10/05/2021, 23:59:17 Initializing platform accessory 'Guest Thermostat'...10/05/2021, 23:59:17 Initializing platform accessory 'Lobby Thermostat'...10/05/2021, 23:59:17 Initializing platform accessory 'Office Thermostat'...10/05/2021, 23:59:17 Initializing platform accessory 'Evohome Away Mode'...10/05/2021, 23:59:17 Initializing platform accessory 'Evohome Day Off Mode'...10/05/2021, 23:59:17 Initializing platform accessory 'Evohome Heating Off Mode'...10/05/2021, 23:59:17 Initializing platform accessory 'Evohome Eco Mode'...10/05/2021, 23:59:17 Initializing platform accessory 'Evohome Custom Mode'...

**Comment by EddieDSuza** [comment]
Can you reboot the server and paste the logs

**Comment by isaleem-mi6** [comment]
Did that straight after a reboot above. Thanks for checking
