### ISSUE TITLE
Bug plugin Ring !

### ISSUE THREAD

**Issue by Stewart06** [hoobs-org/HOOBS#1264]
Bonjour,

Cela fait un bon moment que je rencontre beaucoup de problème avec le plugin Ring pour y récupérer ma sonnette connectée.

Le plus souvent cela me faisait planter l’instance et je devais redémarrer Hoobs et cela est bien ennuyeux quand vous n’êtes pas chez vous, obligé de passer par un VPN pour s’y connecter. Depuis que le plugin Ring a été mis à jour on dirait que Hoobs ne s’arrête plus, mais j’ai toujours ce message d’erreur.

Cela est dû à quoi ?

Hello,

 It's been a while since I had a lot of problem with the Ring plugin to retrieve my connected doorbell.

 Most of the time it would crash the instance and I had to restart Hoobs and it is annoying when you are not at home, having to go through a VPN to connect to it.  Since the Ring plugin has been updated it looks like Hoobs is not stopping anymore, but I still get this error message.

 What is this due to?

[HOOBS 7C88@Setup Endpoints] The write handler for the characteristic 'Setup Endpoints' on the accessory 'Sonnette Entrée' didn't respond at all!. Please check that you properly call the callback!

**Comment by Stewart06** [comment]
[19/05/2021 10:48] [Ring] Preparing Live Stream for Sonnette Entrée

[19/05/2021 10:48] [Ring] Waiting for stream data from Sonnette Entrée (0.933s)

[19/05/2021 10:48] [Ring] Received stream data from Sonnette Entrée (1.031s)

[19/05/2021 10:48] [Ring] Streaming active for Sonnette Entrée

[19/05/2021 10:48] [Ring] Stopped Live Stream for Sonnette Entrée

[19/05/2021 10:48] Error: SIP request made after call was destroyed

[19/05/2021 10:48] at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)

[19/05/2021 10:48] at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)

[19/05/2021 10:48] at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)

[19/05/2021 10:48] at Generator.next (<anonymous>)

[19/05/2021 10:48] at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)

[19/05/2021 10:48] Error: SIP request made after call was destroyed

[19/05/2021 10:48] at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)

[19/05/2021 10:48] at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)

[19/05/2021 10:48] at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)

[19/05/2021 10:48] at Generator.next (<anonymous>)

[19/05/2021 10:48] at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)

[19/05/2021 10:48] undefined

[19/05/2021 10:48] Got SIGTERM, shutting down Bridge...

[19/05/2021 10:48] [Apple TV Platform] Shutting down Apple TV clients...

[19/05/2021 10:48] [Apple TV Platform] Shutting down Apple TV clients...

[19/05/2021 10:48] Catching error on dropMembership: {"code":"ERR_SOCKET_DGRAM_NOT_RUNNING"
