### ISSUE TITLE
Hoobs hung

### ISSUE THREAD

**Issue by lfschwartz** [hoobs-org/HOOBS#1265]
Hoobs in a box is hung and I can't access it from my Mac.  I'm not a programmer. Any help would be appreciated.

Logs:

hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 4437.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs/backups'
    at Object.mkdirSync (fs.js:987:3)
    at Object.module.exports.makeDirSync (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/fs-extra/lib/mkdirs/make-dir.js:101:15)
    at checksum (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:180:10)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:40:68)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs/backups'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 4438.
Stopped HOOBS.
Started HOOBS.
internal/fs/utils.js:308
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs/backups'
    at Object.mkdirSync (fs.js:987:3)
    at Object.module.exports.makeDirSync (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/fs-extra/lib/mkdirs/make-dir.js:101:15)
    at checksum (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:180:10)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:40:68)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs/backups'
}

**Comment by EddieDSuza** [comment]
please follow this Issue #1113 for possible fixes.
