### ISSUE TITLE
Loop and auto restarting cant get past creating a account

### ISSUE THREAD

**Issue by frescogamer** [hoobs-org/HOOBS#1274]
**Description**
I'm new to hoobs, love it so far and setup is very simple. i cant get past the creation of a account tho. i also cant find any solution to the problem i'm having. 

When loading hoobs (either via IP or local) i get prompted to enter account details, after a few seconds it reloads the page and i get a hoobs loading screen, this takes around 2 minutes then i can acces the page again and try to enter credentials again. this keeps looping

**Version**
Latest release

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
none

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYSZLR",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "D6:BC:DB:01:0C:E6"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
    "platforms": [],
    "package_manager": "npm",
    "system": "hoobs"

```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
Started HOOBS.
HOOBS listening on port 80.
Initializing HAP-NodeJS v0.9.3...
No plugins installed.
Preparing Advertiser for 'HOOBS 6768' using bonjour-hap backend!
Starting to advertise 'HOOBS 6768' using bonjour-hap backend!
Bridge is running on port 51826.
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:167:14)
    at Receiver.startLoop (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:121:22)
    at Receiver._write (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/websocket.js:795:35)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  [Symbol(status-code)]: 1002
}
Got SIGINT, shutting down Bridge...
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 1.
Stopped HOOBS.
Started HOOBS.
HOOBS listening on port 80.
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:167:14)
    at Receiver.startLoop (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:121:22)
    at Receiver._write (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/websocket.js:795:35)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  [Symbol(status-code)]: 1002
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 2.
Stopped HOOBS.
hoobs.service: Found left-over process 844 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started HOOBS.
HOOBS listening on port 80.
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:167:14)
    at Receiver.startLoop (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:121:22)
    at Receiver._write (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/node_modules/ws/lib/websocket.js:795:35)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  [Symbol(status-code)]: 1002
}
[HOOBS] Stopping server.
```

**Additional context**

**Comment by askovi** [comment]
try rebooting your mac
