### ISSUE TITLE
Raspberry PI and Website have different details

### ISSUE THREAD

**Issue by am60131** [hoobs-org/HOOBS#1289]
**Description**
There appears to be a synchronisation issue between the Software on my Raspberry PI and the website Hoobs.org.  The website does not recognise the user name and the software on the Raspberry PI dos not recognise the email address.  Not sure how this happened but it would be great if you could take a look and advise

**Version**
3.3.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
No

**What device are you using?**
Please let us know the device you are running HOOBS on.
Custom Install

**If this is a custom install, what's your operating system?**
Raspberry PI 400 but planning on moving to Raspberry PI 4 after fixing this

**List your plugins**
Nest
4.5.3 published 3/2/2021 
Ring
9.18.1 published 5/17/2021

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.  Not sure if this is a password vat removed the refresh token. 

```
hoobs@hoobs:/home/hoobs/.hoobs/etc $ cat ~/.hoobs/etc/config.json
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY5QZU",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "18:FE:2B:D7:D2:AF"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-ring",
        "homebridge-nest"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": " [REMOVED]
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
20/06/2021, 13:49:46 HOOBS listening on port 80.
20/06/2021, 13:49:47 Initializing HAP-NodeJS v0.9.2...
20/06/2021, 13:49:48 Loaded plugin 'homebridge-nest'
20/06/2021, 13:49:48 [6/20/2021, 6:49:48 AM] Registering platform 'homebridge-nest.Nest'
20/06/2021, 13:49:50 Loaded plugin 'homebridge-ring'
20/06/2021, 13:49:50 [6/20/2021, 6:49:50 AM] Registering platform 'homebridge-ring.Ring'
20/06/2021, 13:49:50 Loading 2 platforms...
20/06/2021, 13:49:50 [Ring] Initializing Ring platform...
20/06/2021, 13:49:50 [Nest] Initializing Nest platform...
20/06/2021, 13:49:50 [Ring] Configuring cached accessory b910bfe6-19f2-4c43-b69b-4478ca34d778 Front Door
20/06/2021, 13:49:50 [Ring] Configuring cached accessory 77894cae-8287-445e-8cc8-a2219db001f5 Front Garden
20/06/2021, 13:49:50 [Ring] Configuring cached accessory dbd2f5ec-1390-4743-a6ce-960f6ac25f39 Garage
20/06/2021, 13:49:50 [Ring] Configuring cached accessory 250d1b64-6448-40cb-aeb6-26a7a34b5216 Garden
20/06/2021, 13:49:50 [Ring] Configuring cached accessory d33c82b7-28d2-4ef4-97b1-867f23cce877 Hallway
20/06/2021, 13:49:50 [Nest] Fetching Nest devices.
20/06/2021, 13:49:50 [Nest] You did not specify your Nest account credentials {'email','password'}, or an access_token, or googleAuth, in config.json
20/06/2021, 13:49:50 [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.
20/06/2021, 13:49:50 Preparing Advertiser for 'HOOBS C3A1' using bonjour-hap backend!
20/06/2021, 13:49:50 Starting to advertise 'HOOBS C3A1' using bonjour-hap backend!
20/06/2021, 13:49:50 Bridge is running on port 51826.
20/06/2021, 13:49:52 [Ring] Found the following locations:
20/06/2021, 13:49:52 [Ring]   locationId: 6a325fad-02ba-4fef-ad7d-e01398d92e9b - Orpington
20/06/2021, 13:49:53 [Ring] Configuring 4 cameras and 5 devices for location "Orpington" - locationId: 6a325fad-02ba-4fef-ad7d-e01398d92e9b
20/06/2021, 13:51:07 [Ring] Preparing Live Stream for Front Garden
20/06/2021, 13:51:08 [Ring] Waiting for stream data from Front Garden (0.629s)
20/06/2021, 13:51:08 [Ring] Received stream data from Front Garden (0.808s)
20/06/2021, 13:51:08 [Ring] Streaming active for Front Garden
20/06/2021, 13:51:26 [Ring] Stopped Live Stream for Front Garden
20/06/2021, 13:51:32 [Ring] Preparing Live Stream for Front Garden
20/06/2021, 13:51:32 [Ring] Ding 6975857823193164322 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:51:32 err:  Error: remote peer disconnected
20/06/2021, 13:51:32 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:51:32 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:51:32 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:51:32 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:51:33 [Ring] Waiting for stream data from Front Garden (0.795s)
20/06/2021, 13:51:33 [Ring] Received stream data from Front Garden (1.095s)
20/06/2021, 13:51:33 [Ring] Streaming active for Front Garden
20/06/2021, 13:51:34 [Ring] Stopped Live Stream for Front Garden
20/06/2021, 13:51:35 (node:689) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
20/06/2021, 13:51:35 at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
20/06/2021, 13:51:35 at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
20/06/2021, 13:51:35 at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
20/06/2021, 13:51:35 at Generator.next (<anonymous>)
20/06/2021, 13:51:35 at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
20/06/2021, 13:51:35 (Use `node --trace-warnings ...` to show where the warning was created)
20/06/2021, 13:51:35 (node:689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
20/06/2021, 13:51:35 (node:689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
20/06/2021, 13:51:55 [Ring] Preparing Live Stream for Front Door
20/06/2021, 13:51:56 [Ring] Waiting for stream data from Front Door (0.573s)
20/06/2021, 13:51:58 [Ring] Received stream data from Front Door (2.075s)
20/06/2021, 13:51:58 [Ring] Preparing Live Stream for Front Garden
20/06/2021, 13:51:58 [Ring] Ding 6975857930567346722 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:51:58 err:  Error: remote peer disconnected
20/06/2021, 13:51:58 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:51:58 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:51:58 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:51:58 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:51:58 [Ring] Waiting for stream data from Front Garden (0.697s)
20/06/2021, 13:51:59 [Ring] Received stream data from Front Garden (1.115s)
20/06/2021, 13:51:59 [Ring] Streaming active for Front Door
20/06/2021, 13:51:59 [Ring] Streaming active for Front Garden
20/06/2021, 13:52:03 [Ring] Stopped Live Stream for Front Garden
20/06/2021, 13:52:03 [Ring] Preparing Live Stream for Garage
20/06/2021, 13:52:04 [Ring] Waiting for stream data from Garage (0.561s)
20/06/2021, 13:52:04 [Ring] Received stream data from Garage (0.983s)
20/06/2021, 13:52:05 [Ring] Streaming active for Garage
20/06/2021, 13:52:05 [Ring] Stopped Live Stream for Garage
20/06/2021, 13:52:05 [Ring] Preparing Live Stream for Garden
20/06/2021, 13:52:06 [Ring] Waiting for stream data from Garden (0.622s)
20/06/2021, 13:52:06 [Ring] Received stream data from Garden (0.773s)
20/06/2021, 13:52:06 [Ring] Streaming active for Garden
20/06/2021, 13:52:07 (node:689) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
20/06/2021, 13:52:07 at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
20/06/2021, 13:52:07 at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
20/06/2021, 13:52:07 at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
20/06/2021, 13:52:07 at Generator.next (<anonymous>)
20/06/2021, 13:52:07 at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
20/06/2021, 13:52:07 (node:689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
20/06/2021, 13:52:11 [Ring] Preparing Live Stream for Garage
20/06/2021, 13:52:11 [Ring] Ding 6975858068010639332 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:52:11 err:  Error: remote peer disconnected
20/06/2021, 13:52:11 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:52:11 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:52:11 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:52:11 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:52:11 [Ring] Waiting for stream data from Garage (0.749s)
20/06/2021, 13:52:11 [Ring] Received stream data from Garage (0.958s)
20/06/2021, 13:52:12 [Ring] Stopped Live Stream for Garden
20/06/2021, 13:52:12 [Ring] Stopped Live Stream for Garage
20/06/2021, 13:52:12 [Ring] Preparing Live Stream for Front Garden
20/06/2021, 13:52:12 [Ring] Ding 6975858042236496418 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:52:12 err:  Error: remote peer disconnected
20/06/2021, 13:52:12 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:52:12 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:52:12 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:52:12 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:52:12 [Ring] Waiting for stream data from Front Garden (0.809s)
20/06/2021, 13:52:15 [Ring] Received stream data from Front Garden (2.944s)
20/06/2021, 13:52:15 [Ring] Streaming active for Front Garden
20/06/2021, 13:52:15 [Ring] Stopped Live Stream for Front Garden
20/06/2021, 13:52:17 (node:689) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
20/06/2021, 13:52:17 at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
20/06/2021, 13:52:17 at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
20/06/2021, 13:52:17 at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
20/06/2021, 13:52:17 at Generator.next (<anonymous>)
20/06/2021, 13:52:17 at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
20/06/2021, 13:52:17 (node:689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
20/06/2021, 13:52:26 [Ring] Preparing Live Stream for Front Garden
20/06/2021, 13:52:27 [Ring] Ding 6975858102366038562 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:52:27 err:  Error: remote peer disconnected
20/06/2021, 13:52:27 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:52:27 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:52:27 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:52:27 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:52:27 [Ring] Waiting for stream data from Front Garden (0.784s)
20/06/2021, 13:52:27 [Ring] Received stream data from Front Garden (1.001s)
20/06/2021, 13:52:27 [Ring] Stopped Live Stream for Front Door
20/06/2021, 13:52:27 [Ring] Streaming active for Front Garden
20/06/2021, 13:52:31 [Ring] Stopped Live Stream for Front Garden
20/06/2021, 13:52:31 [Ring] Preparing Live Stream for Garage
20/06/2021, 13:52:32 [Ring] Waiting for stream data from Garage (0.602s)
20/06/2021, 13:52:32 [Ring] Received stream data from Garage (1.006s)
20/06/2021, 13:52:33 [Ring] Streaming active for Garage
20/06/2021, 13:52:37 [Ring] Preparing Live Stream for Front Garden
20/06/2021, 13:52:37 [Ring] Ding 6975858166790548002 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:52:37 err:  Error: remote peer disconnected
20/06/2021, 13:52:37 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:52:37 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:52:37 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:52:37 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:52:38 [Ring] Waiting for stream data from Front Garden (0.76s)
20/06/2021, 13:52:38 [Ring] Received stream data from Front Garden (0.986s)
20/06/2021, 13:52:38 [Ring] Stopped Live Stream for Garage
20/06/2021, 13:52:38 [Ring] Streaming active for Front Garden
20/06/2021, 13:52:38 [Ring] Stopped Live Stream for Front Garden
20/06/2021, 13:52:38 [Ring] Preparing Live Stream for Front Door
20/06/2021, 13:52:39 [Ring] Ding 6975858033645346577 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:52:39 err:  Error: remote peer disconnected
20/06/2021, 13:52:39 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:52:39 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:52:39 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:52:39 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:52:40 [Ring] Waiting for stream data from Front Door (1.287s)
20/06/2021, 13:52:40 (node:689) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
20/06/2021, 13:52:40 at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
20/06/2021, 13:52:40 at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
20/06/2021, 13:52:40 at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
20/06/2021, 13:52:40 at Generator.next (<anonymous>)
20/06/2021, 13:52:40 at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
20/06/2021, 13:52:40 (node:689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
20/06/2021, 13:52:41 [Ring] Received stream data from Front Door (2.834s)
20/06/2021, 13:52:41 [Ring] Streaming active for Front Door
20/06/2021, 13:52:45 [Ring] Front Garden Detected Motion. Loading snapshot before sending event to HomeKit
20/06/2021, 13:52:48 [Ring] Preparing Live Stream for Front Garden
20/06/2021, 13:52:48 [Ring] Waiting for stream data from Front Garden (0.246s)
20/06/2021, 13:52:48 [Ring] Received stream data from Front Garden (0.321s)
20/06/2021, 13:52:48 [Ring] Stopped Live Stream for Front Door
20/06/2021, 13:52:48 [Ring] Streaming active for Front Garden
20/06/2021, 13:52:52 [Ring] Preparing Live Stream for Front Door
20/06/2021, 13:52:52 [Ring] Ding 6975858218328940305 is expired (480).  Fetching a new ding and trying video stream again
20/06/2021, 13:52:52 err:  Error: remote peer disconnected
20/06/2021, 13:52:52 at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/sip/sip.js:584:43)
20/06/2021, 13:52:52 at TLSSocket.emit (events.js:327:22)
20/06/2021, 13:52:52 at endReadableNT (internal/streams/readable.js:1327:12)
20/06/2021, 13:52:52 at processTicksAndRejections (internal/process/task_queues.js:80:21)
20/06/2021, 13:52:53 [Ring] Waiting for stream data from Front Door (0.771s)
20/06/2021, 13:52:55 [Ring] Received stream data from Front Door (2.943s)
20/06/2021, 13:52:55 [Ring] Stopped Live Stream for Front Garden
20/06/2021, 13:52:55 [Ring] Streaming active for Front Door
20/06/2021, 13:53:01 [Ring] Stopped Live Stream for Front Door
20/06/2021, 14:17:04 [Ring] Front Garden Detected Motion. Loading snapshot before sending event to HomeKit
```

**Additional context**

**Comment by mkellsy** [comment]
The Pi doesn’t communicate with our website. It is a local account.
