### ISSUE TITLE
Update from 3.3.5 to 3.3.6 and crash in hue plugin

### ISSUE THREAD

**Issue by MrWGT** [hoobs-org/HOOBS#1315]
**Description**
Updated from 3.3.5 to 3.3.6 and hoobs crashes with hue plugin.

**Version**
3.3.6

**Did you upgrade**
yes

**Pervious version**
3.3.5

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
no

**What device are you using?**
Please let us know the device you are running HOOBS on.
hoobs on intel nuc

**If this is a custom install, what's your operating system?**
lubuntu 20.x

**List your plugins**
hue plugin
fritz!platform

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
will do later

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
6.7.2021, 18:36:25 [Hue] ConBee II: 2 services6.7.2021, 18:36:25 [Hue] homebridge: error: AssertionError [ERR_ASSERTION]: Services must be created with a valid UUID.
    at new Service (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Service.ts:289:11)
    at parseServiceJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:124:19)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:69:21
    at Array.forEach (<anonymous>)
    at Object.parseAccessoryJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:68:17)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:402:36)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:376:44
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:370:29
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:312:5)

**Additional context**
none

**Comment by mkellsy** [comment]
We are looking into this.

**Comment by mkellsy** [comment]
Run this command
```
sudo npm install -g --unsafe-perm @hoobs/hoobs@latest
```

**Comment by MrWGT** [comment]
Works... Thanks. 😊
