### ISSUE TITLE
Bond plugin broken after upgrade to 3.37

### ISSUE THREAD

**Issue by rpk113** [hoobs-org/HOOBS#1317]
Running raspberry pi zero W
Hoobs v 3.3.7
Node JS v 14.17.0

```
7/6/2021, 8:10:31 PM [Bond] A request error occurred: undefined
7/6/2021, 8:10:31 PM [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
7/6/2021, 8:10:31 PM [Bond] A request error occurred: undefined
7/6/2021, 8:10:31 PM [Bond] Error getting version: TypeError: Cannot read property 'bondid' of undefined
7/6/2021, 8:10:31 PM [Bond] 2 cached accessories were loaded
7/6/2021, 8:10:31 PM (node:1225) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bondid' of undefined
7/6/2021, 8:10:31 PM at BondPlatform.getDevices (/home/hoobs/.hoobs/node_modules/homebridge-bond/dist/platform.js:47:65)
7/6/2021, 8:10:31 PM at /home/hoobs/.hoobs/node_modules/homebridge-bond/dist/platform.js:39:26
7/6/2021, 8:10:31 PM at Array.forEach (<anonymous>)
7/6/2021, 8:10:31 PM at /home/hoobs/.hoobs/node_modules/homebridge-bond/dist/platform.js:38:28
7/6/2021, 8:10:31 PM at processTicksAndRejections (internal/process/task_queues.js:95:5)
7/6/2021, 8:10:31 PM at runNextTicks (internal/process/task_queues.js:64:3)
7/6/2021, 8:10:31 PM at processTimers (internal/timers.js:495:9)
7/6/2021, 8:10:31 PM (Use `node --trace-warnings ...` to show where the warning was created)
7/6/2021, 8:10:31 PM (node:1225) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 43)
7/6/2021, 8:10:31 PM (node:1225) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mkellsy** [comment]
I am purchasing a Bond bridge so I can test this.
