### ISSUE TITLE
Can’t start HOOBS - error no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs'

### ISSUE THREAD

**Issue by grapii** [hoobs-org/HOOBS#1453]
**Description**
Devices were unresponsive in Homekit so tried to login to HOOBS.local to see what was happening, but was faced with this issue - no login, no HOOBS screen, just a browser black & white page saying:

Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs'
    at Object.realpathSync (fs.js:1728:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/server/server.js:80:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:315:20)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)

**Version**
Please include the version of HOOBS you are using.
Unsure maybe 3.3.2

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Ring
Nest
Shelly
Camera FPEG

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
How????

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by EddieDSuza** [comment]
follow this #1159 to fix the issue

**Comment by grapii** [comment]
Thanks - managed to SSH onto HOOBS and issue cmd: sudo npm install -g --unsafe-perm @hoobs/hoobs 

All back and working now - thanks
