### ISSUE TITLE
Cannot access hoops.local or by its IP address after upgrading to v4

### ISSUE THREAD

**Issue by vikagarwal** [hoobs-org/HOOBS#1530]
**Description**
I was running my hoobs v3.x on Raspberry pi 4 all this while without issues. I then 2 days ago tried upgrading to Hoobs V4. Since then the hoobs.local or the IP address are not showing anything. I am able to SSH into Hoobs but that's about it. 

**Version**
V4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.12

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
ring, Leviton, iRobot, MyQ

**Post your config**

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYYTIH",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "CA",
        "postal_code": "xxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxxxxxxxx",
        "username": "76:72:05:32:57:A4"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-ring",
        "homebridge-leviton",
        "homebridge-roomba-stv",
        "homebridge-myq"
    ],
    "accessories": [
        {
            "accessory": "Roomba",
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            },
            "name": "Dobby",
            "model": "980",
            "blid": "3117450421323740",
            "robotpwd": "xxxxxx",
            "ipaddress": "192.168.86.68",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": false,
            "cacheTTL": 30
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "showPanicButtons": false,
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2Mjg4OTI4NjgsImlzcyI6IlJpbmdPYXV0aFNlcnZpY2UtcHJvZDp1cy1lYXN0LTE6OTI2YmM1ZWYiLCJyZWZyZXNoX2NpZCI6InJpbmdfb2ZmaWNpYWxfYW5kcm9pZCIsInJlZnJlc2hfc2NvcGVzIjpbImNsaWVudCJdLCJyZWZyZXNoX3VzZXJfaWQiOjU1NzM5NDM3LCJybmQiOiJOdFV1dWdKS1p0ZWVIZyIsInNlc3Npb25faWQiOiI3ZTZlOTE5Ni1hOTZhLTQ0MDctOWIzMC03YjQ5ZjczMTYyNmEiLCJ0eXBlIjoicmVmcmVzaC10b2tlbiJ9.6rc-2fS6H4G29eeQBfy4m4Kf1Z10pe5E5TvAXLDZYyfWxSDJQO3hvK_bJmjL-hMINw2pOFfueC7ezDGvIdN5-A",
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true
        },
        {
            "platform": "LevitonDecoraSmart",
            "plugin_map": {
                "plugin_name": "homebridge-leviton"
            },
            "email": "xxxxx",
            "password": "xxxxx"
        },
        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "email": "xxxx",
            "password": "xxxxx"
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
hoobs@hoobs:~ $ sudo hoobs service log

You must first enable the HOOBS service
```

**Additional context**

**Comment by vikagarwal** [comment]
I tried the below as well:

hoobs@hoobs:~ $ hoobs service start

You must first enable the HOOBS service

hoobs@hoobs:~ $ hoobs service enable

You must first install the HOOBS service

hoobs@hoobs:~ $ hoobs service install
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
(node:23840) UnhandledPromiseRejectionWarning: Error: Command failed: apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

    at checkExecSyncError (child_process.js:760:11)
    at Object.execSync (child_process.js:833:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:42:25
    at new Promise (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:23:12)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:141:76
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:144:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by EddieDSuza** [comment]
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network. 

If you're using Windows, you must have the Apple Bonjour Service installed (restart your computer after installing it): https://support.apple.com/kb/DL999?locale=en_US

HOOBS is also available at the following addresses:

http://hoobs (no domain)

http://hoobs.lan (some routers)

http://192.168.x.x (replace with local ip address given to the HOOBS Box by your router)

**Comment by mkellsy** [comment]
It looks like you reset the device. Run this command
```
sudo hbs install
```

Follow the prompts.

**Comment by vikagarwal** [comment]
I already tried the steps from that doc. Now when I try the first step in that doc sudo systemctl stop hoobs.service 
I get a message - “ Failed to stop hoobs.service: Unit hoobs.service not loaded.”

**Comment by mkellsy** [comment]
That's good. The new service is called hoobsd.
Check to see if nginx is running.
```
sudo systemctl status nginx
```

If it is stop it and disable it
```
sudo systemctl stop nginx
sudo systemctl disable nginx
```

Then restart the hoobsd service
```
sudo systemctl restart hoobsd
```

If it still won't start. Try resetting
```
sudo hbs system reset
sudo hbs install
```

**Comment by vikagarwal** [comment]
Okay so on running those commands I get - Unit nginx.service could not be found.

and on trying to install command I get this -
Error: Cannot find module '/usr/lib/hoobsd/node_modules/http-terminator/dist/src/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by mkellsy** [comment]
That's SD card corruption. This can happen from unplugging your Pi from a running state.
You may need to re-flash your SD card.
