### ISSUE TITLE
Problem with upgrading to v4 and issues when following migration document

### ISSUE THREAD

**Issue by grapii** [hoobs-org/HOOBS#1533]
**Description**
I tried upgrading from 3.3.12 to v4 using the UI.  After a while, I could not connect to hoobs.local, think it was still upgrading I left it alone.  After over 12hours I still couldn't connect. so I followed this document to manually fix the issue: https://support.hoobs.org/docs/60e5b9026c19a6a5ca8ead7a

However I got many errors and still do not have the system running.

Is it possible to start from scratch with v4? if so how?

I got the following issues when running commands:

**sudo apt install -y hoobsd hoobs-cli hoobs-gui helm**
```
make: Entering directory '/usr/lib/hbs/node_modules/node-uname/build'
  CC(target) Release/obj.target/uname/uname.o
make: *** [uname.target.mk:107: Release/obj.target/uname/uname.o] Segmentation fault
make: Leaving directory '/usr/lib/hbs/node_modules/node-uname/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/hbs/node_modules/node-uname
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

dpkg: error processing package hoobs-cli (--configure):
 installed hoobs-cli package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of hoobs-gui:
 hoobs-gui depends on hoobsd (>= 4.0.0); however:
  Package hoobsd is not configured yet.

dpkg: error processing package hoobs-gui (--configure):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 hoobsd
 hoobs-cli
 hoobs-gui
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**sudo hbs system restore ~/migration.zip**
```
 ERROR  /usr/lib/hbs/node_modules/bindings/bindings.js:126
  err = new Error(
        ^
 ERROR  Error: Could not locate the bindings file. Tried:
 → /usr/lib/hbs/node_modules/node-uname/build/uname.node
 → /usr/lib/hbs/node_modules/node-uname/build/Debug/uname.node
 → /usr/lib/hbs/node_modules/node-uname/build/Release/uname.node
 → /usr/lib/hbs/node_modules/node-uname/out/Debug/uname.node
 → /usr/lib/hbs/node_modules/node-uname/Debug/uname.node
 → /usr/lib/hbs/node_modules/node-uname/out/Release/uname.node
 → /usr/lib/hbs/node_modules/node-uname/Release/uname.node
 → /usr/lib/hbs/node_modules/node-uname/build/default/uname.node
 → /usr/lib/hbs/node_modules/node-uname/compiled/14.17.6/linux/arm/uname.node
 → /usr/lib/hbs/node_modules/node-uname/addon-build/release/install-root/uname.node
 → /usr/lib/hbs/node_modules/node-uname/addon-build/debug/install-root/uname.node
 → /usr/lib/hbs/node_modules/node-uname/addon-build/default/install-root/uname.node
 → /usr/lib/hbs/node_modules/node-uname/lib/binding/node-v83-linux-arm/uname.node
    at bindings (/usr/lib/hbs/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/lib/hbs/node_modules/node-uname/uname.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/src/extentions/ffmpeg.ts:22:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/src/extentions/index.ts:21:1)
```

**Version**
Please include the version of HOOBS you are using.
4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.3.12

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
homebridge-ring
homebridge-camera-ffmpeg
homebridge-nest
homebridge-shelly

**Post your config**
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "",
    },
    "bridge": {
        "name": "HOOBS",
        "port":,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-ring",
        "homebridge-camera-ffmpeg",
        "homebridge-nest",
        "homebridge-shelly"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "",
            "hideDeviceIds": [
                ""
            ],
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": true,
            "avoidSnapshotBatteryDrain": false,
            "sendDoorbellMotionNotificationsToTv": false,
            "sendCameraMotionNotificationsToTv": false,
            "hideInHomeDoorbellSwitch": true
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Front",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Porch",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "mapvideo": "0:0",
                        "mapaudio": "0:1",
                        "vcodec": "copy",
                        "audio": true,
                        "debug": false
                    }
                },
                {
                    "name": "Garage",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Garden Centre",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Patio Left",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Patio Right",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Garden Left",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Garden Right",
                    "videoConfig": {
                        "source": "-re -i rtsp://Streaming/Channels/302",
                        "stillImageSource": "-i http://",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": false
                    }
                }
            ]
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "googleAuth": {
                "issueToken": "https://accounts.google.com/o/oauth2",
                "apiKey": "",
                "cookies": ""
            },
            "options": [
                "Thermostat.Fan.Disable",
                "Thermostat.Eco.Disable",
                "HomeAway.Disable",
                "Protect.Disable"
            ]
        },
        {
            "platform": "Shelly",
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            },
            "name": "Shelly",
            "admin": {
                "enabled": true
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
cannot get to HOOBS.local
```

**Additional context**

**Comment by mkellsy** [comment]
Thanks for reporting.

I have already discovered this issue. The issue is, post-install the node modules are installed and some of these node modules require a gyp compile.

To address this, in 4.1, I am releasing pre-build gyp modules along with the proper node modules already included in the .deb package.

To do this I had to update our build process to handle cross platform installs. 4.1 will support amd64, arm64 and armhf. All other architectures are unsupported because Node is only available for these architectures.

For your current HOOBS Box, please email info@hoobs.com. We can work with you and replace the SD Card if needed. Please allow 24 - 48 hours for a response.
