### ISSUE TITLE
Can not get HOOBS to update TO 3.3.12 OR VERSION 4

### ISSUE THREAD

**Issue by pricejordan41** [hoobs-org/HOOBS#1536]
**Description**
I have TWO HOOBS in a box servers - both of them are currently running 3.3.5, when I try to upgrade to 3.3.12 I click update, but then it just loads and does nothing and shut the box down. It then restarts and when you go back in to see the current version it still says 3.3.5 - I would like to upgrade to version 4, but don't know how. I think 

**Version**
3.3.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**

I am trying to upgrade to version 4

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No - They came on Version 3

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Ring
Google Nest
Camera FFMPEG
Dummy Switches

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

Server 1:

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY9PK4",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "accessories",
        "inactive_logoff": 30,
        "theme": "throwback-blue",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "76712"
    },
    "bridge": {
        "name": "HOOBS Server 1",
        "port": 51826,
        "pin": "031-45-154",
        "username": "57:31:07:8E:70:D5"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "name": "Arrived Home"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "name": "Left Home"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "name": "Arming Security System AWAY"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "name": "Disarming Security System"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": false,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "name": "setting alarm to home"
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-google-nest"
            },
            "name": "Nest Thermostat",
            "fanDurationMinutes": 30,
            "googleAuth": {
                "cookies": "REMOVED",
                "issueToken": "REMOVED",
                "apiKey": "REMOVED"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera FFmpeg"
        }
    ]
}
```

SERVER 2:

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY14OH",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS Server 2",
        "port": 51826,
        "pin": "031-45-154",
        "username": "9B:5F:9B:D5:5A:AC"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "REMOVED",
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "locationIds": [
                "91e05712-fca9-471d-9fcd-5cdc4387e022"
            ],
            "hideCameraSirenSwitch": true
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

FROM SERVER 2:

```
9/23/2021, 3:17:14 PM HOOBS listening on port 80.
9/23/2021, 3:17:16 PM Initializing HAP-NodeJS v0.9.3...
9/23/2021, 3:17:21 PM Loaded plugin 'homebridge-ring'
9/23/2021, 3:17:21 PM [9/23/2021, 2:17:21 PM] Registering platform 'homebridge-ring.Ring'
9/23/2021, 3:17:21 PM Loading 1 platforms...
9/23/2021, 3:17:21 PM [Ring] Initializing Ring platform...
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory ceeccc03-b6e2-4a46-b97d-a6982b7af494 Alarm
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 5c1019d0-6015-47d4-87d7-2edea2aa81ab Front Door
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 9474e1c8-7a41-4201-b10e-4caffa91686a Garage Door
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory cb400e95-d7ec-49f7-b37d-a849ff0ed345 Guest Bedroom Window
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 59b9f93c-ee04-4aa5-aed0-7c27cc896aff Back Door
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 8fd39fd8-3b5a-48b7-9a63-66e09178c22f Living Room
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 57201b05-d266-4e1e-9277-600ed9dec7b6 Office Window
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 7235c695-5641-416d-bdd4-dc31c60d092b Master Bedroom
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 06e6e4e1-1323-46f8-977f-f81de5abdf7e Office Cam
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 19205232-6960-46d0-a54d-5476457d29e2 Living Room
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory ec81c2bd-aa38-4a65-9c4b-7bf16b3b5f4b Drive Way
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 5f3a6269-29d5-404a-94f7-84146616cf60 Front Door
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 40746ae1-5bb4-4b41-ae09-ec5cc1cf5d53 Living Room Chime
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory b82f6a86-e689-4072-bb04-c6172ade5a32 Back yard
9/23/2021, 3:17:21 PM [Ring] Configuring cached accessory 9edd08ec-98ca-4479-972c-6bbec7f2f713 Drive Way
9/23/2021, 3:17:21 PM Preparing Advertiser for 'HOOBS Server 2 E888' using bonjour-hap backend!
9/23/2021, 3:17:22 PM Starting to advertise 'HOOBS Server 2 E888' using bonjour-hap backend!
9/23/2021, 3:17:22 PM Bridge is running on port 51826.
9/23/2021, 3:17:23 PM [Ring] Found the following locations:
9/23/2021, 3:17:23 PM [Ring]   locationId: 91e05712-fca9-471d-9fcd-5cdc4387e022 - Jordan's Home
9/23/2021, 3:17:23 PM [Ring] Creating location socket.io connection - Jordan's Home
9/23/2021, 3:17:25 PM [Ring] Ring connected to socket.io server
9/23/2021, 3:17:26 PM [Ring] Configuring 6 cameras and 25 devices for location "Jordan's Home" - locationId: 91e05712-fca9-471d-9fcd-5cdc4387e022
9/23/2021, 3:17:26 PM [Ring] Hidden accessory 0da7a3b1-a45b-4dcd-9c82-656faa042a42 hub.redsky Base Station
9/23/2021, 3:17:26 PM [Ring] Hidden accessory 0558cf25-5b38-4cf9-bbe1-bfc621263e40 security-keypad Garage door keypad
9/23/2021, 3:17:26 PM [Ring] Hidden accessory ee1b8082-33be-435e-b6fe-964cfa58f032 security-keypad Entryway Keypad
9/23/2021, 3:17:26 PM [Ring] Hidden accessory 296c8f41-84b5-404b-953b-5905d447b0d4 security-keypad Back Door Keypad
9/24/2021, 6:45:34 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 6:47:59 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 6:48:39 PM [Ring] Arming (Away) Alarm
9/24/2021, 6:48:43 PM [Ring] Disarming Alarm
9/24/2021, 6:49:46 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 6:50:01 PM [Ring] Preparing Live Stream for Back yard
9/24/2021, 6:50:02 PM [Ring] Waiting for stream data from Back yard (1.152s)
9/24/2021, 6:50:03 PM [Ring] Received stream data from Back yard (2.282s)
9/24/2021, 6:50:04 PM [Ring] Streaming active for Back yard
9/24/2021, 6:50:11 PM [Ring] Stopped Live Stream for Back yard
9/24/2021, 6:51:39 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 6:52:59 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 6:54:17 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 6:57:50 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 6:58:57 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 7:00:07 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 7:00:33 PM [Ring] Preparing Live Stream for Living Room
9/24/2021, 7:00:34 PM [Ring] Waiting for stream data from Living Room (0.927s)
9/24/2021, 7:00:34 PM [Ring] Received stream data from Living Room (1.489s)
9/24/2021, 7:00:35 PM [Ring] Streaming active for Living Room
9/24/2021, 7:00:50 PM [Ring] Stopped Live Stream for Living Room
9/24/2021, 7:00:51 PM [Ring] Preparing Live Stream for Front yard
9/24/2021, 7:00:52 PM [Ring] Waiting for stream data from Front yard (0.926s)
9/24/2021, 7:00:52 PM [Ring] Received stream data from Front yard (1.141s)
9/24/2021, 7:00:52 PM [Ring] Streaming active for Front yard
9/24/2021, 7:01:01 PM [Ring] Stopped Live Stream for Front yard
9/24/2021, 7:01:12 PM [Ring] Preparing Live Stream for Office Cam
9/24/2021, 7:01:13 PM [Ring] Ding 7011654391338595258 is expired (480).  Fetching a new ding and trying video stream again
9/24/2021, 7:01:13 PM err:  Error: remote peer disconnected
9/24/2021, 7:01:13 PM at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip.js:557:38)
9/24/2021, 7:01:13 PM at TLSSocket.emit (events.js:388:22)
9/24/2021, 7:01:13 PM at endReadableNT (internal/streams/readable.js:1336:12)
9/24/2021, 7:01:13 PM at processTicksAndRejections (internal/process/task_queues.js:82:21)
9/24/2021, 7:01:13 PM [Ring] Waiting for stream data from Office Cam (1.13s)
9/24/2021, 7:01:13 PM [Ring] Received stream data from Office Cam (1.282s)
9/24/2021, 7:01:14 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 7:01:14 PM [Ring] Streaming active for Office Cam
9/24/2021, 7:01:25 PM [Ring] Stopped Live Stream for Office Cam
9/24/2021, 7:01:25 PM [Ring] Preparing Live Stream for Living Room
9/24/2021, 7:01:26 PM [Ring] Ding 7011654511592085187 is expired (480).  Fetching a new ding and trying video stream again
9/24/2021, 7:01:26 PM err:  Error: remote peer disconnected
9/24/2021, 7:01:26 PM at TLSSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip.js:557:38)
9/24/2021, 7:01:26 PM at TLSSocket.emit (events.js:388:22)
9/24/2021, 7:01:26 PM at endReadableNT (internal/streams/readable.js:1336:12)
9/24/2021, 7:01:26 PM at processTicksAndRejections (internal/process/task_queues.js:82:21)
9/24/2021, 7:01:27 PM [Ring] Waiting for stream data from Living Room (1.397s)
9/24/2021, 7:01:28 PM [Ring] Received stream data from Living Room (2.714s)
9/24/2021, 7:01:28 PM [Ring] Streaming active for Living Room
9/24/2021, 7:01:32 PM [Ring] Front Door Detected Motion
9/24/2021, 7:01:34 PM [Ring] Stopped Live Stream for Living Room
9/24/2021, 7:12:00 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 7:14:08 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 7:16:37 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
9/24/2021, 7:17:44 PM [Ring] Office Cam Detected Motion. Loading snapshot before sending event to HomeKit
```

**Additional context**

**Comment by mkellsy** [comment]
What do you get when you run this
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by pricejordan41** [comment]
```
obsbs@hoobs:/home/hoobs/.hoobs/etc $ sudo npm install -g --unsafe-perm @hoobs/hoo
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-26T21_56_46_000Z-debug.log
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
```

That is what I get.

**Comment by pricejordan41** [comment]
> What do you get when you run this
> 
> ```
> sudo npm install -g --unsafe-perm @hoobs/hoobs
> ```

**Comment by mkellsy** [comment]
Here's how to fix that error
https://support.hoobs.org/docs/60e62f336c19a6a5ca8f580f

**Comment by pricejordan41** [comment]
I keep getting this error chain: 

```
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:dKDzr8ptROqmZr/kDCTCiDR14xjJ4s0hSAW+9XIibv8.
Please contact your system administrator.
Add correct host key in /Users/jordanprice/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/jordanprice/.ssh/known_hosts:1
ECDSA host key for hoobs.local has changed and you have requested strict checking.
Host key verification failed.
jordanprice@Jordans-Mac-mini ~ % /Users/jordanprice/.ssh/known_hosts
zsh: permission denied: /Users/jordanprice/.ssh/known_hosts
jordanprice@Jordans-Mac-mini ~ % 
```

**Comment by pricejordan41** [comment]
@mkellsy - I was able to remove the ssh hoobs@"hoobs.local" and replace with the IP address of the server I am updating (again I have two units) - which then let me in. 

However, once running the code to reinstall Hoobs, I get this chain of error messages:

```
hoobs@hoobs:~ $ sudo rm -fR /usr/local/lib/node_modules/@hoobs
hoobs@hoobs:~ $ sudo npm install -g --unsafe-perm @hoobs/hoobs
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/usr/local/lib/node_modules/@hoobs',
npm WARN cleanup     [Error: EROFS: read-only file system, rmdir '/usr/local/lib/node_modules/@hoobs'] {
npm WARN cleanup       errno: -30,
npm WARN cleanup       code: 'EROFS',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/usr/local/lib/node_modules/@hoobs'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! make: Entering directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
npm ERR!   CXX(target) Release/obj.target/pty/src/unix/pty.o
npm ERR! make: Leaving directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.0 | linux | arm
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
npm ERR! ../src/unix/pty.cc:486:43: warning: ‘void* memset(void*, int, size_t)’ writing to an object of type ‘class Nan::Persistent<v8::Function>’ with no trivial copy-assignment [-Wclass-memaccess]
npm ERR!    memset(&baton->cb, -1, sizeof(baton->cb));
npm ERR!                                            ^
npm ERR! In file included from ../../nan/nan.h:407,
npm ERR!                  from ../src/unix/pty.cc:20:
npm ERR! ../../nan/nan_persistent_12_inl.h:12:40: note: ‘class Nan::Persistent<v8::Function>’ declared here
npm ERR!  template<typename T, typename M> class Persistent :
npm ERR!                                         ^~~~~~~~~~
npm ERR! In file included from ../../nan/nan.h:58,
npm ERR!                  from ../src/unix/pty.cc:20:
npm ERR! ../src/unix/pty.cc: At global scope:
npm ERR! /root/.cache/node-gyp/14.17.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!        (node::addon_register_func) (regfunc),                          \
npm ERR!                                            ^
npm ERR! /root/.cache/node-gyp/14.17.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!    NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!    ^~~~~~~~~~~~~
npm ERR! ../src/unix/pty.cc:708:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!  NODE_MODULE(pty, init)
npm ERR!  ^~~~~~~~~~~
npm ERR! during RTL pass: combine
npm ERR! ../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyGetProc(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/unix/pty.cc:403:1: internal compiler error: Bus error
npm ERR!  }
npm ERR!  ^
npm ERR! /usr/lib/debug/.build-id/cd/2c63b6e3f197ec331e0b6db3556717a4334e0e.debug: Input/output error
npm ERR! /usr/lib/debug//usr/lib/gcc/arm-linux-gnueabihf/8/2c63b6e3f197ec331e0b6db3556717a4334e0e.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/a9/0cce12f2cf78f277bea689e5b5192d1eb184ec.debug: Input/output error
npm ERR! /usr/lib/debug//usr/lib/arm-linux-gnueabihf/0cce12f2cf78f277bea689e5b5192d1eb184ec.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/ec/388ce3d7a91f24482f8a5246299cb6d2b1285a.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/388ce3d7a91f24482f8a5246299cb6d2b1285a.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/a6/010f1538e27bea78bb9c1ec44e4b4f905c182c.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/010f1538e27bea78bb9c1ec44e4b4f905c182c.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/f3/05e05f58c5f0ec6b3a673163bc40cc722fcab0.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/05e05f58c5f0ec6b3a673163bc40cc722fcab0.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/7e/4394818ff15f29c729ffa8417a1e22ec3852b0.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/4394818ff15f29c729ffa8417a1e22ec3852b0.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/bc/c9ee6666973f3f41da5bdf8c8d7c299e4a09a2.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/c9ee6666973f3f41da5bdf8c8d7c299e4a09a2.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/2e/0f28fd5cc5dcfa1d8aab98635fc705c4e82b15.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/0f28fd5cc5dcfa1d8aab98635fc705c4e82b15.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/24/22b5cf95895f5f4f69dae68ad9f99198e43121.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/22b5cf95895f5f4f69dae68ad9f99198e43121.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/ef/dd27c16f5283e5c53dcbd1bbc3ef136e312d1b.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/dd27c16f5283e5c53dcbd1bbc3ef136e312d1b.debug: Input/output error
npm ERR! /usr/lib/debug/.build-id/fb/85e699c11db06c7b24f74de2cdada3146442a8.debug: Input/output error
npm ERR! /usr/lib/debug//lib/arm-linux-gnueabihf/85e699c11db06c7b24f74de2cdada3146442a8.debug: Input/output error
npm ERR! Please submit a full bug report,
npm ERR! with preprocessed source if appropriate.
npm ERR! See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
npm ERR! make: *** [pty.target.mk:109: Release/obj.target/pty/src/unix/pty.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 5.4.72-v7+
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
```

Now, when trying to pull up the hoobs interface - I am presented with this code:

```
Error: EIO: i/o error, stat '/usr/local/lib/node_modules/@hoobs/hoobs/interface/system/software'
```

**Comment by mkellsy** [comment]
Are you trying to access SSH with double quotes around the hostname?
Don't do that. The command is this
```
ssh hoobs@hoobs.local
```

Also the warning you are getting about SSH. This could be caused by 2 reasons.
1. The SSH key is wrong in your `/Users/jordanprice/.ssh/known_hosts` file.
2. There is actually a virus on your network that is intercepting SSH traffic.

I would review the clients on your network. Maybe change your Wi-Fi password. Then I would remove your known_hosts file and start fresh.

```
rm -f /Users/jordanprice/.ssh/known_hosts
```

As for the GYP errors you are getting. The key is this log entry.
```
npm ERR! ../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyGetProc(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/unix/pty.cc:403:1: internal compiler error: Bus error
```

There is something wrong with Python on the system. It would be best to re-flash. Start fresh. You can backup the `/home/hoobs/.hoobs` folder before re-flashing, or at least save your config. You can view your config with this command.

```
cat /home/hoobs/.hoobs/etc/config.json
```

**Comment by pricejordan41** [comment]
how do I reflash? I can not get the dashboards to load and/or to access via Mac terminal. 

I think I was getting that error since there was two servers on? how do I select a different server? replace the "Hoobs.local" with the ip address?

**Comment by mkellsy** [comment]
Yes use the IP address. Version 4.0 allows you to change this.

**Comment by pricejordan41** [comment]
Okay so how do I refresh again?

**Comment by pricejordan41** [comment]
and how do I back up before reflashing without being able to access the hoobs dashboard

**Comment by mkellsy** [comment]
You have a HOOBS Box. Send an email to info@hoobs.com if you are not comfortable flashing we will take care of it for you. Please allow 24 - 48 hours for a response.
