### ISSUE TITLE
hoobsd not starting

### ISSUE THREAD

**Issue by NFMi** [hoobs-org/HOOBS#1730]
Hoobsd was running fine on raspberry Pi os. Today it I noticed that all lights connected through hoops are no longer working so I tried to restart hoops as usual when something like this happens.

sudo hoobsd restart puts out following error message

/usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:30
})();
  ^
Error: Error: Cannot find module './eiows_linux_83'
Require stack:
- /usr/lib/hoobsd/node_modules/eiows/dist/eiows.js
- /usr/lib/hoobsd/hub/index.js
- /usr/lib/hoobsd/main.js
- /usr/bin/hoobsd

Compilation of µWebSockets has failed and there is no correct pre-compiled binary available for your system or an unsupported node version is used. Please install a supported C++17 compiler or update node and reinstall the module 'eiows'.
    at /usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:27:15
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:30:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/src/hub/index.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/src/main.ts:33:1) 

the same massage appears in the logs

pi@raspberrypi:~ $ sudo hbs log
25.12.2021, 05:31:28 Hue Bridge  ERROR  ^
25.12.2021, 05:31:28 Hue Bridge  ERROR  Error: Error: Cannot find module './eiows_linux_83'
25.12.2021, 05:31:28 Hue Bridge  ERROR  Require stack:
25.12.2021, 05:31:28 Hue Bridge  ERROR  - /usr/lib/hoobsd/node_modules/eiows/dist/eiows.js
25.12.2021, 05:31:28 Hue Bridge  ERROR  - /usr/lib/hoobsd/hub/index.js
25.12.2021, 05:31:28 Hue Bridge  ERROR  - /usr/lib/hoobsd/main.js
25.12.2021, 05:31:28 Hue Bridge  ERROR  - /usr/bin/hoobsd
25.12.2021, 05:31:28 Hue Bridge  ERROR  at /usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:27:15
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Object.<anonymous> (/usr/lib/hoobsd/node_modules/eiows/dist/eiows.js:30:3)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Module._compile (internal/modules/cjs/loader.js:1085:14)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Module.load (internal/modules/cjs/loader.js:950:32)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Module.require (internal/modules/cjs/loader.js:974:19)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at require (internal/modules/cjs/helpers.js:93:18)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Object.<anonymous> (/usr/src/hub/index.ts:25:1)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Module._compile (internal/modules/cjs/loader.js:1085:14)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Module.load (internal/modules/cjs/loader.js:950:32)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Module.require (internal/modules/cjs/loader.js:974:19)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at require (internal/modules/cjs/helpers.js:93:18)
25.12.2021, 05:31:28 Hue Bridge  ERROR  at Object.<anonymous> (/usr/src/main.ts:33:1)

can someone help me ?

**Comment by NFMi** [comment]
running sudo hbs install produces this error:

 ERROR  (node:2470) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 
    at new SemVer (/usr/lib/hbs/node_modules/semver/classes/semver.js:38:13)
    at compare (/usr/lib/hbs/node_modules/semver/functions/compare.js:3:32)
    at Object.gt (/usr/lib/hbs/node_modules/semver/functions/gt.js:2:29)
    at Object.info (/usr/src/system/index.ts:427:46)
    at Command.<anonymous> (/usr/src/main.ts:52:70)
    at Command.listener [as _actionHandler] (/usr/lib/hbs/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/usr/lib/hbs/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/usr/lib/hbs/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/usr/lib/hbs/node_modules/commander/index.js:1460:12)
    at Command.parse (/usr/lib/hbs/node_modules/commander/index.js:1292:10)
    at Main (/usr/src/main.ts:1050:13)
    at Object.<anonymous> (/usr/bin/hbs:23:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
(Use `node --trace-warnings ...` to show where the warning was created)
 ERROR  (node:2470) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 ERROR  (node:2470) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mkellsy** [comment]
Node or corrupt install could be you issue.
This command
```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```
should fix your install and Node for you

**Comment by NFMi** [comment]
Thank you.
I forget to post here but I updated node to v16.13.1
I don't know why, but it fixed the issue.

**Comment by cronusfortunam** [comment]
curl -sk https://dl.hoobs.org/fix | sudo bash - 

this command did not work for me
