### ISSUE TITLE
Cannot find lights in Hue Plugin

### ISSUE THREAD

**Issue by lxheckel** [hoobs-org/HOOBS#1767]
**Description**
I had been using HOOBS happily with my Apple Home Kit for over a year. In Dec. 2021 I started having connection issues and lost the connection to Apple Homekit entirely around 5.1.22. The log showed an error with the homebridge version which was supposed to be 1.3.9 but was 1.3.4. I found out that despite the fact that Dashboard showed that I had the latest version installed (4.0.something at the time) it was apparently not the latest version. I boldly reinstalled HOOBS and the Hue Plugin and reconnected the plugin to my (unchanged) Hue Bridge but since then I cannot access my lights any more no matter which boxes in the config of the plugin I check/uncheck - except for one smart plug. I have tried the usual (reboot, reinstall plugin, reinstall one of the lights etc.) but do not find a solution. I am running out of options.

**Expected behavoir**
Access the lights connected to the Philips Hue Bridge via the Hue Plugin

**Plugin name**
Hue

**Version**
4.1.21, node version 16.13.1, homebridge 1.3.9, plugin version 0.13.34

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No (clean reinstallation)

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

could not find the config in either one of the indicated places

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
8.1.2022, 22:14:55Hue Bridge starting
8.1.2022, 22:15:34Hue BridgeLoaded plugin 'homebridge-hue'
8.1.2022, 22:15:34Hue BridgeLoading 1 platforms...
8.1.2022, 22:15:34Hue BridgeLX Hue Bridgehomebridge-hue v0.13.34, node v16.13.1, homebridge v1.3.9
8.1.2022, 22:15:34Hue BridgeLX Hue Bridgesearching bridges and gateways
8.1.2022, 22:15:39Hue BridgeLX Hue BridgePhilips hue: Signify Netherlands B.V. BSB002 bridge v1949107040, api v1.48.0
8.1.2022, 22:15:40Hue BridgeLX Hue BridgePhilips hue: 2 accessories
8.1.2022, 22:15:40Hue BridgeLX Hue Bridgemasked debug info dumped to /var/lib/hoobs/huebridge/homebridge-hue.json.gz
8.1.2022, 22:15:40Hue BridgeLX Hue BridgePhilips hue: 2 services
8.1.2022, 22:15:40Hue BridgeBridge is running on port 51826.
8.1.2022, 22:15:40Hue BridgeLX Hue BridgePhilips hue: event stream connected to https://192.168.178.20/eventstream/clip/v2```

**Additional context**
plugin config:

    "platform": "Hue",
    "name": "LX Hue Bridge",
    "brightnessAdjustment": 100,
    "heartrate": 5,
    "lowBattery": 25,
    "timeout": 5,
    "waitTimePut": 50,
    "waitTimePutGroup": 1000,
    "waitTimeResend": 300,
    "waitTimeUpdate": 20,
    "lights": true,
    "group0": true,
    "users": {
        "001788FFFE2A1***": "gKigdHGcT2lI8ErwWu598af3EZLBnrB9TrJ95***"
    },
    "rooms": true
}

**Comment by lxheckel** [comment]
in case anybody asks: exposing groups shows for example "Group 0" which properly turns all lights on and off and I can also still access all lights properly from the Philips Hue app. Installing older versions of the Hue Plugin (for example 1.3.30 as of 3.12.21) also results in the same problem of not finding my lights. Maybe there are some old sins from previous configuration attempts on my Hue Bridge but I am desperately trying to avoid reinstalling all my smart devices as I have quite a few.

**Comment by lxheckel** [comment]
over night a new error msg appeared:
8.1.2022, 23:20:03LX Hue BridgeHueWarnungPhilips hue: event stream error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at EventStreamClient.parseUpdate (/var/lib/hoobs/lxhuebridge/node_modules/homebridge-hue/lib/EventStreamClient.js:230:26)
    at EventStreamClient.parseContainer (/var/lib/hoobs/lxhuebridge/node_modules/homebridge-hue/lib/EventStreamClient.js:198:16)
    at IncomingMessage.<anonymous> (/var/lib/hoobs/lxhuebridge/node_modules/homebridge-hue/lib/EventStreamClient.js:162:26)
    at IncomingMessage.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)

**Comment by lxheckel** [comment]
...just realized that this might not be the best place for the question. I have started a similar issue here: https://github.com/ebaauw/homebridge-hue/issues/1076 and will close both issues as soon as I get enough feedback.

**Comment by lxheckel** [comment]
Problem solved: https://github.com/ebaauw/homebridge-hue/issues/1076
