### ISSUE TITLE
Unable to sign in to Simplisafe Auth via web interface or Desktop app

### ISSUE THREAD

**Issue by andresmakesgames** [hoobs-org/HOOBS#1789]
**Description**
As noted in a closed ticket in the Simplisafe3 homebridge plugin (https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/271) authorizing with Simplisafe's new OAUTH protocol is not possible on the web inteface, and when selecting the Link Account button in the HOOBS Desktop app on both Windows and MacOS, we see a blank window with a close button that never resolves into the login page.

**Expected behavior**
Ideally, the window should open to Simplisafe's OATH login page so I can log in and get a token.

**Plugin name**
homebridge-simplisafe3

**Please report the issue to the plugin developer**
An issue was opened in their repo https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/271 and was closed by the developer, citing that this works in Homebridge's Config UI X, so this is an issue with HOOBS specifically.

**Version**
4.1.22

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Previous version**
3.1, though I do not believe this is a factor, as the problem is with authenticating on the Desktop app and not specifically a problem with the plugin.

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
I deleted the credentials. But they won't authenticate anyway - OAUTH is now needed as of December 2021.
```
{
    "platform": "homebridge-simplisafe3.SimpliSafe 3",
    "name": "Home Alarm",
    "cameras": true,
    "sensorRefresh": 15,
    "persistAccessories": true,
    "resetSimpliSafeId": true,
    "cameraOptions": {
        "enableHwaccelRpi": true
    }
}
```

**Post your log**
```
2/5/2022, 5:53:11 PMSimplisafe BridgeConfiguration change
2/5/2022, 5:53:11 PMsimplisafe3bridge stopping
2/5/2022, 5:53:16 PMSimplisafe Bridge starting
2/5/2022, 5:53:22 PMSimplisafe BridgeLoaded plugin 'homebridge-simplisafe3'
2/5/2022, 5:53:22 PMSimplisafe BridgeLoading 1 platforms...
2/5/2022, 5:53:22 PMSimplisafe BridgeHome AlarmERRORSimpliSafe login failed with error: Error: No authentication credentials detected.
    at SimpliSafe3AuthenticationManager.refreshCredentials (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/common/authManager.js:199:15)
    at new SS3Platform (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:90:41)
    at /usr/src/bridge/server.ts:455:46
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/src/bridge/server.ts:438:31)
    at Server.start (/usr/src/bridge/server.ts:239:69)
2/5/2022, 5:53:22 PMSimplisafe BridgeHome AlarmERRORSee the plugin README for more information on authenticating with SimpliSafe.
2/5/2022, 5:53:22 PMSimplisafe BridgeHome AlarmERRORInitial accessories refresh failed with error: Error: Not authenticated with SimpliSafe.
    at /var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:109:56
2/5/2022, 5:53:22 PMSimplisafe BridgeBridge is running on port 51866.
```

**Additional context**
As I mentioned, I tested on the Desktop app on both Windows and MacOS. I get the same blank screen. Trying to authenticate on the web interface is not possible.
Allegedly the plugin supports oath via terminal: https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#readme but SSHing into HOOBS, I see the CLI is very limited and I don't know how I could execute this command.

**Comment by andresmakesgames** [comment]
Found a fix. For those still having issues, uninstall the plugin and delete the bridge, then reinstall it into a new bridge. The Auth window then resolves correctly.
