### ISSUE TITLE
Hoobs issue unexepted Token if

### ISSUE THREAD

**Issue by mistertropi** [hoobs-org/HOOBS#1801]
Hey Guys,

I hope someone can help me.
I get the following error in the log when starting Hoobs:

SyntaxError: Unexpected token 'if'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/hap-nodejs/src/index.ts:3:1)

I dont know exactly what I can do....

Thank you

**Comment by mkellsy** [comment]
The error is from NodeJS, it looks like a corrupt install.

What device are you using?

**Comment by mistertropi** [comment]
Thanks man!
it is on a rasberry pi 3. the version is the current one. the error always comes over night...
