### ISSUE TITLE
Unable to connect to Hoobs 

### ISSUE THREAD

**Issue by michaelromero2020** [hoobs-org/HOOBS#1810]
**Description**
Was in the middle of updating my Hoobs unit and it didn't finish out. When I tried reconnecting I get a "site can't be reached" error. 

**Version**
Don't know 

**Did you upgrade**
Please let us know if you upgraded from a previous version.
Yes I was trying to. 

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ √] HOOBS Box

I was able to connect via the terminal (MAC OS) and here's the log. Any ideas of what I need to do?

> hoobs@hoobs:~ $ sudo hbs log
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at populateConstructorExports (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:243:9)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:30:1)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Module._compile (node:internal/modules/cjs/loader:1105:14)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Module.load (node:internal/modules/cjs/loader:981:32)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Module.require (node:internal/modules/cjs/loader:1005:19)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at require (node:internal/modules/cjs/helpers:102:18)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/index.js:15:19)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Module._compile (node:internal/modules/cjs/loader:1105:14)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Module.load (node:internal/modules/cjs/loader:981:32)
5/3/2022, 9:00:42 PM Xiaomi Roborock Vacuum Bridge  ERROR  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
5/3/2022, 9:00:43 PM Samsung Tizen Bridge starting
5/3/2022, 9:00:43 PM Simplisafe3 Bridge Configuration change
5/3/2022, 9:00:43 PM simplisafe3bridge stopping
5/3/2022, 9:00:44 PM Tplink Smarthome Bridge starting
5/3/2022, 9:00:50 PM Simplisafe3 Bridge starting
5/3/2022, 9:00:50 PM Xiaomi Roborock Vacuum Bridge starting
5/3/2022, 9:00:52 PM myQ Bridge starting
5/3/2022, 9:00:53 PM  ERROR  Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:866:20)
    at ChildProcess.target.send (node:internal/child_process:739:19)
    at /usr/src/hub/services/socket.ts:66:33
    at new Promise (<anonymous>)
    at Socket.fetch (/usr/src/hub/services/socket.ts:50:16)
    at /usr/src/hub/services/ipc.ts:39:41
    at new Promise (<anonymous>)
    at HubIPC.fetch (/usr/src/hub/services/ipc.ts:35:16)
    at /usr/src/hub/services/monitor.ts:35:28
    at new Promise (<anonymous>)
    at Monitor (/usr/src/hub/services/monitor.ts:34:24)
    at Timeout._a [as _onTimeout] (/usr/src/hub/services/monitor.ts:88:44)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
5/3/2022, 9:00:53 PM Homekit stopping
5/3/2022, 9:00:53 PM myQ Bridge stopping
5/3/2022, 9:00:53 PM Simplisafe3 Bridge stopping
5/3/2022, 9:00:53 PM Tplink Smarthome Bridge stopping
5/3/2022, 9:00:53 PM Ikea Tradfri Gateway Bridge stopping
5/3/2022, 9:00:53 PM Govee Bridge stopping
5/3/2022, 9:00:53 PM Samsung Tizen Bridge stopping
5/3/2022, 9:00:53 PM Xiaomi Roborock Vacuum Bridge stopping
5/3/2022, 9:00:53 PM Tuya Web Bridge stopping
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  /usr/lib/hoobsd/node_modules/toidentifier/index.js:26
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  .split(' ')
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  ^
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  TypeError: Cannot read properties of undefined (reading 'split')
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at toIdentifier (/usr/lib/hoobsd/node_modules/toidentifier/index.js:26:6)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at forEachCode (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:245:16)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Array.forEach (<anonymous>)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at populateConstructorExports (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:243:9)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:30:1)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Module._compile (node:internal/modules/cjs/loader:1105:14)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Module.load (node:internal/modules/cjs/loader:981:32)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Module.require (node:internal/modules/cjs/loader:1005:19)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at require (node:internal/modules/cjs/helpers:102:18)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/index.js:15:19)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Module._compile (node:internal/modules/cjs/loader:1105:14)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Module.load (node:internal/modules/cjs/loader:981:32)
5/3/2022, 9:00:54 PM Samsung Tizen Bridge  ERROR  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
hoobs@hoobs:~ $ 

>

**Comment by michaelromero2020** [comment]
`hoobs@hoobs:~ $ sudo hbs system versions

/usr/lib/hoobsd/node_modules/toidentifier/index.js:26
    .split(' ')
     ^
TypeError: Cannot read properties of undefined (reading 'split')
    at toIdentifier (/usr/lib/hoobsd/node_modules/toidentifier/index.js:26:6)
    at forEachCode (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:245:16)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:243:9)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/index.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

application | distribution | package_manager | version | latest  | upgraded | init_system | running
---------------------------------------------------------------------------------------------------
cli         | raspbian     | apt-get         | 4.2.4   | 4.2.4   | true     |             |        
gui         | raspbian     | apt-get         | 4.2.2   | 4.2.2   | true     |             |        
hoobsd      | raspbian     | apt-get         |         | 4.2.5   | true     | systemd     | false  
node        | raspbian     | apt-get         | 16.15.0 | 16.15.0 | true     |             |        

hoobs@hoobs:~ $ 
`

**Comment by michaelromero2020** [comment]
> hoobs@hoobs:~ $ sudo hbs system upgrade
node is already up-to-date
cli is already up-to-date

/usr/lib/hoobsd/node_modules/toidentifier/index.js:26
    .split(' ')
     ^
TypeError: Cannot read properties of undefined (reading 'split')
    at toIdentifier (/usr/lib/hoobsd/node_modules/toidentifier/index.js:26:6)
    at forEachCode (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:245:16)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:243:9)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/index.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
hoobsd is already up-to-date
gui is already up-to-date
>

**Comment by mkellsy** [comment]
The fix script has the changes, it should fix this error too. It's a yarn cache issue.
```
curl -sk https://dl.hoobs.org/fix | sudo bash -
```

If this doesn't work please open a support ticket here
https://support.hoobs.org/ticket
