### ISSUE TITLE
Device already registered, reset device

### ISSUE THREAD

**Issue by jwvanderbeck** [hoobs-org/HOOBS#1826]
**Description**
All of my HOOBS devices stopped responding in the Home app (they work fine in HOOBS).  In a desperate attempt to fix it I removed the hubs then went to re-add them but when I did I got an error saying the device is already added and I need to reset it first.

However I can find no way to reset it inside HOOBS.  I found search results from older versions of HOOBS saying to go to the Help menu and click Reset but the help menu in HOOBS 4 just takes me to a webpage for documentation and no where in there can I find any information on resetting a devce (I searched for "reset" in the docs)

**Version**
4.2.5

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Nest, Nest Cam, myQ originally.  In an attempt at trouble shooting I removed all plugins but Nest at the moment.

**Post your config**
* Remove any passwords from the config file. This is public.

```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "refreshToken": "removed",
            "name": "Nest"
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
6/21/2022, 2:55:00 AMNest BridgeNestErrorNest API call to subscribe to device settings updates returned an error: ENOTFOUND6/21/2022, 2:55:00 AMNest BridgeNestRetrying in 10 seconds.6/21/2022, 2:59:10 AMNest BridgeNestErrorNest API call to subscribe to device settings updates returned an error: ENOTFOUND6/21/2022, 2:59:10 AMNest BridgeNestRetrying in 10 seconds.6/21/2022, 7:46:32 PMNest BridgeBridge change6/21/2022, 7:46:33 PMnestbridge stopping6/21/2022, 7:46:36 PMNest Bridge starting6/21/2022, 7:46:38 PMnestbridge stopping6/21/2022, 7:46:41 PMNest Bridge starting6/21/2022, 7:46:46 PMNest BridgeLoaded plugin 'homebridge-nest'6/21/2022, 7:46:46 PMNest BridgeLoading 1 platforms...6/21/2022, 7:46:46 PMNest BridgeNestFetching Nest devices.6/21/2022, 7:46:46 PMNest BridgeBridge is running on port 51826.6/21/2022, 7:46:50 PMNest BridgeNestiniting home_away_sensor "Home Occupied": deviceId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c2 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/21/2022, 7:46:50 PMNest BridgeNestiniting lock (P) "Entryway Lock": deviceId: 00177A00000D0FD0 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/21/2022, 7:47:34 PMnestcambridge stopping6/21/2022, 7:47:39 PMNest Cam Bridge starting6/21/2022, 7:51:38 PMnestcambridge stopping6/21/2022, 7:51:43 PMNest Cam Bridge starting6/21/2022, 7:52:20 PMnestcambridge stopping6/21/2022, 7:52:57 PMNest Cam Bridge starting6/21/2022, 7:53:24 PMnestcambridge stopping6/21/2022, 7:53:29 PMNest Cam Bridge starting6/21/2022, 7:54:14 PMnestcambridge stopping6/21/2022, 7:54:19 PMNest Cam Bridge starting6/21/2022, 7:55:07 PMnestbridge stopping6/21/2022, 7:55:31 PMNest Bridge starting6/21/2022, 7:55:43 PMNest BridgeLoaded plugin 'homebridge-nest'6/21/2022, 7:55:43 PMNest BridgeLoading 1 platforms...6/21/2022, 7:55:43 PMNest BridgeNestFetching Nest devices.6/21/2022, 7:55:43 PMNest BridgeNestErrorYou did not specify your Nest account credentials {'email','password'}, or an access_token, refreshToken, or googleAuth, in config.json6/21/2022, 7:55:43 PMNest BridgeNestErrorNOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.6/21/2022, 7:55:44 PMNest BridgeBridge is running on port 51826.6/21/2022, 7:55:46 PMNest BridgeConfiguration change6/21/2022, 7:55:46 PMnestbridge stopping6/21/2022, 7:55:51 PMNest Bridge starting6/21/2022, 7:55:56 PMNest BridgeLoaded plugin 'homebridge-nest'6/21/2022, 7:55:56 PMNest BridgeLoading 1 platforms...6/21/2022, 7:55:56 PMNest BridgeNestFetching Nest devices.6/21/2022, 7:55:57 PMNest BridgeBridge is running on port 51826.6/21/2022, 7:56:00 PMNest BridgeNestiniting home_away_sensor "Home Occupied": deviceId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c2 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/21/2022, 7:56:00 PMNest BridgeNestiniting lock (P) "Entryway Lock": deviceId: 00177A00000D0FD0 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/21/2022, 8:09:40 PMNest BridgeError[Nest Bridge 0F0A@Home Occupied@Home Occupied@On] SET handler returned write response value, though the characteristic doesn't support write response6/21/2022, 8:09:44 PMNest BridgeError[Nest Bridge 0F0A@Home Occupied@Home Occupied@On] SET handler returned write response value, though the characteristic doesn't support write response6/22/2022, 2:30:00 AMNest BridgeNestErrorAPI observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}6/22/2022, 2:30:00 AMNest BridgeNestError^^^^^ this message is for information only, it does not mean there is a problem, please do not file a ticket unless you actually have a problem with the function of the plug-in6/22/2022, 2:30:00 AMNest BridgeNestErrorRetrying in 10 seconds.6/22/2022, 7:25:11 AMNest BridgeNestErrorAPI observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}6/22/2022, 7:25:11 AMNest BridgeNestError^^^^^ this message is for information only, it does not mean there is a problem, please do not file a ticket unless you actually have a problem with the function of the plug-in6/22/2022, 7:25:11 AMNest BridgeNestErrorRetrying in 10 seconds.6/22/2022, 8:53:20 AMNest BridgeNestErrorNest API call to subscribe to device settings updates returned an error: EAI_AGAIN6/22/2022, 8:53:20 AMNest BridgeNestRetrying in 10 seconds.6/22/2022, 12:06:30 PMhub is running on port 806/22/2022, 12:06:31 PMmyQ Bridge starting6/22/2022, 12:06:31 PMNest Cam Bridge starting6/22/2022, 12:06:32 PMNest Bridge starting6/22/2022, 12:06:38 PMNest BridgeLoaded plugin 'homebridge-nest'6/22/2022, 12:06:38 PMNest BridgeLoading 1 platforms...6/22/2022, 12:06:38 PMNest BridgeNestFetching Nest devices.6/22/2022, 12:06:39 PMNest BridgeBridge is running on port 51826.6/22/2022, 12:06:43 PMNest BridgeNestiniting home_away_sensor "Home Occupied": deviceId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c2 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/22/2022, 12:06:43 PMNest BridgeNestiniting lock (P) "Entryway Lock": deviceId: 00177A00000D0FD0 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/22/2022, 12:22:29 PMNest BridgeNestErrorAPI observe: error Error: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at new NodeError (node:internal/errors:372:5)
    at ClientHttp2Stream._destroy (node:internal/http2/core:2332:13)
    at _destroy (node:internal/streams/destroy:102:25)
    at ClientHttp2Stream.destroy (node:internal/streams/destroy:64:5)
    at Http2Stream.onStreamClose (node:internal/http2/core:544:12) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}6/22/2022, 12:22:29 PMNest BridgeNestError^^^^^ this message is for information only, it does not mean there is a problem, please do not file a ticket unless you actually have a problem with the function of the plug-in6/22/2022, 12:22:29 PMNest BridgeNestErrorRetrying in 10 seconds.6/22/2022, 8:28:28 PMmyqbridge stopping6/22/2022, 8:28:36 PMnestcambridge stopping6/22/2022, 8:28:38 PMErrorError: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:866:20)
    at ChildProcess.target.send (node:internal/child_process:739:19)
    at /usr/src/hub/services/socket.ts:66:33
    at new Promise (<anonymous>)
    at Socket.fetch (/usr/src/hub/services/socket.ts:50:16)
    at /usr/src/hub/services/ipc.ts:39:41
    at new Promise (<anonymous>)
    at HubIPC.fetch (/usr/src/hub/services/ipc.ts:35:16)
    at AccessoriesController.get (/usr/src/hub/controllers/accessories.ts:156:44)
    at /usr/src/hub/controllers/accessories.ts:34:146
    at Layer.handle [as handle_request] (/usr/lib/hoobsd/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/hoobsd/node_modules/express/lib/router/route.js:144:13)
    at Security (/usr/src/services/security.ts:33:9)6/22/2022, 8:28:38 PMNest Bridge stopping6/22/2022, 8:28:52 PMhub is running on port 806/22/2022, 8:28:54 PMNest Bridge starting6/22/2022, 8:28:59 PMNest BridgeLoaded plugin 'homebridge-nest'6/22/2022, 8:28:59 PMNest BridgeLoading 1 platforms...6/22/2022, 8:28:59 PMNest BridgeNestFetching Nest devices.6/22/2022, 8:28:59 PMNest BridgeBridge is running on port 51826.6/22/2022, 8:29:03 PMNest BridgeNestiniting home_away_sensor "Home Occupied": deviceId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c2 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/22/2022, 8:29:03 PMNest BridgeNestiniting lock (P) "Entryway Lock": deviceId: 00177A00000D0FD0 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/22/2022, 8:37:58 PMnestbridge stopping6/22/2022, 8:38:03 PMNest Bridge starting6/22/2022, 8:38:08 PMNest BridgeLoaded plugin 'homebridge-nest'6/22/2022, 8:38:08 PMNest BridgeLoading 1 platforms...6/22/2022, 8:38:08 PMNest BridgeNestFetching Nest devices.6/22/2022, 8:38:08 PMNest BridgeBridge is running on port 51826.6/22/2022, 8:38:12 PMNest BridgeNestiniting home_away_sensor "Home Occupied": deviceId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c2 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c26/22/2022, 8:38:12 PMNest BridgeNestiniting lock (P) "Entryway Lock": deviceId: 00177A00000D0FD0 structureId: 8fc980c7-eb63-11ec-b1d6-0a008177e7c2
```

**Additional context**
Note, the log includes lines from the plugins I removed while trying to troubleshoot.
The devices have always shown up and worked fine in HOOBS itself but not inside the Home app.  They initially worked, but then just have showed not responding for days now.

**Comment by askovi** [comment]
Homekit wants the bridge to be reset, meaning it needs a new identifier. Go to that bridge page and click the Generate New Identifier button. Wait for the bridge to restart after so you get the new QR code then you'll be able to scan it again.

**Comment by jwvanderbeck** [comment]
I did the Generate New Identifier already but even after changing it and restarting the bridge it said the same thing.  However I just stumbled onto the "Cache" and specifically clearing the cache which warns me this will make the device be seen as new in Homekit so let's see if that works.

**Comment by jwvanderbeck** [comment]
Well despite the warning saying I would need to repair after it doesn't appear to have worked, and Homekit still says it is already paired :(  So I've tried both the Generate New Identifier and Cache->Clear options (saving and restarting the bridge each time) but Homekit still insists it is already paired and needs to be reset first.

**Comment by askovi** [comment]
Did you remove the bridge from Homekit first? In Home settings -> Hubs & Bridges.
Then generate new identifier. Make sure the QR code refreshes to a new one then scan.

**Comment by jwvanderbeck** [comment]
Yes that was the first step I had taken in an attempt to "remove and re-add".  The hub no longer shows in Homekit.

**Comment by jwvanderbeck** [comment]
I wonder if the QR code wasn't actually updating for some reason.  I restarted the bridge a few times, then I force refreshed my browser and scanned again and now it is working!
