### ISSUE TITLE
red error-message in the log

### ISSUE THREAD

**Issue by The-Paw** [hoobs-org/HOOBS#1860]
**Version**
4.2.8

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
midea air
hue
eveatmo
xiaomi fan
broadlink rm pro

```
2.3.2023, 18:23:03WARNUNGdevice reboot command received
2.3.2023, 18:23:03FEHLERError: Command failed: killall dnsmasq || true
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Hotspot.stop (/usr/lib/hoobsd/node_modules/@hoobs/network/lib/hotspot.js:115:9)
    at process.teardown (/usr/lib/hoobsd/node_modules/@hoobs/network/index.js:72:21)
    at process.emit (node:events:525:35)
    at process.emit (/usr/lib/hoobsd/node_modules/source-map-support/source-map-support.js:516:21)
```

What could be the case ??

**Comment by askovi** [comment]
That message can safely be ignored. The unit was trying to stop the network hotspot before rebooting.
