### ISSUE TITLE
Hoobs Desktop unreachable/blank

### ISSUE THREAD

**Issue by apolinski** [hoobs-org/HOOBS#1866]
**Description**
I setup my Hoobs box and updated the firmware.  Upon reboot the desktop looked fine and everything appeared to be working.  I then tried to install the sunsa wand bridge.  After reboot, the desktop comes up blank in the web interface. All of the skeleton of the web interface is there but no content.  Using the Hoobs Desktop, it cannot find a device.  The terminal (putty) seems to connect but I don't know a lot of how to debug via the terminal.  

I tried the Hoobs fix command (curl...) twice as instructed and it didn't change anything.  I can't create a backup (don't know how via terminal) or reflash the card.  The command I googled for dumping the log doesn't work.  I've run out of things to try and the Hoobs is essentially just a paperweight now.

**Version**
Unknown but I think it successfully updated on 4/24/2023.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
Yes

**Pervious version**
I don't know which version the box came with but I bought it a year ago.

**What device are you using?**
Please let us know the device you are running HOOBS on.
 HOOBS Box

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

No plugins.  Just tried to install the sunsa-homebridge when the issue happened.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
hoobs@hoobs:~ $ cat ~/.hoobs/etc/config.json
cat: /home/hoobs/.hoobs/etc/config.json: No such file or directory
```

**Post your log**
You can get the log from the interface. This is in the Log section.
Interface is not working.

```
N/A
```

**Additional context**

**Comment by apolinski** [comment]
Additional:

TypeError: Cannot read properties of undefined (reading 'split')
    at toIdentifier (/usr/lib/hoobsd/node_modules/toidentifier/index.js:26:6)
    at forEachCode (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:245:16)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:243:9)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/node_modules/http-errors/index.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/usr/lib/hoobsd/node_modules/send/index.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
 ERROR  TypeError: system_1.default.hoobsd.upgrade is not a function
    at Command.<anonymous> (/usr/src/main.ts:52:121)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by askovi** [comment]
I can't seem to be able to replicate the issue with the sunsa wand plugin. I assume something else must have gone wrong that could have corrupted your microSD card. If you are able to, try reflashing it using these instructions: https://support.hoobs.org/topics/resetting-re-flashing/how-to-i-re-flash-the-software

Otherwise, please reach out to HOOBS Support here for additional help or replacement under warranty: https://support.hoobs.org/ticket
