### ISSUE TITLE
HOOBS on macOS, Failing to Start

### ISSUE THREAD

**Issue by salpena78** [hoobs-org/HOOBS#284]
upgraded and I get this:

homebridge.service: Failed with result 'exit-code'.
   throw err;
Dec 05 08:30:24 hoobs homebridge[4949]:     ^
Dec 05 08:30:24 hoobs homebridge[4949]: Error: Cannot find module 'path-is-absolute'
Dec 05 08:30:24 hoobs homebridge[4949]: Require stack:
Dec 05 08:30:24 hoobs homebridge[4949]: - /home/hoobs/.hoobs/node_modules/glob/glob.js
Dec 05 08:30:24 hoobs homebridge[4949]: - /home/hoobs/.hoobs/lib/cli.js
Dec 05 08:30:24 hoobs homebridge[4949]: - /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs 

and below that I get:
   code: 'MODULE_NOT_FOUND',
Dec 05 08:30:24 hoobs homebridge[4949]:   requireStack: [
Dec 05 08:30:24 hoobs homebridge[4949]:     '/home/hoobs/.hoobs/node_modules/glob/glob.js',
Dec 05 08:30:24 hoobs homebridge[4949]:     '/home/hoobs/.hoobs/lib/cli.js',
Dec 05 08:30:24 hoobs homebridge[4949]:     '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
Dec 05 08:30:24 hoobs homebridge[4949]:   ]
Dec 05 08:30:24 hoobs homebridge[4949]: }
Dec 05 08:30:24 hoobs systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 08:30:24 hoobs systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by mkellsy** [comment]
More details
```
-- Logs begin at Thu 2019-02-14 03:11:59 MST. --
Dec 05 08:59:59 hoobs homebridge[19145]:     at Module.require (internal/modules/cjs/loader.js:852:19) {
Dec 05 08:59:59 hoobs homebridge[19145]:   code: 'MODULE_NOT_FOUND',
Dec 05 08:59:59 hoobs homebridge[19145]:   requireStack: [
Dec 05 08:59:59 hoobs homebridge[19145]:     '/home/hoobs/.hoobs/node_modules/glob/glob.js',
Dec 05 08:59:59 hoobs homebridge[19145]:     '/home/hoobs/.hoobs/lib/cli.js',
Dec 05 08:59:59 hoobs homebridge[19145]:     '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
Dec 05 08:59:59 hoobs homebridge[19145]:   ]
Dec 05 08:59:59 hoobs homebridge[19145]: }
Dec 05 08:59:59 hoobs systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 08:59:59 hoobs systemd[1]: homebridge.service: Failed with result 'exit-code'.
Dec 05 09:00:02 hoobs systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Dec 05 09:00:02 hoobs systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 745.
Dec 05 09:00:03 hoobs systemd[1]: Stopped Homebridge.
Dec 05 09:00:03 hoobs systemd[1]: Started Homebridge.
Dec 05 09:00:04 hoobs homebridge[19167]: internal/modules/cjs/loader.js:800
Dec 05 09:00:04 hoobs homebridge[19167]:     throw err;
Dec 05 09:00:04 hoobs homebridge[19167]:     ^
Dec 05 09:00:04 hoobs homebridge[19167]: Error: Cannot find module 'path-is-absolute'
Dec 05 09:00:04 hoobs homebridge[19167]: Require stack:
Dec 05 09:00:04 hoobs homebridge[19167]: - /home/hoobs/.hoobs/node_modules/glob/glob.js
Dec 05 09:00:04 hoobs homebridge[19167]: - /home/hoobs/.hoobs/lib/cli.js
Dec 05 09:00:04 hoobs homebridge[19167]: - /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
Dec 05 09:00:04 hoobs homebridge[19167]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Module.require (internal/modules/cjs/loader.js:852:19)
Dec 05 09:00:04 hoobs homebridge[19167]:     at require (internal/modules/cjs/helpers.js:74:18)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/glob/glob.js:51:18)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Module._compile (internal/modules/cjs/loader.js:959:30)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Module.load (internal/modules/cjs/loader.js:815:32)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
Dec 05 09:00:04 hoobs homebridge[19167]:     at Module.require (internal/modules/cjs/loader.js:852:19) {
Dec 05 09:00:04 hoobs homebridge[19167]:   code: 'MODULE_NOT_FOUND',
Dec 05 09:00:04 hoobs homebridge[19167]:   requireStack: [
Dec 05 09:00:04 hoobs homebridge[19167]:     '/home/hoobs/.hoobs/node_modules/glob/glob.js',
Dec 05 09:00:04 hoobs homebridge[19167]:     '/home/hoobs/.hoobs/lib/cli.js',
Dec 05 09:00:04 hoobs homebridge[19167]:     '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
Dec 05 09:00:04 hoobs homebridge[19167]:   ]
Dec 05 09:00:04 hoobs homebridge[19167]: }
Dec 05 09:00:04 hoobs systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 09:00:04 hoobs systemd[1]: homebridge.service: Failed with result 'exit-code'.
Dec 05 09:00:07 hoobs systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Dec 05 09:00:07 hoobs systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 746.
Dec 05 09:00:07 hoobs systemd[1]: Stopped Homebridge.
Dec 05 09:00:07 hoobs systemd[1]: Started Homebridge.
^C
```

**Comment by mkellsy** [comment]
What device are you on?
What's the Operating System?
When you type `node -v` what version are you on?

HOOBS requires Node 12.13.1.

**Comment by salpena78** [comment]
Mac OS Catalina 
V12.13.1

Thank you,






Pena Family LLC

Jose Pena / General Manager 

salpena@penafamllc.com

5204312502



C: 5204312502 / Fax: 5204233971 


2820 N Pinal Ave Suite 12 #200

**Comment by mkellsy** [comment]
From your email, I see you are running HOOBS with sudo. On Mac, we only support root if it is ran from Launch. https://github.com/hoobs-org/HOOBS/wiki/2.6-Running-HOOBS-on-Startup

What do you get if you simply run this command `hoobs`. No sudo.

**Comment by mkellsy** [comment]
We also have a tutorial on how to install HOOBS on macOS.

1. https://github.com/hoobs-org/HOOBS/wiki/2.5.0-macOS-Installation
2. https://github.com/hoobs-org/HOOBS/wiki/2.6-Running-HOOBS-on-Startup
3. https://github.com/hoobs-org/HOOBS/wiki/2.7.0-macOS-Remote-Access

**Comment by mkellsy** [comment]
Stale issue
