### ISSUE TITLE
Hoobs Errored after adding plugin

### ISSUE THREAD

**Issue by Fookes74** [hoobs-org/HOOBS#289]
**Description**
Installed MQTTthings plugin - went to configuration section - added config - restarted - nothing working. all devices shown as 'no response' Error messages in hoobs logs.

**Version**
3.1.1.

**Did you upgrade**
Yes

**Pervious version**
2.1.1, I believe

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Yes

**What device are you using?**
Custom install

**If this is a custom install, what's your operating system?**
Raspberry Pi - Raspbian Buster

**List your plugins**
MQTTthings plugin is what I'm trying to add

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
{
    "accessory": "mqttthing",
    "type": "outlet",
    "name": "Kettle",
    "url": "mqtt//:192.168.1.29",
    "username": "",
    "password": "",
    "topics": {
        "getOn": "stat/kettle/POWER",
        "setOn": "cmnd/kettle/power",
        "getOnline": "tele/kettle/LWT",
        "getWatts": {
            "topic": "tele/kettle/SENSOR",
            "apply": "return JSON.parse(message).ENERGY.Power;"
        },
        "getVolts": {
            "topic": "tele/kettle/SENSOR",
            "apply": "return JSON.parse(message).ENERGY.Voltage;"
        },
        "getAmperes": {
            "topic": "tele/kettle/SENSOR",
            "apply": "return JSON.parse(message).ENERGY.Current;"
        }
    },
    "history": "true",
    "logMqtt": true,
    "onValue": "ON",
    "offValue": "OFF",
    "onlineValue": "Online",
    "startPub": {
        "cmnd/kettle/power": ""
    },
    "manufacturer": "ITEAD",
    "model": "Sonoff POW R2"
}

**Post your log**

[12/6/2019, 19:03:05] HOOBS listning on port 8080.
[Homebridge] [12/6/2019, 19:03:07] Loaded config.json with 16 accessories and 6 platforms.
[Homebridge] [12/6/2019, 19:03:07] ---
[Homebridge] [12/6/2019, 19:03:10] Loaded plugin: homebridge-alexa
[Homebridge] [12/6/2019, 19:03:10] Registering platform 'homebridge-alexa.Alexa'
[Homebridge] [12/6/2019, 19:03:10] ---
[Homebridge] [12/6/2019, 19:03:10] Loaded plugin: homebridge-camera-ffmpeg-omx
[Homebridge] [12/6/2019, 19:03:10] Registering platform 'homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx'
[Homebridge] [12/6/2019, 19:03:10] ---
[Homebridge] [12/6/2019, 19:03:10] Loaded plugin: homebridge-dummy
[Homebridge] [12/6/2019, 19:03:10] Registering accessory 'homebridge-dummy.DummySwitch'
[Homebridge] [12/6/2019, 19:03:10] ---
[Homebridge] [12/6/2019, 19:03:10] Loaded plugin: homebridge-mi-aqara
[Homebridge] [12/6/2019, 19:03:10] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[Homebridge] [12/6/2019, 19:03:10] ---
[Homebridge] [12/6/2019, 19:03:11] Loaded plugin: homebridge-mqtt-switch-tasmota
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[Homebridge] [12/6/2019, 19:03:11] ---
[Homebridge] [12/6/2019, 19:03:11] Loaded plugin: homebridge-mqttthing
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-mqttthing.mqttthing'
[Homebridge] [12/6/2019, 19:03:11] ---
[Homebridge] [12/6/2019, 19:03:11] Loaded plugin: homebridge-people-guest-mode
[Homebridge] [12/6/2019, 19:03:11] Registering platform 'homebridge-people-guest-mode.People'
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-people-guest-mode.PeopleAccessory'
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-people-guest-mode.PeopleAllAccessory'
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-people-guest-mode.GuestModeSwitch'
[Homebridge] [12/6/2019, 19:03:11] ---
[Homebridge] [12/6/2019, 19:03:11] Loaded plugin: homebridge-raspberrypi-temperature
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[Homebridge] [12/6/2019, 19:03:11] ---
[Homebridge] [12/6/2019, 19:03:11] Loaded plugin: homebridge-smartglass
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-smartglass.Smartglass'
[Homebridge] [12/6/2019, 19:03:11] ---
[Homebridge] [12/6/2019, 19:03:11] Loaded plugin: homebridge-sonoff-tasmota-http
[Homebridge] [12/6/2019, 19:03:11] Registering accessory 'homebridge-sonoff-tasmota-http.SonoffTasmotaHTTP'
[Homebridge] [12/6/2019, 19:03:11] ---
[Homebridge] [12/6/2019, 19:03:12] Loaded plugin: homebridge-weather-plus
[Homebridge] [12/6/2019, 19:03:15] Registering platform 'homebridge-weather-plus.WeatherPlus'
[Homebridge] [12/6/2019, 19:03:15] ---
[Homebridge] [12/6/2019, 19:03:15] Loaded plugin: homebridge-yeelight-wifi
[Homebridge] [12/6/2019, 19:03:15] Registering platform 'homebridge-yeelight.yeelight'
[Homebridge] [12/6/2019, 19:03:15] ---
[Homebridge] [12/6/2019, 19:03:15] Loading 6 platforms...
[Homebridge] [12/6/2019, 19:03:15] [Yeelight] Initializing yeelight platform...
[Homebridge] [12/6/2019, 19:03:15] [Yeelight] starting YeePlatform using homebridge API v2.4
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]**************************************************************
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.8.0 By YinHang
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]**************************************************************
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]start success...
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]config gateways: 7811dc64e359
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]binding to the default interface
[Homebridge] [12/6/2019, 19:03:15] [People] Initializing People platform...
[Homebridge] [12/6/2019, 19:03:15] [People] Initializing platform accessory 'Chris'...
[Homebridge] [12/6/2019, 19:03:15] [People] Initializing platform accessory 'Helen'...
[Homebridge] [12/6/2019, 19:03:15] [People] Initializing platform accessory 'Guest Mode'...
[Homebridge] [12/6/2019, 19:03:15] [People] Initializing platform accessory 'Anyone'...
[Homebridge] [12/6/2019, 19:03:15] [People] WebHook: Started server on port '51828'.
[Homebridge] [12/6/2019, 19:03:15] [Camera-ffmpeg-omx] Initializing Camera-ffmpeg-omx platform...
[Homebridge] [12/6/2019, 19:03:15] [Alexa] Initializing Alexa platform...
[Homebridge] [12/6/2019, 19:03:15] [Alexa] homebridge-alexa v0.4.43, node v12.13.1, homebridge v0.4.50
[Homebridge] [12/6/2019, 19:03:15] [WeatherPlus] Initializing WeatherPlus platform...
[Homebridge] [12/6/2019, 19:03:15] [WeatherPlus] Adding station with weather service Dark Sky named 'Now'
[Homebridge] [12/6/2019, 19:03:15] [WeatherPlus] Initializing platform accessory 'Now'...
[Homebridge] [12/6/2019, 19:03:15] [WeatherPlus] Initializing platform accessory 'Middleton Forecast Today'...
[Homebridge] [12/6/2019, 19:03:15] [WeatherPlus] Initializing platform accessory 'Middleton Forecast In 1 Day'...
[Homebridge] [12/6/2019, 19:03:15] [WeatherPlus] Initializing platform accessory 'Middleton Forecast In 2 Days'...
[Homebridge] [12/6/2019, 19:03:15] Loading 16 accessories...
[Homebridge] [12/6/2019, 19:03:15] [Kitchen Table] Initializing mqtt-switch-tasmota accessory...
[Homebridge] [12/6/2019, 19:03:15] [Kitchen Table] Nazwa do RESULT  POWER1
[Homebridge] [12/6/2019, 19:03:15] [Kitchen Oven] Initializing mqtt-switch-tasmota accessory...
[Homebridge] [12/6/2019, 19:03:15] [Kitchen Oven] Nazwa do RESULT  POWER2
[Homebridge] [12/6/2019, 19:03:15] [Kitchen Cupboards] Initializing mqtt-switch-tasmota accessory...
[Homebridge] [12/6/2019, 19:03:15] [Kitchen Cupboards] Nazwa do RESULT  POWER3
[Homebridge] [12/6/2019, 19:03:15] [TV Lamp] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [TV Lamp] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [Table Lamp] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [Table Lamp] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [French Doors] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [French Doors] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [Hall Lamp] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [Hall Lamp] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [Coffee] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [Coffee] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [Bedroom Bulbs] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [Bedroom Bulbs] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [Star Lamp] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [Star Lamp] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [Flower Lamp] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [Flower Lamp] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [Fairy Lights] Initializing SonoffTasmotaHTTP accessory...
[Homebridge] [12/6/2019, 19:03:15] [Fairy Lights] Sonoff Tasmota HTTP Initialized
[Homebridge] [12/6/2019, 19:03:15] [RaspberryPi CPU Temperature] Initializing RaspberryPiTemperature accessory...
[Homebridge] [12/6/2019, 19:03:15] [Xbox One] Initializing Smartglass accessory...
[Homebridge] [12/6/2019, 19:03:15] [Xbox One] Registering Television Service...
[Homebridge] [12/6/2019, 19:03:15] [Xbox One] Registering Information Service...
[Homebridge] [12/6/2019, 19:03:15] [Xbox One] Registering Volume Service...
[Homebridge] [12/6/2019, 19:03:15] [Xbox One] Registering Key Service...
[Homebridge] [12/6/2019, 19:03:15] [Xbox One] Registering InputSource Service...
[Homebridge] [12/6/2019, 19:03:15] [Home Security] Initializing DummySwitch accessory...
[Homebridge] [12/6/2019, 19:03:15] [Home Security] Setting switch to false
[Homebridge] [12/6/2019, 19:03:15] [Kettle] Initializing mqttthing accessory...
[Homebridge] [12/6/2019, 19:03:15] [Kettle] MQTT options: {"keepalive":10,"clientId":"mqttthing_Kettle_a9898dbf","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"username":"","password":"","rejectUnauthorized":false}
[Homebridge] [12/6/2019, 19:03:15] Error: Missing protocol
[Homebridge] at Object.connect (/home/hoobs/.hoobs/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/connect/index.js:64:13)
[Homebridge] at mqttInit (/home/hoobs/.hoobs/node_modules/homebridge-mqttthing/index.js:65:31)
[Homebridge] at new makeThing (/home/hoobs/.hoobs/node_modules/homebridge-mqttthing/index.js:88:22)
[Homebridge] at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:316:35)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:81:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] [12/6/2019, 19:03:15] [MiAqaraPlatform] [INFO]Aqara LAN protocol server is listening on port: 9898
[Homebridge] HAP Warning: Characteristic undefined not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
[Homebridge] HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
The url in your config is wrong
```
"url": "mqtt//:192.168.1.29",
```

Should be
```
"url": "mqtt://192.168.1.29",
```
