### ISSUE TITLE
Tried to fix broken installation after node-red installation had broken hoobs3

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#293]
in terminal ssh to box

`sudo npm i homebridge-to-hoobs-prepare`

LOG:
hoobs@hoobs:~ $ sudo npm i homebridge-to-hoobs-prepare

> homebridge-to-hoobs-prepare@1.0.32 postinstall /home/hoobs/node_modules/homebridge-to-hoobs-prepare
> ./install.sh

Checking Node
------------------------------------------------------------
⠋ Node Version 12.13.1
⠹ Updating Repositories
bash: line 143: /root/.bashrc: Permission denied
⠋ NPM Version 6.13.2
⠸ bash: line 166: /root/.bashrc: Permission denied
bash: line 221: 23114 Killed                  spin
------------------------------------------------------------
Node has been upgraded. You now can upgrade HOOBS.          
------------------------------------------------------------
npm WARN saveError ENOENT: no such file or directory, open '/home/hoobs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/hoobs/package.json'
npm WARN hoobs No description
npm WARN hoobs No repository field.
npm WARN hoobs No README data
npm WARN hoobs No license field.

+ homebridge-to-hoobs-prepare@1.0.32
removed 1 package, updated 1 package and audited 1 package in 9.24s
found 0 vulnerabilities

hoobs@hoobs:~ $ 

Then
`sudo npm i homebridge-to-hoobs`

LOG:
hoobs@hoobs:~ $ sudo npm i homebridge-to-hoobs

> homebridge-to-hoobs@1.0.32 preinstall /home/hoobs/node_modules/homebridge-to-hoobs
> ./prepare.sh

Checking Node
------------------------------------------------------------
Node Version 12.13.1
Updating Repositories
./prepare.sh: line 94: /root/.bashrc: Permission denied
NPM Version 6.13.2
./prepare.sh: line 113: /root/.bashrc: Permission denied
------------------------------------------------------------

> homebridge-to-hoobs@1.0.32 postinstall /home/hoobs/node_modules/homebridge-to-hoobs
> ./install.sh

Thank You for choosing HOOBS
---------------------------------------------------------
⠋ Node Version 12.13.1
⠹ Updating Repositories
⠸ bash: line 147: /root/.bashrc: Permission denied
⠋ NPM Version 6.13.2
⠸ bash: line 170: /root/.bashrc: Permission denied
⠼ Installing HOOBS
⠦ Configuring
---------------------------------------------------------

Initializing HOOBS
---------------------------------------------------------
⠋ Installing PrerequisitesE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
(node:23521) UnhandledPromiseRejectionWarning: Error: Command failed: apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:31:25
    at new Promise (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/prerequisites.js:6:12)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs-init:9:104
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs-init:13:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:23521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼ Installing Prerequisites

**Comment by BobbySlope** [comment]
this is what the node red installation script had done
https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered
