### ISSUE TITLE
Box Customer Upgrade issue

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#299]
Tried install manually, Fails on this Step

`hoobs@hoobs:~ $ sudo npm install -g --unsafe-perm @hoobs/hoobs
npm ERR! code EEXIST
npm ERR! path /usr/local/bin/hoobs-cockpit
npm ERR! Refusing to delete /usr/local/bin/hoobs-cockpit: ../lib/node_modules/@hoobs/cockpit/bin/hoobs-cockpit symlink target is not controlled by npm /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! File exists: /usr/local/bin/hoobs-cockpit
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-08T19_52_28_892Z-debug.log
hoobs@hoobs:~ $ `

debug log output

`1131 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib$
1131 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/l$
1131 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/cha$
1131 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib$
1131 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/nod$
1131 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/nod$
1131 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/nod$
1131 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/nod$
1131 verbose stack     at callback (/usr/local/lib/node_modules/npm/node_modules/gra$
1131 verbose stack     at FSReqCallback.oncomplete (fs.js:158:21)
1132 verbose cwd /home/hoobs
1133 verbose Linux 4.19.58-v7+
1134 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsaf$
1135 verbose node v12.13.1
1136 verbose npm  v6.13.2
1137 error code EEXIST
1138 error path /usr/local/bin/hoobs-cockpit
1139 error Refusing to delete /usr/local/bin/hoobs-cockpit: ../lib/node_modules/@hoo$
1140 error File exists: /usr/local/bin/hoobs-cockpit
1141 error Move it away, and try again.
1142 verbose exit [ 1, true ]
`

command:

sudo rm /usr/local/bin/hoobs-cockpit

tried again:
sudo npm install -g --unsafe-perm @hoobs/hoobs

runned trough

`Configuring NGINX
  Checking Configuration
+ @hoobs/hoobs@3.1.1
updated 3 packages in 32.159s`

**Comment by BobbySlope** [comment]
hoobs@hoobs:~ $ hoobs
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js
- /home/hoobs/.hoobs/node_modules/node-pty/lib/index.js
- /home/hoobs/.hoobs/lib/api.js
- /home/hoobs/.hoobs/lib/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js',
    '/home/hoobs/.hoobs/node_modules/node-pty/lib/index.js',
    '/home/hoobs/.hoobs/lib/api.js',
    '/home/hoobs/.hoobs/lib/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js
- /home/hoobs/.hoobs/node_modules/node-pty/lib/index.js
- /home/hoobs/.hoobs/lib/api.js
- /home/hoobs/.hoobs/lib/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hoobs/.hoobs/node_modules/node-pty/lib/unixTerminal.js',
    '/home/hoobs/.hoobs/node_modules/node-pty/lib/index.js',
    '/home/hoobs/.hoobs/lib/api.js',
    '/home/hoobs/.hoobs/lib/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}

**Comment by BobbySlope** [comment]
here's the fix

cd ~/.hoobs/etc
npm rebuild node-pty --update-binary

after that all worked normally
