### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by jahnkenneth** [hoobs-org/HOOBS#352]
**Description**
After restarting hoops I get the following error:
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826

**Version**
Hoobs 3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY5HKI",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "no",
        "temp_units": "celsius",
        "country_code": "NO",
        "postal_code": "7550"
    },
    "bridge": {
        "username": "CC:22:3D:E3:CE:30",
        "name": "HOOBS",
        "pin": "031-45-154",
        "port": 51826
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "name": "Stue",
            "hubIP": "192.168.68.113",
            "otherPlatforms": [
                {
                    "name": "loftstue",
                    "hubIP": "192.168.68.104"
                },
                {
                    "name": "hovedsoverom",
                    "hubIP": "192.168.68.112"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        },
        {
            "deviceCfgs": [
                {
                    "ledBulbDisable": true,
                    "airQualityDisable": 1,
                    "ledBulbName": "MiAirPurifier LED Switch",
                    "airPurifierName": "MiAirPurifier",
                    "buzzerSwitchName": "MiAirPurifier Buzzer Switch",
                    "airPurifierDisable": 1,
                    "silentModeSwitchDisable": 1,
                    "silentModeSwitchName": "MiAirPurifier Silent Mode Switch",
                    "airQualityName": "MiAirPurifier AirQuality",
                    "type": "MiAirPurifier",
                    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "ip": "192.168.88.xx",
                    "buzzerSwitchDisable": true
                },
                {
                    "ledBulbDisable": true,
                    "humidityDisable": 1,
                    "ledBulbName": "MiAirPurifier2 LED Switch",
                    "buzzerSwitchName": "MiAirPurifier2 Buzzer Switch",
                    "airPurifierName": "MiAirPurifier2",
                    "airPurifierDisable": 1,
                    "silentModeSwitchDisable": 1,
                    "humidityName": "MiAirPurifier2 Humidity",
                    "silentModeSwitchName": "MiAirPurifier2 Silent Mode Switch",
                    "type": "MiAirPurifier2",
                    "temperatureDisable": 1,
                    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "ip": "192.168.88.xx",
                    "temperatureName": "MiAirPurifier2 Temperature",
                    "airQualityDisable": 1,
                    "buzzerSwitchDisable": true,
                    "airQualityName": "MiAirPurifier2 AirQuality"
                },
                {
                    "ledBulbDisable": true,
                    "humidityDisable": 1,
                    "ledBulbName": "MiAirPurifierPro LED Switch",
                    "buzzerSwitchName": "MiAirPurifierPro Buzzer Switch",
                    "airPurifierName": "MiAirPurifierPro",
                    "airPurifierDisable": 1,
                    "silentModeSwitchDisable": 1,
                    "humidityName": "MiAirPurifierPro Humidity",
                    "silentModeSwitchName": "MiAirPurifierPro Silent Mode Switch",
                    "type": "MiAirPurifierPro",
                    "temperatureDisable": 1,
                    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "ip": "192.168.88.xx",
                    "temperatureName": "MiAirPurifierPro Temperature",
                    "airQualityDisable": 1,
                    "buzzerSwitchDisable": true,
                    "airQualityName": "MiAirPurifierPro AirQuality"
                },
                {
                    "ledBulbDisable": true,
                    "humidityDisable": false,
                    "ledBulbName": "MiAirPurifier2S LED Switch",
                    "buzzerSwitchName": "MiAirPurifier2S Buzzer Switch",
                    "airPurifierName": "MiAirPurifier2S",
                    "airPurifierDisable": false,
                    "silentModeSwitchDisable": 1,
                    "humidityName": "MiAirPurifier2S Humidity",
                    "silentModeSwitchName": "MiAirPurifier2S Silent Mode Switch",
                    "type": "MiAirPurifier2S",
                    "temperatureDisable": false,
                    "token": "73b63e6a3eee1492c2ba2de23213abf2",
                    "ip": "192.168.68.122",
                    "temperatureName": "MiAirPurifier2S Temperature",
                    "airQualityDisable": false,
                    "buzzerSwitchDisable": true,
                    "airQualityName": "MiAirPurifier2S AirQuality"
                }
            ],
            "name": "No name",
            "platform": "MiAirPurifierPlatform"
        },
        {
            "email": "xxxxxxxxx",
            "password": "xxxxxxxxx",
            "hideDoorbellSwitch": true,
            "platform": "Ring"
        },
        {
            "name": "Google Smart Home",
            "platform": "google-smarthome",
            "token": "xxxxxxx",
            "notice": "Keep your token a secret!"
        },
        {
            "platform": "MiAirPurifierPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-mi-airpurifier"
            }
        },
        {
            "platform": "google-home",
            "plugin_map": {
                "plugin_name": "google-home"
            },
            "name": "Google Home",
            "debug": false,
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imdvb2dsZS1vYXV0aDJ8MTAzMDI2NDAxNDA3NDkxMDIyMTA3IiwiaWF0IjoxNTc2OTM4ODc0fQ.CbyOQRDr-TojXeGOgLIlLEl8a-f_I-PqTcOh-OfG6Mg"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[12/21/2019, 15:36:17] HOOBS listning on port 8080.
[Homebridge] [12/21/2019, 15:36:18] Loaded config.json with 0 accessories and 6 platforms.
[Homebridge] [12/21/2019, 15:36:18] ---
[Homebridge] [12/21/2019, 15:36:20] Loaded plugin: homebridge-harmony
[Homebridge] [12/21/2019, 15:36:20] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[Homebridge] [12/21/2019, 15:36:20] ---
[Homebridge] [12/21/2019, 15:36:20] Loaded plugin: homebridge-mi-airpurifier
[Homebridge] [12/21/2019, 15:36:20] Registering platform 'homebridge-mi-airpurifier.MiAirPurifierPlatform'
[Homebridge] [12/21/2019, 15:36:20] ---
[Homebridge] [12/21/2019, 15:36:22] Loaded plugin: homebridge-ring
[Homebridge] [12/21/2019, 15:36:22] Registering platform 'homebridge-ring.Ring'
[Homebridge] [12/21/2019, 15:36:22] ---
[Homebridge] [12/21/2019, 15:36:22] Loaded plugin: google-home
[Homebridge] [12/21/2019, 15:36:22] Registering platform 'google-home.google-home'
[Homebridge] [12/21/2019, 15:36:22] ---
[Homebridge] [12/21/2019, 15:36:22] Loading 6 platforms...
[Homebridge] [12/21/2019, 15:36:22] [Stue] Initializing HarmonyHubWebSocket platform...
[Homebridge] [12/21/2019, 15:36:22] [Stue] HarmonyPlatform Init
[Homebridge] [12/21/2019, 15:36:22] [Stue] undefined
[Homebridge] [12/21/2019, 15:36:22] [Stue] undefined
[Homebridge] [12/21/2019, 15:36:22] [Stue] undefined
[Homebridge] [12/21/2019, 15:36:22] [No name] Initializing MiAirPurifierPlatform platform...
[Homebridge] [12/21/2019, 15:36:22] [No name] [MiAirPurifierPlatform][INFO]*******************************************************************
[Homebridge] [12/21/2019, 15:36:22] [No name] [MiAirPurifierPlatform][INFO]          MiAirPurifierPlatform v0.1.3 By YinHang
[Homebridge] [12/21/2019, 15:36:22] [No name] [MiAirPurifierPlatform][INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-airpurifier
[Homebridge] [12/21/2019, 15:36:22] [No name] [MiAirPurifierPlatform][INFO]                                              QQ Group: 107927710
[Homebridge] [12/21/2019, 15:36:22] [No name] [MiAirPurifierPlatform][INFO]*******************************************************************
[Homebridge] [12/21/2019, 15:36:22] [No name] [MiAirPurifierPlatform][INFO]start success...
[Homebridge] [12/21/2019, 15:36:22] [No name] [MiAirPurifierPlatform][INFO]device size: 4, accessories size: 4
[Homebridge] [12/21/2019, 15:36:22] [No name] Initializing platform accessory 'MiAirPurifier2S'...
[Homebridge] HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BB-0000-1000-8000-0026BB765291. Adding anyway.
[Homebridge] [12/21/2019, 15:36:22] [No name] Initializing platform accessory 'MiAirPurifier2S Temperature'...
[Homebridge] [12/21/2019, 15:36:22] [No name] Initializing platform accessory 'MiAirPurifier2S Humidity'...
[Homebridge] [12/21/2019, 15:36:22] [No name] Initializing platform accessory 'MiAirPurifier2S AirQuality'...
[Homebridge] [12/21/2019, 15:36:22] [Ring] Initializing Ring platform...
[Homebridge] [12/21/2019, 15:36:22] Error: The requested platform 'google-smarthome' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] at internal/main/run_main_module.js:17:11
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
```

**Additional context**

**Comment by mkellsy** [comment]
it looks like you have google-home and google-smarthome defined in your config.
Remove google-smarthome this from your config.
```
{
    "name": "Google Smart Home",
    "platform": "google-smarthome",
    "token": "xxxxxxx",
    "notice": "Keep your token a secret!"
},
```
