### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#363]
**Description**

5 Pi's running HOOBS on the same network after upgrading to 3.1.10 1 of my Pi's is crashing with the error in the discription

**Version**
Please include the version of HOOBS you are using.

3.1.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.

- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Platform Wemo

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://XXXXXXXXXXXXX",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "tealzier",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51826,
        "pin": "XXX-XX-XXX"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "name": "WeMoHomebridge",
            "platform": "BelkinWeMo",
            "noMotionTimer": 60
        },
        {
            "platform": "BelkinWeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[12/23/2019, 7:01:40 PM] HOOBS listning on port 8080.[Homebridge] [12/23/2019, 7:01:42 PM] Loaded config.json with 0 accessories and 2 platforms.[Homebridge] [12/23/2019, 7:01:42 PM] ---[Homebridge] [12/23/2019, 7:01:44 PM] Loaded plugin: homebridge-platform-wemo[Homebridge] [12/23/2019, 7:01:44 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'[Homebridge] [12/23/2019, 7:01:44 PM] ---[Homebridge] [12/23/2019, 7:01:44 PM] Loading 2 platforms...[Homebridge] [12/23/2019, 7:01:44 PM] [WeMoHomebridge] Initializing BelkinWeMo platform...[Homebridge] [12/23/2019, 7:01:44 PM] [BelkinWeMo] Initializing BelkinWeMo platform...[Homebridge] [12/23/2019, 7:01:44 PM] Loading 0 accessories...[Homebridge] [12/23/2019, 7:01:44 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4cffdb91-9b75-43b2-b0b9-09a1756a5b16[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)[Homebridge] at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:407:22)[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:85:10)[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)[Homebridge] at startup (internal/bootstrap/node.js:283:19)[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)[Homebridge] [12/23/2019, 7:01:44 PM] Got SIGTERM, shutting down service...[List Accessories] connect ECONNREFUSED 127.0.0.1:51826[List Accessories] connect ECONNREFUSED 127.0.0.1:51826[Homebridge] [12/23/2019, 7:04:02 PM] Loaded config.json with 0 accessories and 2 platforms.[Homebridge] [12/23/2019, 7:04:02 PM] ---[Homebridge] [12/23/2019, 7:04:02 PM] Loaded plugin: homebridge-platform-wemo[Homebridge] [12/23/2019, 7:04:02 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'[Homebridge] [12/23/2019, 7:04:02 PM] ---[Homebridge] [12/23/2019, 7:04:02 PM] Loading 2 platforms...[Homebridge] [12/23/2019, 7:04:02 PM] [WeMoHomebridge] Initializing BelkinWeMo platform...[Homebridge] [12/23/2019, 7:04:02 PM] [BelkinWeMo] Initializing BelkinWeMo platform...[Homebridge] [12/23/2019, 7:04:02 PM] Loading 0 accessories...[Homebridge] [12/23/2019, 7:04:02 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4cffdb91-9b75-43b2-b0b9-09a1756a5b16[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)[Homebridge] at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:407:22)[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:85:10)[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)[Homebridge] at startup (internal/bootstrap/node.js:283:19)[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)[Homebridge] [12/23/2019, 7:04:02 PM] Got SIGTERM, shutting down service...[List Accessories] connect ECONNREFUSED 127.0.0.1:51826[Homebridge] [12/23/2019, 7:04:30 PM] Loaded config.json with 0 accessories and 2 platforms.[Homebridge] [12/23/2019, 7:04:30 PM] ---[Homebridge] [12/23/2019, 7:04:30 PM] Loaded plugin: homebridge-platform-wemo[Homebridge] [12/23/2019, 7:04:30 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'[Homebridge] [12/23/2019, 7:04:30 PM] ---[Homebridge] [12/23/2019, 7:04:30 PM] Loading 2 platforms...[Homebridge] [12/23/2019, 7:04:30 PM] [WeMoHomebridge] Initializing BelkinWeMo platform...[Homebridge] [12/23/2019, 7:04:30 PM] [BelkinWeMo] Initializing BelkinWeMo platform...[Homebridge] [12/23/2019, 7:04:30 PM] Loading 0 accessories...[Homebridge] [12/23/2019, 7:04:30 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4cffdb91-9b75-43b2-b0b9-09a1756a5b16[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)[Homebridge] at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:407:22)[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:85:10)[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)[Homebridge] at startup (internal/bootstrap/node.js:283:19)[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)[Homebridge] [12/23/2019, 7:04:30 PM] Got SIGTERM, shutting down service...[List Accessories] connect ECONNREFUSED 127.0.0.1:51826[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
```

**Additional context**

Is it possible to change the UUID?

**Comment by OfficialKaos** [comment]
Strange thing is they were all running ok before the upgrade and they were ok for about 16 hours after the upgrade?

**Comment by OfficialKaos** [comment]
How can I clear cached accessories in 3.1.10

**Comment by OfficialKaos** [comment]
Ok so with the advise of the HOOBS team I've fixed it.
Top right drop down window, click help and reset connection and username, I deleted homebridge and re added it to HomeKit. Needed to put everything back in their rooms but I think this is a pluggin issue as it didn't happen on my other Pi's and it happenend when I originally migrated to HOOBS about a year ago with this same pluggin
