### ISSUE TITLE
Hoobs not running

### ISSUE THREAD

**Issue by mikelito80** [hoobs-org/HOOBS#379]
**Description**
Hello, after installing the migration plugin to Hoobs 3 , it doesn't work.

**Version**

HOOBS Version | 3.1.14

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes

**Pervious version**
I don´t know

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
I´m not sure

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box

**List your plugins**
Samsung tizen
Config ui
mel cloud
homebridge migration

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "es",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Salon TV",
                    "ip": "192.168.68.118",
                    "mac": "64:1C:AE:42:05:F0"
                }
            ]
        }
    ]
}```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [12/27/2019, 6:29:31 PM] Got SIGTERM, shutting down service...
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[Homebridge] [12/27/2019, 6:29:53 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [12/27/2019, 6:29:53 PM] ---
[Homebridge] [12/27/2019, 6:29:54 PM] No plugins found. See the README for information on installing plugins.
[Homebridge] [12/27/2019, 6:29:54 PM] Loading 1 platforms...
[Homebridge] [12/27/2019, 6:29:54 PM] Error: The requested platform 'SamsungTizen' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:776:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [12/27/2019, 6:29:54 PM] Got SIGTERM, shutting down service...
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[Homebridge] [12/27/2019, 6:35:02 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [12/27/2019, 6:35:03 PM] ---
[Homebridge] [12/27/2019, 6:35:03 PM] No plugins found. See the README for information on installing plugins.
[Homebridge] [12/27/2019, 6:35:03 PM] Loading 1 platforms...
[Homebridge] [12/27/2019, 6:35:03 PM] Error: The requested platform 'SamsungTizen' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:776:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [12/27/2019, 6:35:03 PM] Got SIGTERM, shutting down service...
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
[Homebridge] [12/27/2019, 6:37:35 PM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [12/27/2019, 6:37:35 PM] ---
[Homebridge] [12/27/2019, 6:37:35 PM] No plugins found. See the README for information on installing plugins.
[Homebridge] [12/27/2019, 6:37:35 PM] Loading 1 platforms...
[Homebridge] [12/27/2019, 6:37:35 PM] Error: The requested platform 'SamsungTizen' was not registered by any plugin.
[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:330:47)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:77:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:776:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [12/27/2019, 6:37:35 PM] Got SIGTERM, shutting down service...
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826
**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
How did you install the SamsungTizen plugin? Trying to find the cause of this.

**Comment by mikelito80** [comment]
I installed it before actualizing to hoobs 3. The system cracked after actualizing to hoobs 3. It never worked.

**Comment by mkellsy** [comment]
Try to install the plugin from the UI. I was able to install this without issue.

**Comment by docgilno** [comment]
Got the same problem after updating my hoobs today. Must be a bug in the update. I have not changed anything to my hoobs setup. Only did an update and now the hoobs will not start homebridge.

**Comment by mikelito80** [comment]
I deleted the samsung tizen codes and now hooks is running. But now I can not add hoops to homekit.

**Comment by mkellsy** [comment]
I re-worked the migration logic in 3.1.15.

It is more fault tolerant and allows you to switch between HOOBS and Homebridge until you decide you want to remove Homebridge (Which there is a script for)

**Comment by mikelito80** [comment]
I still can not add hoobs to homekit. The home app does not find any accessory.

**Comment by mkellsy** [comment]
Are you using a mesh network?

**Comment by mikelito80** [comment]
Yes

**Comment by mkellsy** [comment]
You need to connect HOOBS to the main node to pair with HomeKit. Once that is done you can move it. This is a known issue with both HOOBS and Homebridge.
