### ISSUE TITLE
Crashing Plugins are not separated

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#385]
**Description**
A single plugin can cause a hoobs service crash. So if a plugin crashes, all others cant run anymore. I thought since some beta a plugin crash doesn’t affect other ones anymore?

I saw that behaviour at a customer and I reproduced it on the latest version. To test it, I leaved parameters at the Roborock plugin blank. It crashes with a Uncaught Exception Error, the service is stopped and cant be started successfuly anymore.

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
Loaded config.json with 2 accessories and 8 platforms.
[Homebridge] [12/29/2019, 4:13:10 PM] ---
[Homebridge] [12/29/2019, 4:13:10 PM] Warning: skipping plugin found at '/home/hoobs/node_modules/homebridge-hue' since we already loaded the same plugin from '/home/hoobs/.hoobs/node_modules/homebridge-hue'.
[Homebridge] [12/29/2019, 4:13:13 PM] Loaded plugin: homebridge-camera-ffmpeg
[Homebridge] [12/29/2019, 4:13:13 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[Homebridge] [12/29/2019, 4:13:13 PM] ---
[Homebridge] [12/29/2019, 4:13:13 PM] Loaded plugin: homebridge-fritz-platform
[Homebridge] [12/29/2019, 4:13:14 PM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[Homebridge] [12/29/2019, 4:13:14 PM] ---
[Homebridge] [12/29/2019, 4:13:14 PM] Plugin /home/hoobs/.hoobs/node_modules/homebridge-hue requires Node version of ^12.13.0 which does not satisfy the current Node version of v10.16.3. You may need to upgrade your installation of Node.
[Homebridge] [12/29/2019, 4:13:15 PM] Loaded plugin: homebridge-hue
[Homebridge] [12/29/2019, 4:13:15 PM] Registering platform 'homebridge-hue.Hue'
[Homebridge] [12/29/2019, 4:13:15 PM] ---
[Homebridge] [12/29/2019, 4:13:15 PM] Loaded plugin: homebridge-mqttthing
[Homebridge] [12/29/2019, 4:13:15 PM] Registering accessory 'homebridge-mqttthing.mqttthing'
[Homebridge] [12/29/2019, 4:13:15 PM] ---
[Homebridge] [12/29/2019, 4:13:15 PM] Loaded plugin: homebridge-nukiio
[Homebridge] [12/29/2019, 4:13:15 PM] Registering platform 'homebridge-nukiio.NukiBridge'
[Homebridge] [12/29/2019, 4:13:15 PM] Registering accessory 'homebridge-nukiio.NukiLock'
[Homebridge] [12/29/2019, 4:13:15 PM] Registering accessory 'homebridge-nukiio.NukiOpener'
[Homebridge] [12/29/2019, 4:13:15 PM] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
[Homebridge] [12/29/2019, 4:13:15 PM] ---
[Homebridge] [12/29/2019, 4:13:15 PM] Loaded plugin: homebridge-platform-lightify
[Homebridge] [12/29/2019, 4:13:15 PM] Registering platform 'homebridge-platform-lightify.Lightify'
[Homebridge] [12/29/2019, 4:13:15 PM] ---
[Homebridge] [12/29/2019, 4:13:16 PM] Loaded plugin: homebridge-platform-wemo
[Homebridge] [12/29/2019, 4:13:16 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[Homebridge] [12/29/2019, 4:13:16 PM] ---
[Homebridge] [12/29/2019, 4:13:16 PM] Loaded plugin: homebridge-raspberrypi-temperature
[Homebridge] [12/29/2019, 4:13:16 PM] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[Homebridge] [12/29/2019, 4:13:16 PM] ---
[Homebridge] [12/29/2019, 4:13:16 PM] Loaded plugin: homebridge-zigbee
[Homebridge] [12/29/2019, 4:13:16 PM] Registering platform 'homebridge-zigbee.ZigBeePlatform'
[Homebridge] [12/29/2019, 4:13:16 PM] ---
[Homebridge] [12/29/2019, 4:13:16 PM] Plugin /home/hoobs/.hoobs/node_modules/homebridge-zp requires Node version of ^12.13.1 which does not satisfy the current Node version of v10.16.3. You may need to upgrade your installation of Node.
[Homebridge] [12/29/2019, 4:13:17 PM] Loaded plugin: homebridge-zp
[Homebridge] [12/29/2019, 4:13:17 PM] Registering platform 'homebridge-lib.Lib'
[Homebridge] [12/29/2019, 4:13:17 PM] Registering platform 'homebridge-zp.ZP'
[Homebridge] [12/29/2019, 4:13:17 PM] ---
[Homebridge] [12/29/2019, 4:13:17 PM] Loaded plugin: chamberlain
[Homebridge] [12/29/2019, 4:13:17 PM] Registering accessory 'chamberlain.Chamberlain'
[Homebridge] [12/29/2019, 4:13:17 PM] ---
[Homebridge] [12/29/2019, 4:13:17 PM] Loaded plugin: roborock
[Homebridge] [12/29/2019, 4:13:17 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[Homebridge] [12/29/2019, 4:13:17 PM] ---
[Homebridge] [12/29/2019, 4:13:17 PM] Loaded plugin: shelly
[Homebridge] [12/29/2019, 4:13:18 PM] Registering platform 'homebridge-shelly.Shelly'
[Homebridge] [12/29/2019, 4:13:18 PM] ---
[Homebridge] [12/29/2019, 4:13:18 PM] Loading 8 platforms...
[Homebridge] [12/29/2019, 4:13:18 PM] [ZigBee Platform] Initializing ZigBeePlatform platform...
[Homebridge] [12/29/2019, 4:13:18 PM] [ZigBee Platform] ZigBee platform initialization
[Homebridge] [12/29/2019, 4:13:18 PM] [FritzPlatform] Initializing FritzPlatform platform...
[Homebridge] [12/29/2019, 4:13:18 PM] [FritzPlatform] [INFO] **************************************************************
[Homebridge] [12/29/2019, 4:13:18 PM] [FritzPlatform] [INFO] FritzPlatform v4.1.0 by SeydX
[Homebridge] [12/29/2019, 4:13:18 PM] [FritzPlatform] [INFO] GitHub: https://github.com/SeydX/homebridge-fritz-platform
[Homebridge] [12/29/2019, 4:13:18 PM] [FritzPlatform] [INFO] Email: seyd55@outlook.de
[Homebridge] [12/29/2019, 4:13:18 PM] [FritzPlatform] [INFO] **************************************************************
[Homebridge] [12/29/2019, 4:13:18 PM] [FritzPlatform] [INFO] start success...
[Homebridge] [12/29/2019, 4:13:18 PM] [Camera Platform] Initializing Camera-ffmpeg platform...
[Homebridge] [12/29/2019, 4:13:18 PM] [BelkinWeMo] Initializing BelkinWeMo platform...
[Homebridge] [12/29/2019, 4:13:18 PM] [Hue] Initializing Hue platform...
[Homebridge] [12/29/2019, 4:13:18 PM] [Hue] config.json: warning: plugin_map: ignoring unknown key
[Homebridge] [12/29/2019, 4:13:18 PM] [Hue] homebridge-hue v0.11.42, node v10.16.3, homebridge v0.4.50
[Homebridge] [12/29/2019, 4:13:18 PM] [Hue] warning: not using recommended node version v12.13.0 LTS
[Homebridge] [12/29/2019, 4:13:18 PM] [Shelly] Initializing Shelly platform...
[Homebridge] [12/29/2019, 4:13:18 PM] [Sonos] Initializing ZP platform...
[Homebridge] [12/29/2019, 4:13:18 PM] [Sonos] homebridge-zp v1.0.16, node 10.16.3, homebridge v0.4.50, homebridge-lib v4.4.8
[Homebridge] [12/29/2019, 4:13:18 PM] [Sonos] warning: 10.16.3: not using recommended node v12.13.1 LTS
[Homebridge] [12/29/2019, 4:13:18 PM] [Lightify] Initializing Lightify platform...
[Homebridge] [12/29/2019, 4:13:18 PM] Loading 2 accessories...
[Homebridge] [12/29/2019, 4:13:18 PM] [Pi CPU Temp] Initializing RaspberryPiTemperature accessory...
[Homebridge] [12/29/2019, 4:13:18 PM] [Roborock Vacuum] Initializing XiaomiRoborockVacuum accessory...
[Homebridge] Uncaught Exception Error: You must provide an ip address of the vacuum cleaner.
[Homebridge] at new XiaomiRoborockVacuum (/home/hoobs/.hoobs/node_modules/@hoobs/roborock/index.js:127:13)
[Homebridge] at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:316:35)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:81:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[Homebridge] at startup (internal/bootstrap/node.js:283:19)
[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[Homebridge] [12/29/2019, 4:13:18 PM] Error: You must provide an ip address of the vacuum cleaner.
[Homebridge] at new XiaomiRoborockVacuum (/home/hoobs/.hoobs/node_modules/@hoobs/roborock/index.js:127:13)
[Homebridge] at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:316:35)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:81:14)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:86:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[Homebridge] at startup (internal/bootstrap/node.js:283:19)
[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[Homebridge] [12/29/2019, 4:13:18 PM] Got SIGTERM, shutting down service...
[Homebridge] [12/29/2019, 4:13:18 PM] [Hue] warning: latest version: homebridge-hue v0.11.45
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
```

**Comment by mkellsy** [comment]
This can happen, because Homebridge requires a kill if a plugin is mis-behaving. It actually puts HB is a wired state if HB is not killed. This would require a major re-write of HB.

I have plans (already logged) to run isolated containers for plugins that fork back to the main process. Needs a ton of work.

**Comment by rpolenthon** [comment]
Okay

**Comment by mkellsy** [comment]
Remember the accessories wont load issue? Or the issue where everything is wired after installing a plugin? Caused by not killing HB when a plugin crashes. It actually brings down HAP silently, and even prevents HB from restarting.

**Comment by mkellsy** [comment]
I closed this because I don't want this feature added, until HB is converted to TypeScript with Yarn as the package manager.

**Comment by rpolenthon** [comment]
Yeah, sorry I missed that. I thought it got implemented with a previous beta. 

This feature is great to have, but there are currently more important things to do.

**Comment by mkellsy** [comment]
It was in the beta, but we only played with "nice" plugins (in retrospect). As soon as the other plugins started flooding in showed why HB did this in the first place.
