### ISSUE TITLE
Factory Reset returns error -- reboot required

### ISSUE THREAD

**Issue by rpolenthon** [hoobs-org/HOOBS#387]
**Description**
I tried the factory reset, after some minutes without any automatic interface update, I refreshed the page and got the error below. It can be fixed with a reboot.

```
Error: ENOENT: no such file or directory, lstat '/home/hoobs/.hoobs/lib'
    at Object.realpathSync (fs.js:1461:7)
    at Function.get paths [as paths] (/home/hoobs/.hoobs/lib/server.js:50:39)
    at API.HBS.app.get (/home/hoobs/.hoobs/lib/api.js:144:50)
    at Layer.handle [as handle_request] (/home/hoobs/.hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/hoobs/.hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/hoobs/.hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/hoobs/.hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /home/hoobs/.hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/home/hoobs/.hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/home/hoobs/.hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/hoobs/.hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/home/hoobs/.hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/hoobs/.hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:198:13)
    at SendStream.error (/home/hoobs/.hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/hoobs/.hoobs/node_modules/send/index.js:421:12)
```

**Version**
3.1.14

**Comment by mkellsy** [comment]
Migration fixed in 3.1.15.

To fix 3.1.14 run this
```
rm -fR ~/.hoobs
```

from SSH

**Comment by rpolenthon** [comment]
It already fixed itself after a reboot of the pi.

**Comment by rpolenthon** [comment]
Ah, you are right. The plugins were still there so it was necessary to remove the .hoobs directory.
