### ISSUE TITLE
Wifi set up not working

### ISSUE THREAD

**Issue by danlun** [hoobs-org/HOOBS#459]
**Description**
On a PI2 I have plugged in a Wifi USB dongle from DLINK; DWA-131. I have installed drivers and can see the dongle via the Terminal in Hoobs installation. But unplugging the wired network, rebooting im NOT getting the HOOBS network to start on my PI to be able to start up the wifi connection. I havent found another way to shift from wired to WiFi network.

**Version**
3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Telldus plugin for homebridge

**Post your config**
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0xxxxxxxxx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "PT",
        "postal_code": "8200-112"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxxxxxxxxx",
        "username": "xxxxxxxx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Telldus",
            "name": "Telldus Liv!e",
            "public_key": "xxxxx",
            "private_key": "xxxx",
            "token": "xxxx",
            "token_secret": "xxx",
            "plugin_map": {
                "plugin_name": "homebridge-telldus"
            }
        }
    ]
}

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section. (It states "intercafe" in this sentence instead of "interface", a small detail :-)

```
[1/29/2020, 11:18:01 AM] HOOBS listning on port 8080.
[Homebridge] [1/29/2020, 11:18:03 AM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [1/29/2020, 11:18:03 AM] Loaded plugin: "homebridge-telldus"
[Homebridge] [1/29/2020, 11:18:03 AM] Registering platform "homebridge-telldus.Telldus"
[Homebridge] [1/29/2020, 11:18:03 AM] Loading 1 platforms...
[Homebridge] [1/29/2020, 11:18:03 AM] [Telldus Liv!e] Initializing Telldus platform...
[Homebridge] [1/29/2020, 11:18:03 AM] [Telldus Liv!e] isLocal: false
[Homebridge] [1/29/2020, 11:18:03 AM] [Telldus Liv!e] Loading accessories...
[Homebridge] [1/29/2020, 11:18:04 AM] Loading 0 accessories...
[Homebridge] [1/29/2020, 11:18:04 AM] API launched
[Homebridge] [1/29/2020, 11:18:04 AM] [Telldus Liv!e] request to https://api.telldus.com/json/sensors/list failed, reason: getaddrinfo EAI_AGAIN api.telldus.com
[Homebridge] [1/29/2020, 11:18:04 AM] Unhandled Rejection "FetchError: request to https://api.telldus.com/json/sensors/list failed, reason: getaddrinfo EAI_AGAIN api.telldus.com".
[Homebridge] [1/29/2020, 11:18:04 AM] FetchError: request to https://api.telldus.com/json/sensors/list failed, reason: getaddrinfo EAI_AGAIN api.telldus.com
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Homebridge] (node:470) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Homebridge] [1/29/2020, 11:29:06 AM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [1/29/2020, 11:29:07 AM] Loaded plugin: "homebridge-telldus"
[Homebridge] [1/29/2020, 11:29:07 AM] Registering platform "homebridge-telldus.Telldus"
[Homebridge] [1/29/2020, 11:29:07 AM] Loading 1 platforms...
[Homebridge] [1/29/2020, 11:29:07 AM] [Telldus Liv!e] Initializing Telldus platform...
[Homebridge] [1/29/2020, 11:29:07 AM] [Telldus Liv!e] isLocal: false
[Homebridge] [1/29/2020, 11:29:07 AM] [Telldus Liv!e] Loading accessories...
[Homebridge] [1/29/2020, 11:29:07 AM] Loading 0 accessories...
[Homebridge] [1/29/2020, 11:29:07 AM] API launched
[Homebridge] [1/29/2020, 11:29:08 AM] [Telldus Liv!e] Found 0 sensors in telldus live.
[Homebridge] [1/29/2020, 11:29:08 AM] [Telldus Liv!e] Found 4 devices in telldus live.
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Creating accessory with ID 6165489. Name from telldus: Arbetsrum - vägg
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Creating accessory with ID 6165484. Name from telldus: Bedroom - Dan
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Creating accessory with ID 6165479. Name from telldus: Bedroom - Lisbeth
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Creating accessory with ID 6165474. Name from telldus: Living room - standing lamp
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Initializing platform accessory "Arbetsrum - vägg".
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Initializing platform accessory "Bedroom - Dan".
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Initializing platform accessory "Bedroom - Lisbeth".
[Homebridge] [1/29/2020, 11:29:11 AM] [Telldus Liv!e] Initializing platform accessory "Living room - standing lamp".
[Homebridge] [1/29/2020, 11:29:11 AM] Service is running on port 51826.
[Homebridge] [1/29/2020, 11:29:15 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/29/2020, 11:29:15 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [on]
[Homebridge] [1/29/2020, 11:29:15 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/29/2020, 11:29:15 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [27]
[Homebridge] [1/29/2020, 11:29:15 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/29/2020, 11:29:16 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [on]
[Homebridge] [1/29/2020, 1:29:20 PM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/29/2020, 1:29:20 PM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [27]
[Homebridge] [1/29/2020, 1:29:20 PM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/29/2020, 1:29:20 PM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/29/2020, 1:29:20 PM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [on]
[Homebridge] [1/29/2020, 1:29:20 PM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [on]
[Homebridge] [1/30/2020, 2:34:33 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [27]
[Homebridge] [1/30/2020, 2:34:33 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/30/2020, 2:34:33 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/30/2020, 2:34:33 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
[Homebridge] [1/30/2020, 2:34:33 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/30/2020, 2:34:33 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/30/2020, 12:28:13 PM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/30/2020, 12:28:13 PM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [21]
[Homebridge] [1/30/2020, 12:28:13 PM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/30/2020, 12:28:13 PM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/30/2020, 12:28:13 PM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
[Homebridge] [1/30/2020, 12:28:13 PM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/31/2020, 3:33:53 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/31/2020, 3:33:53 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
[Homebridge] [1/31/2020, 3:33:53 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/31/2020, 3:33:53 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/31/2020, 3:33:53 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/31/2020, 3:33:53 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [21]
[Homebridge] [1/31/2020, 5:09:36 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/31/2020, 5:09:36 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/31/2020, 5:09:36 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/31/2020, 5:09:36 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/31/2020, 5:09:36 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [21]
[Homebridge] [1/31/2020, 5:09:36 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
[Homebridge] [1/31/2020, 5:17:32 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/31/2020, 5:17:32 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/31/2020, 5:17:32 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [21]
[Homebridge] [1/31/2020, 5:17:32 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/31/2020, 5:17:32 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/31/2020, 5:17:32 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
[Homebridge] [1/31/2020, 5:17:35 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/31/2020, 5:17:35 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/31/2020, 5:17:35 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [21]
[Homebridge] [1/31/2020, 5:17:35 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/31/2020, 5:17:35 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/31/2020, 5:17:35 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
[Homebridge] [1/31/2020, 5:28:04 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/31/2020, 5:28:04 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/31/2020, 5:28:04 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/31/2020, 5:28:04 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [21]
[Homebridge] [1/31/2020, 5:28:04 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/31/2020, 5:28:04 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
[Homebridge] [1/31/2020, 5:28:06 AM] [Telldus Liv!e] [Bedroom - Dan] Getting value for dimmer Bedroom - Dan [21]
[Homebridge] [1/31/2020, 5:28:06 AM] [Telldus Liv!e] [Bedroom - Dan] Getting state for switch Bedroom - Dan [on]
[Homebridge] [1/31/2020, 5:28:06 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting value for dimmer Bedroom - Lisbeth [0]
[Homebridge] [1/31/2020, 5:28:06 AM] [Telldus Liv!e] [Arbetsrum - vägg] Getting state for switch Arbetsrum - vägg [off]
[Homebridge] [1/31/2020, 5:28:06 AM] [Telldus Liv!e] [Bedroom - Lisbeth] Getting state for switch Bedroom - Lisbeth [off]
[Homebridge] [1/31/2020, 5:28:06 AM] [Telldus Liv!e] [Living room - standing lamp] Getting state for switch Living room - standing lamp [off]
```

**Additional context**
Here is the iwconfig info from Terminal

hoobs@hoobs:~/.hoobs/etc $ iwconfig
eth0      no wireless extensions.

lo        no wireless extensions.

wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

hoobs@hoobs:~/.hoobs/etc $

**Comment by mkellsy** [comment]
We use Balina for this. You can find a list of supported dongles here.

https://www.balena.io/docs/reference/hardware/wifi-dongles/

**Comment by danlun** [comment]
Aha, well that wasnt clear for me when starting this off. But okay. Then maybe this isnt a bug? Nevertheless I have a DWA-131 dongle which is on the reffered page "elinux rpi wifi page" as described on Balena web pages. 
Worst case I of course need to buy another dongle, but the ones on Balea web pages was mostly in "no production". Like the Adafruit Miniature Wifi (802.11B/G/N) Module, the EP-N8531 and the original Raspeberri PI dongle...... Maybe something to discuss with them?
Im living in Portugal and the market/availability isnt as good as elsewhere here, so when the web doesnt have items (being possible to send to here) we are a bit stuck.... Thats why Im hoping on the DWA-131....

**Comment by mkellsy** [comment]
We actually don't control this part, it is part of balina. They have the ultimate say in what this connect utility supports.

**Comment by danlun** [comment]
Okay, have written to them.....
