### ISSUE TITLE
Got SIGINT, shuttling down service 

### ISSUE THREAD

**Issue by NickWerhle116** [hoobs-org/HOOBS#463]
Whenever I install SmartThings Tonesto7
It will not work. It immediately shuts down homebridge. There is 3 different packages and all 3 of them have been updated in the past week

**Expected behavoir**
Connect to my SmartThings devices, switches, thermostats 

**Plugin name**
SmartThings Tonesto7
**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.
Newest installed it today
**Did you upgrade**
Please let us know if you upgraded from a previous version.
No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
 No

**What device are you using?**
Please let us know the device you are running HOOBS on.

- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system  and version you are using. Ex. Fedora 30 or macOS Catalina.
RPI3B+
I just installed the iso from the site today
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYDF57",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "USERNAME”
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "SmartThings",
            "plugin_map": {
                "plugin_name": "homebridge-smartthings-tonesto7"
            }
        }
    ]
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```

[2/1/2020, 4:39:43 PM] HOOBS listning on port 8080.[Homebridge] [2/1/2020, 4:39:44 PM] Loaded config.json with 0 accessories and 0 platforms.[Homebridge] [2/1/2020, 4:39:45 PM] No plugins found.[Homebridge] [2/1/2020, 4:39:45 PM] Loading 0 platforms...[Homebridge] [2/1/2020, 4:39:45 PM] Loading 0 accessories...[Homebridge] [2/1/2020, 4:39:45 PM] API launched[Homebridge] [2/1/2020, 4:39:45 PM] Service is running on port 51826.[Homebridge] [2/1/2020, 4:44:49 PM] Got SIGINT, shutting down service...+ homebridge-smartthings-tonesto7@1.5.16
added 5 packages from 2 contributors and audited 841 packages in 12.696s
16 packages are looking for funding
  run `npm fund` for detailsfound 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details[2/1/2020, 4:45:07 PM] Installed "homebridge-smartthings-tonesto7" package.[Homebridge] [2/1/2020, 4:45:08 PM] Loaded config.json with 0 accessories and 1 platforms.[Homebridge] [2/1/2020, 4:45:09 PM] Loaded plugin: "homebridge-smartthings-tonesto7"[Homebridge] Homebridge Version: 2.4[Homebridge] [2/1/2020, 4:45:09 PM] Registering platform "homebridge-smartthings.SmartThings"[Homebridge] [2/1/2020, 4:45:09 PM] Loading 1 platforms...[Homebridge] [2/1/2020, 4:45:09 PM] [SmartThings] Initializing SmartThings platform...[Homebridge] [2/1/2020, 4:45:09 PM] [SmartThings] Fetching SmartThings devices.[Homebridge] [2/1/2020, 4:45:09 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at Object.init (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-tonesto7/lib/he_st_api.js:108:26)
    at HE_ST_Platform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-tonesto7/index.js:194:19)
    at Server._loadPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:369:22)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:296:18)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11[Homebridge] [2/1/2020, 4:45:09 PM] Got SIGTERM, shutting down service...[Homebridge] [2/1/2020, 4:54:05 PM] Loaded config.json with 0 accessories and 1 platforms.[Homebridge] [2/1/2020, 4:54:06 PM] Loaded plugin: "homebridge-smartthings-tonesto7"[Homebridge] Homebridge Version: 2.4[Homebridge] [2/1/2020, 4:54:06 PM] Registering platform "homebridge-smartthings.SmartThings"[Homebridge] [2/1/2020, 4:54:06 PM] Loading 1 platforms...[Homebridge] [2/1/2020, 4:54:06 PM] [SmartThings] Initializing SmartThings platform...[Homebridge] [2/1/2020, 4:54:06 PM] [SmartThings] Fetching SmartThings devices.[Homebridge] [2/1/2020, 4:54:06 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined

at validateString (internal/validators.js:112:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at Object.init (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-tonesto7/lib/he_st_api.js:108:26)
    at HE_ST_Platform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-tonesto7/index.js:194:19)
    at Server._loadPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:369:22)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:296:18)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11[Homebridge] [2/1/2020, 4:54:06 PM] Got SIGTERM, shutting down service...[Homebridge] [2/1/2020, 4:54:13 PM] Loaded config.json with 0 accessories and 1 platforms.[Homebridge] [2/1/2020, 4:54:14 PM] Loaded plugin: "homebridge-smartthings-tonesto7"[Homebridge] Homebridge Version: 2.4[Homebridge] [2/1/2020, 4:54:14 PM] Registering platform "homebridge-smartthings.SmartThings"[Homebridge] [2/1/2020, 4:54:14 PM] Loading 1 platforms...[Homebridge] [2/1/2020, 4:54:14 PM] [SmartThings] Initializing SmartThings platform...[Homebridge] [2/1/2020, 4:54:14 PM] [SmartThings] Fetching SmartThings devices.[Homebridge] [2/1/2020, 4:54:14 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at Object.init (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-tonesto7/lib/he_st_api.js:108:26)
    at HE_ST_Platform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-tonesto7/index.js:194:19)
    at Server._loadPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:369:22)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:296:18)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11[Homebridge] [2/1/2020, 4:54:14 PM] Got SIGTERM, shutting down service...
```

**Additional context**

**Comment by askovi** [comment]
Please follow the issue template and provide all the required details.

**Comment by NickWerhle116** [comment]
> Please follow the issue template and provide all the required details.
Sorry I fixed it

**Comment by askovi** [comment]
You have to configure a plugin with all the required details. 
For smartthings use this plugin homebridge-smartthings-v2

Configuration details here: https://www.npmjs.com/package/homebridge-smartthings-v2

**Comment by mkellsy** [comment]
That plugin is no longer maintained. Please use this one homebridge-smartthings-v2. He moved all development to that plugin.
