### ISSUE TITLE
Error during searching for Plugins - Docker

### ISSUE THREAD

**Issue by MexxReal** [hoobs-org/HOOBS#486]
**Description**
During searching for plugins, the search crashes and I have to do the login again. I can't install any plugin.

**Version**
Hoobs is runinng in docker. 

- Hoobs is actually running in docker, it's HOOBS Core Version 3.1.20 (Docker). The compose-file uses for the image: hoobs/hoobs:latest.
- Homebridge version 0.4.50
- Node version 10.18.0

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- Custom Install on PI4B

**If this is a custom install, what's your operating system?**
Raspbian Buster Lite

**List your plugins**
None, bc of error

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

docker-compose.yml:
 ```
 hoobs:
    image: hoobs/hoobs:latest
    container_name: hoobs
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
    volumes:
      - /opt/appdata/hoobs:/hoobs
    ports:
      - 8080:8080
      - 8181:8181
      - 51826:51826
    restart: always
```

/opt/appdata/hoobs/default.json:
```
{
	"server":{
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://",
        "polling_seconds": 5,
        "docker": true
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "90404"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "",
    "ports": {},
    "plugins": [],
    "accessories": [],
	"platforms": []
}
```

/opt/appdata/hoobs/package.json:
```
{
    "name": "@hoobs/hoobs",
    "version": "3.1.20",
    "description": "Certified HOOBS stack",
    "license": "Apache-2.0",
    "keywords": [
        "HOOBS",
        "homebridge"
    ],
    "repository": {
        "type": "git",
        "url": "git://github.com/hoobs-org/hoobs-core.git"
    },
    "bugs": {
        "url": "https://github.com/hoobs-org/hoobs-core/issues"
    },
    "main": "lib/cli.js",
    "author": "Michael J Kellsy",
    "engines": {
        "node": ">=10.16.0"
    },
    "dependencies": {
        "@hoobs/homebridge": "^3.1.18",
        "@hoobs/systeminfo": "^4.14.7",
        "archiver": "^3.1.1",
        "axios": "^0.19.0",
        "commander": "^3.0.2",
        "cors": "^2.8.5",
        "express": "^4.17.1",
        "express-ws": "^4.0.0",
        "folder-hash": "^3.3.0",
        "formidable": "^1.2.1",
        "fs-extra": "^8.1.0",
        "glob": "^7.1.6",
        "lodash": "^4.17.15",
        "node-cache": "^5.0.0",
        "node-pty": "^0.9.0",
        "ora": "^4.0.2",
        "prompt": "^1.0.0",
        "recursive-copy": "^2.0.10",
		"request": "^2.88.0",
        "rimraf": "^3.0.0",
        "sanitize-filename": "^1.6.3",
        "unzipper": "^0.10.5",
        "ws": "^7.2.0"
    },
    "postcss": {
        "plugins": {
            "autoprefixer": {}
        }
    },
    "browserslist": [
        "> 1%",
        "last 2 versions"
    ],
    "optionalDependencies": {
        "bufferutil": "^4.0.1",
        "utf-8-validate": "^5.0.2"
    }
}
```

Config-File from hoobs GUI:
```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY0CGE",
        "polling_seconds": 5,
        "docker": true
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "12487",
        "latitude": "52.520007",
        "longitude": "13.404954"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "32:3E:54:C8:A4:01"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```

**Post your log**

$ docker-compose logs
```
hoobs | [2/20/2020, 9:31:22 PM] Unhandled Rejection "Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com raw.githubusercontent.com:443".
hoobs | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
hoobs | [2/20/2020, 9:31:52 PM] Unhandled Rejection "Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com raw.githubusercontent.com:443".
hoobs | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
hoobs | [2/20/2020, 9:31:52 PM] Unhandled Rejection "Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com raw.githubusercontent.com:443".
hoobs | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
hoobs | [2/20/2020, 9:31:57 PM] Unhandled Rejection "Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com raw.githubusercontent.com:443".
hoobs | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
hoobs | [2/20/2020, 9:31:57 PM] Unhandled Rejection "Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com raw.githubusercontent.com:443".
hoobs | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 9)
hoobs | [2/20/2020, 9:32:02 PM] Unhandled Rejection "Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com raw.githubusercontent.com:443".
hoobs | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 11)
hoobs | [2/20/2020, 9:32:02 PM] Unhandled Rejection "Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com raw.githubusercontent.com:443".
hoobs | (node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 13)
hoobs | [2/20/2020, 9:32:07 PM] Cannot read property 'objects' of undefined
hoobs | TypeError: Cannot read property 'objects' of undefined
hoobs | at Request [as _callback] (/hoobs/lib/plugins.js:363:41)
hoobs | at self.callback (/hoobs/node_modules/request/request.js:185:22)
hoobs | at Request.emit (events.js:198:13)
hoobs | at Request.onRequestError (/hoobs/node_modules/request/request.js:881:8)
hoobs | at ClientRequest.emit (events.js:198:13)
hoobs | at TLSSocket.socketErrorListener (_http_client.js:392:9)
hoobs | at TLSSocket.emit (events.js:198:13)
hoobs | at emitErrorNT (internal/streams/destroy.js:91:8)
hoobs | at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
hoobs | at process._tickCallback (internal/process/next_tick.js:63:19)
hoobs | /hoobs/lib/plugins.js:363
hoobs | body.objects = body.objects || [];
hoobs | ^
hoobs |
hoobs | TypeError: Cannot read property 'objects' of undefined
hoobs | at Request [as _callback] (/hoobs/lib/plugins.js:363:41)
hoobs | at self.callback (/hoobs/node_modules/request/request.js:185:22)
hoobs | at Request.emit (events.js:198:13)
hoobs | at Request.onRequestError (/hoobs/node_modules/request/request.js:881:8)
hoobs | at ClientRequest.emit (events.js:198:13)
hoobs | at TLSSocket.socketErrorListener (_http_client.js:392:9)
hoobs | at TLSSocket.emit (events.js:198:13)
hoobs | at emitErrorNT (internal/streams/destroy.js:91:8)
hoobs | at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
hoobs | at process._tickCallback (internal/process/next_tick.js:63:19)
hoobs |
hoobs | [2/20/2020, 9:32:17 PM] HOOBS listning on port 8080.
hoobs | [Homebridge] [2/20/2020, 9:32:18 PM] Loaded config.json with 0 accessories and 0 platforms.
hoobs | [Homebridge] [2/20/2020, 9:32:18 PM] No plugins found.
hoobs | [Homebridge] [2/20/2020, 9:32:18 PM] Loading 0 platforms...
hoobs | [Homebridge] [2/20/2020, 9:32:18 PM] Loading 0 accessories...
hoobs | [Homebridge] [2/20/2020, 9:32:18 PM] API launched
hoobs | [Homebridge] [2/20/2020, 9:32:18 PM] Service is running on port 51826.
```

**Additional context**
- it's impossible to run in terminal of hoobs $ wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
 Error: 
sh: sudo: not found
wget: bad address 'bit.ly'

**Comment by mkellsy** [comment]
Found out that this has nothing to do with the docker version. It happens when NPM returns a non 200 response, and the "body" is null.

I corrected this in 3.1.21
