### ISSUE TITLE
Zip Code update causes home bridge server to stop

### ISSUE THREAD

**Issue by joshchipps** [hoobs-org/HOOBS#528]
**Description**

**Version**
3.1.23

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.1.22

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Rasbian Buster 4.19.97-v7+

**List your plugins**
SmartThings V2

**Post your config**
```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYGM18",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "legally-pink",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "95008"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "07:50:A1:D2:21:7E"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "SmartThings-v2",
            "plugin_map": {
                "plugin_name": "homebridge-smartthings-v2"
            },
            "name": "SmartThings-v2",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "disableErrorReporting": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "Good"
                }
            },
            "access_token": "redacted",
            "app_id": "redacted",
            "app_url": "redacted"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[3/22/2020, 18:04:05] HOOBS listening on port 8080.
[Homebridge] [3/22/2020, 18:04:07] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [3/22/2020, 18:04:07] No plugins found.
[Homebridge] [3/22/2020, 18:04:07] Loading 0 platforms...
[Homebridge] [3/22/2020, 18:04:07] Loading 0 accessories...
[Homebridge] [3/22/2020, 18:04:07] API launched
[Homebridge] [3/22/2020, 18:04:07] Service is running on port 51826.
[Homebridge] [3/22/2020, 18:13:00] Got SIGINT, shutting down service...
[Homebridge] [3/22/2020, 18:13:02] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [3/22/2020, 18:13:02] No plugins found.
[Homebridge] [3/22/2020, 18:13:02] Loading 0 platforms...
[Homebridge] [3/22/2020, 18:13:02] Loading 0 accessories...
[Homebridge] [3/22/2020, 18:13:02] API launched
[Homebridge] [3/22/2020, 18:13:02] Service is running on port 51826.
[Homebridge] [3/22/2020, 18:13:14] Got SIGINT, shutting down service...
[Homebridge] [3/22/2020, 18:13:16] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [3/22/2020, 18:13:16] No plugins found.
[Homebridge] [3/22/2020, 18:13:16] Loading 0 platforms...
[Homebridge] [3/22/2020, 18:13:16] Loading 0 accessories...
[Homebridge] [3/22/2020, 18:13:16] API launched
[Homebridge] [3/22/2020, 18:13:16] Service is running on port 51826.
[Homebridge] [3/22/2020, 18:14:12] Got SIGINT, shutting down service...
npm
 notice created a lockfile as package-lock.json. You should commit this file.
npm
 WARN winston-daily-rotate-file@4.4.2 requires a peer of winston@^3 but none is installed. You must install peer dependencies yourself.
+ homebridge-smartthings-v2@2.3.2
added 52 packages from 44 contributors, removed 4 packages and audited 1057 packages in 17.25s

17 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
[3/22/2020, 18:14:34] Installed "homebridge-smartthings-v2" package.
[Homebridge] [3/22/2020, 18:14:35] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [3/22/2020, 18:14:36] Loaded plugin: "homebridge-smartthings-v2"
[Homebridge] [3/22/2020, 18:14:36] Registering platform "homebridge-smartthings-v2.SmartThings-v2"
[Homebridge] [3/22/2020, 18:14:36] Loading 1 platforms...
[Homebridge] [3/22/2020, 18:14:36] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] [3/22/2020, 18:14:36] [SmartThings-v2] SmartThings-v2 Plugin is not Configured | Skipping...
[Homebridge] [3/22/2020, 18:14:36] Loading 0 accessories...
[Homebridge] [3/22/2020, 18:14:36] API launched
[Homebridge] [3/22/2020, 18:14:36] Service is running on port 51826.
[Homebridge] [3/22/2020, 18:16:24] Got SIGINT, shutting down service...
[Homebridge] [3/22/2020, 18:16:26] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [3/22/2020, 18:16:27] Loaded plugin: "homebridge-smartthings-v2"
[Homebridge] [3/22/2020, 18:16:27] Registering platform "homebridge-smartthings-v2.SmartThings-v2"
[Homebridge] [3/22/2020, 18:16:27] Loading 1 platforms...
[Homebridge] [3/22/2020, 18:16:27] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] INFO: Homebridge Version: 2.4
[Homebridge] INFO: SmartThings-v2 Plugin Version: 2.3.2
[Homebridge] INFO: Sentry MachineId: b63e32ede9e4c2b398d634b7f44afc380e7c8dd37a102b38f20ba14b10b3cb02
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] [3/22/2020, 18:16:27] Loading 0 accessories...
[Homebridge] INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
[Homebridge] GOOD: Refreshing All Device Data | Source: (First Launch)
[Homebridge] [3/22/2020, 18:16:27] API launched
[Homebridge] [3/22/2020, 18:16:27] Service is running on port 51826.
[Homebridge] NOTICE: Temperature Unit is Now: (F)
[Homebridge] NOTICE: Updating Global Values | HubIP: 192.168.40.45 | UseLocal: false
[Homebridge] WARN: Devices to Remove: (0) []
[Homebridge] INFO: Devices to Update: (0)
[Homebridge] GOOD: Devices to Create: (42) [
[Homebridge] [32m'Front Door Lock'[39m,
[Homebridge] [32m'Garage Lights'[39m,
[Homebridge] [32m'Front Lamp'[39m,
[Homebridge] [32m'Thermostat'[39m,
[Homebridge] [32m'Entrance Light'[39m,
[Homebridge] [32m'Front Door'[39m,
[Homebridge] [32m'Garage Motion Sensor'[39m,
[Homebridge] [32m'Garage Patio Door'[39m,
[Homebridge] [32m'Master Siren'[39m,
[Homebridge] [32m'Living Room Lamp'[39m,
[Homebridge] [32m'Master Bedroom Right'[39m,
[Homebridge] [32m'Office Window'[39m,
[Homebridge] [32m'Kitchen Outlet'[39m,
[Homebridge] [32m'Rachio - Rachio-8EF2ED'[39m,
[Homebridge] [32m'Safe'[39m,
[Homebridge] [32m'Sliding Glass Door'[39m,
[Homebridge] [32m'Water Leak Sensor'[39m,
[Homebridge] [32m'Bacchus Window'[39m,
[Homebridge] [32m'Wine Cellar'[39m,
[Homebridge] [32m'private'[39m,
[Homebridge] [32m'master bathroom'[39m,
[Homebridge] [32m'Rachio - Planter beds and all yard'[39m,
[Homebridge] [32m'First Alert Smoke Detector and Carbon Monoxide Alarm (ZCOMBO)'[39m,
[Homebridge] [32m'Front Door'[39m,
[Homebridge] [32m'Garage Patio Door'[39m,
[Homebridge] [32m'Wine Cellar'[39m,
[Homebridge] [32m'Garage Motion Sensor'[39m,
[Homebridge] [32m'Sliding Glass Door'[39m,
[Homebridge] [32m'Upstairs First Alert Smoke Detector'[39m,
[Homebridge] [32m'Water Leak Sensor'[39m,
[Homebridge] [32m'Bacchus Window'[39m,
[Homebridge] [32m'Master Bedroom Right'[39m,
[Homebridge] [32m'Safe'[39m,
[Homebridge] [32m'Thermostat'[39m,
[Homebridge] [32m'Office Window'[39m,
[Homebridge] [32m'Front Door Lock'[39m,
[Homebridge] [32m'master bathroom'[39m,
[Homebridge] [32m'Garage Lights'[39m,
[Homebridge] [32m'Front Lamp'[39m,
[Homebridge] [32m'Living Room Lamp'[39m,
[Homebridge] [32m'Kitchen Outlet'[39m,
[Homebridge] [32m'Entrance Light'[39m
[Homebridge] ]
[Homebridge] INFO: Added Device: (Front Door Lock | d38dd30c-0b18-42ed-991a-efaf99f4d232)
[Homebridge] INFO: Added Device: (Garage Lights | 410b88b8-56e7-4955-bf0d-eb24aa2c53e1)
[Homebridge] INFO: Added Device: (Front Lamp | f2d7ec28-6288-46ae-8fb5-0e93a0b1abf2)
[Homebridge] INFO: Added Device: (Thermostat | 38539055-a0dd-4c7d-bf5c-c5a3e3e9f1c4)
[Homebridge] INFO: Added Device: (Entrance Light | 9521cf8f-4aaf-45c8-86a4-5c24dddf40fa)
[Homebridge] INFO: Added Device: (Front Door | 3ea88fae-5760-485f-880f-8c1de16e05aa)
[Homebridge] INFO: Added Device: (Garage Motion Sensor | b64efa01-f6b9-449d-8f76-0f72b3bf5bf2)
[Homebridge] INFO: Added Device: (Garage Patio Door | f6cec51d-78a6-49bf-a346-90ec55b10a2c)
[Homebridge] INFO: Added Device: (Master Siren | 04e243a0-9ba5-4b85-80d1-6163e3d80e1d)
[Homebridge] INFO: Added Device: (Living Room Lamp | 2b52d350-0c13-412d-aeb2-cd516b32c64c)
[Homebridge] INFO: Added Device: (Master Bedroom Right | bb89d496-14cc-45c3-a52f-d1af84db276a)
[Homebridge] INFO: Added Device: (Office Window | a4463d68-e561-4d13-a5c5-8afc5638faa6)
[Homebridge] INFO: Added Device: (Kitchen Outlet | 07158c84-7ea5-404f-aacf-74b07a4f5886)
[Homebridge] INFO: Added Device: (Rachio - Rachio-8EF2ED | c450b6e0-4877-4e03-a6d7-00251a26510a)
[Homebridge] INFO: Added Device: (Safe | 6fdf560a-2245-400e-860d-267f95a45288)
[Homebridge] INFO: Added Device: (Sliding Glass Door | 8e2d9f05-a753-496c-aabe-04112b93dbd0)
[Homebridge] INFO: Added Device: (Water Leak Sensor | 6e377916-3ad9-4468-8ab5-2ba8c78d5692)
[Homebridge] INFO: Added Device: (Bacchus Window | 52a72549-5998-465c-a4c8-1068817a45f3)
[Homebridge] INFO: Added Device: (Wine Cellar | b4bdde5d-45b5-42d8-b999-3ede87e1879b)
[Homebridge] INFO: Added Device: (private | 8a892b51-95c8-95e6-9b7d-bb206995daa7)
[Homebridge] INFO: Added Device: (master bathroom | 9b94f5af-df9b-4146-84c1-971d8b6c2a1c)
[Homebridge] INFO: Added Device: (Rachio - Planter beds and all yard | 352a886e-bedc-4564-85c5-bf2b92402a6d)
[Homebridge] INFO: Added Device: (First Alert Smoke Detector and Carbon Monoxide Alarm (ZCOMBO) | cbd2d931-e569-44a3-bb97-debe743aebf5)
[Homebridge] [3/22/2020, 18:16:30] Unhandled Rejection "Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 810252c5-a941-4356-8980-9b5eb574a5cd".
[Homebridge] [3/22/2020, 18:16:30] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 810252c5-a941-4356-8980-9b5eb574a5cd
    at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:456:18)
    at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:31:14)
    at API.emit (events.js:210:5)
    at API.EventEmitter.emit (domain.js:475:20)
    at API.registerPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:154:10)
    at ST_Platform.addDevice (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:225:25)
    at /home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:195:61
    at Array.forEach (<anonymous>)
[Homebridge] (node:1502) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Homebridge] INFO: INFO: Your plugin version is up-to-date
[Homebridge] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.2
[Homebridge] ERROR: sendUpdateStatus Error: [object Object] | Message: Request failed with status code 404
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] NOTICE: Sending Device Command: off | Name: (Living Room Lamp) | DeviceID: (2b52d350-0c13-412d-aeb2-cd516b32c64c) | SendToLocalHub: (false)
[Homebridge] NOTICE: Sending Device Command: off | Name: (Entrance Light) | DeviceID: (9521cf8f-4aaf-45c8-86a4-5c24dddf40fa) | SendToLocalHub: (false)
[Homebridge] NOTICE: Sending Device Command: off | Name: (Front Lamp) | DeviceID: (f2d7ec28-6288-46ae-8fb5-0e93a0b1abf2) | SendToLocalHub: (false)
[Homebridge] NOTICE: Sending Device Command: on | Name: (Living Room Lamp) | DeviceID: (2b52d350-0c13-412d-aeb2-cd516b32c64c) | SendToLocalHub: (false)
[Homebridge] NOTICE: Sending Device Command: on | Name: (Entrance Light) | DeviceID: (9521cf8f-4aaf-45c8-86a4-5c24dddf40fa) | SendToLocalHub: (false)
[Homebridge] NOTICE: Sending Device Command: on | Name: (Front Lamp) | DeviceID: (f2d7ec28-6288-46ae-8fb5-0e93a0b1abf2) | SendToLocalHub: (false)
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] GOOD: Refreshing All Device Data
[Homebridge] NOTICE: Temperature Unit is Now: (F)
[Homebridge] NOTICE: Updating Global Values | HubIP: 192.168.40.45 | UseLocal: false
[Homebridge] WARN: Devices to Remove: (0) []
[Homebridge] INFO: Devices to Update: (23)
[Homebridge] GOOD: Devices to Create: (1) [ [32m'Upstairs First Alert Smoke Detector'[39m ]
[Homebridge] INFO: Added Device: (Upstairs First Alert Smoke Detector | d8b17622-9ed4-4eab-bf68-a59f808314ae)
[Homebridge] ALERT: Total Initialization Time: (2 seconds)
[Homebridge] NOTICE: Unknown Capabilities: ["Health Check","Indicator","Outlet","Three Axis","Ocf","Execute","Network Meter","Smoke Detector"]
[Homebridge] INFO: SmartThings DeviceCache Size: (24)
[Homebridge] INFO: Checking Package Version for Updates...
[Homebridge] INFO: INFO: Your plugin version is up-to-date
[Homebridge] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.2
[Homebridge] ERROR: sendUpdateStatus Error: [object Object] | Message: Request failed with status code 404
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
[Homebridge] heatingSetpoint:  68
[Homebridge] coolingSetpoint:  77
```

**Additional context**
It seems the only way to get HomeKit back running is to do a factory reset, and re-add Smartthings plug in.  Almost any change to HOOBS will result in the home bridge server stopping, and nothing will restart it.

**Comment by mkellsy** [comment]
Duplicate of #529
