### ISSUE TITLE
Samsung Smartthings V2 - Added devices aren't showing up in HOOBS

### ISSUE THREAD

**Issue by joshchipps** [hoobs-org/HOOBS#529]
**Description**
I have a small/medium system with about 31 devices.  But in hoobs I only see 23.  I've recently added additional Samsung branded devices that I already have on my system but they do not show up in HOOBS to HomeKit.

**Expected behavoir**
I should see ALL my devices

**Plugin name**
Samsung Smartthings V2

**Please report the issue to the plugin developer**
Is this a plug in problem?

**Version**
3.1.23

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Rasbian Buster
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYGM18",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "legally-pink",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "95008"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "07:50:A1:D2:21:7E"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "SmartThings-v2",
            "plugin_map": {
                "plugin_name": "homebridge-smartthings-v2"
            },
            "name": "SmartThings-v2",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "disableErrorReporting": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "Good"
                }
            },
            "access_token": "Redacted",
            "app_id": "Redacted",
            "app_url": "Redacted"
        }
    ]
}
```

**Post your log**
```
[Homebridge] [3/22/2020, 18:16:30] Unhandled Rejection "Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 810252c5-a941-4356-8980-9b5eb574a5cd".
[Homebridge] [3/22/2020, 18:16:30] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 810252c5-a941-4356-8980-9b5eb574a5cd
    at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:456:18)
    at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:31:14)
    at API.emit (events.js:210:5)
    at API.EventEmitter.emit (domain.js:475:20)
    at API.registerPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:154:10)
    at ST_Platform.addDevice (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:225:25)
    at /home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:195:61
    at Array.forEach (<anonymous>)
[Homebridge] (node:1502) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
...
[Homebridge] ERROR: sendUpdateStatus Error: [object Object] | Message: Request failed with status code 404
```

> Log truncated to show relevant information

**Additional context**

**Comment by mkellsy** [comment]
Change the username for the bridge. This can be done in the Config screen under the Apple Home section. Click the refresh icon.

Then you will need to re-pair with homekit.

**Comment by mkellsy** [comment]
I dug further into this and realized it is common with Homebridge.

In the Help screen click the Reset Connection button.
