### ISSUE TITLE
Can Not connect To Hoobs.local

### ISSUE THREAD

**Issue by Thommy-de** [hoobs-org/HOOBS#530]
When i try Login To Hoobs.local im getting Stucked With a yellow Screen and the Homemanager App is showing that the Server is down.
When i‘m Closing the Browser the homemanager App is showing That the Server is Running.

**Comment by askovi** [comment]
Please login via ssh with user: hoobs pass: hoobsadmin and run command: sudo hoobs service log
Post the logs here so we can debug.

**Comment by bergomel** [comment]
Hello, I'm running into the same problem. What can I do? Reinstall HOOBS? Thanks

hoobs@hoobs:~ $ sudo hoobs service log
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 13.
Stopped HOOBS.
hoobs.service: Found left-over process 949 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 973 (sh) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 974 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 981 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1300:21)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
{and it repeats several times...}
