### ISSUE TITLE
Error after installing Xiaomi Homebridge-roborock plugin

### ISSUE THREAD

**Issue by MexxReal** [hoobs-org/HOOBS#544]
**Description**
After installation and configuration of homebridge-roborock plugin I get an error in log of Hoobs and the service can't be started.   
The installation of this plugin followed two ways:
1. installation and configuration via hoobs-WBM
2. installation and configuration via console

Both ways are ending in described error. 

**Expected behavoir**
The homebridge-service starts without any failures.

**Plugin name**
homebridge-roborock 0.5.3, veröffentlicht 4/5/2020

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
- Hoobs image complete (downloaded from hoobs.org)

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYCJ2F",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 10,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "12487",
        "latitude": "52.520007",
        "longitude": "13.404954"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "5E:6C:32:8B:AD:68"
    },
    "description": "Zuhause",
    "ports": {},
    "accessories": [
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "homebridge-roborock",
                "index": 0
            },
            "name": "Robi",
            "waterBox": true,
            "pause": false,
            "dock": true,
            "delay": false,
            "cleanword": "sauge",
            "autoroom": true,
            "ip": "192.168.178.12",
            "token": "123456"
        }
    ],
    "platforms": [
        {
            "platform": "eveatmo",
            "plugin_map": {
                "plugin_name": "homebridge-eveatmo"
            },
            "name": "eveatmo platform",
            "ttl": 600,
            "extra_co2_sensor": false,
            "co2_alert_threshold": 2000,
            "auth": {
                "client_id": "123456",
                "client_secret": "qwerty",
                "username": "xyz@xyz.de",
                "password": "xwertz"
            }
        },
        {
            "platform": "TadoPlatform",
            "username": "xyz@xyz.de",
            "password": "qwertz",
            "homeID": 123456,
            "unit": "celsius",
            "plugin_map": {
                "plugin_name": "homebridge-tado-platform"
            },
            "polling": 10,
            "reConfig": false,
            "occupancy": false,
            "anyone": false,
            "weather": false,
            "openWindow": false,
            "solarIntensity": false,
            "centralSwitch": false,
            "externalSensor": false,
            "deviceOptions": {
                "RU2929790720-1": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 1,
                    "zoneName": "Wohnzimmer",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU2929790720",
                    "type": "thermostat"
                },
                "VA1559299584-1": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 1,
                    "zoneName": "Wohnzimmer",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA1559299584",
                    "type": "thermostat"
                },
                "VA2698774016-4": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 4,
                    "zoneName": "Badezimmer",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA2698774016",
                    "type": "thermostat"
                },
                "RU1235422976-6": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 6,
                    "zoneName": "Schlafzimmer",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU1235422976",
                    "type": "thermostat"
                },
                "VA2090862336-6": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 6,
                    "zoneName": "Schlafzimmer",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA2090862336",
                    "type": "thermostat"
                },
                "VA3310028032-7": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 7,
                    "zoneName": "Küche",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA3310028032",
                    "type": "thermostat"
                },
                "VA3930785024-8": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 8,
                    "zoneName": "Arbeitszimmer",
                    "zoneType": "HEATING",
                    "deviceType": "VA",
                    "serial": "VA3930785024",
                    "type": "thermostat"
                }
            }
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "hosts": [
                "192.168.178.5"
            ],
            "users": {
                "ABC": "qwertz"
            }
        }
    ]
}
```

**Post your log**

```
[Homebridge] [4/12/2020, 12:28:57 PM] Loaded config.json with 1 accessories and 3 platforms.
[Homebridge] [4/12/2020, 12:28:57 PM] Loaded plugin: "homebridge-eveatmo"
[Homebridge] [4/12/2020, 12:28:57 PM] Registering platform "homebridge-eveatmo.eveatmo"
[Homebridge] [4/12/2020, 12:28:58 PM] Loaded plugin: "homebridge-roborock"
[Homebridge] [4/12/2020, 12:28:58 PM] Registering accessory "homebridge-roborock.RoborockVacuum"
[Homebridge] [4/12/2020, 12:28:58 PM] Plugin /home/hoobs/.hoobs/node_modules/homebridge-tado-platform requires Node version of ^10.15.3 which does not satisfy the current Node version of v12.14.1. You may need to upgrade your installation of Node.
[Homebridge] [4/12/2020, 12:28:58 PM] Loaded plugin: "homebridge-tado-platform"
[Homebridge] [4/12/2020, 12:28:58 PM] Registering platform "homebridge-tado-platform.TadoPlatform"
[Homebridge] [4/12/2020, 12:28:59 PM] Loaded plugin: "hue"
[Homebridge] [4/12/2020, 12:28:59 PM] Registering platform "homebridge-hue.Hue"
[Homebridge] [4/12/2020, 12:28:59 PM] Loading 3 platforms...
[Homebridge] [4/12/2020, 12:28:59 PM] [eveatmo platform] Initializing eveatmo platform...
[Homebridge] [4/12/2020, 12:28:59 PM] [eveatmo platform] Loading new data from API for: weatherstation
[Homebridge] [4/12/2020, 12:28:59 PM] [TadoPlatform] Initializing TadoPlatform platform...
[Homebridge] [4/12/2020, 12:28:59 PM] [TadoPlatform] [INFO] **************************************************************
[Homebridge] [4/12/2020, 12:28:59 PM] [TadoPlatform] [INFO] TadoPlatform v5.1.6 by SeydX
[Homebridge] [4/12/2020, 12:28:59 PM] [TadoPlatform] [INFO] GitHub: https://github.com/SeydX/homebridge-tado-platform
[Homebridge] [4/12/2020, 12:28:59 PM] [TadoPlatform] [INFO] Email: seyd55@outlook.de
[Homebridge] [4/12/2020, 12:28:59 PM] [TadoPlatform] [INFO] **************************************************************
[Homebridge] [4/12/2020, 12:28:59 PM] [TadoPlatform] [INFO] start success...
[Homebridge] [4/12/2020, 12:28:59 PM] [Hue] Initializing Hue platform...
[Homebridge] [4/12/2020, 12:28:59 PM] [Hue] config.json: warning: plugin_map: ignoring unknown key
[Homebridge] [4/12/2020, 12:28:59 PM] [Hue] homebrige-hue v0.11.46, node v12.14.1, homebridge v0.4.50
[Homebridge] [4/12/2020, 12:28:59 PM] [Hue] warning: not using recommended node version v7.0.0 LTS
[Homebridge] [4/12/2020, 12:28:59 PM] [Hue] warning: not using recommended homebridge version v0.4.22
[Homebridge] [4/12/2020, 12:28:59 PM] Loading 1 accessories...
[Homebridge] [4/12/2020, 12:28:59 PM] Error: The requested accessory 'XiaomiRoborockVacuum' was not registered by any plugin.
    at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:258:48)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[Homebridge] [4/12/2020, 12:28:59 PM] Got SIGTERM, shutting down service...
[Homebridge] [4/12/2020, 12:29:00 PM] [Hue] npm registry: status 404 Not Found
[Homebridge] [4/12/2020, 12:29:00 PM] [Hue] Philips hue: Philips BSB002 bridge v1937113020, api v1.37.0
[Homebridge] [4/12/2020, 12:29:00 PM] [Hue] Philips hue: warning: not using recommended Hue bridge api version undefined
```

**Additional context**
/

**Comment by BobbySlope** [comment]
Theres an certified Plugin for Roborock please install this one.

HOOBS Certified
**Roborock**
0.6.5 published 12/6/2019
Xiaomi/Roborock plugin for HOOBS.

**Comment by MexxReal** [comment]
Thanks, this one works now. It seems very rudimentary. Does this plugin do autoroom detection and how do I set the value for water flow, if mopping is enabled?

**Comment by mkellsy** [comment]
We are testing 3.1.24 this should fix your issue. We are looking to release tommorow.

**Comment by mkellsy** [comment]
I just released 3.1.27
This issue has been fixed.
I recommend updating.

**Comment by JazzerAlto** [comment]
Any idea when the Hoobs team is going to update the certified Roborock plugin to catch up with the current release from the original author?  A lot of nice updates being made.

**Comment by BobbySlope** [comment]
we are currently working on the next major release of HOOBS, we will update all certified plugins with the release

**Comment by mkellsy** [comment]
I will update this plugin in the next few days

**Comment by JazzerAlto** [comment]
Thanks for the update.

**Comment by MexxReal** [comment]
Thanks for information. I'll install the other plugin again and tell you, if the fix works.

**Comment by mkellsy** [comment]
I upgraded this plugin. You may need to wait 24 hours before it shows.

**Comment by MexxReal** [comment]
I updated hoobs to v. 3.1.27 and the Roborock Plugin to the newest version. After updating the plugin connection to hoobs via Apple Homekit wasn't possible anymore. None of the devices are accessible anymore in Homekit-app and all rules are without function. 
Idk why, but hoobs log doesn't shows an error..

**Comment by JazzerAlto** [comment]
I am not seeing any issues with my setup.  Hoobs on 3.1.27 and plug in updated last night to the newest version.  My vacuum model is a Roborock S6.

**Comment by MexxReal** [comment]
Idk what I've done wrong, but I had to delete all plugins and accessories. After new configuration hoobs is now up & running without anything. I will now try to reinstall the Roborock-Plugin only. 
My model is also the S6.

Maybe it's a problem regarding to the other plugins (Eveatmo & Tado)..

**Comment by MexxReal** [comment]
Problem found! It's the eveatmo-plugin. Because of that, I'll close this ticket. It has become fixed.
