### ISSUE TITLE
Homebridge 0.4.53

### ISSUE THREAD

**Issue by jpjandrucko** [hoobs-org/HOOBS#548]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

 [A plugin I use requires upgrade if homebridge to 0.4.53  ]

**Describe the solution you'd like**

Upgrade homebridge to 0.4.53

**Describe alternatives you've considered**

**Additional context**

**Comment by mkellsy** [comment]
We are upgrading the HOOBS bridge. If the plugin is just logging a warning, it is OK to ignore it.

**Comment by jpjandrucko** [comment]
not a warning.  

[Homebridge] [4/13/2020, 12:20:41 PM] Error: The requested platform 'ZP' was not registered by any plugin.
    at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

best i can figure is homebridge needs to be updated.

**Comment by jpjandrucko** [comment]
https://github.com/ebaauw/homebridge-zp/issues/130

**Comment by mkellsy** [comment]
Yes we are working on this. We are upgrading our bridge. It is going to take some time.

WORKAROUND
Open the terminal and run these commands
```
cd ~/.hoobs
npm install homebridge-zp@1.0.23
```

**Comment by jpjandrucko** [comment]
Hoobs users - roll back to .23

open terminal and run the below.  HOOBS is working on an update.

cd ~/.hoobs
npm install homebridge-zp@1.0.23

**Comment by mkellsy** [comment]
We are testing 3.1.24 this should fix your issue. We are looking to release tommorow.

**Comment by MikeDeltaHH** [comment]
homebridge-zp works now with Hoobs 3.1.26 - any news about the certified plugin updates?

**Comment by mkellsy** [comment]
We are changing our certified program so it is easier to manage. It is tied to this site.
https://plugins.hoobs.org
