### ISSUE TITLE
Starting HOOBS service on Mac get Path had bad ownership/permissions

### ISSUE THREAD

**Issue by ptbtx** [hoobs-org/HOOBS#568]
**Description**
Following this guide on starting HOOBS service on Mac
https://support.hoobs.org/docs/5e763f09e87d1e02b6c19d39
Got this failure:
petebrunet@hoobs ~ % sudo launchctl load -w /Library/LaunchDaemons/com.hoobs.core.plist
Password:
/Library/LaunchDaemons/com.hoobs.core.plist: Path had bad ownership/permissions
petebrunet@hoobs ~ % ls -l /Library/LaunchDaemons/com.hoobs.core.plist
-rw-r--r--@ 1 petebrunet wheel 859 Apr 23 12:06 /Library/LaunchDaemons/com.hoobs.core.plist

**Version**
HOOBS 3.1.2.7
HomeKit 2.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina 10.15.4

**List your plugins**
homebridge-hubitat-tonesto7

Note: I do not yet have a Hubitat hub

**Post your config**
```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY245E",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "78633",
        "latitude": "30.710390",
        "longitude": "-97.707740"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "48:0C:43:09:56:CE"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Hubitat",
            "plugin_map": {
                "plugin_name": "homebridge-hubitat-tonesto7"
            }
        }
    ]
}
```

**Post your log**
```
[4/23/2020, 11:45:19 AM] HOOBS listening on port 8080.
[Homebridge] [4/23/2020, 11:45:19 AM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [4/23/2020, 11:45:20 AM] Loaded plugin "homebridge-hubitat-tonesto7".
[Homebridge] Homebridge Version: 2.4
[Homebridge] [4/23/2020, 11:45:20 AM] Registering platform "homebridge-hubitat.Hubitat"
[Homebridge] [4/23/2020, 11:45:20 AM] Loading 1 platforms...
[Homebridge] [4/23/2020, 11:45:20 AM] [Hubitat] Initializing Hubitat platform...
[Homebridge] [4/23/2020, 11:45:20 AM] [Hubitat] Fetching Hubitat devices.
[Homebridge] [4/23/2020, 11:45:20 AM] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Object.init (/Users/petebrunet/.hoobs/node_modules/homebridge-hubitat-tonesto7/lib/he_st_api.js:108:26)
    at HE_ST_Platform.accessories (/Users/petebrunet/.hoobs/node_modules/homebridge-hubitat-tonesto7/index.js:194:19)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:373:22)
    at Server._loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:302:18)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:93:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[Homebridge] [4/23/2020, 11:45:20 AM] Got SIGTERM, shutting down Homebridge...
[Homebridge] [4/23/2020, 11:59:36 AM] Loaded config.json with 0 accessories and 1 platforms.
[Homebridge] [4/23/2020, 11:59:37 AM] Loaded plugin "homebridge-hubitat-tonesto7".
[Homebridge] Homebridge Version: 2.4
[Homebridge] [4/23/2020, 11:59:37 AM] Registering platform "homebridge-hubitat.Hubitat"
[Homebridge] [4/23/2020, 11:59:37 AM] Loading 1 platforms...
[Homebridge] [4/23/2020, 11:59:37 AM] [Hubitat] Initializing Hubitat platform...
[Homebridge] [4/23/2020, 11:59:37 AM] [Hubitat] Fetching Hubitat devices.
[Homebridge] [4/23/2020, 11:59:37 AM] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Object.init (/Users/petebrunet/.hoobs/node_modules/homebridge-hubitat-tonesto7/lib/he_st_api.js:108:26)
    at HE_ST_Platform.accessories (/Users/petebrunet/.hoobs/node_modules/homebridge-hubitat-tonesto7/index.js:194:19)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:373:22)
    at Server._loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:302:18)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:93:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[Homebridge] [4/23/2020, 11:59:37 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by mkellsy** [comment]
You .plist file needs to be owned by the root user
```
chown root:wheel /Library/LaunchDaemons/com.hoobs.core.plist
```

You also need to define the "url" variable in your Hubatat config.

**Comment by ptbtx** [comment]
Thanks.  chown worked.  Will try fixing the url variable next week when my Hubitat Elevation arrives.
