### ISSUE TITLE
Error loading plug-in and crash HOOBS

### ISSUE THREAD

**Issue by quizatsaderac** [hoobs-org/HOOBS#579]
**Description**

After updating the HOOBS system in 3.1.27, the system stops on a plug-in error TYDOM. Before the update (3.1.1) all worked fine. 
I contacted the plug-in administrator and he think that it is related to release breaking de hap-nodejs (0.6.3  broken and 0.6.4 ok)

**Version**
version : 3.1.27

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
3.1.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X] Custom Install

**If this is a custom install, what's your operating system?**
BCM2835 - Pi 2 Model B

**List your plugins**
Thekeys
tydom
Harmony
tuya-web
platform wemo

**Post your config**

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYP105",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-light",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "40270"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "54:FC:08:2F:93:E7"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "TheKeys",
            "plugin_map": {
                "plugin_name": "homebridge-thekeys",
                "index": 0
            },
            "name": "The Keys",
            "locker_name": "maison",
            "identifier": "xxxxx",
            "code": "xxxxxxxxxxxxxxxx",
            "ip": "192.168.1.XX"
        }
    ],
    "platforms": [
        {
            "platform": "Tydom",
            "plugin_map": {
                "plugin_name": "homebridge-tydom"
            },
            "hostname": "mediation.tydom.com",
            "username": "xxxxxxxxxx",
            "password": "xxxxxxxxxx"
        },
        {
            "platform": "BelkinWeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            }
        },
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "salon",
            "hubIP": "192.168.1.XX",
            "hubName": "salon",
            "publishAllTVAsExternalAccessory": "false",
            "TVAccessory": "false",
            "switchAccessories": "true",
            "publishGeneralMuteSwitch": "true",
            "publishGeneralVolumeSlider": "false",
            "publishSwitchActivitiesAsIndividualAccessories": "true",
            "publishDevicesAsIndividualAccessories": "false",
            "publishSequencesAsIndividualAccessories": "false",
            "publishHomeControlsAsIndividualAccessories": "false"
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxxxxxxxx",
                "password": "xxxxxxxx",
                "countryCode": "+33",
                "platform": "tuya",
                "pollingInterval": 10
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        }
    ]
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
[5/1/2020, 11:15:30] HOOBS listening on port 8080.
[Homebridge] [5/1/2020, 11:15:33] Loaded config.json with 1 accessories and 4 platforms.
[Homebridge] [5/1/2020, 11:15:36] Loaded plugin "homebridge-harmony".
[Homebridge] [5/1/2020, 11:15:36] Registering platform "homebridge-harmony.HarmonyHubWebSocket"
[Homebridge] [5/1/2020, 11:15:37] Loaded plugin "homebridge-platform-wemo".
[Homebridge] [5/1/2020, 11:15:37] Registering platform "homebridge-platform-wemo.BelkinWeMo"
[Homebridge] [5/1/2020, 11:15:38] Loaded plugin "homebridge-thekeys".
[Homebridge] [5/1/2020, 11:15:38] Registering accessory "homebridge-thekeys.TheKeys"
[Homebridge] [5/1/2020, 11:15:38] Loaded plugin "homebridge-tuya-web".
[Homebridge] [5/1/2020, 11:15:38] Registering platform "homebridge-tuya-web.TuyaWebPlatform"
[Homebridge] [5/1/2020, 11:15:38] Error loading plugin "homebridge-tydom".
[Homebridge] [5/1/2020, 11:15:39] TypeError: Cannot read property 'SECURITY_SYSTEM' of undefined
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-tydom/src/utils/tydom.ts:117:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-tydom/src/controller.ts:22:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-tydom/src/platform.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-tydom/src/index.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
[Homebridge] [5/1/2020, 11:15:39] Loading 4 platforms...
[Homebridge] [5/1/2020, 11:15:39] Error: The requested platform "Tydom" was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/api.js:132:19)
    at Server._loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:289:47)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:93:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
[Homebridge] [5/1/2020, 11:15:39] Got SIGTERM, shutting down Homebridge...
```

**Additional context**

I usually proceeded to the regular update of hoobs, but the problem was the same. I decided to reinstall hoobs with the first downloaded version and still the problem.

**Comment by BobbySlope** [comment]
We will release an hoobs update today that integrates the new hap version

**Comment by BobbySlope** [comment]
# Update to HOOBS 3.2.0 Available

### What's New in 3.2.0
* Bug Fixes
* Removed NGINX
* Faster Load Times
* Updated HAP Core
* Cleaned Bridge Code
* Support For Short Form UUIDS
* Support Plugins for Latest HB Version
* Support Identifier less Plugin Registration
* Allow Non HOOBS Scoped Certified Plugins
