### ISSUE TITLE
Homebridge not running 3.2.1

### ISSUE THREAD

**Issue by DavidWhicker** [hoobs-org/HOOBS#583]
**Description**
Homebridge service refused to run

**Version**
3.2.1 ( problem existed on 3.2 )

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.2 and tested from 3.1.27

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Rasberry PI 4

**List your plugins**
Yalesyncalarm

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "xx",
        "polling_seconds": 1
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": "xx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xx",
        "username": "xx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "YaleSyncAlarm",
            "name": "Burglar Alarm",
            "username": "xx",
            "password": "xx",
            "refreshInterval": 0,
            "plugin_map": {
                "plugin_name": "homebridge-yalesyncalarm"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
02/05/2020, 08:05:12 [Burglar Alarm] Initializing YaleSyncAlarm platform...
02/05/2020, 08:05:12 Error: Cannot update reachability on non-bridged accessory!
    at Accessory._this.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:259:23)
    at Platform.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/platform.js:88:37)
    at YaleSyncPlatform.configurePanel (/home/hoobs/.hoobs/node_modules/homebridge-yalesyncalarm/dist/YaleSyncPlatform.js:382:23)
    at YaleSyncPlatform.configureAccessory (/home/hoobs/.hoobs/node_modules/homebridge-yalesyncalarm/dist/YaleSyncPlatform.js:235:22)
    at Server.configCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:332:26)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:95:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

**Additional context**

**Comment by mkellsy** [comment]
Reachability is an old feature that is not really used much. It was changed in HB
I am making it fail gracefully if an older plugin tries to set this.

**Comment by mkellsy** [comment]
3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by DavidWhicker** [comment]
Thank you. I’ll look out for it
