### ISSUE TITLE
Mise à jour de HOOBS v3.2.1

### ISSUE THREAD

**Issue by Stewart06** [hoobs-org/HOOBS#589]
Bonjour,

Je vous contact car depuis la mise à jour de HOOBS en version 3.2.1 plus aucun service ne démarre.

J'ai également fait la mise à jour de RING et le plugin a disparu.

Auriez-vous une solution ?

**Comment by Stewart06** [comment]
02/05/2020 à 16:04:46 HOOBS listening on port 8090.
02/05/2020 à 16:04:49 Loaded plugin "homebridge-apple-tv-remote".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-camera-ffmpeg".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-delay-switch".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-dummy".
02/05/2020 à 16:04:51 Loaded plugin "homebridge-dummy-thermostat".
02/05/2020 à 16:04:52 Loaded plugin "homebridge-ewelink-max".
02/05/2020 à 16:04:52 homebridge API version: 2.5
02/05/2020 à 16:04:52 Loaded plugin "homebridge-rpitemp".
02/05/2020 à 16:04:52 Loaded plugin "homebridge-samsung-tizen".
02/05/2020 à 16:04:52 Loaded plugin "homebridge-wol".
02/05/2020 à 16:04:52 [SamsungTizen] Initializing SamsungTizen platform...
02/05/2020 à 16:04:52 [Apple TV Platform] Initializing AppleTvPlatform platform...
02/05/2020 à 16:04:52 [eWeLink] Initializing eWeLink platform...
02/05/2020 à 16:04:52 [eWeLink] Intialising eWeLink
02/05/2020 à 16:04:52 [eWeLink] Found 0 group(s)
02/05/2020 à 16:04:52 Error: The requested platform "Ring" was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/api.js:128:23)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:271:35)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:87:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
02/05/2020 à 16:04:52 Got SIGTERM, shutting down Bridge...
02/05/2020 à 16:04:52 [Apple TV Platform] Shutting down Apple TV clients...

**Comment by mkellsy** [comment]
We have a fix for this coming in version 3.2.2

**Comment by mkellsy** [comment]
3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by Stewart06** [comment]
Je viens de mettre la version 3.2.2 et toujours le même problème le serveur ne démarre pas !

I just put version 3.2.2. And still the same problem, the server doesn't start!



Le 2 mai 2020 à 21:10, Michael Kellsy <notifications@github.com<mailto:notifications@github.com>> a écrit :



3.2.2 is published to NPM. It may take a few hours to show up.

**Comment by mkellsy** [comment]
Duplicate
