### ISSUE TITLE
Homebridge stopped after update

### ISSUE THREAD

**Issue by fabr85** [hoobs-org/HOOBS#594]
**Description**
Homebridge stopped after update

Log:
[5/2/2020, 6:00:47 PM] ---
[5/2/2020, 6:00:47 PM] Loading 3 platforms...
[5/2/2020, 6:00:47 PM] [Config] Initializing config platform...
[5/2/2020, 6:00:47 PM] [Config] Running in Standalone Mode.
[5/2/2020, 6:00:47 PM] [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
[5/2/2020, 6:00:47 PM] [MoodoPlatform] Initializing MoodoPlatform platform...
[5/2/2020, 6:00:47 PM] Loading 1 accessories...
[5/2/2020, 6:00:47 PM] Error loading accessory requested in your config.json at position 1
[5/2/2020, 6:00:47 PM] Error: The requested accessory 'HomebridgeMoodo' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:197:15)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge/src/server.ts:346:37)
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:329:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:155:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
homebridge.service: Succeeded.
[5/2/2020, 6:00:49 PM] [Config] Homebridge Config UI X v4.17.1 is listening on :: port 8080
   hoobs : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x
pam_unix(sudo:session): session opened for user root by (uid=0)
   hoobs : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 3204
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
   hoobs : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x
pam_unix(sudo:session): session opened for user root by (uid=0)

**Version**
3.2.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

macOS Catalina.

**List your plugins**
Moodo
Dyson

{
    "bridge": {
        "name": "HOOBS",
        "username": "DELETED",
        "port": 51826,
        "pin": "DELETED"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [
        {
            "accessory": "HomebridgeMoodo",
            "device_key": 3669,
            "name": "Foodoo",
            "token": "DELETED"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "sudo": true,
            "standalone": true,
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        },
        {
            "platform": "DysonPureCoolPlatform",
            "username": "DELETED",
            "password": "DELETED",
            "countryCode": "DE",
            "devices": [
                {
                    "ipAddress": "192.168.178.133",
                    "serialNumber": "DELETED",
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false
                }
            ]
        },
        {
            "token": "DELETED",
            "devices": [
                {
                    "id": 3669,
                    "name": "Foodoo",
                    "type": "fan",
                    "showCapsules": true,
                    "useCapsuleNames": true,
                    "showTimer": true,
                    "isSingleAccessoryModeEnabled": true
                }
            ],
            "platform": "MoodoPlatform"
        }
    ]
}

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
These logs are form Homebridge not HOOBS.
If this is a HOOBS 2.1.1 box, please upgrade.

**Comment by fabr85** [comment]
First: closing topics in this way is neither polite nor helpful
second: it is a Hoobs ordered in August 2019. its software is up to date. I was told I don't need a hardware upgrade to Hoobs 3 because it is the same system.

what now?

**Comment by askovi** [comment]
Hi Fabian. Please install the plugin homebridge-to-hoobs in order to bring your system on HOOBS 3. Then you can easily update from the new dashboard after that.

**Comment by mkellsy** [comment]
Sorry for closing this. Didn't mean to. The buttons are next to each other. Happens from time to time.
