### ISSUE TITLE
3.2.2 version crashes with homebridge-magichome-platform plugin

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/HOOBS#609]
**Description**
See log pasted below

**Expected behavoir**
Worked 100% fine prior to 3.1.22

**Plugin name**
Please let us know what the plugin name is. We need to be able to find it on NPM.

homebridge-magichome-platform

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.
3.2.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

RPI-4

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISJGL46LI",
        "polling_seconds": 2,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "34994"
    },
    "bridge": {
        "name": "HOOBS",
        "username": "xx",
        "port": 51826,
        "pin": "xx"
    },
    "description": "This file is used for plugin configuration.",
    "ports": {},
    "plugins": [
        "homebridge-tuya-web",
        "homebridge-camera-ffmpeg",
        "wink",
        "homebridge-magichome-platform"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "xx",
            "client_secret": "xx",
            "access_token": "xx",
            "refresh_token": "xx",
            "direct_access": true,
            "temperature_unit": "F",
            "switch_ids": [
                657654
            ],
            "username": "xx",
            "password": "xx",
            "plugin_map": {
                "plugin_name": "wink"
            }
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xx",
                "password": "xx",
                "countryCode": "01",
                "platform": "tuya",
                "pollingInterval": 60
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Logitech Web-cam",
                    "motion": true,
                    "manufacturer": "Logitech",
                    "model": "USB Webcam",
                    "serialNumber": "1234567890",
                    "videoConfig": {
                        "source": "-f v4l2 -i /dev/video0",
                        "stillImageSource": "-f video4linux2 -input_format mjpeg -video_size 640x360 -ss 0.9 -i /dev/video0 -frames:v 1",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 300,
                        "vcodec": "h264_omx",
                        "packetSize": 188,
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Wyze-Cam-LR",
                    "motion": true,
                    "manufacturer": "Wyze-Cam",
                    "model": "V2",
                    "serialNumber": "A4DA223286C3",
                    "firmwareRevision": "4.28.4.40",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://xxx:Homebridge@10.0.0.7/live",
                        "stillImageSource": "-rtsp_flags prefer_tcp -i rtsp://xxx:Homebridge@10.0.0.7/live",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 360,
                        "maxFPS": 30,
                        "maxBitrate": 299,
                        "vcodec": "h264_omx",
                        "audio": true,
                        "packetSize": 752,
                        "hflip": false,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": false
                    }
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            }
        },
        {
            "platform": "MagicHome-Platform",
            "lights": [
                {
                    "name": "Living Room LED Strip",
                    "ip": "10.0.0.10",
                    "setup": "RGBW",
                    "purewhite": false
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-magichome-platform"
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```5/3/2020, 7:18:19 PM Error: spawn /home/hoobs/.hoobs/node_modules/homebridge-magichome-platform/src/flux_led.py EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)POST LOG HERE
```

**Additional context**

**Comment by themick4u** [comment]
Moved off of Wink to Hubitat and issue cleared right up (after removing the Wink3 plugin)!

**Comment by dancio10** [comment]
this plugin does not work for me..not from any error but if i turn on / off light from homekit nothing happens
