### ISSUE TITLE
Upgrade to last version failed twice

### ISSUE THREAD

**Issue by manuelguerreiro** [hoobs-org/HOOBS#611]
**Description**
The update to last version is failing. I get stucked on a yelow screen. I rebuild the image and restore a backup and destroyed again on the upgrade

**Version**
3.2.1 to 3.2.3?

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
3.2.1 from the we bimage

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspbery 4b with your image

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
ffmpg, fibaro, netatmo

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by manuelguerreiro** [comment]
Here are the logs
Started HOOBS.
HOOBS listening on port 8080.
Loaded plugin "homebridge-camera-ffmpeg".
Loaded plugin "homebridge-eveatmo".
Loaded plugin "homebridge-fibaro-hc2".
Loaded plugin "homebridge-harmony".
Loaded plugin "homebridge-rpi".
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1047
.getCharacteristic(Characteristic_1.Characteristic.Identify)
^
TypeError: Cannot read property 'getCharacteristic' of undefined
at Accessory._this._sideloadServices (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1047:17)
at Function.Accessory.deserialize (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1387:19)
at Function.deserialize (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/platform.js:121:49)
at Server.loadCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:232:51)
at new Server (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:60:47)
at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:47:20)
at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
at Module._compile (internal/modules/cjs/loader.js:1156:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
at Module.load (internal/modules/cjs/loader.js:1000:32)
at Function.Module._load (internal/modules/cjs/loader.js:899:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
at internal/main/run_main_module.js:18:47

**Comment by askovi** [comment]
This is fixed in 3.2.6
