### ISSUE TITLE
network disconnecting and reconnecting on every "Refresh Interval"

### ISSUE THREAD

**Issue by gmum4d** [hoobs-org/HOOBS#618]
**Description**
I installed Pi-hole and at first I thought all was ok, but I noticed when using node red (on the same pi) that it keeps loosing a connection to the server. So I checked my hoobs logs and it seems to be in a error loop, disconnecting and re connecting every few seconds with a TCP error. This seems to coincide with the "Refresh Interval" setting.

**Version**
Version 3.2.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.

Yes.

**Pervious version**
If you upgraded, please let us know your previous version.

Previous 3.2.1

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

No

**What device are you using?**
Please let us know the device you are running HOOBS on.

HOOBS SD Card

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Alexa - https://plugins.hoobs.org/plugin/homebridge-alexa
Http Switch - https://plugins.hoobs.org/plugin/homebridge-http-switch
Marantz Volume - https://plugins.hoobs.org/plugin/homebridge-marantz-volume
mqttthing - https://plugins.hoobs.org/plugin/homebridge-mqttthing
Samsung Tizen - https://plugins.hoobs.org/plugin/homebridge-samsung-tizen
Shelly - https://plugins.hoobs.org/plugin/homebridge-shelly
Smartthings V2 - https://plugins.hoobs.org/plugin/homebridge-smartthings-v2
Tado Platform - https://plugins.hoobs.org/plugin/homebridge-tado-platform

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYG89F",
        "polling_seconds": 60,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "GB",
        "postal_code": •••••••",
        "latitude": "51.5705131",
        "longitude": "0.5602555"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "•••••••"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "marantz-volume",
            "name": "Marantz Volume",
            "host": "192.168.0.5",
            "defaultVolume": 15,
            "maxVolume": 100,
            "plugin_map": {
                "plugin_name": "homebridge-marantz-volume",
                "index": 0
            }
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "TVAUDIO",
            "switchType": "stateless",
            "timeout": 100,
            "onUrl": "http://192.168.0.5/goform/formiPhoneAppDirect.xml?SITV",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "VINYL",
            "switchType": "stateless",
            "timeout": 100,
            "onUrl": "http://192.168.0.5/goform/formiPhoneAppDirect.xml?SICD",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "IRADIO",
            "switchType": "stateless",
            "timeout": 100,
            "onUrl": "http://192.168.0.5/goform/formiPhoneAppDirect.xml?SIIRADIO",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "Alexa",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "name": "Alexa",
            "username": "•••••••",
            "password": "•••••••",
            "pin": "032-45-154",
            "routines": true,
            "refresh": 3600
        },
        {
            "platform": "SamsungTizen",
            "switches": [
                {
                    "name": "Change input",
                    "command": "KEY_HDMI"
                },
                {
                    "name": "mute",
                    "mute": "true"
                }
            ],
            "inputs": [
                {
                    "name": "01 LIVE TV",
                    "type": "command",
                    "power": true,
                    "value": [
                        "KEY_TV",
                        "KEY_ENTER",
                        "KEY_GUIDE"
                    ]
                },
                {
                    "name": "02 NETFLIX",
                    "power": true,
                    "type": "app",
                    "value": "11101200001",
                    "refresh": 5000
                },
                {
                    "name": "03 PLEX",
                    "power": true,
                    "type": "app",
                    "value": "3201512006963"
                },
                {
                    "name": "07 AMAZON PRIME",
                    "power": true,
                    "type": "app",
                    "value": "3201512006785"
                },
                {
                    "name": "05 BBC iPLAYER",
                    "power": true,
                    "type": "app",
                    "value": "3201601007670"
                },
                {
                    "name": "06 ITV HUB",
                    "power": true,
                    "type": "app",
                    "value": "121299000089"
                },
                {
                    "name": "08 NOW TV",
                    "power": true,
                    "type": "app",
                    "value": "3201603008746"
                },
                {
                    "name": "09 All 4",
                    "power": true,
                    "type": "app",
                    "value": "111299002148"
                },
                {
                    "name": "10 MY5",
                    "power": true,
                    "type": "app",
                    "value": "121299000612"
                },
                {
                    "name": "11 YOUTUBE",
                    "power": true,
                    "type": "app",
                    "value": "111299001912"
                },
                {
                    "name": "04 APPLE TV",
                    "type": "command",
                    "power": true,
                    "value": [
                        "KEY_HDMI1"
                    ]
                },
                {
                    "name": "BBC HD",
                    "power": true,
                    "type": "command",
                    "value": [
                        "KEY_TV",
                        "KEY_ENTER"
                    ]
                }
            ],
            "devices": [
                {
                    "name": "SAMSUNG-TV",
                    "ip": "192.168.0.15",
                    "mac": "54:bd:79:01:9a:e3"
                }
            ],
            "name": "SamsungTizen",
            "app_list": true
        },
        {
            "platform": "TadoPlatform",
            "name": "Tado",
            "username": "•••••••",
            "password": "•••••••",
            "homeID": 282298,
            "unit": "celsius",
            "polling": 10,
            "exclude": [
                "RU1758072320-1"
            ],
            "reConfig": false,
            "occupancy": true,
            "anyone": true,
            "weather": true,
            "openWindow": true,
            "solarIntensity": false,
            "centralSwitch": false,
            "externalSensor": false,
            "deviceOptions": {
                "RU1758072320": {
                    "active": true,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "roomName": "Heating"
                },
                "RU1758072320-1": {
                    "active": false,
                    "heatValue": 5,
                    "coolValue": 5,
                    "maxDelay": 10,
                    "overrideMode": "manual",
                    "ID": 1,
                    "zoneName": "Heating",
                    "zoneType": "HEATING",
                    "deviceType": "RU",
                    "serial": "RU1758072320",
                    "type": "thermostat"
                }
            },
            "plugin_map": {
                "plugin_name": "homebridge-tado-platform"
            }
        },
        {
            "platform": "SamsungTizen",
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            }
        },
        {
            "platform": "Shelly",
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            },
            "name": "Shelly",
            "admin": {
                "enabled": false,
                "port": 8181
            }
        },
        {
            "platform": "SmartThings-v2",
            "plugin_map": {
                "plugin_name": "homebridge-smartthings-v2"
            },
            "name": "SmartThings-v2",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "disableErrorReporting": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "Good"
                }
            },
            "access_token": "•••••••",
            "app_id": "•••••••",
            "app_url": "•••••••"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
07/05/2020, 06:24:05 HOOBS listening on port 8080.
07/05/2020, 06:24:23 Loaded plugin "homebridge-alexa".
07/05/2020, 06:24:23 Loaded plugin "homebridge-http-switch".
07/05/2020, 06:24:23 Loaded plugin "homebridge-marantz-volume".
07/05/2020, 06:24:26 Loaded plugin "homebridge-mqttthing".
07/05/2020, 06:24:26 Loaded plugin "homebridge-samsung-tizen".
07/05/2020, 06:24:26 Loaded plugin "homebridge-shelly".
07/05/2020, 06:24:26 Loaded plugin "homebridge-tado-platform".
07/05/2020, 06:24:27 [Alexa] homebridge-alexa v0.4.72, node v12.13.1, homebridge v3.2.3
07/05/2020, 06:24:27 [Alexa] Initializing platform accessory "Alexa"...
07/05/2020, 06:24:27 [Tado] [INFO] **************************************************************
07/05/2020, 06:24:27 [Tado] [INFO] TadoPlatform v5.1.6 by SeydX
07/05/2020, 06:24:27 [Tado] [INFO] GitHub: https://github.com/SeydX/homebridge-tado-platform
07/05/2020, 06:24:27 [Tado] [INFO] Email: seyd55@outlook.de
07/05/2020, 06:24:27 [Tado] [INFO] **************************************************************
07/05/2020, 06:24:27 [Tado] [INFO] start success...
07/05/2020, 06:24:27 [TVAUDIO] Switch successfully configured...
07/05/2020, 06:24:27 [VINYL] Switch successfully configured...
07/05/2020, 06:24:27 [IRADIO] Switch successfully configured...
07/05/2020, 06:24:27 [Shelly] 7 accessories loaded from cache
07/05/2020, 06:24:27 Bridge is running on port 51826.
07/05/2020, 06:24:27 SAMSUNG-TV is running on port 42013.
07/05/2020, 06:24:30 [Tado] [INFO] Configuring accessory Gary
07/05/2020, 06:24:30 [Tado] [INFO] Configuring accessory Lynn
07/05/2020, 06:24:30 [Tado] [INFO] Configuring accessory Anyone
07/05/2020, 06:24:30 [Tado] [INFO] Configuring accessory Weather
07/05/2020, 06:24:36 [SAMSUNG-TV] connect ECONNREFUSED 192.168.0.15:8002
07/05/2020, 06:24:47 [Alexa] alexaDiscovery - returned 31 devices
07/05/2020, 06:24:47 Error: from server 192.168.0.54:39869 Error: connect ECONNREFUSED 192.168.0.54:39869
07/05/2020, 06:24:47 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
07/05/2020, 06:24:47 errno: 'ECONNREFUSED',
07/05/2020, 06:24:47 code: 'ECONNREFUSED',
07/05/2020, 06:24:47 syscall: 'connect',
07/05/2020, 06:24:47 address: '192.168.0.54',
07/05/2020, 06:24:47 port: 39869
07/05/2020, 06:24:47 }
```

**Additional context**
This problem occurred after installing Pihole on the same Pi.  I have tried uninstalling PiHole But the problem persists. I have since re installed Pihole to see if a re-install fixed it, but it didn't.  The Error at the bottom of the log is the one that happens on every "Refresh interval".  The IP address in the error is the IP of the Pi.  If I log onto Node Red, this also disconnects and reconnects at the same time.

Please help
Many thanks

**Comment by mkellsy** [comment]
We have a fix for this in version 3.2.4

**Comment by gmum4d** [comment]
Still occurring in 3.2.4. Every hour!

`
15/05/2020, 12:25:36 Error: from server 192.168.0.54:40565 Error: connect ECONNREFUSED 192.168.0.54:40565
15/05/2020, 12:25:36 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
15/05/2020, 12:25:36 errno: 'ECONNREFUSED',
15/05/2020, 12:25:36 code: 'ECONNREFUSED',
15/05/2020, 12:25:36 syscall: 'connect',
15/05/2020, 12:25:36 address: '192.168.0.54',
15/05/2020, 12:25:36 port: 40565
15/05/2020, 12:25:36 }

...

15/05/2020, 13:25:36 Error: from server 192.168.0.54:41855 Error: connect ECONNREFUSED 192.168.0.54:41855
15/05/2020, 13:25:36 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
15/05/2020, 13:25:36 errno: 'ECONNREFUSED',
15/05/2020, 13:25:36 code: 'ECONNREFUSED',
15/05/2020, 13:25:36 syscall: 'connect',
15/05/2020, 13:25:36 address: '192.168.0.54',
15/05/2020, 13:25:36 port: 41855
15/05/2020, 13:25:36 }

...

15/05/2020, 14:25:36 Error: from server 192.168.0.54:42657 Error: connect ECONNREFUSED 192.168.0.54:42657
15/05/2020, 14:25:36 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
15/05/2020, 14:25:36 errno: 'ECONNREFUSED',
15/05/2020, 14:25:36 code: 'ECONNREFUSED',
15/05/2020, 14:25:36 syscall: 'connect',
15/05/2020, 14:25:36 address: '192.168.0.54',
15/05/2020, 14:25:36 port: 42657
15/05/2020, 14:25:36 }`

**Comment by mkellsy** [comment]
This is due to a plugin. Some device on your network becomes unreachable. The plugin used is throwing an exception when this is not reachable, thus crashing the bridge. This plugin should handle this more gracefully.

I don't know what it causing this. What device is at 192.168.0.54?
