### ISSUE TITLE
UI wont work when not connected via SSH

### ISSUE THREAD

**Issue by asinger720** [hoobs-org/HOOBS#626]
**Description**
I can't use the web UI unless i connect via SSH and run wget -q -O - http://bit.ly/get-hoobs | sudo bash - in the Terminal

**Version**
3.2.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.2.3

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspbian

**List your plugins**
Samsung Tizen (4.3.2)
HOOBS Ring (8.1.0)

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYCELC",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "11050"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "DC:60:69:87:19:5C"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Living Room TV",
                    "ip": "192.168.1.162",
                    "mac": "38:68:A4:9E:A5:92",
                    "refresh": 3000
                },
                {
                    "name": "Basement TV",
                    "ip": "192.168.1.253",
                    "mac": "8C:79:F5:EF:1F:14",
                    "refresh": 3000
                }
            ],
            "app_list": true
        },
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODk0NzAzNDYsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MjEzNTMzMjMsInJuZCI6Imp3ZVVsUm1Od3FVakJ3IiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.sA7ewvp06Rlg1fdEoiEUoKYZWfz9GuHRoRx6ItiaLgRtErTyRwYXve_iJ1lMpWJ-n7UM7fbvHVNsgCXRSeBU7A",
            "hideUnsupportedServices": true,
            "locationIds": []
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
root@raspberrypi:/root/.hoobs/etc# sudo hoobs service log
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.```

**Additional context**
Add any other context about the problem here.

**Comment by mkellsy** [comment]
Run this
```
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
sudo reboot
```

**Comment by asinger720** [comment]
@mkellsy didn't work.  I get the following error

Failed to set capabilities on file `/usr/local/bin/node' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

**Comment by mkellsy** [comment]
Try /use/bin/node
