### ISSUE TITLE
Hoobs update failed

### ISSUE THREAD

**Issue by nejcklinc** [hoobs-org/HOOBS#627]
**Description**
After trying to update to latest version I got error:
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs/lib'
    at Object.realpathSync (fs.js:1529:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/lib/server.js:70:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:223:5)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)

**Version**
3.1.27

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Previous version**
Upgrade failled.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi 4 Model B Rev 1.1

**List your plugins**
Shelly Plugin
Weather Plus Plugin

**POST LOG HERE:**
[5/15/2020, 2:55:30 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[5/15/2020, 2:55:33 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
[5/15/2020, 2:55:33 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 8)
[5/15/2020, 2:55:33 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 11)
[5/15/2020, 2:55:33 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 14)
[5/15/2020, 2:55:34 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 17)
[5/15/2020, 2:55:34 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 20)
[5/15/2020, 2:55:34 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 23)
[5/15/2020, 2:55:34 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 26)
[5/15/2020, 2:55:36 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 29)
[5/15/2020, 2:55:36 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 32)
[5/15/2020, 2:55:43 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 35)
[5/15/2020, 2:55:44 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 38)
[5/15/2020, 2:55:44 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 41)
[5/15/2020, 2:55:44 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 44)
[5/15/2020, 2:55:44 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 47)
[5/15/2020, 2:55:45 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 50)
[5/15/2020, 2:55:45 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 53)
[5/15/2020, 2:55:45 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 56)
[5/15/2020, 2:55:46 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 59)
[5/15/2020, 2:55:47 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 62)
[5/15/2020, 2:55:54 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 65)
[5/15/2020, 2:55:54 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 68)
[5/15/2020, 2:55:54 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 71)
[5/15/2020, 2:55:55 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 74)
[5/15/2020, 2:55:55 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 77)
[5/15/2020, 2:55:55 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 80)
[5/15/2020, 2:55:55 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 83)
[5/15/2020, 2:55:56 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 86)
[5/15/2020, 2:56:14 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 88)
[5/15/2020, 2:56:17 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 90)
[5/15/2020, 2:57:12 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 92)
[5/15/2020, 2:57:41 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 95)
[5/15/2020, 2:57:41 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 98)
[5/15/2020, 2:57:41 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 101)
[5/15/2020, 2:57:41 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 104)
[5/15/2020, 2:57:41 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 107)
[5/15/2020, 2:57:41 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 110)
[5/15/2020, 2:57:41 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 113)
[5/15/2020, 2:57:42 AM] Unhandled Rejection "Error: Request failed with status code 503".
(node:1039) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 116)
[Homebridge] [5/15/2020, 2:59:22 AM] Got SIGINT, shutting down Homebridge...
   hoobs : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/npm install -g --unsafe-perm @hoobs/hoobs
pam_unix(sudo:session): session opened for user root by (uid=0)
/usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
+ @hoobs/hoobs@3.2.4
added 5 packages from 3 contributors, removed 22 packages and updated 17 packages in 17.31s
pam_unix(sudo:session): session closed for user root
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs/lib'
    at Object.realpathSync (fs.js:1529:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/lib/server.js:70:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:223:5)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs/lib'
    at Object.realpathSync (fs.js:1529:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/lib/server.js:70:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:223:5)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs/lib'
    at Object.realpathSync (fs.js:1529:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/lib/server.js:70:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:223:5)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs/lib'
    at Object.realpathSync (fs.js:1529:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/lib/server.js:70:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:223:5)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs/lib'
    at Object.realpathSync (fs.js:1529:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/lib/server.js:70:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:223:5)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)

**Comment by mkellsy** [comment]
See if this works
```
sudo npm install -g--unsafe-perm @hoobs/hoobs
```

**Comment by nejcklinc** [comment]
Working now - thanks
