### ISSUE TITLE
HOOBs not starting after update

### ISSUE THREAD

**Issue by therapcat** [hoobs-org/HOOBS#631]
I have no idea why I updated, but now it won't run at all. 

Is there any way to downgrade the homebridge part? 

OS | Raspbian GNU/Linux Buster (10)
-- | --
hostname: hoobs

Nodejs v12.16.3
NPM v6.14.4
hoobs
/var/lib/homebridge
/var/lib/homebridge/config.json

Plugins:

   "platform": "PoolControllerPlatform",
            "name": "Pool Controller",
            "ip_address": "http://localhost:3000",
            "secure": "false"
"platform": "DysonPlatform",
            "name": "DysonPlatform",
"platform": "HarmonyHubWebSocket",
            "cleanCache": "true",
platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "tempUnits": "f",
            "sudo": true,
            "standalone": true,
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"

ERROR OUTPUT BELOW:
pam_unix(sudo:session): session closed for user root
[5/18/2020, 9:16:41 PM] Loaded config.json with 0 accessories and 4 platforms.
[5/18/2020, 9:16:41 PM] ---
[5/18/2020, 9:16:43 PM] Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/nodejs-poolcontroller'
    at Object.statSync (fs.js:933:3)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:291:38
    at Array.filter (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:291:12
    at Set.forEach (<anonymous>)
    at PluginManager.loadInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:277:22)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:116:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:149:24)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge.service: Succeeded.
[5/18/2020, 9:16:45 PM] [Config] Homebridge Config UI X v4.19.0 is listening on :: port 8080

**Comment by askovi** [comment]
Please install the plugin homebridge-to-hoobs to upgrade to HOOBS 3 then you'll be able to update from the dashboard to HOOBS 3.2.4

**Comment by therapcat** [comment]
So I did this but now the jspoolController does not work. Is there not anyway to downgrade to what I had before? 1.0?

**Comment by askovi** [comment]
If you're still experiencing issues on 3.2.6, please open a new issue and follow the bug report template.
