### ISSUE TITLE
Hoobs update failed

### ISSUE THREAD

**Issue by raphi089** [hoobs-org/HOOBS#632]
**Description**
After trying to update to latest version I got error:
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/@hoobs/hoobs/lib'
    at Object.realpathSync (fs.js:1546:7)
    at Function.get paths [as paths] (/usr/local/lib/node_modules/@hoobs/hoobs/lib/server.js:70:40)
    at /usr/local/lib/node_modules/@hoobs/hoobs/lib/api.js:185:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:311:20)
    at SendStream.error (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:421:12)
    at next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:763:28)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/send/index.js:771:23
    at FSReqCallback.oncomplete (fs.js:166:21)

**Version**
3.1.4

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
3.1.23

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Windows 10 Home 64 Bit

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
homebridge-broadlink-rm

**Post your config**
Sorry, don't know how to do this.

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
Can't access to it because of error.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
A reboot fixes this.
