### ISSUE TITLE
install on a Mac

### ISSUE THREAD

**Issue by omolko** [hoobs-org/HOOBS#653]
Hi 
First install everything goes ok (I use https://github.com/hoobs-org/HOOBS/wiki/2.5.0-macOS-Installation)  but I can't access to http://hoobs.local:8080 (white screen)

MacBook Pro i7 2015 (catalina 10.15.4)
it seems to be an Error: listen EADDRINUSE but I don't know what to do.
thanks for your help 

omolko@hoobs ~ % sudo nano /etc/sudoers
Password:
omolko@hoobs ~ % % sudo nano /etc/sudoers
fg: no current job
omolko@hoobs ~ % sudo nano /etc/sudoers
omolko@hoobs ~ % hoobs
Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 80
}
[HOOBS] Stopping server.
omolko@hoobs ~ % sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
omolko@hoobs ~ %

**Comment by mkellsy** [comment]
Mac requires that you run as root
```
sudo hoobs
```

**Comment by omolko** [comment]
Thanks for replying 
I try it already (seen in another post) but it's the same

**Comment by pateism** [comment]
maybe just a simple typo, you are trying to connect to port 8080 so need HTTPS rather than HTTP


httpS://hoobs.local:8080/
