### ISSUE TITLE
Camera FFMPEG not loading

### ISSUE THREAD

**Issue by tlight93** [hoobs-org/HOOBS#659]
**Description**
Plugin refuses to load

**Plugin name**
Camera-FFMPEG

**Version**
3.2.6
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes
- [ ] No

**Pervious version**
3.2.4

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x ] Custom Install - macOS

**If this is a custom install, what's your operating system?**
macOS Catalina

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYVTGN1J",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "32218"
    },
    "bridge": {
        "name": "HOOBS Bridge",
        "port": 51826,
        "pin": "031-45-113",
        "username": "EB:FA:46:43:8A:DD"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-http-motion-sensor",
        "homebridge-camera-ffmpeg"
    ],
    "accessories": [
        {
            "accessory": "http-motion-sensor",
            "plugin_map": {
                "plugin_name": "homebridge-http-motion-sensor",
                "index": 0
            },
            "name": "Front Porch",
            "port": 10170
        },
        {
            "accessory": "http-motion-sensor",
            "plugin_map": {
                "plugin_name": "homebridge-http-motion-sensor",
                "index": 0
            },
            "name": "Back Door",
            "port": 10171
        },
        {
            "accessory": "http-motion-sensor",
            "plugin_map": {
                "plugin_name": "homebridge-http-motion-sensor",
                "index": 0
            },
            "name": "Driveway",
            "port": 10172
        }
    ],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "cameras": [
                {
                    "name": "Front Porch",
                    "motion": "true",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://10.0.1.170/img/media.sav",
                        "maxStreams": 2,
                        "maxWidth": 960,
                        "maxHeight": 540,
                        "debug": "true",
                        "maxFPS": 30,
                        "videoFilter": "scale=960:540",
                        "packetSize": 188
                    }
                },
                {
                    "name": "Back Door",
                    "motion": "true",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://10.0.1.171/img/media.sav",
                        "maxWidth": 960,
                        "maxHeight": 540,
                        "maxStreams": 2,
                        "debug": "true",
                        "maxFPS": 30,
                        "videoFilter": "scale=960:540",
                        "packetSize": 188
                    }
                },
                {
                    "name": "Driveway",
                    "motion": "true",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://10.0.1.172/img/media.sav",
                        "maxWidth": 960,
                        "maxHeight": 540,
                        "maxStreams": 2,
                        "debug": "true",
                        "maxFPS": 30,
                        "videoFilter": "scale=960:540",
                        "packetSize": 188
                    }
                }
            ]
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
5/25/2020, 2:39:44 PM - HOOBS listening on port 8080.
5/25/2020, 2:39:44 PM - Error loading plugin "homebridge-camera-ffmpeg".
5/25/2020, 2:39:44 PM - Error: No valid exports main found for '/Users/tommy/.hoobs/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tommy/.hoobs/node_modules/googleapis-common/build/src/apirequest.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
5/25/2020, 2:39:44 PM - Loaded plugin "homebridge-http-motion-sensor".
5/25/2020, 2:39:44 PM - The requested platform "Camera-ffmpeg" was not registered by any plugin.
5/25/2020, 2:39:44 PM - Your config.json is requesting the platform "Camera-ffmpeg" which has not been published by any installed plugins.
5/25/2020, 2:39:44 PM - Bridge is running on port 51826.
5/25/2020, 2:39:44 PM - [Front Porch] The device 'Front Porch' can now be reached under http://0.0.0.0:10170
5/25/2020, 2:39:44 PM - [Back Door] The device 'Back Door' can now be reached under http://0.0.0.0:10171
5/25/2020, 2:39:44 PM - [Driveway] The device 'Driveway' can now be reached under http://0.0.0.0:10172
5/25/2020, 2:40:20 PM - Got SIGINT, shutting down Bridge...
5/25/2020, 2:40:23 PM - Error loading plugin "homebridge-camera-ffmpeg".
5/25/2020, 2:40:23 PM - Error: No valid exports main found for '/Users/tommy/.hoobs/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tommy/.hoobs/node_modules/googleapis-common/build/src/apirequest.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
5/25/2020, 2:40:23 PM - Loaded plugin "homebridge-http-motion-sensor".
5/25/2020, 2:40:23 PM - The requested platform "Camera-ffmpeg" was not registered by any plugin.
5/25/2020, 2:40:23 PM - Your config.json is requesting the platform "Camera-ffmpeg" which has not been published by any installed plugins.
5/25/2020, 2:40:23 PM - Bridge is running on port 51826.
5/25/2020, 2:40:23 PM - [Front Porch] The device 'Front Porch' can now be reached under http://0.0.0.0:10170
5/25/2020, 2:40:23 PM - [Back Door] The device 'Back Door' can now be reached under http://0.0.0.0:10171
5/25/2020, 2:40:23 PM - [Driveway] The device 'Driveway' can now be reached under http://0.0.0.0:10172
5/25/2020, 2:40:35 PM - added 1 package from 1 contributor, removed 50 packages and audited 78 packages in 1.039s
5/25/2020, 2:40:35 PM - 
29 packages are looking for funding
  run `npm fund` for details
5/25/2020, 2:40:35 PM - found 0 vulnerabilities
5/25/2020, 2:40:36 PM - Plugin "homebridge-camera-ffmpeg" removed.
5/25/2020, 2:40:36 PM - Got SIGINT, shutting down Bridge...
5/25/2020, 2:40:39 PM - Loaded plugin "homebridge-http-motion-sensor".
5/25/2020, 2:40:39 PM - Bridge is running on port 51826.
5/25/2020, 2:40:39 PM - [Front Porch] The device 'Front Porch' can now be reached under http://0.0.0.0:10170
5/25/2020, 2:40:39 PM - [Back Door] The device 'Back Door' can now be reached under http://0.0.0.0:10171
5/25/2020, 2:40:39 PM - [Driveway] The device 'Driveway' can now be reached under http://0.0.0.0:10172
5/25/2020, 2:40:48 PM - 
> ffmpeg-for-homebridge@0.0.4 install /Users/tommy/.hoobs/node_modules/ffmpeg-for-homebridge
> node install.js
5/25/2020, 2:40:49 PM - ffmpeg version git-2020-02-18-6e7fa54 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --enable-videotoolbox --pkgconfigdir=/Users/runner/runners/2.164.0/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/lib/pkgconfig --prefix=/Users/runner/runners/2.164.0/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace --pkg-config-flags=--static --extra-cflags=-I/Users/runner/runners/2.164.0/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/include --extra-ldflags=-L/Users/runner/runners/2.164.0/work/ffmpeg-for-homebridge/ffmpeg-for-homebridge/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
  libavutil      56. 40.100 / 56. 40.100
  libavcodec     58. 68.102 / 58. 68.102
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 75.100 /  7. 75.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
5/25/2020, 2:40:49 PM - [36m
ffmpeg has been downloaded to /Users/tommy/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg[0m
5/25/2020, 2:40:49 PM - [37mThank you for using [4mhttps://github.com/homebridge/ffmpeg-for-homebridge[0m
5/25/2020, 2:40:49 PM - + homebridge-camera-ffmpeg@1.1.1
added 48 packages from 34 contributors, removed 2 packages and updated 1 package in 2.186s
5/25/2020, 2:40:49 PM - 
31 packages are looking for funding
  run `npm fund` for details
5/25/2020, 2:40:49 PM - Plugin "homebridge-camera-ffmpeg" installed.
5/25/2020, 2:40:49 PM - Got SIGINT, shutting down Bridge...
5/25/2020, 2:40:52 PM - Error loading plugin "homebridge-camera-ffmpeg".
5/25/2020, 2:40:52 PM - Error: No valid exports main found for '/Users/tommy/.hoobs/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tommy/.hoobs/node_modules/googleapis-common/build/src/apirequest.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
5/25/2020, 2:40:52 PM - Loaded plugin "homebridge-http-motion-sensor".
5/25/2020, 2:40:52 PM - The requested platform "Camera-ffmpeg" was not registered by any plugin.
5/25/2020, 2:40:52 PM - Your config.json is requesting the platform "Camera-ffmpeg" which has not been published by any installed plugins.
5/25/2020, 2:40:52 PM - Bridge is running on port 51826.
5/25/2020, 2:40:52 PM - [Front Porch] The device 'Front Porch' can now be reached under http://0.0.0.0:10170
5/25/2020, 2:40:52 PM - [Back Door] The device 'Back Door' can now be reached under http://0.0.0.0:10171
5/25/2020, 2:40:52 PM - [Driveway] The device 'Driveway' can now be reached under http://0.0.0.0:10172
5/25/2020, 2:41:15 PM - Got SIGINT, shutting down Bridge...
5/25/2020, 2:41:19 PM - Error loading plugin "homebridge-camera-ffmpeg".
5/25/2020, 2:41:19 PM - Error: No valid exports main found for '/Users/tommy/.hoobs/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tommy/.hoobs/node_modules/googleapis-common/build/src/apirequest.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
5/25/2020, 2:41:19 PM - Loaded plugin "homebridge-http-motion-sensor".
5/25/2020, 2:41:19 PM - The requested platform "Camera-ffmpeg" was not registered by any plugin.
5/25/2020, 2:41:19 PM - Your config.json is requesting the platform "Camera-ffmpeg" which has not been published by any installed plugins.
5/25/2020, 2:41:19 PM - Bridge is running on port 51826.
5/25/2020, 2:41:19 PM - [Front Porch] The device 'Front Porch' can now be reached under http://0.0.0.0:10170
5/25/2020, 2:41:19 PM - [Back Door] The device 'Back Door' can now be reached under http://0.0.0.0:10171
5/25/2020, 2:41:19 PM - [Driveway] The device 'Driveway' can now be reached under http://0.0.0.0:10172
5/26/2020, 10:24:41 AM - Got SIGINT, shutting down Bridge...
5/26/2020, 10:24:44 AM - Error loading plugin "homebridge-camera-ffmpeg".
5/26/2020, 10:24:44 AM - Error: No valid exports main found for '/Users/tommy/.hoobs/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tommy/.hoobs/node_modules/googleapis-common/build/src/apirequest.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
5/26/2020, 10:24:44 AM - Loaded plugin "homebridge-http-motion-sensor".
5/26/2020, 10:24:44 AM - The requested platform "Camera-ffmpeg" was not registered by any plugin.
5/26/2020, 10:24:44 AM - Your config.json is requesting the platform "Camera-ffmpeg" which has not been published by any installed plugins.
5/26/2020, 10:24:44 AM - Bridge is running on port 51826.
5/26/2020, 10:24:44 AM - [Front Porch] The device 'Front Porch' can now be reached under http://0.0.0.0:10170
5/26/2020, 10:24:44 AM - [Back Door] The device 'Back Door' can now be reached under http://0.0.0.0:10171
5/26/2020, 10:24:44 AM - [Driveway] The device 'Driveway' can now be reached under http://0.0.0.0:10172
5/26/2020, 10:55:49 AM - Got SIGINT, shutting down Bridge...
5/26/2020, 10:55:52 AM - Persist directory removed.
5/26/2020, 10:55:53 AM - Error loading plugin "homebridge-camera-ffmpeg".
5/26/2020, 10:55:53 AM - Error: No valid exports main found for '/Users/tommy/.hoobs/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tommy/.hoobs/node_modules/googleapis-common/build/src/apirequest.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
5/26/2020, 10:55:53 AM - Loaded plugin "homebridge-http-motion-sensor".
5/26/2020, 10:55:53 AM - The requested platform "Camera-ffmpeg" was not registered by any plugin.
5/26/2020, 10:55:53 AM - Your config.json is requesting the platform "Camera-ffmpeg" which has not been published by any installed plugins.
5/26/2020, 10:55:53 AM - Bridge is running on port 51826.
5/26/2020, 10:55:53 AM - [Front Porch] The device 'Front Porch' can now be reached under http://0.0.0.0:10170
5/26/2020, 10:55:53 AM - [Back Door] The device 'Back Door' can now be reached under http://0.0.0.0:10171
5/26/2020, 10:55:53 AM - [Driveway] The device 'Driveway' can now be reached under http://0.0.0.0:10172```

**Additional context**
I've tried to get audio working, and could not, but I suspect it's a macOS issue. And I cannot get resolutions to actually work right. Cameras are 720p enabled on camera's admin pages, but will only show up at about 640x360, no matter what parameters I put in.

**Comment by askovi** [comment]
What’s your node version? Run this in terminal to get it:

`node -v`

**Comment by tlight93** [comment]
> What’s your node version? Run this in terminal to get it:
> 
> `node -v`

13.3.0

**Comment by askovi** [comment]
Please download and install the LTS version from here: https://nodejs.org/en/download/

Then restart HOOBS and see if it fixes your issue.

**Comment by tlight93** [comment]
It won't start HOOBS at all now. I get the following:

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

**Comment by askovi** [comment]
Yes that’s normal. Run this to recompile HOOBS for the new version of node you just installed:

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by tlight93** [comment]
> Yes that’s normal. Run this to recompile HOOBS for the new version of node you just installed:
> 
> `sudo npm install -g --unsafe-perm @hoobs/hoobs`

Now I'm getting this after running that command and trying to start HOOBS:

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

**Comment by askovi** [comment]
That’s the same error. Try uninstalling first then reinstalling to trigger it:

`sudo npm uninstall -g @hoobs/hoobs`

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by tlight93** [comment]
> That’s the same error. Try uninstalling first then reinstalling to trigger it:
> 
> `sudo npm uninstall -g @hoobs/hoobs`
> 
> `sudo npm install -g --unsafe-perm @hoobs/hoobs`

Perfect! Thank you so much! That got me back into HOOBS, and I was able to add the cameras, and they're working again, I would like to try getting audio to work on them, but it's not a huge issue if I can't get that working. I'm not sure what to add to the config.json for audio.

**Comment by askovi** [comment]
First make sure your ffmpeg has audio codecs by running this command

`ffmpeg -v`

Look for libfdk_aac to be present in the list

If it is, then just add parameter

`audio: true`

to each camera object in the config.

**Comment by tlight93** [comment]
I do not see that one in my list. Is it possible to add it through Terminal or download and install? Sorry, I'm not very experienced.

**Comment by askovi** [comment]
No it needs to be recompiled for Mac using that codec. I don't have a guide for Mac, we only have it released for the Raspberry Pi.

**Comment by tlight93** [comment]
Ok. I figure that most of my issues will be resolved when I eventually get a Raspberry Pi, I know that's the ideal device for running HOOBS, I just wanted to get a good idea of how well I could get things working before I bought one. Thank you again for all of your help!
