### ISSUE TITLE
Failed update

### ISSUE THREAD

**Issue by j0ha** [hoobs-org/HOOBS#670]
**Description**
After updating hoobs from v.3.1.27 to v.3.2.6 I get this error. A restart doesn’t help. The update failed. 

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.1.27

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

homebridge-gpio-valve
homebridge-dht
homebridge-gpio-device

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```


    "description": "This file is used for plugin configuration.",
    "ports": {},
    "accessories": [
        {
            "accessory": "Dht",
            "name": "Temperatur/Luftfeuchtigkeit",
            "gpio": "4",
            "service": "dht11",
            "plugin_map": {
                "plugin_name": "homebridge-dht",
                "index": 0
            }
        },
        {
            "accessory": "GPIOValve",
            "name": "Zone 1",
            "pin": 21,
            "openOnHigh": false,
            "isTimed": true,
            "defaultDuration": 1200,
            "type": "IRRIGATION",
            "identifyDuration": 10,
            "plugin_map": {
                "plugin_name": "homebridge-gpio-valve",
                "index": 0
            }
        },
        {
            "accessory": "GPIOValve",
            "name": "Zone 2",
            "pin": 20,
            "openOnHigh": false,
            "isTimed": true,
            "defaultDuration": 1200,
            "type": "IRRIGATION",
            "identifyDuration": 10,
            "plugin_map": {
                "plugin_name": "homebridge-gpio-valve",
                "index": 0
            }
        },
        {
            "accessory": "GPIOValve",
            "name": "Zone 3",
            "pin": 16,
            "openOnHigh": false,
            "isTimed": true,
            "defaultDuration": 1200,
            "type": "IRRIGATION",
            "identifyDuration": 10,
            "plugin_map": {
                "plugin_name": "homebridge-gpio-valve",
                "index": 0
            }
        }
    ],
    "platforms": []
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```

31.5.2020, 22:50:23 Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/hapCrypto.js:79:35)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:486:39)
    at HAPServer._this._handlePairVerify (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:450:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:227:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1129:12)
31.5.2020, 22:50:23 Got SIGTERM, shutting down Bridge...
31.5.2020, 22:50:23 Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/hapCrypto.js:79:35)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:486:39)
    at HAPServer._this._handlePairVerify (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:450:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:227:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1129:12)

```

**Additional context**

**Comment by askovi** [comment]
Node needs to be upgraded for that IV library and then trigger a rebuild of HOOBS. 

See solution here: https://github.com/hoobs-org/HOOBS/issues/649
