### ISSUE TITLE
Can't install homebridge-hubitat-makerapi

### ISSUE THREAD

**Issue by ptbtx** [hoobs-org/HOOBS#671]
**Description**
Can't install homebridge-hubitat-makerapi.

**Expected behavoir**
It should install.

**Plugin name**
homebridge-hubitat-makerapi

**Please report the issue to the plugin developer**
Don't know where to report it - but the plugin installed with no problem prior when I had hoobs running as a service on my Mac as per https://support.hoobs.org/docs/5e763ebbe87d1e02b6c19d37

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.2.4

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYE8MM",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "3E:DB:83:9C:2D:2B"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--prefer-offline',
1 verbose cli   '--no-audit',
1 verbose cli   '--unsafe-perm',
1 verbose cli   '--progress=true',
1 verbose cli   'homebridge-hubitat-makerapi@0.4.11'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session 25b91a1667fc43c5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-hubitat-makerapi 111ms (from cache)
8 silly pacote version manifest for homebridge-hubitat-makerapi@0.4.11 fetched in 171ms
9 timing stage:loadCurrentTree Completed in 352ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 5ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-hubitat-makerapi@0.4.11 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/ansi_up 204ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/chalk 198ms attempt #2 (from cache)
19 http fetch GET 200 https://registry.npmjs.org/compare-versions 199ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/express 207ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/ip-range-check 230ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/mired 226ms (from cache)
23 http fetch GET 200 https://registry.npmjs.org/urlencode 206ms (from cache)
24 http fetch GET 200 https://registry.npmjs.org/winston-logrotate 204ms (from cache)
25 http fetch GET 200 https://registry.npmjs.org/ws 203ms (from cache)
26 silly pacote range manifest for ansi_up@^4.0.4 fetched in 312ms
27 silly resolveWithNewModule ansi_up@4.0.4 checking installable status
28 silly pacote range manifest for chalk@^2.4.2 fetched in 309ms
29 silly resolveWithNewModule chalk@2.4.2 checking installable status
30 silly pacote range manifest for compare-versions@^3.4.0 fetched in 302ms
31 silly resolveWithNewModule compare-versions@3.6.0 checking installable status
32 silly pacote range manifest for express@^4.17.1 fetched in 302ms
33 silly resolveWithNewModule express@4.17.1 checking installable status
34 silly pacote range manifest for ip-range-check@^0.2.0 fetched in 300ms
35 silly resolveWithNewModule ip-range-check@0.2.0 checking installable status
36 silly pacote range manifest for mired@^0.0.0 fetched in 297ms
37 silly resolveWithNewModule mired@0.0.0 checking installable status
38 silly pacote range manifest for urlencode@^1.1.0 fetched in 280ms
39 silly resolveWithNewModule urlencode@1.1.0 checking installable status
40 silly pacote version manifest for winston-logrotate@=1.3.0 fetched in 281ms
41 silly resolveWithNewModule winston-logrotate@1.3.0 checking installable status
42 silly pacote range manifest for ws@^7.1.2 fetched in 281ms
43 silly resolveWithNewModule ws@7.3.0 checking installable status
44 http fetch GET 200 https://registry.npmjs.org/ansi-styles 49ms (from cache)
45 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp 57ms (from cache)
46 silly pacote range manifest for ansi-styles@^3.2.1 fetched in 87ms
47 silly resolveWithNewModule ansi-styles@3.2.1 checking installable status
48 http fetch GET 200 https://registry.npmjs.org/supports-color 83ms (from cache)
49 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 99ms
50 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
51 silly pacote range manifest for supports-color@^5.3.0 fetched in 102ms
52 silly resolveWithNewModule supports-color@5.5.0 checking installable status
53 http fetch GET 200 https://registry.npmjs.org/color-convert 23ms (from cache)
54 silly pacote range manifest for color-convert@^1.9.0 fetched in 38ms
55 silly resolveWithNewModule color-convert@1.9.3 checking installable status
56 http fetch GET 200 https://registry.npmjs.org/color-name 18ms (from cache)
57 silly pacote version manifest for color-name@1.1.3 fetched in 28ms
58 silly resolveWithNewModule color-name@1.1.3 checking installable status
59 http fetch GET 200 https://registry.npmjs.org/has-flag 19ms (from cache)
60 silly pacote range manifest for has-flag@^3.0.0 fetched in 32ms
61 silly resolveWithNewModule has-flag@3.0.0 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/accepts 146ms (from cache)
63 http fetch GET 200 https://registry.npmjs.org/array-flatten 147ms (from cache)
64 http fetch GET 200 https://registry.npmjs.org/body-parser 147ms (from cache)
65 http fetch GET 200 https://registry.npmjs.org/cookie 145ms (from cache)
66 http fetch GET 200 https://registry.npmjs.org/content-disposition 152ms (from cache)
67 http fetch GET 200 https://registry.npmjs.org/content-type 166ms (from cache)
68 http fetch GET 200 https://registry.npmjs.org/cookie-signature 166ms (from cache)
69 http fetch GET 200 https://registry.npmjs.org/debug 166ms (from cache)
70 http fetch GET 200 https://registry.npmjs.org/depd 168ms (from cache)
71 http fetch GET 200 https://registry.npmjs.org/encodeurl 168ms (from cache)
72 silly pacote range manifest for accepts@~1.3.7 fetched in 213ms
73 silly resolveWithNewModule accepts@1.3.7 checking installable status
74 silly pacote version manifest for cookie@0.4.0 fetched in 217ms
75 silly resolveWithNewModule cookie@0.4.0 checking installable status
76 silly pacote version manifest for body-parser@1.19.0 fetched in 235ms
77 silly resolveWithNewModule body-parser@1.19.0 checking installable status
78 silly pacote version manifest for array-flatten@1.1.1 fetched in 247ms
79 silly resolveWithNewModule array-flatten@1.1.1 checking installable status
80 silly pacote version manifest for content-disposition@0.5.3 fetched in 249ms
81 silly resolveWithNewModule content-disposition@0.5.3 checking installable status
82 silly pacote range manifest for content-type@~1.0.4 fetched in 256ms
83 silly resolveWithNewModule content-type@1.0.4 checking installable status
84 silly pacote version manifest for cookie-signature@1.0.6 fetched in 260ms
85 silly resolveWithNewModule cookie-signature@1.0.6 checking installable status
86 silly pacote version manifest for debug@2.6.9 fetched in 266ms
87 silly resolveWithNewModule debug@2.6.9 checking installable status
88 silly pacote range manifest for depd@~1.1.2 fetched in 310ms
89 silly resolveWithNewModule depd@1.1.2 checking installable status
90 silly pacote range manifest for encodeurl@~1.0.2 fetched in 312ms
91 silly resolveWithNewModule encodeurl@1.0.2 checking installable status
92 http fetch GET 200 https://registry.npmjs.org/escape-html 184ms (from cache)
93 http fetch GET 200 https://registry.npmjs.org/etag 116ms (from cache)
94 http fetch GET 200 https://registry.npmjs.org/finalhandler 122ms (from cache)
95 http fetch GET 200 https://registry.npmjs.org/merge-descriptors 116ms (from cache)
96 http fetch GET 200 https://registry.npmjs.org/fresh 129ms (from cache)
97 http fetch GET 200 https://registry.npmjs.org/methods 122ms (from cache)
98 http fetch GET 200 https://registry.npmjs.org/parseurl 117ms (from cache)
99 http fetch GET 200 https://registry.npmjs.org/on-finished 127ms (from cache)
100 http fetch GET 200 https://registry.npmjs.org/path-to-regexp 104ms (from cache)
101 silly pacote range manifest for escape-html@~1.0.3 fetched in 238ms
102 silly resolveWithNewModule escape-html@1.0.3 checking installable status
103 http fetch GET 200 https://registry.npmjs.org/proxy-addr 120ms (from cache)
104 silly pacote range manifest for etag@~1.8.1 fetched in 175ms
105 silly resolveWithNewModule etag@1.8.1 checking installable status
106 silly pacote range manifest for finalhandler@~1.1.2 fetched in 187ms
107 silly resolveWithNewModule finalhandler@1.1.2 checking installable status
108 silly pacote version manifest for merge-descriptors@1.0.1 fetched in 188ms
109 silly resolveWithNewModule merge-descriptors@1.0.1 checking installable status
110 silly pacote range manifest for parseurl@~1.3.3 fetched in 182ms
111 silly resolveWithNewModule parseurl@1.3.3 checking installable status
112 silly pacote version manifest for fresh@0.5.2 fetched in 203ms
113 silly resolveWithNewModule fresh@0.5.2 checking installable status
114 silly pacote range manifest for methods@~1.1.2 fetched in 199ms
115 silly resolveWithNewModule methods@1.1.2 checking installable status
116 silly pacote version manifest for path-to-regexp@0.1.7 fetched in 193ms
117 silly resolveWithNewModule path-to-regexp@0.1.7 checking installable status
118 silly pacote range manifest for on-finished@~2.3.0 fetched in 229ms
119 silly resolveWithNewModule on-finished@2.3.0 checking installable status
120 silly pacote range manifest for proxy-addr@~2.0.5 fetched in 221ms
121 silly resolveWithNewModule proxy-addr@2.0.6 checking installable status
122 http fetch GET 200 https://registry.npmjs.org/range-parser 148ms (from cache)
123 http fetch GET 200 https://registry.npmjs.org/qs 156ms (from cache)
124 http fetch GET 200 https://registry.npmjs.org/safe-buffer 157ms (from cache)
125 http fetch GET 200 https://registry.npmjs.org/send 142ms (from cache)
126 http fetch GET 200 https://registry.npmjs.org/serve-static 144ms (from cache)
127 http fetch GET 200 https://registry.npmjs.org/statuses 144ms (from cache)
128 http fetch GET 200 https://registry.npmjs.org/setprototypeof 149ms (from cache)
129 http fetch GET 200 https://registry.npmjs.org/type-is 146ms (from cache)
130 silly pacote range manifest for range-parser@~1.2.1 fetched in 217ms
131 silly resolveWithNewModule range-parser@1.2.1 checking installable status
132 http fetch GET 200 https://registry.npmjs.org/utils-merge 137ms (from cache)
133 silly pacote version manifest for qs@6.7.0 fetched in 229ms
134 silly resolveWithNewModule qs@6.7.0 checking installable status
135 http fetch GET 200 https://registry.npmjs.org/vary 122ms (from cache)
136 silly pacote version manifest for safe-buffer@5.1.2 fetched in 221ms
137 silly resolveWithNewModule safe-buffer@5.1.2 checking installable status
138 silly pacote version manifest for serve-static@1.14.1 fetched in 198ms
139 silly resolveWithNewModule serve-static@1.14.1 checking installable status
140 silly pacote version manifest for send@0.17.1 fetched in 205ms
141 silly resolveWithNewModule send@0.17.1 checking installable status
142 silly pacote range manifest for statuses@~1.5.0 fetched in 202ms
143 silly resolveWithNewModule statuses@1.5.0 checking installable status
144 silly pacote version manifest for setprototypeof@1.1.1 fetched in 207ms
145 silly resolveWithNewModule setprototypeof@1.1.1 checking installable status
146 silly pacote range manifest for type-is@~1.6.18 fetched in 190ms
147 silly resolveWithNewModule type-is@1.6.18 checking installable status
148 silly pacote version manifest for utils-merge@1.0.1 fetched in 174ms
149 silly resolveWithNewModule utils-merge@1.0.1 checking installable status
150 silly pacote range manifest for vary@~1.1.2 fetched in 155ms
151 silly resolveWithNewModule vary@1.1.2 checking installable status
152 http fetch GET 200 https://registry.npmjs.org/mime-types 32ms (from cache)
153 http fetch GET 200 https://registry.npmjs.org/negotiator 35ms (from cache)
154 silly pacote range manifest for mime-types@~2.1.24 fetched in 46ms
155 silly resolveWithNewModule mime-types@2.1.27 checking installable status
156 silly pacote version manifest for negotiator@0.6.2 fetched in 49ms
157 silly resolveWithNewModule negotiator@0.6.2 checking installable status
158 http fetch GET 200 https://registry.npmjs.org/mime-db 21ms (from cache)
159 silly pacote version manifest for mime-db@1.44.0 fetched in 31ms
160 silly resolveWithNewModule mime-db@1.44.0 checking installable status
161 http fetch GET 200 https://registry.npmjs.org/bytes 39ms (from cache)
162 http fetch GET 200 https://registry.npmjs.org/iconv-lite 38ms (from cache)
163 http fetch GET 200 https://registry.npmjs.org/http-errors 47ms (from cache)
164 http fetch GET 200 https://registry.npmjs.org/raw-body 45ms (from cache)
165 silly pacote version manifest for bytes@3.1.0 fetched in 63ms
166 silly resolveWithNewModule bytes@3.1.0 checking installable status
167 silly pacote version manifest for http-errors@1.7.2 fetched in 66ms
168 silly resolveWithNewModule http-errors@1.7.2 checking installable status
169 silly pacote version manifest for iconv-lite@0.4.24 fetched in 68ms
170 silly resolveWithNewModule iconv-lite@0.4.24 checking installable status
171 silly pacote version manifest for raw-body@2.4.0 fetched in 71ms
172 silly resolveWithNewModule raw-body@2.4.0 checking installable status
173 http fetch GET 200 https://registry.npmjs.org/ms 20ms (from cache)
174 silly pacote version manifest for ms@2.0.0 fetched in 28ms
175 silly resolveWithNewModule ms@2.0.0 checking installable status
176 http fetch GET 200 https://registry.npmjs.org/inherits 28ms (from cache)
177 http fetch GET 200 https://registry.npmjs.org/toidentifier 29ms attempt #2 (from cache)
178 silly pacote version manifest for inherits@2.0.3 fetched in 40ms
179 silly resolveWithNewModule inherits@2.0.3 checking installable status
180 silly pacote version manifest for toidentifier@1.0.0 fetched in 42ms
181 silly resolveWithNewModule toidentifier@1.0.0 checking installable status
182 http fetch GET 200 https://registry.npmjs.org/safer-buffer 32ms (from cache)
183 silly pacote range manifest for safer-buffer@>= 2.1.2 < 3 fetched in 43ms
184 silly resolveWithNewModule safer-buffer@2.1.2 checking installable status
185 http fetch GET 200 https://registry.npmjs.org/ee-first 22ms (from cache)
186 silly pacote version manifest for ee-first@1.1.1 fetched in 32ms
187 silly resolveWithNewModule ee-first@1.1.1 checking installable status
188 http fetch GET 200 https://registry.npmjs.org/unpipe 19ms (from cache)
189 silly pacote version manifest for unpipe@1.0.0 fetched in 26ms
190 silly resolveWithNewModule unpipe@1.0.0 checking installable status
191 http fetch GET 200 https://registry.npmjs.org/media-typer 20ms (from cache)
192 silly pacote version manifest for media-typer@0.3.0 fetched in 29ms
193 silly resolveWithNewModule media-typer@0.3.0 checking installable status
194 http fetch GET 200 https://registry.npmjs.org/forwarded 44ms (from cache)
195 http fetch GET 200 https://registry.npmjs.org/ipaddr.js 47ms (from cache)
196 silly pacote range manifest for forwarded@~0.1.2 fetched in 58ms
197 silly resolveWithNewModule forwarded@0.1.2 checking installable status
198 silly pacote version manifest for ipaddr.js@1.9.1 fetched in 62ms
199 silly resolveWithNewModule ipaddr.js@1.9.1 checking installable status
200 silly pacote version manifest for ms@2.1.1 fetched in 16ms
201 silly resolveWithNewModule ms@2.1.1 checking installable status
202 http fetch GET 200 https://registry.npmjs.org/destroy 34ms (from cache)
203 http fetch GET 200 https://registry.npmjs.org/mime 37ms (from cache)
204 silly pacote range manifest for destroy@~1.0.4 fetched in 49ms
205 silly resolveWithNewModule destroy@1.0.4 checking installable status
206 silly pacote version manifest for mime@1.6.0 fetched in 53ms
207 silly resolveWithNewModule mime@1.6.0 checking installable status
208 http fetch GET 200 https://registry.npmjs.org/bluebird 47ms (from cache)
209 http fetch GET 200 https://registry.npmjs.org/fs-extra 65ms (from cache)
210 http fetch GET 200 https://registry.npmjs.org/logrotate-stream 68ms (from cache)
211 silly fetchPackageMetaData error for fs-extra@0.24.0 Unexpected end of JSON input while parsing near '...ame":"fs-extra","vers'
212 http fetch GET 200 https://registry.npmjs.org/winston 74ms (from cache)
213 silly pacote version manifest for bluebird@2.9.30 fetched in 96ms
214 silly resolveWithNewModule bluebird@2.9.30 checking installable status
215 silly pacote version manifest for logrotate-stream@0.2.5 fetched in 95ms
216 silly resolveWithNewModule logrotate-stream@0.2.5 checking installable status
217 silly pacote range manifest for winston@^2.1.0 fetched in 99ms
218 silly resolveWithNewModule winston@2.4.4 checking installable status
219 timing stage:rollbackFailedOptional Completed in 2ms
220 timing stage:runTopLevelLifecycles Completed in 2682ms
221 silly saveTree @hoobs/hoobs@3.2.6
221 silly saveTree └─┬ homebridge-hubitat-makerapi@0.4.11
221 silly saveTree   ├── ansi_up@4.0.4
221 silly saveTree   ├─┬ chalk@2.4.2
221 silly saveTree   │ ├─┬ ansi-styles@3.2.1
221 silly saveTree   │ │ └─┬ color-convert@1.9.3
221 silly saveTree   │ │   └── color-name@1.1.3
221 silly saveTree   │ ├── escape-string-regexp@1.0.5
221 silly saveTree   │ └─┬ supports-color@5.5.0
221 silly saveTree   │   └── has-flag@3.0.0
221 silly saveTree   ├── compare-versions@3.6.0
221 silly saveTree   ├─┬ express@4.17.1
221 silly saveTree   │ ├─┬ accepts@1.3.7
221 silly saveTree   │ │ ├─┬ mime-types@2.1.27
221 silly saveTree   │ │ │ └── mime-db@1.44.0
221 silly saveTree   │ │ └── negotiator@0.6.2
221 silly saveTree   │ ├── array-flatten@1.1.1
221 silly saveTree   │ ├─┬ body-parser@1.19.0
221 silly saveTree   │ │ ├── bytes@3.1.0
221 silly saveTree   │ │ ├── content-type@1.0.4
221 silly saveTree   │ │ ├─┬ debug@2.6.9
221 silly saveTree   │ │ │ └── ms@2.0.0
221 silly saveTree   │ │ ├── depd@1.1.2
221 silly saveTree   │ │ ├─┬ http-errors@1.7.2
221 silly saveTree   │ │ │ ├── inherits@2.0.3
221 silly saveTree   │ │ │ ├── setprototypeof@1.1.1
221 silly saveTree   │ │ │ ├── statuses@1.5.0
221 silly saveTree   │ │ │ └── toidentifier@1.0.0
221 silly saveTree   │ │ ├─┬ iconv-lite@0.4.24
221 silly saveTree   │ │ │ └── safer-buffer@2.1.2
221 silly saveTree   │ │ ├─┬ on-finished@2.3.0
221 silly saveTree   │ │ │ └── ee-first@1.1.1
221 silly saveTree   │ │ ├── qs@6.7.0
221 silly saveTree   │ │ ├─┬ raw-body@2.4.0
221 silly saveTree   │ │ │ └── unpipe@1.0.0
221 silly saveTree   │ │ └─┬ type-is@1.6.18
221 silly saveTree   │ │   └── media-typer@0.3.0
221 silly saveTree   │ ├─┬ content-disposition@0.5.3
221 silly saveTree   │ │ └── safe-buffer@5.1.2
221 silly saveTree   │ ├── content-type@1.0.4
221 silly saveTree   │ ├── cookie-signature@1.0.6
221 silly saveTree   │ ├── cookie@0.4.0
221 silly saveTree   │ ├── debug@2.6.9
221 silly saveTree   │ ├── depd@1.1.2
221 silly saveTree   │ ├── encodeurl@1.0.2
221 silly saveTree   │ ├── escape-html@1.0.3
221 silly saveTree   │ ├── etag@1.8.1
221 silly saveTree   │ ├─┬ finalhandler@1.1.2
221 silly saveTree   │ │ └── parseurl@1.3.3
221 silly saveTree   │ ├── fresh@0.5.2
221 silly saveTree   │ ├── merge-descriptors@1.0.1
221 silly saveTree   │ ├── methods@1.1.2
221 silly saveTree   │ ├── on-finished@2.3.0
221 silly saveTree   │ ├── parseurl@1.3.3
221 silly saveTree   │ ├── path-to-regexp@0.1.7
221 silly saveTree   │ ├─┬ proxy-addr@2.0.6
221 silly saveTree   │ │ ├── forwarded@0.1.2
221 silly saveTree   │ │ └── ipaddr.js@1.9.1
221 silly saveTree   │ ├── qs@6.7.0
221 silly saveTree   │ ├── range-parser@1.2.1
221 silly saveTree   │ ├── safe-buffer@5.1.2
221 silly saveTree   │ ├─┬ send@0.17.1
221 silly saveTree   │ │ ├── destroy@1.0.4
221 silly saveTree   │ │ ├── mime@1.6.0
221 silly saveTree   │ │ └── ms@2.1.1
221 silly saveTree   │ ├── serve-static@1.14.1
221 silly saveTree   │ ├── setprototypeof@1.1.1
221 silly saveTree   │ ├── statuses@1.5.0
221 silly saveTree   │ ├── type-is@1.6.18
221 silly saveTree   │ ├── utils-merge@1.0.1
221 silly saveTree   │ └── vary@1.1.2
221 silly saveTree   ├── ip-range-check@0.2.0
221 silly saveTree   ├── mired@0.0.0
221 silly saveTree   ├── urlencode@1.1.0
221 silly saveTree   ├─┬ winston-logrotate@1.3.0
221 silly saveTree   │ ├── bluebird@2.9.30
221 silly saveTree   │ ├── logrotate-stream@0.2.5
221 silly saveTree   │ └── winston@2.4.4
221 silly saveTree   └── ws@7.3.0
222 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ame":"fs-extra","vers'
222 verbose stack     at JSON.parse (<anonymous>)
222 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
222 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
222 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
223 verbose cwd /home/hoobs/.hoobs
224 verbose Linux 4.19.97-v7+
225 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-hubitat-makerapi@0.4.11"
226 verbose node v12.16.2
227 verbose npm  v6.14.4
228 error Unexpected end of JSON input while parsing near '...ame":"fs-extra","vers'
229 verbose exit [ 1, true ]
```

**Additional context**
I installed the SD card on my Pi 3B today.  It installed as 3.2.4.  I then upgraded to 3.2.6.  Then I tried to install homebridge-hubitat-makerapi which installed with no problem prior when I had hoobs running as a service on my Mac as per https://support.hoobs.org/docs/5e763ebbe87d1e02b6c19d37

Software
HOOBS Core
Current Version: 3.2.6
Up to Date
Bridge Name    HOOBS
HOOBS Version    3.2.6
Node Version    12.16.2
Username    3E:DB:83:9C:2D:2B
Bridge Port    51826
Home Setup PIN    031-45-154
Home Setup ID    X-HM://0023ISYWYE8MM
Application Path    /home/hoobs/.hoobs
Configuration Path    /home/hoobs/.hoobs/etc
Local Modules Path    /home/hoobs/.hoobs/node_modules
Global Modules Path    /usr/local/lib/node_modules

System
Manufacturer    Raspberry Pi Foundation
Model    BCM2835 - Pi 3 Model B
Version    a22082 - Rev. 1.2
Serial    00000000b5a62113

Operating System
Platform    linux
Distro    Raspbian GNU/Linux
Release    10
Codename    buster
Kernel    4.19.97-v7+
Arch    arm
Hostname    hoobs
Codepage    UTF-8
Logofile    raspbian
Serial    9440392fba1246ef8fba5c1e2bdf324d
Build   
Servicepack   
Uefi    false

**Comment by askovi** [comment]
Are you installing it from the UI?

**Comment by BobbySlope** [comment]
just tested on an spare rpi, installs without issues on 3.2.6 on rpi image

**Comment by ptbtx** [comment]
I followed the instructions: plug in SD card, plug in ethernet cable, plug in power, go to hoobs.local, log in, find the plugin, install.  What am I doing wrong?

**Comment by ptbtx** [comment]
Should the SD card be left in the Pi?

**Comment by ptbtx** [comment]
I don't know if this is related but when I try to add HOOBS to the Home app by scanning the QR code I get "Accessory already added - To add this accessory to your home, you'll need to reset it first."  I've tried restart on the HOOBS UI but that doesn't resolve the issue.  How do I reset it?

**Comment by ptbtx** [comment]
Ignore that last one - web search found that there is a reset button under Help.

**Comment by ptbtx** [comment]
I pointed to this issue from https://github.com/danTapps/homebridge-hubitat-makerapi/issues/15

**Comment by ptbtx** [comment]
How do I reinstall the HOOBS SD card so I can get back to 3.2.4?  Maybe if I do that I might be able to get past this problem.

**Comment by askovi** [comment]
If you want to downgrade (not recommended), you can do it via ssh. Login with username: hoobs and password: hoobsadmin then run this command:

`sudo npm install -g --unsafe-perm @hoobs/hoobs@3.2.4`

**Comment by ptbtx** [comment]
Will try to stay at 3.2.6.  How to install this plugin is confusing.  Searching for the maker plugin gives you two options: Details and Install.  Install didn't work as logged above.  So I clicked on Details and I see another set of instructions.  I followed the two steps listed.  In the second step it directs us to do this:
$ sudo npm i -g homebridge
$ sudo npm i -g homebridge-hubitat-makerapi
create ~/.homebridge/config.json
  It's actually in ~/.hoobs/etc
$ homebridge
Going back to the Plugins page shows nothing.  Rebooting didn't help.  

How do I proceed?  I assume starting homebridge was not a good idea; hopefully a reboot got rid of that.  Do I need to npm uninstall homebridge?

**Comment by ptbtx** [comment]
Should the SD card be left in the Pi?  The install instructions don't say anything about removing it, but it would be good to have a statement indicating what to do about it.

**Comment by ptbtx** [comment]
Going back to 3.2.4 didn't help.  BobbySlope, how can I replicate your environment?  I have a new Pi 3B which I'll be happy to start from scratch with but I don't know how to do that.

**Comment by askovi** [comment]
I just installed the Hubitat Makerapi 0.4.11 on HOOBS 3.2.6 and added the default configuration and it runs fine, no errors. 
I recommend you reflash your SD card and start fresh. Take the card out of your Pi, use the provided SD card adapter and plug it into your computer. Then follow the instructions here to reflash it: https://support.hoobs.org/docs/5e875c220ab68b0344e872ca

**Comment by ptbtx** [comment]
That went pretty well up until I got to the plugins page.  The step by step guide shows the following page with a lot of options.

![image](https://user-images.githubusercontent.com/63991611/84118023-063f0b80-a9f8-11ea-8655-9952ded9f94a.png)

Mine only has a Search option.  After the search I clicked Install and it's hung, i.e. the activity indicator never stops.

**Comment by ptbtx** [comment]
That non-stopping activity indicator must have been bogus.  I let it run all night and it was still like that in the morning but I could still navigate around the UI and when I got back to the Plugins page that was gone and the Plugin was there.  The log looked OK too except for the message:

uncaughtException: The "url" argument must be of type string.

And that is fixed by updating the configuration as described in the Details section of the plugin.

In the process of updating to 3.2.6 I again encountered the never ending activity indicator.  But closing the web page and restarting hoobs.local was functioning properly.

This issue can be closed now.  Apparently the SD image sent to me by HOOBS was bad.  Many thanks to askovi for how to reflash the image.

**Comment by askovi** [comment]
The UI spinner can hang sometimes if the action takes too long. Just refresh the page after a minute or so and it will be gone and the action will be done.
