### ISSUE TITLE
HOOBS fails to start on UnRAID

### ISSUE THREAD

**Issue by phoenixnodes** [hoobs-org/HOOBS#674]
**Description**
HOOBS fails to start and cannot be accessed.

**Version**
Newest

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ x] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

UnRAID

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
None

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
Default
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
TypeError: Cannot read property 'length' of null
at ServerResponse._send (_http_outgoing.js:305:33)
at write_ (_http_outgoing.js:683:15)
at ServerResponse.write (_http_outgoing.js:629:15)
at ReadStream.ondata (_stream_readable.js:695:22)
at ReadStream.emit (events.js:310:20)
at addChunk (_stream_readable.js:286:12)
at readableAddChunk (_stream_readable.js:268:9)
at ReadStream.Readable.push (_stream_readable.js:209:10)
at internal/fs/streams.js:210:12
at FSReqCallback.wrapper [as oncomplete] (fs.js:488:5)
HOOBS listening on port 80.
No plugins found.
Bridge is running on port 51826.
TypeError: Cannot read property 'length' of null
at ServerResponse._send (_http_outgoing.js:305:33)
at write_ (_http_outgoing.js:683:15)
at ServerResponse.write (_http_outgoing.js:629:15)
at ReadStream.ondata (_stream_readable.js:695:22)
at ReadStream.emit (events.js:310:20)
at addChunk (_stream_readable.js:286:12)
at readableAddChunk (_stream_readable.js:268:9)
at ReadStream.Readable.push (_stream_readable.js:209:10)
at internal/fs/streams.js:210:12
at FSReqCallback.wrapper [as oncomplete] (fs.js:488:5)
Got SIGINT, shutting down Bridge...
_http_outgoing.js:305
this.outputSize += header.length;
^
```

**Additional context**

**Comment by askovi** [comment]
HOOBS is not supported on UnRAID. See here for supported operating systems: https://support.hoobs.org/docs/5e763e30e87d1e02b6c19d33
