### ISSUE TITLE
Homebrigde service not running

### ISSUE THREAD

**Issue by FEXtheBEST** [hoobs-org/HOOBS#681]
**Description**
I've installed hoobs 3 days ago following the instructions on your site. When I log into the hoobs.local I see this error "Homebridge service not running".

**Version**
3.2.6

**Did you upgrade**
No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
No

**What device are you using?**
Please let us know the device you are running HOOBS on.
Custom Install

**If this is a custom install, what's your operating system?**
RasperryPi 4

**List your plugins**
BoschIndego - not working
Dyson Pure Cool Platform
R Pi
Wakeonlan
Xiaomi Roborock Vacuum

**Post your config**
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY3G2M",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "83224",
        "latitude": "47.78099",
        "longitude": "12.45359"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "53:9A:90:87:9D:83"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Boschindego",
            "name": "Wilfried",
            "model": 350,
            "email": "Felix@Plaschka.de",
            "pass": "****",
            "update_interval": "10000",
            "view_log": true
        },
        {
            "accessory": "WakeOnLan",
            "name": "Felix-PC",
            "macAddress": "40-B0-76-A0-A8-8C",
            "plugin_map": {
                "plugin_name": "homebridge-wakeonlan",
                "index": 0
            }
        },
        {
            "accessory": "XiaomiRoborockVacuum",
            "plugin_map": {
                "plugin_name": "homebridge-xiaomi-roborock-vacuum",
                "index": 0
            },
            "name": "Robbie",
            "waterBox": false,
            "pause": false,
            "dock": true,
            "delay": false,
            "cleanword": "Robben",
            "autoroom": false,
            "token": "4a68665244463831425655776b744455",
            "ip": "172.16.0.11"
        },
        {
            "accessory": "BoschIndego",
            "plugin_map": {
                "plugin_name": "homebridge-boschindego",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "RPi",
            "plugin_map": {
                "plugin_name": "homebridge-rpi"
            },
            "name": "Rasperry Pi4",
            "hosts": [
                {
                    "host": "localhost",
                    "name": "RasperryPi"
                }
            ]
        },
        {
            "platform": "DysonPureCoolPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-dyson-pure-cool"
            },
            "username": "Fplaschka@gmail.com",
            "password": "******",
            "countryCode": "DE",
            "updateInterval": 10000,
            "devices": [
                {
                    "ipAddress": "172.16.0.9",
                    "serialNumber": "PT4-EU-KKA1203A",
                    "enableAutoModeWhenActivating": true,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true,
                    "isSingleAccessoryModeEnabled": false
                }
            ],
            "retrySignInInterval": 10000
        }
    ]
}

```

**Post your log**
5.6.2020, 17:30:52 HOOBS listening on port 80.
5.6.2020, 17:30:54 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:30:54 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:30:54 Loaded plugin "homebridge-harmony".
5.6.2020, 17:30:55 Loaded plugin "homebridge-rpi".
5.6.2020, 17:30:55 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:30:55 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:30:55 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:30:55 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:30:55 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:30:55 [TV] HarmonyPlatform Init
5.6.2020, 17:30:55 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:30:55 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:30:55 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:30:55 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:30:55 BoschIndego Init1
5.6.2020, 17:30:55 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
5.6.2020, 17:30:55 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:30:55 [TV] INFO - shutdown
5.6.2020, 17:32:00 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:32:00 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:32:00 Loaded plugin "homebridge-harmony".
5.6.2020, 17:32:00 Loaded plugin "homebridge-rpi".
5.6.2020, 17:32:00 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:32:01 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:32:01 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:32:01 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:32:01 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:32:01 [TV] HarmonyPlatform Init
5.6.2020, 17:32:01 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:32:01 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:32:01 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:32:01 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:32:01 BoschIndego Init1
5.6.2020, 17:32:01 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
5.6.2020, 17:32:01 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:32:01 [TV] INFO - shutdown
5.6.2020, 17:33:24 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:33:24 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:33:25 Loaded plugin "homebridge-harmony".
5.6.2020, 17:33:25 Loaded plugin "homebridge-rpi".
5.6.2020, 17:33:25 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:33:25 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:33:25 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:33:25 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:33:25 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:33:25 [TV] HarmonyPlatform Init
5.6.2020, 17:33:25 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:33:25 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:33:25 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:33:25 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:33:25 BoschIndego Init1
5.6.2020, 17:33:25 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
5.6.2020, 17:33:25 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:33:25 [TV] INFO - shutdown
5.6.2020, 17:33:33 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:33:33 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:33:33 Loaded plugin "homebridge-harmony".
5.6.2020, 17:33:33 Loaded plugin "homebridge-rpi".
5.6.2020, 17:33:34 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:33:34 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:33:34 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:33:34 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:33:34 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:33:34 [TV] HarmonyPlatform Init
5.6.2020, 17:33:34 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:33:34 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:33:34 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:33:34 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:33:34 BoschIndego Init1
5.6.2020, 17:33:34 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
5.6.2020, 17:33:34 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:33:34 [TV] INFO - shutdown
5.6.2020, 17:37:42 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:37:42 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:37:42 Loaded plugin "homebridge-harmony".
5.6.2020, 17:37:42 Loaded plugin "homebridge-rpi".
5.6.2020, 17:37:42 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:37:42 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:37:42 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:37:42 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:37:42 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:37:42 [TV] HarmonyPlatform Init
5.6.2020, 17:37:42 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:37:42 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:37:42 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:37:42 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:37:42 BoschIndego Init1
5.6.2020, 17:37:42 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
5.6.2020, 17:37:42 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:37:42 [TV] INFO - shutdown
5.6.2020, 17:38:36 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:38:36 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:38:36 Loaded plugin "homebridge-harmony".
5.6.2020, 17:38:36 Loaded plugin "homebridge-rpi".
5.6.2020, 17:38:36 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:38:37 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:38:37 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:38:37 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:38:37 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:38:37 [TV] HarmonyPlatform Init
5.6.2020, 17:38:37 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:38:37 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:38:37 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:38:37 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:38:37 BoschIndego Init1
5.6.2020, 17:38:37 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
5.6.2020, 17:38:37 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:38:37 [TV] INFO - shutdown
5.6.2020, 17:40:50 connect ECONNREFUSED 127.0.0.1:51826
5.6.2020, 17:42:02 removed 28 packages and audited 233 packages in 4.878s
5.6.2020, 17:42:02 
33 packages are looking for funding
  run `npm fund` for details
5.6.2020, 17:42:02 found 0 vulnerabilities
5.6.2020, 17:42:02 Plugin "homebridge-harmony" removed.
5.6.2020, 17:42:03 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:42:03 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:42:04 Loaded plugin "homebridge-rpi".
5.6.2020, 17:42:04 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:42:04 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:42:04 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:42:04 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:42:04 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:42:04 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:42:04 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:42:04 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:42:04 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:42:04 BoschIndego Init1
5.6.2020, 17:42:04 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
5.6.2020, 17:42:04 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:42:13 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:42:13 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:42:13 Loaded plugin "homebridge-rpi".
5.6.2020, 17:42:13 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:42:13 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:42:13 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:42:13 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:42:13 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:42:13 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:42:13 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:42:13 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:42:13 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:42:13 BoschIndego Init1
5.6.2020, 17:42:13 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
5.6.2020, 17:42:13 Got SIGTERM, shutting down Bridge...
5.6.2020, 17:43:54 Loaded plugin "homebridge-boschindego".
5.6.2020, 17:43:54 Loaded plugin "homebridge-dyson-pure-cool".
5.6.2020, 17:43:54 Loaded plugin "homebridge-rpi".
5.6.2020, 17:43:54 Loaded plugin "homebridge-wakeonlan".
5.6.2020, 17:43:55 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
5.6.2020, 17:43:55 [Rasperry Pi4] homebridge-rpi v1.1.7, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.7
5.6.2020, 17:43:55 [Rasperry Pi4] warning: 12.16.2: not using recommended node v12.17.0 LTS
5.6.2020, 17:43:55 [Rasperry Pi4] warning: config.json: plugin_map: invalid key
5.6.2020, 17:43:55 The requested accessory "Boschindego" was not registered by any plugin.
5.6.2020, 17:43:55 Your config.json is requesting the accessory "Boschindego" which has not been published by any installed plugins.
5.6.2020, 17:43:55 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:43:55 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
5.6.2020, 17:43:55 BoschIndego Init1
5.6.2020, 17:43:55 Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1064:19)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:383:31)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
5.6.2020, 17:43:55 Got SIGTERM, shutting down Bridge...
```
POST LOG HERE
```

**Additional context**
I tried to install and configurate the Harmony Plugin - it didn't work so i uninstalled it. Now its not working.

**Comment by askovi** [comment]
Your problem is with the BoschIndego plugin. It doesn't seem to be registering properly. Try uninstalling it and see if it fixes your issues

**Comment by FEXtheBEST** [comment]
Its working!
Thank you very much for this fast answer!

**Comment by FEXtheBEST** [comment]
Other question: 
I got the Xiaomi Mi Robot in my Xiaomi Home App. 
I successfully added him to Hoobs / Homebridge by checking his IP and token...

I got a Roborock S5 Max aswell in my Roborock App. How can i read out the token and IP of the Roborock? Do i have to install the Roborock in my Xiaomi App?

**Comment by askovi** [comment]
The token for Xiaomi devices is a complex task at the moment to retrieve. We got a video tutorial coming up this weekend on how to do it.

**Comment by FEXtheBEST** [comment]
Hey, ty. 
Where can i find the video tutorial?

**Comment by BobbySlope** [comment]
https://youtu.be/HNgqfa-E5fA
