### ISSUE TITLE
Can't get HOOBS cluster working on new Raspberry Pi install

### ISSUE THREAD

**Issue by SlasherKG** [hoobs-org/HOOBS#686]
**Description**
Trying to set up using sudo hoobs cluster client gives this error:
(node:7563) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at Prompt.then (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/client.js:88:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.
N/A

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.
Raspberry Pi 3B running Raspbian.
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
N/A

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`
* Remove any passwords from the config file. This is public.
N/A

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by BobbySlope** [comment]
>This will be done in the next major release

**Comment by SlasherKG** [comment]
Any updates on this new version?
I was able to get it working on the older 3.1.27 version, but that one doesn't support most of the latest plugins that I'm using, so it's kind of useless.
It breaks if you try to update to a newer version as well, so that's a no go.
I really need to get this cluster set up and working with the latest version.

Thank you.

**Comment by rpolenthon** [comment]
The issue is still there. Looks like creating hoobs cluster instances is not possible anymore on Raspbian.

Hopefully, there will be a fix soon, as HOOBS users cant create instances for more than three months now :(
