### ISSUE TITLE
Bridge service cannot start

### ISSUE THREAD

**Issue by hardretro** [hoobs-org/HOOBS#696]
**Description**
Bridge service refuses to start.

**Version**
Please include the version of HOOBS you are using.
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
Unknown

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ ] No
- [ X ] Unsure

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

Nest
Nast Cam2

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "polling_seconds": 5,
        "port": 8383,
        "origin": "*",
        "home_setup_id": "X-HM://0023ISYWY5A5C",
        "autostart": 1
    },
    "client": {
        "locale": "en",
        "country_code": "CA",
        "inactive_logoff": 30,
        "default_route": "status",
        "postal_code": "M1K 1X3",
        "theme": "hoobs-light",
        "temp_units": "celsius"
    },
    "bridge": {
        "port": 51826,
        "username": "CF:9C:6E:94:F6:F9",
        "name": "Homebridge Controller",
        "pin": "031-45-154"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "googleAuth": {
                "apiKey": "*******************",
                "issueToken": "*******************",
                "cookies": "*******************"
            },
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            }
        },
        {
            "googleAuth": {
                "cookies": *******************",
                "apiKey": "*******************",
                "issueToken": "*******************"
            },
            "plugin_map": {
                "plugin_name": "homebridge-nest-cam2"
            },
            "platform": "Nest-cam",
            "ffmpegCodec": "libx264"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
6/23/2020, 11:13:36 AM - HOOBS listening on port 8383.
6/23/2020, 11:13:38 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:13:38 AM - Loaded plugin "nest".
6/23/2020, 11:13:38 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:13:38 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:13:39 AM - Got SIGTERM, shutting down Bridge...
6/23/2020, 11:20:01 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:20:01 AM - Loaded plugin "nest".
6/23/2020, 11:20:01 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:20:02 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:20:02 AM - Got SIGTERM, shutting down Bridge...
6/23/2020, 11:21:53 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:21:53 AM - Loaded plugin "nest".
6/23/2020, 11:21:53 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:21:53 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:21:53 AM - Got SIGTERM, shutting down Bridge...
6/23/2020, 11:23:38 AM - + homebridge-nest@4.4.6
added 17 packages from 13 contributors in 5.562s
6/23/2020, 11:23:38 AM - 
13 packages are looking for funding
  run `npm fund` for details
6/23/2020, 11:23:38 AM - Plugin "homebridge-nest" installed.
6/23/2020, 11:23:39 AM - Loaded plugin "homebridge-nest".
6/23/2020, 11:23:39 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:23:39 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:23:39 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:23:39 AM - Got SIGTERM, shutting down Bridge...
6/23/2020, 11:23:53 AM - Loaded plugin "homebridge-nest".
6/23/2020, 11:23:53 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:23:53 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:23:53 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:23:53 AM - Got SIGTERM, shutting down Bridge...
6/23/2020, 11:24:41 AM - Loaded plugin "homebridge-nest".
6/23/2020, 11:24:41 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:24:41 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:24:41 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:24:41 AM - Got SIGTERM, shutting down Bridge...
6/23/2020, 11:24:50 AM - Loaded plugin "homebridge-nest".
6/23/2020, 11:24:50 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:24:50 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:24:50 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:24:50 AM - Got SIGTERM, shutting down Bridge...
6/23/2020, 11:24:53 AM - [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AC01AC221802UM structureId: 36d52c71-bb9c-11e4-a599-22000a2f935d
6/23/2020, 11:24:53 AM - [Nest] initing home_away_sensor "Home Occupied": deviceId: 36d52c71-bb9c-11e4-a599-22000a2f935d structureId: 36d52c71-bb9c-11e4-a599-22000a2f935d
6/23/2020, 11:24:53 AM - [Nest] initing protect "Downstairs": deviceId: 18B4300000AD7268 structureId: 36d52c71-bb9c-11e4-a599-22000a2f935d
6/23/2020, 11:24:53 AM - [Nest] initing protect "Basement": deviceId: 18B4300000AD6090 structureId: 36d52c71-bb9c-11e4-a599-22000a2f935d
6/23/2020, 11:24:53 AM - [Nest] initing protect "Upstairs": deviceId: 18B4300000AD67DA structureId: 36d52c71-bb9c-11e4-a599-22000a2f935d
6/23/2020, 11:24:53 AM - [Nest] initing lock "Entryway Lock": deviceId: 00177A000002A71C structureId: 36d52c71-bb9c-11e4-a599-22000a2f935d
6/23/2020, 11:24:53 AM - [Nest] Initializing platform accessory "Living Room Thermostat"...
6/23/2020, 11:24:53 AM - [Nest] Initializing platform accessory "Home Occupied"...
6/23/2020, 11:24:53 AM - [Nest] Initializing platform accessory "Downstairs"...
6/23/2020, 11:24:53 AM - [Nest] Initializing platform accessory "Basement"...
6/23/2020, 11:24:53 AM - [Nest] Initializing platform accessory "Upstairs"...
6/23/2020, 11:24:53 AM - [Nest] Initializing platform accessory "Entryway Lock"...
6/23/2020, 11:28:39 AM - Loaded plugin "homebridge-nest".
6/23/2020, 11:28:39 AM - Loaded plugin "homebridge-nest-cam2".
6/23/2020, 11:28:39 AM - [Nest] Fetching Nest devices.
6/23/2020, 11:28:39 AM - TypeError: Cannot read property 'fieldTest' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam2/dist/index.js:62:76)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/23/2020, 11:28:39 AM - Got SIGTERM, shutting down Bridge...
```

**Additional context**

**Comment by hardretro** [comment]
Please close this, was resolved by removing Nest Cam2 and using Nest Cam Hoobs instead.
