### ISSUE TITLE
Bridge Stops After Install of homebridge-harmony

### ISSUE THREAD

**Issue by dben110** [hoobs-org/HOOBS#707]
**Description**
After installing this plugin via the HOOBS web UI, the Bridge service will not stay running. Bridge service stops soon after a manual restart.

**Expected behavoir**
Bridge service should stay running after installation

**Plugin name**
homebridge-harmony v1.3.11

**Please report the issue to the plugin developer**
Developer of the plugin states to contact HOOBS first.

**Version**
HOOBS Core 3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Pervious version**
DId not upgrade from a previous version

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Fedora 32

**Post your config**
* Remove any passwords from the config file. This is public.

##Replaced "home_setup_id", "postal code", "pin", "username", "blid", "robotpwd", and Simplisafe username/password.
```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0000000000000",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "00000"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "000-000-000",
        "username": "00:00:00:00:00:00"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Roomba",
            "plugin_map": {
                "plugin_name": "homebridge-roomba-stv",
                "index": 0
            },
            "name": "Woodhouse",
            "blid": "real-blid",
            "robotpwd": "robots-password",
            "ipaddress": "192.168.1.45",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "cacheTTL": 30,
            "model": "Roomba i7"
        }
    ],
    "platforms": [
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "plugin_map": {
                "plugin_name": "homebridge-simplisafe3"
            },
            "name": "Home Alarm",
            "cameras": true,
            "sensorRefresh": 10,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "auth": {
                "username": "myusername",
                "password": "password"
            },
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "debug": false
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
7/1/2020, 8:29:01 PM [Woodhouse] Running status requested
7/1/2020, 8:29:01 PM [Woodhouse] Battery status requested
7/1/2020, 8:52:14 PM [Woodhouse] Running status requested
7/1/2020, 8:52:14 PM [Woodhouse] Battery status requested
7/1/2020, 8:53:56 PM [Woodhouse] Running status requested
7/1/2020, 8:53:56 PM [Woodhouse] Battery status requested
7/1/2020, 8:54:31 PM [Woodhouse] Running status requested
7/1/2020, 8:54:31 PM [Woodhouse] Battery status requested
7/1/2020, 8:54:37 PM [Woodhouse] Running status requested
7/1/2020, 8:54:37 PM [Woodhouse] Battery status requested
7/1/2020, 8:54:54 PM [Woodhouse] Running status requested
7/1/2020, 8:54:54 PM [Woodhouse] Battery status requested
7/1/2020, 8:55:41 PM [Woodhouse] Running status requested
7/1/2020, 8:55:41 PM [Woodhouse] Battery status requested
7/1/2020, 9:03:04 PM [Woodhouse] Running status requested
7/1/2020, 9:03:04 PM [Woodhouse] Battery status requested
7/1/2020, 9:03:15 PM [Woodhouse] Running status requested
7/1/2020, 9:03:15 PM [Woodhouse] Battery status requested
7/1/2020, 9:08:17 PM [Woodhouse] Running status requested
7/1/2020, 9:08:17 PM [Woodhouse] Battery status requested
7/1/2020, 9:09:40 PM [Woodhouse] Running status requested
7/1/2020, 9:09:40 PM [Woodhouse] Battery level requested
7/1/2020, 9:09:40 PM [Woodhouse] Charging status requested
7/1/2020, 9:09:40 PM [Woodhouse] Battery status requested
7/1/2020, 9:15:16 PM 
> websocket@1.0.31 install /home/hoobs/.hoobs/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)
7/1/2020, 9:15:17 PM make: Entering directory '/home/hoobs/.hoobs/node_modules/websocket/build'
7/1/2020, 9:15:17 PM   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
7/1/2020, 9:15:19 PM   SOLINK_MODULE(target) Release/obj.target/bufferutil.node
7/1/2020, 9:15:19 PM   COPY Release/bufferutil.node
7/1/2020, 9:15:19 PM   CXX(target) Release/obj.target/validation/src/validation.o
7/1/2020, 9:15:20 PM   SOLINK_MODULE(target) Release/obj.target/validation.node
7/1/2020, 9:15:20 PM   COPY Release/validation.node
7/1/2020, 9:15:20 PM make: Leaving directory '/home/hoobs/.hoobs/node_modules/websocket/build'
7/1/2020, 9:15:20 PM + homebridge-harmony@1.3.11
added 28 packages from 32 contributors in 9.563s
7/1/2020, 9:15:20 PM 
14 packages are looking for funding
  run `npm fund` for details
7/1/2020, 9:15:20 PM Plugin "homebridge-harmony" installed.
7/1/2020, 9:15:21 PM Got SIGINT, shutting down Bridge...
7/1/2020, 9:15:25 PM Loaded plugin "homebridge-harmony".
7/1/2020, 9:15:25 PM Loaded plugin "homebridge-roomba-stv".
7/1/2020, 9:15:25 PM Loaded plugin "homebridge-simplisafe3".
7/1/2020, 9:15:25 PM [HarmonyHubWebSocket] HarmonyPlatform Init
7/1/2020, 9:15:25 PM [Woodhouse] Enabling keepAlive
7/1/2020, 9:15:25 PM [HarmonyHubWebSocket] DidFinishLaunching
7/1/2020, 9:15:25 PM [HarmonyHubWebSocket] (undefined)INFO - Loading activities...
7/1/2020, 9:15:25 PM [HarmonyHubWebSocket] INFO - starting hub discovery
7/1/2020, 9:15:25 PM Bridge is running on port 51826.
7/1/2020, 9:15:26 PM [Woodhouse] Running status requested
7/1/2020, 9:15:26 PM [Woodhouse] Battery level requested
7/1/2020, 9:15:26 PM [Woodhouse] Charging status requested
7/1/2020, 9:15:26 PM [Woodhouse] Battery status requested
7/1/2020, 9:15:28 PM [Home Alarm] Motion Sensor 'Bedroom' requires secret alerts to be enabled in SimpliSafe before you can add it to Homebridge.
7/1/2020, 9:15:28 PM [Home Alarm] Motion Sensor 'Bedroom' requires secret alerts to be enabled in SimpliSafe before you can add it to Homebridge.
7/1/2020, 9:15:31 PM [HarmonyHubWebSocket] INFO - stopping hub discovery, hubs found : undefined
7/1/2020, 9:15:31 PM [HarmonyHubWebSocket] (undefined)INFO - received discovered hubs  undefined
7/1/2020, 9:15:31 PM TypeError: Cannot read property 'length' of undefined
    at HarmonyBase.checkHubsFound (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:126:24)
    at HarmonyPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:227:16)
    at HarmonyPlatform.emit (events.js:310:20)
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyPlatform.js:168:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
7/1/2020, 9:15:31 PM Got SIGTERM, shutting down Bridge...
7/1/2020, 9:15:31 PM [HarmonyHubWebSocket] INFO - shutdown
7/1/2020, 9:16:11 PM Loaded plugin "homebridge-harmony".
7/1/2020, 9:16:12 PM Loaded plugin "homebridge-roomba-stv".
7/1/2020, 9:16:12 PM Loaded plugin "homebridge-simplisafe3".
7/1/2020, 9:16:12 PM [HarmonyHubWebSocket] HarmonyPlatform Init
7/1/2020, 9:16:12 PM [Woodhouse] Enabling keepAlive
7/1/2020, 9:16:12 PM [HarmonyHubWebSocket] DidFinishLaunching
7/1/2020, 9:16:12 PM [HarmonyHubWebSocket] (undefined)INFO - Loading activities...
7/1/2020, 9:16:12 PM [HarmonyHubWebSocket] INFO - starting hub discovery
7/1/2020, 9:16:12 PM Bridge is running on port 51826.
7/1/2020, 9:16:15 PM [Home Alarm] Motion Sensor 'Bedroom' requires secret alerts to be enabled in SimpliSafe before you can add it to Homebridge.
7/1/2020, 9:16:15 PM [Home Alarm] Motion Sensor 'Bedroom' requires secret alerts to be enabled in SimpliSafe before you can add it to Homebridge.
7/1/2020, 9:16:18 PM [HarmonyHubWebSocket] INFO - stopping hub discovery, hubs found : undefined
7/1/2020, 9:16:18 PM [HarmonyHubWebSocket] (undefined)INFO - received discovered hubs  undefined
7/1/2020, 9:16:18 PM TypeError: Cannot read property 'length' of undefined
    at HarmonyBase.checkHubsFound (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:126:24)
    at HarmonyPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:227:16)
    at HarmonyPlatform.emit (events.js:310:20)
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyPlatform.js:168:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
7/1/2020, 9:16:18 PM Got SIGTERM, shutting down Bridge...
7/1/2020, 9:16:18 PM [HarmonyHubWebSocket] INFO - shutdown
7/1/2020, 9:17:25 PM 
> bufferutil@4.0.1 install /home/hoobs/.hoobs/node_modules/bufferutil
> node-gyp-build
7/1/2020, 9:17:25 PM 
> utf-8-validate@5.0.2 install /home/hoobs/.hoobs/node_modules/utf-8-validate
> node-gyp-build
7/1/2020, 9:17:26 PM added 3 packages from 2 contributors, removed 28 packages and audited 184 packages in 3.321s
7/1/2020, 9:17:26 PM 
3 packages are looking for funding
  run `npm fund` for details
7/1/2020, 9:17:26 PM found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
7/1/2020, 9:17:26 PM Plugin "homebridge-harmony" removed.
7/1/2020, 9:17:27 PM Loaded plugin "homebridge-roomba-stv".
7/1/2020, 9:17:27 PM Loaded plugin "homebridge-simplisafe3".
7/1/2020, 9:17:27 PM [Woodhouse] Enabling keepAlive
7/1/2020, 9:17:27 PM Bridge is running on port 51826.
7/1/2020, 9:17:30 PM [Home Alarm] Motion Sensor 'Bedroom' requires secret alerts to be enabled in SimpliSafe before you can add it to Homebridge.
7/1/2020, 9:17:30 PM [Home Alarm] Motion Sensor 'Bedroom' requires secret alerts to be enabled in SimpliSafe before you can add it to Homebridge.
7/1/2020, 9:24:14 PM [Woodhouse] Running status requested
7/1/2020, 9:24:14 PM [Woodhouse] Battery level requested
7/1/2020, 9:24:14 PM [Woodhouse] Charging status requested
7/1/2020, 9:24:14 PM [Woodhouse] Battery status requested```

**Additional context**
Add any other context about the problem here.

**Comment by BobbySlope** [comment]
@askovi may you can check that?
