### ISSUE TITLE
Debug Mode?

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#709]
Need to enable the debug mode.

hoobs -d / sudo hoobs -d 
stop service before does also do nothing...

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 80
}
/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs bridge -u /root/.hoobs/etc -p /root/.hoobs/node_modules -r -d
[HOOBS] Stopping server.

And I need access to the debug file. I dont know where its located.

**Comment by askovi** [comment]
In order to launch HOOBS in debug mode, you have to stop the HOOBS service first. Run the following via ssh:

`sudo hoobs service stop`

then

`hoobs -D`

**Comment by Christian-CFP** [comment]
Got it but I have to run the commands in terminal ssh connection. Inside HOOBS terminal, HOOBS stop working.

**Comment by askovi** [comment]
Correct. The HOOBS UI terminal cannot run without the HOOBS service running.

**Comment by Christian-CFP** [comment]
Maybe I missed this info on your help site or it is not mentioned?

**Comment by askovi** [comment]
Added this information to the documentation notes here: https://support.hoobs.org/docs/5e764e72e87d1e02b6c19d4c
