### ISSUE TITLE
Service does not start after installing Pioneer-AVR Plugin

### ISSUE THREAD

**Issue by Kinzal16** [hoobs-org/HOOBS#714]
**Plugin name**
homebridge-pioneer-avr 
https://github.com/kazcangi/homebridge-pioneer-avr

**Please report the issue to the plugin developer**
Habe ich getan

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
No. Freshly installed

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
"server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://00xxxxxY9xxx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "xx",
        "postal_code": "xxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": xxxxx,
        "pin": "xxx-xxx-xxx",
        "username": "XX:3A:XX:8B:3A:XX"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "pioneerAvrAccessory",
            "model": "SC-2023",
            "name": "My Pioneer AVR",
            "description": "AV Receiver",
            "host": "192.168.191.15",
            "port": 23,
            "plugin_map": {
                "plugin_name": "homebridge-pioneer-avr",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "HubHarmony",
            "hubIP": "192.168.191.14",
            "hubName": "Hub Wohnzimmer",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": false,
            "TVAccessory": false,
            "configureAccesscontrol": false,
            "playPauseBehavior": false,
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": false,
            "linkVolumeControlToTV": false,
            "switchAccessories": true,
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "publishDevicesAsIndividualAccessories": false,
            "publishSequencesAsIndividualAccessories": false,
            "publishHomeControlsAsIndividualAccessories": false,
            "showCommandsAtStartup": false
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
7.7.2020, 18:50:15 (node:1388) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
7.7.2020, 18:50:15 at PioneerAvr.sendCommand (/home/hoobs/.hoobs/node_modules/homebridge-pioneer-avr/pioneer-avr.js:265:5)
7.7.2020, 18:50:15 at processTicksAndRejections (internal/process/task_queues.js:97:5)
7.7.2020, 18:50:15 at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
7.7.2020, 18:50:15 at Function.module.exports.loopWhile (/home/hoobs/.hoobs/node_modules/deasync/index.js:70:11)
7.7.2020, 18:50:15 at Function.sleep (/home/hoobs/.hoobs/node_modules/deasync/index.js:41:18)
7.7.2020, 18:50:15 at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-pioneer-avr/telnet-avr.js:34:25)
7.7.2020, 18:50:15 at Socket.emit (events.js:310:20)
7.7.2020, 18:50:15 at TCP.<anonymous> (net.js:672:12)
7.7.2020, 18:50:15 at Function.module.exports.loopWhile (/home/hoobs/.hoobs/node_modules/deasync/index.js:71:23)
7.7.2020, 18:50:15 at Function.sleep (/home/hoobs/.hoobs/node_modules/deasync/index.js:41:18)
7.7.2020, 18:50:15 at pioneerAvrAccessory.getServices (/home/hoobs/.hoobs/node_modules/homebridge-pioneer-avr/index.js:317:28)
7.7.2020, 18:50:15 at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:375:44)
7.7.2020, 18:50:15 at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
7.7.2020, 18:50:15 at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
7.7.2020, 18:50:15 at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
7.7.2020, 18:50:15 at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
7.7.2020, 18:50:15 at Module._compile (internal/modules/cjs/loader.js:1133:30)
7.7.2020, 18:50:15 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
7.7.2020, 18:50:15 at Module.load (internal/modules/cjs/loader.js:977:32)
7.7.2020, 18:50:15 at Function.Module._load (internal/modules/cjs/loader.js:877:14)
7.7.2020, 18:50:15 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
7.7.2020, 18:50:15 at internal/main/run_main_module.js:18:47
7.7.2020, 18:50:15 (node:1388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 34)
7.7.2020, 18:50:15 [My Pioneer AVR] Error: connect ECONNREFUSED 192.168.191.15:23
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
    at Function.module.exports.loopWhile (/home/hoobs/.hoobs/node_modules/deasync/index.js:71:23)
    at Function.sleep (/home/hoobs/.hoobs/node_modules/deasync/index.js:41:18)
    at pioneerAvrAccessory.getServices (/home/hoobs/.hoobs/node_modules/homebridge-pioneer-avr/index.js:317:28)
    at Server.createAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:375:44)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:266:40)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.191.15',
  port: 23
}
```

**Comment by askovi** [comment]
This is a plugin / device issue. See here: https://github.com/kazcangi/homebridge-pioneer-avr/issues/10

**Comment by Kinzal16** [comment]
How can I fix it?

**Comment by askovi** [comment]
According to one of the comments in the issue above:

> The main error is connection refused by your AVR. The telnet server of the AVR accept only one connection at a time. If something went wrong with it (like a older connection), the port is blocked.

The only way to recover it is to power cycle the AVR by unplug the power cord, wait 10 seconds, then plug it back.

AVControl5 app use port 8102. If your AVR have the port 23 opened, you should use it. If the port 23 is down, you have to use 8102.

**Comment by Kinzal16** [comment]
No I get this Error:

```
7.7.2020, 22:59:31 Loaded plugin "homebridge-pioneer-avr".
7.7.2020, 22:59:31 [Pioneer SC-2022] Discovering inputs
7.7.2020, 22:59:34 Error: async hook stack has become corrupted (actual: 33, expected: 26)
```
