### ISSUE TITLE
Bridge won't start after power outage.

### ISSUE THREAD

**Issue by jjdawgs84** [hoobs-org/HOOBS#723]
**Description**
Power went out, now Hoobs says "Bridge service not running." Tried starting the bridge manually, it immediately stops. Also have Pi-Hole running on the Raspberry Pi 4 (not sure if that makes a difference).

**Version**
HOOBS 3.2.6
Node 12.16.3

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ X] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
GSH
Nest
Dafang
Neato
Samsung Tizen
Tplink Smarthome
Nest Cam2

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 480,
        "home_setup_id": "X-HM://0023ISYWYDG3F",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "45828"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "5D:A3:6D:B7:A5:D2"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "google-home",
            "plugin_map": {
                "plugin_name": "google-home"
            },
            "name": "Google Home",
            "debug": false,
            ""
        },
        {
            "platform": "NeatoVacuumRobot",
            "plugin_map": {
                "plugin_name": "homebridge-neato"
            },
            "email": "jjcollins10@icloud.com",
            "password": ""
        },
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "SamsungTizen",
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Living Room TV",
                    "ip": "192.168.86.33",
                    "mac": "b8:bc:5b:58:b8:1d"
                }
            ]
        },
        {
            "platform": "Nest",
            "googleAuth": {
                "issueToken": "https://accounts.google.com/o/oauth2/iframerpc",
                "cookies": "",
                "apiKey": ""
            },
            "plugin_map": {
                "plugin_name": "nest"
            }
        },
        {
            "platform": "Dafang",
            "plugin_map": {
                "plugin_name": "homebridge-dafang"
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
7/14/2020, 12:20:51 PM HOOBS listening on port 8080.
7/14/2020, 12:23:00 PM Loaded plugin "homebridge-dafang".
7/14/2020, 12:23:00 PM Loaded plugin "homebridge-neato".
7/14/2020, 12:23:00 PM Loaded plugin "homebridge-nest-cam2".
7/14/2020, 12:23:01 PM Loaded plugin "homebridge-samsung-tizen".
7/14/2020, 12:23:01 PM Loaded plugin "homebridge-tplink-smarthome".
7/14/2020, 12:23:02 PM Loaded plugin "google-home".
7/14/2020, 12:23:02 PM Loaded plugin "nest".
7/14/2020, 12:23:02 PM [NeatoVacuumRobot] Refresh is set to: auto
7/14/2020, 12:23:02 PM [TplinkSmarthome] homebridge-tplink-smarthome v4.0.1, node v12.16.3, homebridge v3.2.6
7/14/2020, 12:23:02 PM [Nest] Fetching Nest devices.
7/14/2020, 12:23:02 PM Error: Configuration Not Found. No Cameras Found
    at Dafang.accessories (/home/hoobs/.hoobs/node_modules/homebridge-dafang/src/dafang.js:128:13)
    at Server.loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:357:18)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:286:26)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
7/14/2020, 12:23:04 PM Got SIGTERM, shutting down Bridge...
7/14/2020, 12:23:04 PM [Google Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
7/14/2020, 12:23:04 PM [Google Home] Devices Not Ready
7/14/2020, 12:23:04 PM (node:866) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requestId' of undefined
7/14/2020, 12:23:04 PM at Plugin.deviceNotReady (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:117:29)
7/14/2020, 12:23:04 PM at Plugin.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:38:33)
7/14/2020, 12:23:04 PM at Generator.next (<anonymous>)
7/14/2020, 12:23:04 PM at /home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:7:71
7/14/2020, 12:23:04 PM at new Promise (<anonymous>)
7/14/2020, 12:23:04 PM at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:3:12)
7/14/2020, 12:23:04 PM at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:28:36)
7/14/2020, 12:23:04 PM at WebSocket.emit (events.js:310:20)
7/14/2020, 12:23:04 PM at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/@hoobs/ws-connect/dist/index.js:66:22)
7/14/2020, 12:23:04 PM at WebSocket.emit (events.js:310:20)
7/14/2020, 12:23:04 PM at Receiver.receiverOnMessage (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/websocket.js:800:20)
7/14/2020, 12:23:04 PM at Receiver.emit (events.js:310:20)
7/14/2020, 12:23:04 PM at Receiver.dataMessage (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:422:14)
7/14/2020, 12:23:04 PM at Receiver.getData (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:352:17)
7/14/2020, 12:23:04 PM at Receiver.startLoop (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:138:22)
7/14/2020, 12:23:04 PM at Receiver._write (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:74:10)
7/14/2020, 12:23:04 PM at doWrite (_stream_writable.js:403:12)
7/14/2020, 12:23:04 PM at writeOrBuffer (_stream_writable.js:387:5)
7/14/2020, 12:23:04 PM at Receiver.Writable.write (_stream_writable.js:318:11)
7/14/2020, 12:23:04 PM at TLSSocket.socketOnData (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/websocket.js:875:35)
7/14/2020, 12:23:04 PM at TLSSocket.emit (events.js:310:20)
7/14/2020, 12:23:04 PM at addChunk (_stream_readable.js:286:12)
7/14/2020, 12:23:04 PM (node:866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
7/14/2020, 12:23:04 PM (node:866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
7/14/2020, 12:23:06 PM [NeatoVacuumRobot] Found robot #1 named "Rosie" with serial "GPC45418-XXXXXXXXXXXX"
7/14/2020, 12:23:06 PM [NeatoVacuumRobot] Added cleaning device named: Rosie
7/14/2020, 12:23:06 PM [NeatoVacuumRobot] Initializing platform accessory "Rosie"...
7/14/2020, 12:29:04 PM Loaded plugin "homebridge-dafang".
7/14/2020, 12:29:04 PM Loaded plugin "homebridge-neato".
7/14/2020, 12:29:04 PM Loaded plugin "homebridge-nest-cam2".
7/14/2020, 12:29:05 PM Loaded plugin "homebridge-samsung-tizen".
7/14/2020, 12:29:05 PM Loaded plugin "homebridge-tplink-smarthome".
7/14/2020, 12:29:05 PM Loaded plugin "google-home".
7/14/2020, 12:29:05 PM Loaded plugin "nest".
7/14/2020, 12:29:05 PM [NeatoVacuumRobot] Refresh is set to: auto
7/14/2020, 12:29:05 PM [TplinkSmarthome] homebridge-tplink-smarthome v4.0.1, node v12.16.3, homebridge v3.2.6
7/14/2020, 12:29:05 PM [Nest] Fetching Nest devices.
7/14/2020, 12:29:05 PM Error: Configuration Not Found. No Cameras Found
    at Dafang.accessories (/home/hoobs/.hoobs/node_modules/homebridge-dafang/src/dafang.js:128:13)
    at Server.loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:357:18)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:286:26)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
7/14/2020, 12:29:06 PM Got SIGTERM, shutting down Bridge...
7/14/2020, 12:29:07 PM [Google Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
7/14/2020, 12:29:07 PM [Google Home] Devices Not Ready
7/14/2020, 12:29:07 PM (node:1412) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requestId' of undefined
7/14/2020, 12:29:07 PM at Plugin.deviceNotReady (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:117:29)
7/14/2020, 12:29:07 PM at Plugin.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:38:33)
7/14/2020, 12:29:07 PM at Generator.next (<anonymous>)
7/14/2020, 12:29:07 PM at /home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:7:71
7/14/2020, 12:29:07 PM at new Promise (<anonymous>)
7/14/2020, 12:29:07 PM at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:3:12)
7/14/2020, 12:29:07 PM at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:28:36)
7/14/2020, 12:29:07 PM at WebSocket.emit (events.js:310:20)
7/14/2020, 12:29:07 PM at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/@hoobs/ws-connect/dist/index.js:66:22)
7/14/2020, 12:29:07 PM at WebSocket.emit (events.js:310:20)
7/14/2020, 12:29:07 PM at Receiver.receiverOnMessage (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/websocket.js:800:20)
7/14/2020, 12:29:07 PM at Receiver.emit (events.js:310:20)
7/14/2020, 12:29:07 PM at Receiver.dataMessage (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:422:14)
7/14/2020, 12:29:07 PM at Receiver.getData (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:352:17)
7/14/2020, 12:29:07 PM at Receiver.startLoop (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:138:22)
7/14/2020, 12:29:07 PM at Receiver._write (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:74:10)
7/14/2020, 12:29:07 PM at doWrite (_stream_writable.js:403:12)
7/14/2020, 12:29:07 PM at writeOrBuffer (_stream_writable.js:387:5)
7/14/2020, 12:29:07 PM at Receiver.Writable.write (_stream_writable.js:318:11)
7/14/2020, 12:29:07 PM at TLSSocket.socketOnData (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/websocket.js:875:35)
7/14/2020, 12:29:07 PM at TLSSocket.emit (events.js:310:20)
7/14/2020, 12:29:07 PM at addChunk (_stream_readable.js:286:12)
7/14/2020, 12:29:07 PM (node:1412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
7/14/2020, 12:29:07 PM (node:1412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
7/14/2020, 12:29:09 PM [NeatoVacuumRobot] Found robot #1 named "Rosie" with serial "GPC45418-XXXXXXXXXXXX"
7/14/2020, 12:29:09 PM [NeatoVacuumRobot] Added cleaning device named: Rosie
7/14/2020, 12:29:09 PM [NeatoVacuumRobot] Initializing platform accessory "Rosie"...
```

**Additional context**

**Comment by askovi** [comment]
I edited out sensitive information from your post. Please remove passwords and access tokens when posting your config publicly. 

Regarding your issue, it seems like you dafang plugin is missing its configuration. Either configure it or uninstall the plugin if you’re not using it.

**Comment by jjdawgs84** [comment]
> Regarding your issue, it seems like you dafang plugin is missing its configuration. Either configure it or uninstall the plugin if you’re not using it.


This was it. Thank you!!!

**Comment by askovi** [comment]
Glad you got it working!
