### ISSUE TITLE
HOOBS service will not start, help reading logs

### ISSUE THREAD

**Issue by koweye** [hoobs-org/HOOBS#729]
**Description**
ALL my camera's in homekit refreshes fine on the main homekit screen but when i click to view a live feed, it times out, and i get camera not responding error. i read that people removed it from homekit and readded it and it worked. these are wyze cameras using rtsp, so i removed the camera ffmpeg plug and restarted. then HOOBS service fails to start. i added the camera ffmpeg plugin back and HOOBS service still fails. whats going on?!

**Expected behavoir**
HOOBS service starting

**Plugin name**
not sure, but the only plugin i removed and added back was camera ffmpeg but not sure if that is the cause

**Please report the issue to the plugin developer**
i would if that is the problem

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
7/20/2020, 8:33:02 AM Loaded plugin "homebridge-blinkcameras".
7/20/2020, 8:33:02 AM Loaded plugin "homebridge-camera-ffmpeg".
7/20/2020, 8:33:02 AM Loaded plugin "homebridge-harmony".
7/20/2020, 8:33:02 AM Loaded plugin "homebridge-lifx-lan".
7/20/2020, 8:33:02 AM Loaded plugin "homebridge-nest".
7/20/2020, 8:33:03 AM Loaded plugin "homebridge-nest-cam".
7/20/2020, 8:33:03 AM Loaded plugin "homebridge-ring".
7/20/2020, 8:33:04 AM Loaded plugin "homebridge-smartthings-v2".
7/20/2020, 8:33:04 AM Loaded plugin "homebridge-wyze-connected-home".
7/20/2020, 8:33:04 AM Loaded plugin "homebridge-zp".
7/20/2020, 8:33:04 AM [Nest Protect] Fetching Nest devices.
7/20/2020, 8:33:04 AM INFO: Homebridge Version: 2.5
7/20/2020, 8:33:04 AM INFO: SmartThings-v2 Plugin Version: 2.3.4
7/20/2020, 8:33:04 AM INFO: Checking Package Version for Updates...
7/20/2020, 8:33:04 AM [Sonos] homebridge-zp v1.0.37, node 12.16.3, homebridge v3.2.6, homebridge-lib v4.7.12
7/20/2020, 8:33:04 AM [Sonos] warning: 12.16.3: not using recommended node v12.18.2 LTS
7/20/2020, 8:33:04 AM [Sonos] warning: config.json: plugin_map: invalid key
7/20/2020, 8:33:04 AM [My Harmony Hub] HarmonyPlatform Init
7/20/2020, 8:33:04 AM [My Blink System] Init
7/20/2020, 8:33:04 AM Load homebridge-zp.ZPS1
7/20/2020, 8:33:04 AM [homebridge-zp.ZPS1] homebridge-zp v1.0.37, node 12.16.3, homebridge v3.2.6, homebridge-lib v4.7.12
7/20/2020, 8:33:04 AM [homebridge-zp.ZPS1] warning: 12.16.3: not using recommended node v12.18.2 LTS
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory e18423f1-8a95-460f-8b13-4f5313c7286e Ring Alarm
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory e56752ae-c7a2-4165-9fb8-6672eb00ec57 Bedroom (Middle) Sensor 35929
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory c1c117cf-aec5-4bb4-89eb-26b20b5bee2a Front Door Sensor 60377
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory 10a97f3e-4a07-45cb-82b5-db0b4ca00618 Bedroom (Front) Sensor 39675
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory c38e1228-eae1-488d-94e8-0a5d584554c3 Garage Entry Door Sensor 18306
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory 47a28881-0329-46d2-b4f6-ea9b170c4cae Living Room Motion Sensor 34637
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory 8a082460-aefa-4b43-b947-1b7d5bdeed98 Family Room Sliding Door 07623
7/20/2020, 8:33:04 AM [Ring] Configuring cached accessory 332f5d76-75cb-4ab7-933b-b1b7b6a819b2 Bedroom (Master) Sensor 08891
7/20/2020, 8:33:04 AM [Camera ffmpeg] Configuring accessory Front Door
7/20/2020, 8:33:04 AM [Nest-cam] Configuring accessory Front Door
7/20/2020, 8:33:04 AM [Camera ffmpeg] Configuring accessory Hoku Cam
7/20/2020, 8:33:04 AM [My Blink System] [Server Room System] Registering
7/20/2020, 8:33:04 AM [My Blink System] [Server Room System] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [Server Room System] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [Don't Blink System] Registering
7/20/2020, 8:33:04 AM [My Blink System] [Don't Blink System] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [Don't Blink System] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [3 External - Right Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [3 External - Right Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [3 External - Right Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [4 External - Left and Patio Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [4 External - Left and Patio Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [4 External - Left and Patio Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [5 Dining Room / Kitchen Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [5 Dining Room / Kitchen Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [5 Dining Room / Kitchen Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [6 TV Room / Dining Room Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [6 TV Room / Dining Room Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [6 TV Room / Dining Room Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [7 Garage Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [7 Garage Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [7 Garage Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [8 Hoku Cam Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [8 Hoku Cam Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [8 Hoku Cam Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [1 External - Front Door Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [1 External - Front Door Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [1 External - Front Door Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM [My Blink System] [2 External - Side Gate Camera] Registering
7/20/2020, 8:33:04 AM [My Blink System] [2 External - Side Gate Camera] Initialized
7/20/2020, 8:33:04 AM [My Blink System] [2 External - Side Gate Camera] Loaded cached accessory
7/20/2020, 8:33:04 AM INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
7/20/2020, 8:33:04 AM GOOD: Refreshing All Device Data | Source: (First Launch)
7/20/2020, 8:33:04 AM [Sonos] restored 1 accessories from cache
7/20/2020, 8:33:04 AM [My Harmony Hub] DidFinishLaunching
7/20/2020, 8:33:04 AM [My Harmony Hub] (My Harmony Hub)INFO - Loading activities...
7/20/2020, 8:33:04 AM [My Blink System] Finished Launching
7/20/2020, 8:33:04 AM [My Blink System] Discovering Cameras
7/20/2020, 8:33:04 AM [My Blink System] Authenticating with Blink API as i*******w@gmail.com
7/20/2020, 8:33:04 AM Making new blink client
7/20/2020, 8:33:04 AM LIFX Client UDP error
7/20/2020, 8:33:04 AM Trace: Error: bind EADDRINUSE 0.0.0.0:56700
7/20/2020, 8:33:04 AM at dgram.js:339:20
7/20/2020, 8:33:04 AM at processTicksAndRejections (internal/process/task_queues.js:85:21) {
7/20/2020, 8:33:04 AM errno: 'EADDRINUSE',
7/20/2020, 8:33:04 AM code: 'EADDRINUSE',
7/20/2020, 8:33:04 AM syscall: 'bind',
7/20/2020, 8:33:04 AM address: '0.0.0.0',
7/20/2020, 8:33:04 AM port: 56700
7/20/2020, 8:33:04 AM }
7/20/2020, 8:33:04 AM at Client.<anonymous> (/home/hoobs/.hoobs/node_modules/node-lifx/lib/lifx/client.js:147:13)
7/20/2020, 8:33:04 AM at Socket.emit (events.js:322:22)
7/20/2020, 8:33:04 AM at dgram.js:341:14
7/20/2020, 8:33:04 AM at processTicksAndRejections (internal/process/task_queues.js:85:21)
7/20/2020, 8:33:05 AM [Sonos] listening on http://10.10.10.4:37197/notify
7/20/2020, 8:33:05 AM [Sonos] RINCON_949F3E0890DA01400 [Family Room]: associated S1 zone player
7/20/2020, 8:33:05 AM [Sonos] found 1 S1 zone players in 1 zones
7/20/2020, 8:33:05 AM [Sonos] └─ Family Room
7/20/2020, 8:33:05 AM [Sonos]    └─ RINCON_949F3E0890DA01400 [Family Room]: Sonos Play:1 (S12) (master)
7/20/2020, 8:33:05 AM NOTICE: Temperature Unit is Now: (F)
7/20/2020, 8:33:05 AM NOTICE: Updating Global Values | HubIP: 10.10.10.199 | UseLocal: false
7/20/2020, 8:33:05 AM WARN: Devices to Remove: (0) []
7/20/2020, 8:33:05 AM INFO: Devices to Update: (3)
7/20/2020, 8:33:05 AM GOOD: Devices to Create: (0) []
7/20/2020, 8:33:05 AM ALERT: Total Initialization Time: (1 seconds)
7/20/2020, 8:33:05 AM NOTICE: Unknown Capabilities: ["Momentary","Relay Switch"]
7/20/2020, 8:33:05 AM INFO: SmartThings DeviceCache Size: (3)
7/20/2020, 8:33:05 AM INFO: WebServer Initiated...
7/20/2020, 8:33:05 AM INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
7/20/2020, 8:33:05 AM INFO: Direct Connect Active | Listening at 10.10.10.4:8001
7/20/2020, 8:33:06 AM [My Harmony Hub] (My Harmony Hub)INFO - configuring Main TV Service
7/20/2020, 8:33:06 AM [My Harmony Hub] (My Harmony Hub)INFO - Configuring Main Activity Watch TV
7/20/2020, 8:33:06 AM [My Blink System] Found network Server Room
7/20/2020, 8:33:06 AM [My Blink System] Found network Don't Blink
7/20/2020, 8:33:06 AM [My Blink System] Found camera 3 External - Right
7/20/2020, 8:33:06 AM [My Blink System] Found camera 4 External - Left and Patio
7/20/2020, 8:33:06 AM [My Blink System] Found camera 5 Dining Room / Kitchen
7/20/2020, 8:33:06 AM [My Blink System] Found camera 6 TV Room / Dining Room
7/20/2020, 8:33:06 AM [My Blink System] Found camera 7 Garage
7/20/2020, 8:33:06 AM [My Blink System] Found camera 8 Hoku Cam
7/20/2020, 8:33:06 AM [My Blink System] Found camera 1 External - Front Door
7/20/2020, 8:33:06 AM [My Blink System] Found camera 2 External - Side Gate
7/20/2020, 8:33:06 AM INFO: INFO: Your plugin version is up-to-date
7/20/2020, 8:33:06 AM NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.4
7/20/2020, 8:33:06 AM INFO: SmartThings-v2 Hub Communication Established
7/20/2020, 8:33:07 AM [Ring] Creating location socket.io connection
7/20/2020, 8:33:08 AM [Ring] Ring connected to socket.io server
7/20/2020, 8:33:09 AM [Ring] Configuring 0 cameras and 15 devices for location "My Ring Home" - locationId: 87zdjn-dq8i-0
7/20/2020, 8:33:09 AM [Ring] Hidden accessory bfa528c8-35a9-4d80-94e2-118694af6427 adapter.zigbee ZigBee onboard adapter
7/20/2020, 8:33:09 AM [Ring] Hidden accessory eb0edcd4-11ce-483f-b242-886ae7418f76 access-code.vault Code Vault
7/20/2020, 8:33:09 AM [Ring] Hidden accessory da5785c8-0914-4fba-9185-740c5b5bdc36 access-code Security Access Code
7/20/2020, 8:33:09 AM [Ring] Hidden accessory 2c369f3b-ae30-468b-b9b3-2d2d8be3a282 hub.redsky Base Station
7/20/2020, 8:33:09 AM [Ring] Hidden accessory ad5ee297-ecd1-4d23-8c56-d84260d7ce29 adapter.zwave Z-Wave Adapter
7/20/2020, 8:33:09 AM [Ring] Hidden accessory eb5453d1-01f5-4a8a-8993-caf7ba57a30f range-extender.zwave Ring Z-Wave Extender 50821
7/20/2020, 8:33:09 AM [Ring] Hidden accessory 0d071892-4bfb-495b-bc2d-71ded6297f60 security-keypad Garage Entry Keypad
7/20/2020, 8:33:10 AM [Nest Protect] initing home_away_sensor "Home Occupied": deviceId: ed869260-ace1-11ea-b364-12a67530637f structureId: ed869260-ace1-11ea-b364-12a67530637f
7/20/2020, 8:33:10 AM [Nest Protect] initing protect "Hallway": deviceId: 18B43000003548BF structureId: ed869260-ace1-11ea-b364-12a67530637f
7/20/2020, 8:33:10 AM [Nest Protect] Initializing platform accessory "Home Occupied"...
7/20/2020, 8:33:10 AM [Nest Protect] Initializing platform accessory "Hallway"...
7/20/2020, 8:33:10 AM Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:86:30)
    at HAPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:188:31)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:560:27)
    at Server.publish (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:134:21)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:369:22
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:15:25
    at NestPlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-nest/index.js:123:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
7/20/2020, 8:33:10 AM ERROR: uncaughtException: listen EADDRINUSE: address already in use :::51826
7/20/2020, 8:33:10 AM Error: listen EADDRINUSE: address already in use :::51826
7/20/2020, 8:33:10 AM at Server.setupListenHandle [as _listen2] (net.js:1313:16)
7/20/2020, 8:33:10 AM at listenInCluster (net.js:1361:12)
7/20/2020, 8:33:10 AM at Server.listen (net.js:1449:7)
7/20/2020, 8:33:10 AM at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:86:30)
7/20/2020, 8:33:10 AM at HAPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:188:31)
7/20/2020, 8:33:10 AM at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:560:27)
7/20/2020, 8:33:10 AM at Server.publish (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:134:21)
7/20/2020, 8:33:10 AM at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:369:22
7/20/2020, 8:33:10 AM at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:15:25
7/20/2020, 8:33:10 AM at NestPlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-nest/index.js:123:17)
7/20/2020, 8:33:10 AM at processTicksAndRejections (internal/process/task_queues.js:97:5)
7/20/2020, 8:33:10 AM Got SIGTERM, shutting down Bridge...
7/20/2020, 8:33:10 AM [My Harmony Hub] INFO - shutdown
7/20/2020, 8:33:10 AM [Sonos] closed http://10.10.10.4:37197/notify
7/20/2020, 8:33:13 AM [Sonos] goodbye
```

**Additional context**

**Comment by askovi** [comment]
You have a bunch of 'port already in use error'. Start by rebooting HOOBS from the top right menu and see if they go away. If that doesn't solve it, go in settings -> apple home and change port from 51826 to 51827 and save changes.

**Comment by koweye** [comment]
oh, that did it, reboot...  duh, i should have just tried that! thanks!!!!
