### ISSUE TITLE
Delay Switch Plugin Error

### ISSUE THREAD

**Issue by bikerboy-86** [hoobs-org/HOOBS#748]
Hello everybody,
I updated my Delay Switch plugin and now it no longer works.
Specifically, when I create a delay switch, the Hoobs service stops working.
If I delete it then the Hoobs service runs again.
Simply put, I can't create a delay switch in the delay switch plug-in right now.

**Comment by askovi** [comment]
Please follow the bug report template.

**Comment by bikerboy-86** [comment]
Sorry I'm new here where can I find the bug report template.

**Comment by askovi** [comment]
When you create an issue here it prompts you to select an issue type. Choose Bug report and fill in the required information.

**Comment by bikerboy-86** [comment]
[Homebridge] [2020-8-11 17:24:05] Got SIGINT, shutting down service...
[Homebridge] [2020-8-11 17:24:07] Loaded config.json with 1 accessories and 1 platforms.
[Homebridge] [2020-8-11 17:24:07] Loaded plugin: "homebridge-delay-switch"
[Homebridge] [2020-8-11 17:24:07] Registering accessory "homebridge-delay-switch.DelaySwitch"
[Homebridge] [2020-8-11 17:24:07] Loaded plugin: "shelly"
[Homebridge] [2020-8-11 17:24:08] Registering platform "homebridge-shelly.Shelly"
[Homebridge] [2020-8-11 17:24:08] Loading 1 platforms...
[Homebridge] [2020-8-11 17:24:08] [Shelly] Initializing Shelly platform...
[Homebridge] [2020-8-11 17:24:08] Loading 1 accessories...
[Homebridge] [2020-8-11 17:24:08] [Test] Initializing DelaySwitch accessory...
[Homebridge] [2020-8-11 17:24:08] TypeError: Cannot read property 'hap' of undefined
    at new delaySwitch (/home/hoobs/.hoobs/node_modules/homebridge-delay-switch/index.js:13:23)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:269:35)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[Homebridge] [2020-8-11 17:24:08] Got SIGTERM, shutting down service...

**Comment by bikerboy-86** [comment]
Installed Version 2.2.4 published 8/10/2020 • 23 hours ago

**Comment by bikerboy-86** [comment]
After Update from Hoobs it is now running
