### ISSUE TITLE
Hoobs keeps crushing. Which plugin causes it?

### ISSUE THREAD

**Issue by grabarz1986** [hoobs-org/HOOBS#781]
Hi. Recently Hoobs get very crushy. Could you please based on logs find the suspect?

28.08.2020, 11:15:14 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
28.08.2020, 11:15:14 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
28.08.2020, 11:15:14 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
28.08.2020, 11:15:14 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
28.08.2020, 11:15:14 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
28.08.2020, 11:15:14 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

30.08.2020, 20:34:23 [Vacuum Cleaner] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
30.08.2020, 20:34:28 [Air Quality] AirNow air quality AQI is: 24
30.08.2020, 20:34:28 [Vacuum Cleaner] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
30.08.2020, 20:34:28 [Vacuum Cleaner] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
30.08.2020, 20:34:41 [WeatherPlus] Error retrieving weather report and forecast for DarkSky
30.08.2020, 20:34:41 [WeatherPlus] Error Message: Forecast cannot be retrieved. ERROR: Error: getaddrinfo EAI_AGAIN api.darksky.net
30.08.2020, 20:34:55 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
30.08.2020, 20:34:55 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
30.08.2020, 20:34:55 Got SIGTERM, shutting down Bridge...
30.08.2020, 20:34:57 [Broadlink RM] [31m[ERROR] [0m Broadlink RM device at 192.168.5.220 (c8::f:7::42::d:a::5a::a:8) is no longer reachable after three attempts.
30.08.2020, 20:34:57 [Broadlink RM] [31m[ERROR] [0m Broadlink RM device at 192.168.5.234 (c8::f:7::42::2:1::b2::3:7) is no longer reachable after three attempts.

30.08.2020, 20:39:48 [Broadlink RM] [31m[ERROR] [0m Broadlink RM device at 192.168.5.234 (c8::f:7::42::2:1::b2::3:7) is no longer reachable after three attempts.
30.08.2020, 20:39:48 [Broadlink RM] [31m[ERROR] [0m Broadlink RM device at 192.168.5.220 (c8::f:7::42::d:a::5a::a:8) is no longer reachable after three attempts.
30.08.2020, 20:39:50 Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:679:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at afterDns (dgram.js:625:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
30.08.2020, 20:39:50 Got SIGTERM, shutting down Bridge...

**Comment by BobbySlope** [comment]
the weather plus plugin is causing the crash, please try to uninstall it and see it the hoobs service is running stable again

**Comment by BobbySlope** [comment]
use openwether instead of darksky following this:

https://plugins.hoobs.org/plugin/homebridge-weather-plus
