### ISSUE TITLE
Hoobs won't start

### ISSUE THREAD

**Issue by TheBassfly** [hoobs-org/HOOBS#782]
Hello

Today I tried to update the node to the recent LTS version.

After it, hoobs doesn't start anymore.

In Terminal I got this Error:

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.

What is wrong?

**Comment by leovj** [comment]
I have the same problem!
IMac Mid 2010 High Sierra
`Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
`

**Comment by leovj** [comment]
I find the solution:

Run to as a root
`sudo hoobs`

**Comment by BobbySlope** [comment]
thats it
