### ISSUE TITLE
Hoobs bridge is in restart-loop

### ISSUE THREAD

**Issue by stz74** [hoobs-org/HOOBS#783]
**Description**
Hoobs keeps restarting with error message in console log.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] HOOBS to Download

**List your plugins**
homebridge-eveatmo
homebridge-zp

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

```
{
    "server": {
        "polling_seconds": 5,
        "port": 80,
        "home_setup_id": "X-HM://0023ISYWY98H1",
        "origin": "*",
        "autostart": 0
    },
    "client": {
        "country_code": "AT",
        "latitude": "1",
        "temp_units": "celsius",
        "locale": "en",
        "longitude": "1",
        "postal_code": "1020",
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light"
    },
    "bridge": {
        "port": 51826,
        "username": "D0:E3:D7:D2:CE:83",
        "pin": "111-22-333",
        "name": "HOOBS"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-eveatmo",
        "homebridge-zp"
    ],
    "accessories": [],
    "platforms": [
        {
            "plugin_map": {
                "plugin_name": "homebridge-eveatmo"
            },
            "ttl": 900,
            "extra_co2_sensor": true,
            "platform": "eveatmo",
            "auth": {
                "password": "xxx",
                "username": "xxx",
                "client_id": "xxx",
                "client_secret": "xxx"
            },
            "name": "eveatmo platform",
            "co2_alert_threshold": 1000
        },
        {
            "plugin_map": {
                "plugin_name": "homebridge-zp"
            },
            "speakers": true,
            "brightness": true,
            "service": "switch",
            "excludeAirPlay": false,
            "platform": "ZP",
            "name": "Sonos"
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}

```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
Aug 31 20:49:50 hoobs systemd[1]: hoobs.service: Scheduled restart job, restart counter is at 6529.
Aug 31 20:49:50 hoobs systemd[1]: Stopped HOOBS.
Aug 31 20:49:50 hoobs systemd[1]: hoobs.service: Found left-over process 28195 (hoobs) in control group while starting unit. Ignoring.
Aug 31 20:49:50 hoobs systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Aug 31 20:49:50 hoobs systemd[1]: Started HOOBS.
Aug 31 20:49:52 hoobs hoobs[28295]: HOOBS listening on port 80.
Aug 31 20:49:53 hoobs hoobs[28295]: Loaded plugin "homebridge-eveatmo".
Aug 31 20:49:53 hoobs hoobs[28295]: Loaded plugin "homebridge-zp".
Aug 31 20:49:54 hoobs hoobs[28295]: [eveatmo platform] Loading new data from API for: weatherstation
Aug 31 20:49:54 hoobs hoobs[28295]: [Sonos] homebridge-zp v1.0.39, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.14
Aug 31 20:49:54 hoobs hoobs[28295]: [Sonos] warning: 12.16.2: not using recommended node v12.18.3 LTS
Aug 31 20:49:54 hoobs hoobs[28295]: [Sonos] warning: config.json: plugin_map: invalid key
Aug 31 20:49:54 hoobs hoobs[28295]: Load homebridge-zp.ZPS1
Aug 31 20:49:54 hoobs hoobs[28295]: [homebridge-zp.ZPS1] homebridge-zp v1.0.39, node 12.16.2, homebridge v3.2.6, homebridge-lib v4.7.14
Aug 31 20:49:54 hoobs hoobs[28295]: [homebridge-zp.ZPS1] warning: 12.16.2: not using recommended node v12.18.3 LTS
Aug 31 20:49:54 hoobs hoobs[28295]: [Sonos] restored 4 accessories from cache
Aug 31 20:49:54 hoobs hoobs[28295]: [Sonos] listening on http://192.168.0.59:43637/notify
Aug 31 20:49:54 hoobs hoobs[28295]: [Sonos] RINCON_48A6B8E42CA801400 [Büro]: associated S2 zone player
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] found 6 S2 zone players in 4 zones
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] ├─ Büro
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] │  └─ RINCON_4xxx [Büro]: Sonos Move (S17) (master, airPlay)
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] ├─ Küche
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] │  └─ RINCON_3xxx [Küche]: Sonos SYMFONISK (S21) (master, airPlay)
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] ├─ Schlafzimmer
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] │  └─ RINCON_7xxx [Schlafzimmer]: Sonos SYMFONISK (S20) (master, airPlay)
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos] └─ Wohnzimmer (+LS+RS)
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos]    ├─ RINCON_4yyy [Wohnzimmer]: Sonos Beam (S14) (master, airPlay, tvIn)
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos]    ├─ RINCON_4yyy1 [Wohnzimmer (LS)]: Sonos One SL (S22) (satellite)
Aug 31 20:49:55 hoobs hoobs[28295]: [Sonos]    └─ RINCON_4yyy2 [Wohnzimmer (RS)]: Sonos One SL (S22) (satellite)
Aug 31 20:49:55 hoobs hoobs[28295]: HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
Aug 31 20:49:55 hoobs hoobs[28295]: [eveatmo platform] Initializing platform accessory "xxx undefined"...
Aug 31 20:49:55 hoobs hoobs[28295]: [eveatmo platform] Initializing platform accessory "xxx Modul"...
Aug 31 20:49:55 hoobs hoobs[28295]: Bridge is running on port 51826.
Aug 31 20:49:57 hoobs Node-RED[399]: 31 Aug 20:49:57 - [info] [deconz-server:Conbee] WebSocket opened
Aug 31 20:49:57 hoobs hoobs[28295]: TypeError: Cannot read property 'length' of null
Aug 31 20:49:57 hoobs hoobs[28295]:     at ServerResponse._send (_http_outgoing.js:305:33)
Aug 31 20:49:57 hoobs hoobs[28295]:     at write_ (_http_outgoing.js:683:15)
Aug 31 20:49:57 hoobs hoobs[28295]:     at ServerResponse.write (_http_outgoing.js:629:15)
Aug 31 20:49:57 hoobs hoobs[28295]:     at ReadStream.ondata (_stream_readable.js:695:22)
Aug 31 20:49:57 hoobs hoobs[28295]:     at ReadStream.emit (events.js:310:20)
Aug 31 20:49:57 hoobs hoobs[28295]:     at addChunk (_stream_readable.js:286:12)
Aug 31 20:49:57 hoobs hoobs[28295]:     at readableAddChunk (_stream_readable.js:268:9)
Aug 31 20:49:57 hoobs hoobs[28295]:     at ReadStream.Readable.push (_stream_readable.js:209:10)
Aug 31 20:49:57 hoobs hoobs[28295]:     at internal/fs/streams.js:210:12
Aug 31 20:49:57 hoobs hoobs[28295]:     at FSReqCallback.wrapper [as oncomplete] (fs.js:488:5)
Aug 31 20:49:57 hoobs hoobs[28295]: Got SIGINT, shutting down Bridge...
Aug 31 20:49:58 hoobs hoobs[28295]: [Sonos] closed http://192.168.0.59:43637/notify
Aug 31 20:50:00 hoobs Node-RED[399]: updateDoneStatus-> setting DONE status for node b1515ec2.8759e8
Aug 31 20:50:00 hoobs Node-RED[399]: updateDoneStatus-> setting node.statusUpdatePending=true
Aug 31 20:50:00 hoobs Node-RED[399]: updateDoneStatus -> setting timeout for node b1515ec2.8759e8
Aug 31 20:50:00 hoobs hoobs[28295]: [Sonos] goodbye
Aug 31 20:50:00 hoobs hoobs[28295]: [HOOBS] Stopping server.
Aug 31 20:50:00 hoobs systemd[1]: hoobs.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 20:50:00 hoobs systemd[1]: hoobs.service: Failed with result 'exit-code'.
Aug 31 20:50:03 hoobs systemd[1]: hoobs.service: Service RestartSec=3s expired, scheduling restart.
Aug 31 20:50:03 hoobs systemd[1]: hoobs.service: Scheduled restart job, restart counter is at 6530.
Aug 31 20:50:03 hoobs systemd[1]: Stopped HOOBS.

```

**Additional context**

**Comment by BobbySlope** [comment]
make a backup of your system, then delete one plugin at a time to figure out which plugin causes the issue.
after you found the plugin making the crash, restore the backup to hoobs and delete only this plugin

please let us know whitch plugin it was and we can have a deeper look at it

**Comment by stz74** [comment]
did uninstall both plugins and the hoobs service is still restarting.

is there a way to reset the hoobs installation without doing an installation from scratch?
maybe the issue is related to installing deCONZ for my conbee usb stick on the pi?

**Comment by askovi** [comment]
You need to reflash the sd card.
