### ISSUE TITLE
UUID Issue

### ISSUE THREAD

**Issue by K2i4n6g8** [hoobs-org/HOOBS#786]
Hello,
I have downloaded the latest version of HOOBS
and add the (homebridge-gree-heatercooler) plugin
After adding the accessories and save the bridge stopped.
I have tried to reset connection in Help and manually and won’t work
This is the log I got:

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7211cdb7-e183-4dbb-b496-859d51950783
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:273:27)
    at Server.loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:269:33)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:90:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:

**Comment by askovi** [comment]
Go to the top right menu and click on Help then click Reset Connection. 

Then rescan the new QR code from the dashboard.

**Comment by K2i4n6g8** [comment]
Tried it and won’t work and tried it manually through terminal and won’t work too

**Comment by askovi** [comment]
I installed the plugin and it works fine. Your issue is related to your cache. What else do you have installed, what's your config? 
Have you tried a factory reset?
