### ISSUE TITLE
Hoobs in a restart loop

### ISSUE THREAD

**Issue by Mshutt84** [hoobs-org/HOOBS#797]
Hoobs is stuck in a continual restart loop

Below is the service log

I'm stuck

Started HOOBS.
internal/fs/utils.js:230
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/home/hoobs/.hoobs/backups'
    at Object.mkdirSync (fs.js:841:3)
    at Object.module.exports.makeDirSync (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/fs-extra/lib/mkdirs/make-dir.js:102:15)
    at checksum (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:180:10)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js:40:68)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:249:85)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/hoobs/.hoobs/backups'
}
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 1.
Stopped HOOBS.

**Comment by askovi** [comment]
Is this a HOOBS box or a custom install?

**Comment by Mshutt84** [comment]
It's a hoobs box

**Comment by askovi** [comment]
Login via ssh with user: hoobs and password: hoobsadmin
On MacOS use the Terminal app and type: ssh hoobs@hoobs.local
Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin
On Windows, use Putty with the same credentials as above.

Then run this command to reset the HOOBS Box: 
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --reset`

**Comment by Mshutt84** [comment]
I do all that and when I type "yes" i just get a repeating "y" also doing the final command doesn't seem to do anything for me

**Comment by askovi** [comment]
please post a screenshot of your terminal
