### ISSUE TITLE
Homebridge-to-hoobs failed to install

### ISSUE THREAD

**Issue by jimkyee** [hoobs-org/HOOBS#800]
**Description**
When trying to install the Homebridge-to-hoobs plugin, the installer fails. Below is what I see:

> homebridge-to-hoobs@1.0.37 postinstall C:\Users\Home\AppData\Roaming\npm\node_
modules\homebridge-to-hoobs
> ./install

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-to-hoobs@1.0.37 postinstall: `./install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-to-hoobs@1.0.37 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\
_logs\2020-09-16T16_14_43_943Z-debug.log

**Version**
Homebridge version 1.2.2

**Did you upgrade**
- [ ] Yes
- [X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Windows 10

**List your plugins**
-Homebridge Config UI X
-Homebridge Airmega
-Homebridge Bravia
-Homebridge Calendar
-Homebridge Camera FFmpeg
-Homebridge Harmony
-Homebridge People Guest Mode
-Homebridge Platform Smartac
-Homebridge Wemo
-Homebridge Tplink Smarthome
-Homebridge Xiaomi Roborock Vacuum

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "bridge": {
        "name": "Homebridge 1393",
        "username": "##:##:##:##:##:##",
        "port": 51288,
        "pin": "###-##-###"
    },
    "accessories": [
        {
            "name": "Vacuum",
            "ip": "192.168.3.32",
            "token": "###########################",
            "waterBox": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": false,
            "delay": false,
            "cleanword": "cleaning",
            "autoroom": false,
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "SmartAC",
            "name": "ThinkEco SmartAC Platform",
            "username": "#########",
            "password": "#########"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Hallway",
                    "videoConfig": {
                        "source": "-i rtsp://192.168.3.13/live1",
                        "maxWidth": 1920,
                        "maxHeight": 1080
                    }
                },
                {
                    "name": "Driveway",
                    "videoConfig": {
                        "source": "-i rtsp://192.168.3.13/live2"
                    }
                },
                {
                    "name": "Front Door",
                    "videoConfig": {
                        "source": "-i rtsp://192.168.3.13/live0"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "name": "Harmony Hub",
            "hubIP": "192.168.3.18",
            "devicesToPublishAsAccessoriesSwitch": [
                "Fan|Power;PowerToggle",
                "Fan|Oscillate;Oscillate",
                "Fan|Speed;Speed"
            ],
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"
        },
        {
            "name": "Belkin WeMo",
            "platform": "BelkinWeMo"
        },
        {
            "platform": "Airmega",
            "username": "########",
            "password": "########"
        },
        {
            "name": "TplinkSmarthome",
            "platform": "TplinkSmarthome"
        },
        {
            "platform": "Calendar",
            "calendars": [
                {
                    "name": "Work",
                    "url": "#############",
                    "pollingInterval": 15,
                    "offset": "-150m"
                }
            ]
        },
        {
            "tvs": [
                {
                    "name": "TV",
                    "ip": "192.168.3.5",
                    "serverPort": 8999,
                    "externalaccessory": false,
                    "soundoutput": "speaker",
                    "applications": [
                        {
                            "title": "Netflix"
                        },
                        {
                            "title": "Spotify"
                        },
                        {
                            "title": "Google Play Store"
                        }
                    ],
                    "sources": [
                        "extInput:hdmi"
                    ]
                }
            ],
            "platform": "BraviaPlatform"
        },
        {
            "platform": "People",
            "threshold": 15,
            "webhookPort": 51828,
            "cacheDirectory": "./.node-persist/storage",
            "pingInterval": 10000,
            "ignoreReEnterExitSeconds": 0,
            "people": [
                {
                    "name": "Kam",
                    "target": "192.168.3.34",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Jim",
                    "target": "192.168.3.22",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Jade",
                    "target": "192.168.3.35",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Mom",
                    "target": "192.168.3.25",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Ming",
                    "target": "192.168.3.37",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                }
            ]
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Home\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   'homebridge-to-hoobs@latest'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.18.3
4 verbose npm-session c36a5dc982df0e28
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-to-hoobs 295ms (from cache)
8 silly pacote tag manifest for homebridge-to-hoobs@latest fetched in 334ms
9 timing stage:loadCurrentTree Completed in 363ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-to-hoobs@1.0.37 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 10ms
18 timing stage:loadIdealTree Completed in 15ms
19 silly currentTree npm
20 silly idealTree npm
20 silly idealTree `-- homebridge-to-hoobs@1.0.37
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 15ms
23 silly diffTrees action count 1
24 silly diffTrees add homebridge-to-hoobs@1.0.37
25 silly decomposeActions action count 8
26 silly decomposeActions fetch homebridge-to-hoobs@1.0.37
27 silly decomposeActions extract homebridge-to-hoobs@1.0.37
28 silly decomposeActions preinstall homebridge-to-hoobs@1.0.37
29 silly decomposeActions build homebridge-to-hoobs@1.0.37
30 silly decomposeActions install homebridge-to-hoobs@1.0.37
31 silly decomposeActions postinstall homebridge-to-hoobs@1.0.37
32 silly decomposeActions finalize homebridge-to-hoobs@1.0.37
33 silly decomposeActions refresh-package-json homebridge-to-hoobs@1.0.37
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir C:\Users\Home\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
37 verbose makeCacheDir UID & GID are irrelevant on win32
38 verbose lock using C:\Users\Home\AppData\Roaming\npm-cache\_locks\staging-d914a6f2f9c8f187.lock for C:\Users\Home\AppData\Roaming\npm\node_modules\.staging
39 silly doParallel extract 1
40 silly extract homebridge-to-hoobs@1.0.37
41 silly tarball trying homebridge-to-hoobs@latest by hash: sha512-YlcQeaQIrFgfNDpnb89E6OVL0IQbcAcOS1VmjCbBNZPH6w9IUu1FcDsUcTmPAt2ae7ZW2TYEdoJ4NI+dNHhNnQ==
42 silly extract homebridge-to-hoobs@latest extracted to C:\Users\Home\AppData\Roaming\npm\node_modules\.staging\homebridge-to-hoobs-c664d150 (54ms)
43 timing action:extract Completed in 62ms
44 silly doReverseSerial unbuild 8
45 silly doSerial remove 8
46 silly doSerial move 8
47 silly doSerial finalize 8
48 silly finalize C:\Users\Home\AppData\Roaming\npm\node_modules\homebridge-to-hoobs
49 timing action:finalize Completed in 11ms
50 silly doParallel refresh-package-json 1
51 silly refresh-package-json C:\Users\Home\AppData\Roaming\npm\node_modules\homebridge-to-hoobs
52 timing action:refresh-package-json Completed in 37ms
53 silly doParallel preinstall 1
54 silly preinstall homebridge-to-hoobs@1.0.37
55 info lifecycle homebridge-to-hoobs@1.0.37~preinstall: homebridge-to-hoobs@1.0.37
56 timing action:preinstall Completed in 2ms
57 silly doSerial build 8
58 silly build homebridge-to-hoobs@1.0.37
59 info linkStuff homebridge-to-hoobs@1.0.37
60 silly linkStuff homebridge-to-hoobs@1.0.37 has C:\Users\Home\AppData\Roaming\npm\node_modules as its parent node_modules
61 silly linkStuff homebridge-to-hoobs@1.0.37 is part of a global install
62 silly linkStuff homebridge-to-hoobs@1.0.37 is installed into a global node_modules
63 silly linkStuff homebridge-to-hoobs@1.0.37 is installed into the top-level global node_modules
64 timing action:build Completed in 2ms
65 silly doSerial global-link 8
66 silly doParallel update-linked 0
67 silly doSerial install 8
68 silly install homebridge-to-hoobs@1.0.37
69 info lifecycle homebridge-to-hoobs@1.0.37~install: homebridge-to-hoobs@1.0.37
70 timing action:install Completed in 3ms
71 silly doSerial postinstall 8
72 silly postinstall homebridge-to-hoobs@1.0.37
73 info lifecycle homebridge-to-hoobs@1.0.37~postinstall: homebridge-to-hoobs@1.0.37
74 verbose lifecycle homebridge-to-hoobs@1.0.37~postinstall: unsafe-perm in lifecycle true
75 verbose lifecycle homebridge-to-hoobs@1.0.37~postinstall: PATH: C:\Users\Home\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Home\AppData\Roaming\npm\node_modules\homebridge-to-hoobs\node_modules\.bin;C:\Users\Home\AppData\Roaming\npm\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;;C:\Program Files\nodejs\;C:\Users\Home\AppData\Local\Microsoft\WindowsApps;C:\Users\Home\AppData\Roaming\npm
76 verbose lifecycle homebridge-to-hoobs@1.0.37~postinstall: CWD: C:\Users\Home\AppData\Roaming\npm\node_modules\homebridge-to-hoobs
77 silly lifecycle homebridge-to-hoobs@1.0.37~postinstall: Args: [ '/d /s /c', './install' ]
78 silly lifecycle homebridge-to-hoobs@1.0.37~postinstall: Returned: code: 1  signal: null
79 info lifecycle homebridge-to-hoobs@1.0.37~postinstall: Failed to exec postinstall script
80 timing action:postinstall Completed in 54ms
81 verbose unlock done using C:\Users\Home\AppData\Roaming\npm-cache\_locks\staging-d914a6f2f9c8f187.lock for C:\Users\Home\AppData\Roaming\npm\node_modules\.staging
82 timing stage:rollbackFailedOptional Completed in 7ms
83 timing stage:runTopLevelLifecycles Completed in 591ms
84 verbose stack Error: homebridge-to-hoobs@1.0.37 postinstall: `./install`
84 verbose stack Exit status 1
84 verbose stack     at EventEmitter.<anonymous> (C:\Users\Home\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
84 verbose stack     at EventEmitter.emit (events.js:315:20)
84 verbose stack     at ChildProcess.<anonymous> (C:\Users\Home\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
84 verbose stack     at ChildProcess.emit (events.js:315:20)
84 verbose stack     at maybeClose (internal/child_process.js:1021:16)
84 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
85 verbose pkgid homebridge-to-hoobs@1.0.37
86 verbose cwd C:\WINDOWS\system32
87 verbose Windows_NT 10.0.18363
88 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Home\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "homebridge-to-hoobs@latest"
89 verbose node v12.18.3
90 verbose npm  v6.14.8
91 error code ELIFECYCLE
92 error errno 1
93 error homebridge-to-hoobs@1.0.37 postinstall: `./install`
93 error Exit status 1
94 error Failed at the homebridge-to-hoobs@1.0.37 postinstall script.
94 error This is probably not a problem with npm. There is likely additional logging output above.
95 verbose exit [ 1, true ]
```

**Additional context**

**Comment by askovi** [comment]
Sorry, HOOBS does not run on Windows. You can see the available operating systems here: https://support.hoobs.org/docs/5e763e30e87d1e02b6c19d33

**Comment by jimkyee** [comment]
Appreciate the response, thanks!
