### ISSUE TITLE
HOOBS bridge service not running

### ISSUE THREAD

**Issue by peteconr** [hoobs-org/HOOBS#804]
**Description**
HOOBS bridge service not running.  Homekit compatible devices work fine, but devices running through homebridge are "not responding".

**Version**
3.2.6 downloaded, flashed, installed yesterday

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
n/a

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
n/a

**List your plugins**
Mylink -- 1.5.1-beta.50 published 7/17/2020
Lc7001 -- 0.6.4 published 9/5/2020
Nest Cam -- 5.2.4 published 9/14/2020
(had mylink but deleted as I can't get my integration report for devide id's)

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYMH0J",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "11954"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "redacted",
        "username": "redacted"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest-cam",
            "plugin_map": {
                "plugin_name": "homebridge-nest-cam"
            },
            "ffmpegCodec": "libx264",
            "options": {
                "streamQuality": 3,
                "alertCheckRate": 10,
                "alertCooldownRate": 180,
                "importantOnly": true,
                "motionDetection": true,
                "streamingSwitch": true,
                "chimeSwitch": false,
                "doorbellAlerts": false,
                "doorbellSwitch": false,
                "audioSwitch": true
            }
        },
        {
            "platform": "Somfy myLink",
            "plugin_map": {
                "plugin_name": "homebridge-mylink"
            },
            "systemID": "mtkmdrn shades"
        },
        {
            "platform": "LC7001",
            "plugin_map": {
                "plugin_name": "homebridge-lc7001"
            },
            "name": "LC7001"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
9/17/2020, 10:53:28 AM HOOBS listening on port 80.
9/17/2020, 10:53:29 AM Loaded plugin "homebridge-lc7001".
9/17/2020, 10:53:29 AM homebridge API version: 2.5
9/17/2020, 10:53:29 AM Loaded plugin "homebridge-nest-cam".
9/17/2020, 10:53:29 AM Error loading plugin "homebridge-mylink".
9/17/2020, 10:53:30 AM Error: Cannot find module 'homebridge'
Require stack:
- /home/hoobs/.hoobs/node_modules/hb-kit/lib/utils.js
- /home/hoobs/.hoobs/node_modules/hb-kit/lib/platform.js
- /home/hoobs/.hoobs/node_modules/hb-kit/lib/index.js
- /home/hoobs/.hoobs/node_modules/@pmouli/homebridge-mylink/dist/Plugin.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/plugin.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/hb-kit/lib/utils.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
9/17/2020, 10:53:30 AM The requested platform "Somfy myLink" was not registered by any plugin.
9/17/2020, 10:53:30 AM Your config.json is requesting the platform "Somfy myLink" which has not been published by any installed plugins.
9/17/2020, 10:53:30 AM [LC7001] LC7001 platform initialization.
9/17/2020, 10:53:30 AM [LC7001] Cabana Bar Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Cabana Bath Shower Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Cabana Bathroom Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Hallway Downstairs Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Office Ceiling Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Dining Table Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Media Room Ceiling Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Front Deck Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Gym Outlet Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Office Floor Lamp Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Cabana Floor Lamp Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Stairway Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Guestroom 1 Lamps Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Guestroom 1 Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Master Bath Tub Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Master Bed Entrance Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Master Bed Sidetable Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Master Bed Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Floods Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Guestroom 2 Lamps Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Master Bath Fan Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Living Room TV Outl Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Kitchen Counter Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Dining Table Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Garage Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Upper Front Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Patio Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Living Room Lamp Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Kitchen Island Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Guestroom 2 Sconces Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Bathroom Upstairs Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Guestroom 1 Sconces Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Outside Living Room Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Cabana Bath Fan Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Kitchen Sink Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Media Room Lamp Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Living Room Outlet Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Hallway Upstairs Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Laundry Room Configure Accessory
9/17/2020, 10:53:30 AM [LC7001] Master Bath Main Configure Accessory
9/17/2020, 10:53:30 AM [Nest-cam] You did not specify your Google account credentials, googleAuth, in config.json
9/17/2020, 10:53:30 AM [LC7001] Homebridge issued DidFinishLaunching event.
9/17/2020, 10:53:30 AM [LC7001] Reading configuration for LC7001.
9/17/2020, 10:53:30 AM [LC7001] Attempting to connect to LC7001 at LCM1.local:2112.
9/17/2020, 10:53:30 AM Bridge is running on port 51826.
9/17/2020, 10:53:40 AM [LC7001] Connection to LC7001 established.
9/17/2020, 10:53:40 AM Error parsing JSON. Possible undelimited JSON detected! Replacing all }{s with delimited version.
9/17/2020, 10:53:40 AM [LC7001] Finished polling LC7001 for accessories.
9/17/2020, 10:53:40 AM TypeError: Cannot read property 'PropertyList' of undefined
    at Platform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lc7001/index.js:108:17)
    at Array.findIndex (<anonymous>)
    at platformLC7001.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lc7001/index.js:107:49)
    at Array.forEach (<anonymous>)
    at platformLC7001.matchAccessorieswithLC7001 (/home/hoobs/.hoobs/node_modules/homebridge-lc7001/index.js:106:19)
    at EventEmitter.emit (events.js:310:20)
    at Object.processResponseQueue (/home/hoobs/.hoobs/node_modules/homebridge-lc7001/lib/lc7001.js:221:22)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lc7001/lib/lc7001.js:299:7)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
9/17/2020, 10:53:40 AM Got SIGTERM, shutting down Bridge...
```

**Additional context**
Thank you!

**Comment by askovi** [comment]
Your logs are showing errors with the mylink plugin and the lc7001 plugin. These are plugin errors and not related to HOOBS. You can either uninstall these plugins or open issues on their respective github repositories. They seem to be crashing the HOOBS Service.

**Comment by shamasis** [comment]
Apologies for posting on a closed thread. Same issue upon upgrade to latest 4.2.5.

I got UI up and running temporarily by changing two lines. Don't recommend this for long term.

sudo nano /usr/lib/hoobsd/node_modules/toidentifier/index.js line 26
<img width="322" alt="image" src="https://user-images.githubusercontent.com/232373/173276959-766ae467-7adb-4e79-bf7e-add643f214bd.png">
Changed `reutrn str` to `return (str || '')`

sudo nano /usr/lib/hoobsd/node_modules/depd/index.js line 415
<img width="526" alt="image" src="https://user-images.githubusercontent.com/232373/173277080-e702a123-d802-4722-b3ed-938f48d6f4fd.png">
> commented out the `throw` ... really bad thing to do
> added `fn = function () {}` to suppress error
