### ISSUE TITLE
HOOBS webserver not running after shutdown

### ISSUE THREAD

**Issue by sdecaux** [hoobs-org/HOOBS#818]
**Description**
All was working fine. I went in the Hoobs menu to shutdown my Raspberry. Then hoops.local does not work anymore (either  http://hoobs.local nor http://192.168.0.87 → web site unreachable , but ssh is working ok. I reinstalled everything to the SD card, and restored. All was fine until shutdown : the webserver service seems to not relaunch.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
        "homebridge-netatmo",
        "google-home",
        "homebridge-platform-wemo",
        "homebridge-tahoma",
        "homebridge-rpi"

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
iMac:MobileSync sd$ ssh hoobs@hoobs.local
hoobs@hoobs.local's password: 
Linux hoobs 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l
Raspberry Pi 3 Model B Plus Rev 1.3


*** HOOBS - Homebridge Out Of The Box ***

   _    _  ____   ____  ____   _____   
  | |  | |/ __ \ / __ \|  _ \ / ____|  
  | |__| | |  | | |  | | |_) | (___    
  |  __  | |  | | |  | |  _ < \___ \   
  | |  | | |__| | |__| | |_) |____) |  
  |_|  |_|\____/ \____/|____/|_____/   
                                       

To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs.local
* http://192.168.0.87
* http://[2a01:e0a:278:f9a0:1898:d1d8:2bee:4e4a]


HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Sep 28 15:59:03 2020 from 192.168.0.80
hoobs@hoobs:~ $ sudo hoobs service log
Started HOOBS.
HOOBS listening on port 8080.
Loaded plugin "homebridge-netatmo".
Loaded plugin "homebridge-platform-wemo".
Loaded plugin "homebridge-tahoma".
homebridge-tahoma API version: 2.5
Loaded plugin "google-home".
[Somfy] Fetch accessories...
[Somfy] Login TaHoma server...
The requested platform "RPi" was not registered by any plugin.
Your config.json is requesting the platform "RPi" which has not been published by any installed plugins.
[Somfy] Unable to refresh states (not logged in)
[WeMo Platform] Online: WeMo Switch Bureau [08863BC86514]
[WeMo Platform] Online: WeMo Motion [EC1A59675C6C]
[WeMo Platform] Online: WeMo Switch Chambre [EC1A5982B104]
[Somfy] [Philips Hue Bridge] type: ProtocolGateway > HueBridge, protocol: hue
[Somfy] Device Philips Hue Bridge ignored
[Somfy] [Lampadaire gauche] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lampadaire gauche ignored
[Somfy] [Lampe Go] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lampe Go ignored
[Somfy] [Lumière Fanny] type: Light > DimmerLight, protocol: hue
[Somfy] Device Lumière Fanny ignored
[Somfy] [Lumière bureau] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lumière bureau ignored
[Somfy] [Lampadaire AR] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lampadaire AR ignored
[Somfy] [Lampadaire droite] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lampadaire droite ignored
[Somfy] [Escaliers] type: Light > DimmerHueSaturationLight, protocol: hue
[Somfy] Device Escaliers ignored
[Somfy] [Lumière entrée] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lumière entrée ignored
[Somfy] [bibliothèque] type: Light > DimmerHueSaturationLight, protocol: hue
[Somfy] Device bibliothèque ignored
[Somfy] [Lumière Marie] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lumière Marie ignored
[Somfy] [Lumière parents] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lumière parents ignored
[Somfy] [Lampe vitrine] type: Light > DimmerHueSatOrCTLight, protocol: hue
[Somfy] Device Lampe vitrine ignored
[Somfy] [Alarm] type: Alarm > TSKAlarmController, protocol: internal
[Somfy] Instanciate Alarm as Alarm
[Somfy] [Bouton sensitif] type: Pod > Pod, protocol: internal
[Somfy] No definition found for Pod > Pod in mapping.json file
[Somfy] [VR Salle à manger G] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Salle à manger G as WindowCovering
[Somfy] [Chambre Marie] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate Chambre Marie as WindowCovering
[Somfy] [VR Salon D] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Salon D as WindowCovering
[Somfy] [VR combles couloir] type: RollerShutter > PositionableTiltedRollerShutter, protocol: io
[Somfy] Instanciate VR combles couloir as WindowCovering
[Somfy] [VR chambre amis G] type: RollerShutter > PositionableTiltedRollerShutter, protocol: io
[Somfy] Instanciate VR chambre amis G as WindowCovering
[Somfy] [Bureau] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate Bureau as WindowCovering
[Somfy] [VR Cuisine D] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Cuisine D as WindowCovering
[Somfy] [VR Cuisine M] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Cuisine M as WindowCovering
[Somfy] [Lanceur Entrée] type: RemoteController > RemoteControllerOneWay, protocol: io
[Somfy] No definition found for RemoteController > RemoteControllerOneWay in mapping.json file
[Somfy] [VR Chambre Flo Syl] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Chambre Flo Syl as WindowCovering
[Somfy] [VR Chambre Fanny] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Chambre Fanny as WindowCovering
[Somfy] [VR Salle de Bains] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Salle de Bains as WindowCovering
[Somfy] [VR chambre amis D] type: RollerShutter > PositionableTiltedRollerShutter, protocol: io
[Somfy] Instanciate VR chambre amis D as WindowCovering
[Somfy] [IO (3610449)] type: ProtocolGateway > IOStack, protocol: io
[Somfy] No definition found for ProtocolGateway > IOStack in mapping.json file
[Somfy] [VR Salle à manger D] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Salle à manger D as WindowCovering
[Somfy] [VR Salon G] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Salon G as WindowCovering
[Somfy] [VR Cuisine G] type: RollerShutter > PositionableRollerShutter, protocol: io
[Somfy] Instanciate VR Cuisine G as WindowCovering
[Somfy] [OGP KNX Bridge] type: ProtocolGateway > DynamicBridge, protocol: ogp
[Somfy] No definition found for ProtocolGateway > DynamicBridge in mapping.json file
[Somfy] [OGP Siegenia Bridge] type: ProtocolGateway > DynamicBridge, protocol: ogp
[Somfy] No definition found for ProtocolGateway > DynamicBridge in mapping.json file
[Somfy] [OGP Intesis Bridge] type: ProtocolGateway > DynamicBridge, protocol: ogp
[Somfy] No definition found for ProtocolGateway > DynamicBridge in mapping.json file
[Somfy] Initializing platform accessory "VR Cuisine G"...
[Somfy] Initializing platform accessory "VR Salon G"...
[Somfy] Initializing platform accessory "VR Salle à manger D"...
[Somfy] Initializing platform accessory "VR chambre amis D"...
[Somfy] Initializing platform accessory "VR Salle de Bains"...
[Somfy] Initializing platform accessory "VR Chambre Fanny"...
[Somfy] Initializing platform accessory "VR Chambre Flo Syl"...
[Somfy] Initializing platform accessory "VR Cuisine M"...
[Somfy] Initializing platform accessory "VR Cuisine D"...
[Somfy] Initializing platform accessory "Bureau"...
[Somfy] Initializing platform accessory "VR chambre amis G"...
[Somfy] Initializing platform accessory "VR combles couloir"...
[Somfy] Initializing platform accessory "VR Salon D"...
[Somfy] Initializing platform accessory "Chambre Marie"...
[Somfy] Initializing platform accessory "VR Salle à manger G"...
[Somfy] Initializing platform accessory "Alarm"...
[Google Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[Google Home] Devices Not Ready
(node:622) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requestId' of undefined
at Plugin.deviceNotReady (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:117:29)
at Plugin.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:38:33)
at Generator.next (<anonymous>)
at /home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:7:71
at new Promise (<anonymous>)
at __awaiter (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:3:12)
at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/dist/main.js:28:36)
at WebSocket.emit (events.js:310:20)
at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/@hoobs/ws-connect/dist/index.js:66:22)
at WebSocket.emit (events.js:310:20)
at Receiver.receiverOnMessage (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/websocket.js:800:20)
at Receiver.emit (events.js:310:20)
at Receiver.dataMessage (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:422:14)
at Receiver.getData (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:352:17)
at Receiver.startLoop (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:138:22)
at Receiver._write (/home/hoobs/.hoobs/node_modules/@hoobs/google-home/node_modules/ws/lib/receiver.js:74:10)
(node:622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Google Home] Finished instance discovery
[station netatmo] Initializing platform accessory "SQY Intérieur"...
[station netatmo] Initializing platform accessory "SQY Garage"...
[station netatmo] Initializing platform accessory "SQY Pluvio"...
[station netatmo] Initializing platform accessory "SQY Combles"...
[station netatmo] Initializing platform accessory "SQY Anémomètre"...
[station netatmo] Initializing platform accessory "SQY Extérieur"...
[station netatmo] Initializing platform accessory "SQY"...
Bridge is running on port 51826.
[Google Home] Sending Sync Request
[station netatmo] WARN - Netatmo: Error: getStationsDataError error: Status code500
[station netatmo] WARN - Netatmo: Error: getStationsDataError error: Status code500
```

**Additional context**

**Comment by askovi** [comment]
Try http://hoobs.local:8080 or http://192.168.0.87:8080
According to the logs the HOOBS service is running on port 8080

**Comment by sdecaux** [comment]
Indeed!

But why on earth the port went from 80 to 8080?
How to set it up again on 80?

------------------------------------

**Comment by askovi** [comment]
It’s the fallback port. You can change it in the settings from the UI. However it might cause other issues if something else is using port 80. Make sure to grab the logs again if it doesn’t run after changing the port.
