### ISSUE TITLE
HOOBS starts and then stops - duplicate bridged accessory

### ISSUE THREAD

**Issue by denz1968** [hoobs-org/HOOBS#827]
Hi all

I have previously had homebridge running on my MAC. Decided to go away from that and go the Raspberry Pi route and HOOBS.

Pi is set up and HOOBS dashboard available. However I have an issue with no devices found. Looking at the logs I see an error about a duplicate bridges accessory

at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:273:27)
    at Server.configCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:348:25)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:94:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
06/10/2020, 07:25:54 ERROR: uncaughtException: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 1c495c85-e7e0-4646-a734-84ea68534118
06/10/2020, 07:25:54 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 1c495c85-e7e0-4646-a734-84ea68534118
06/10/2020, 07:25:54 at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:273:27)
06/10/2020, 07:25:54 at Server.configCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:348:25)
06/10/2020, 07:25:54 at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:94:14)
06/10/2020, 07:25:54 at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
06/10/2020, 07:25:54 at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
06/10/2020, 07:25:54 at Module._compile (internal/modules/cjs/loader.js:1133:30)
06/10/2020, 07:25:54 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
06/10/2020, 07:25:54 at Module.load (internal/modules/cjs/loader.js:977:32)
06/10/2020, 07:25:54 at Function.Module._load (internal/modules/cjs/loader.js:877:14)
06/10/2020, 07:25:54 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
06/10/2020, 07:25:54 Got SIGTERM, shutting down Bridge...
06/10/2020, 07:25:56 INFO: INFO: Your plugin version is up-to-date
06/10/2020, 07:25:56 NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.4

Can anyone point me what the actual issue is. Do I need to delete homebridge V2 from my smartthings and re-install, or is there a chance although I think I have deleted it from my MAC it is still there in the background

Thanks in advance

**Comment by denz1968** [comment]
Solved by restart from the help menu
