### ISSUE TITLE
hoobs crashes with latest nest cam plugin : err buffer out of bounds

### ISSUE THREAD

**Issue by WIMWG** [hoobs-org/HOOBS#831]
**Description**
10/7/2020, 10:38:49 AM [homebridge-zp.ZPS1] warning: no zone players found
10/7/2020, 10:38:53 AM RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt8 (internal/buffer.js:243:5)
    at NexusStreamer.handleNexusData (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam/dist/nest/streamer.js:454:41)
    at WebSocket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam/dist/nest/streamer.js:101:18)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (/home/hoobs/.hoobs/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (/home/hoobs/.hoobs/node_modules/ws/lib/receiver.js:428:14)
    at Receiver.getData (/home/hoobs/.hoobs/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/hoobs/.hoobs/node_modules/ws/lib/receiver.js:143:22)
10/7/2020, 10:38:53 AM Got SIGTERM, shutting down Bridge...
10/7/2020, 10:38:53 AM [Harmony] INFO - shutdown
10/7/2020, 10:38:53 AM [SoNoS] closed http://192.168.123.102:33547/notify
10/7/2020, 10:38:56 AM [SoNoS] goodbye

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS SD Card.

**List your plugins**
Harmony
Nest
Nest Cam
TPLink Smarthome
ZP

**Post your config**

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "xxxx”,
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "BE",
        "postal_code": "2250"
    },
    "bridge": {
        "name"xxxxxx",
        "port": 51826,
        "pin": "xxxxxx",
        "username": "xxxxxxxxx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "ZP",
            "plugin_map": {
                "plugin_name": "homebridge-zp"
            },
            "name": "SoNoS",
            "service": "switch",
            "excludeAirPlay": false,
            "forceS2": false,
            "brightness": true,
            "alarms": false,
            "leds": false,
            "speakers": false,
            "nameScheme": "% SoNoS",
            "tv": false
        },
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "hubIP": "xxxxxxxxxx",
            "name": "Harmony",
            "hubName": "Harmony",
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": false,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "publishDevicesAsIndividualAccessories": true,
            "publishSequencesAsIndividualAccessories": true,
            "publishHomeControlsAsIndividualAccessories": true,
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": true,
            "playPauseBehavior": true,
            "switchAccessories": true
        },
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "googleAuth": {
                "issueToken": "xxxx”
                "apiKey": "xxxxx",
                "cookies": "xxxxxx"
            }
        },
        {
            "platform": "Nest-cam",
            "plugin_map": {
                "plugin_name": "homebridge-nest-cam"
            },
            "ffmpegCodec": "libx264",
            "googleAuth": {
                "issueToken": "xxxxx",
                "apiKey": "xxxxxx",
                "cookies": "xxxxxxx"
            },
            "options": {
                "streamQuality": 3,
                "alertCheckRate": 10,
                "alertCooldownRate": 180,
                "importantOnly": true,
                "motionDetection": false,
                "streamingSwitch": false,
                "chimeSwitch": false,
                "doorbellAlerts": false,
                "doorbellSwitch": false,
                "audioSwitch": false
            }
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**
Nest Cam developper says its the older version of hoobs

Personally, I don't run HOOBS and I know that it has been a while since it was updated. I've been updating the plugin with new features from the official Homebridge and am not sure if these features are included in the older HOOBS. I would recommend migrating to homebridge if you can, otherwise, you could try clearing any cache that HOOBS saves.

**Comment by WIMWG** [comment]
ok solved with latest versions thx
