### ISSUE TITLE
Getting SIGTERM error

### ISSUE THREAD

**Issue by RealLatinX** [hoobs-org/HOOBS#846]
Just getting started here... I had Roomba plug-in installed successfully, then tried adding the BigAss Fans API which was a complete washout.

After uninstalling the BAF plugin, I find that I cannot restart HOOBS at all. Getting this message... no idea where to start on this one.... 

```
10/16/2020, 5:54:06 PM Loaded plugin "homebridge-roomba-stv".10/16/2020, 5:54:06 PM TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/src/hoobs/bridge/api.js:114:18)
    at Server.loadPlatforms (/usr/src/hoobs/bridge/server.js:277:35)
    at Server.run (/usr/src/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/src/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/src/hoobs/bin/hoobs:63:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:4710/16/2020, 5:54:06 PM Got SIGTERM, shutting down Bridge...
```

**Comment by RealLatinX** [comment]
Looks like it might be resolved - Platforms "BigAssFans" didn't get removed from Config on uninstall, appears to be working now.

**Comment by askovi** [comment]
Glad your got it working. If you experience any other problems, please open a new issue.
