### ISSUE TITLE
Hue Plugin not works after update

### ISSUE THREAD

**Issue by Hodenbeer** [hoobs-org/HOOBS#854]
**Description**
I install the plugin to connect Hoobs with my other Rasp3 wie DeConz Raspbian II. But after install Hoobs don't run (

**Plugin name**
Hue 0.11.77 veröffentlicht 10/16/2020 

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X ] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X ] Custom Install
Raspberry Pi4B

* Remove any passwords from the config file. This is public.

```
21.10.2020, 19:57:57 Loaded plugin "homebridge-hue".
21.10.2020, 19:57:58 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
21.10.2020, 19:57:58 [Hue] config.json: warning: plugin_map: ignoring unknown key
21.10.2020, 19:57:58 [Hue] homebridge-hue v0.11.77, node v12.16.3, homebridge v3.2.6
21.10.2020, 19:57:58 [Hue] warning: not using recommended node version v12.19.0 LTS
21.10.2020, 19:57:58 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
21.10.2020, 19:57:58 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
21.10.2020, 19:57:59 [Hue] searching bridges and gateways
21.10.2020, 19:58:00 [R2D2] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
21.10.2020, 19:58:04 [Hue] Bitch Bridge: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
21.10.2020, 19:58:04 [Hue] Bitch Bridge: warning: not using recommended deCONZ gateway version 2.5.84
21.10.2020, 19:58:04 [Hue] Bitch Bridge: 1 accessories
21.10.2020, 19:58:04 [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
21.10.2020, 19:58:04 [Hue] Initializing platform accessory "Bitch Bridge"...
21.10.2020, 19:58:04 [Hue] Bitch Bridge: 2 services
21.10.2020, 19:58:04 Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:86:30)
    at HAPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:188:31)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:560:27)
    at Server.publish (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:134:21)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:369:22
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:15:25
    at HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HuePlatform.js:326:5)
21.10.2020, 19:58:04 Got SIGTERM, shutting down Bridge...
21.10.2020, 19:58:07 [Hue] goodbye
```

**Comment by askovi** [comment]
Just reboot from the top right menu. It will fix itself.

**Comment by mkellsy** [comment]
The old service got stuck, happens from time to time. Rebooting the device should fix this.

**Comment by Hodenbeer** [comment]
Oh yes. Thank you, it works :) . I forgot to reboot...
