### ISSUE TITLE
Issue with Node.js preventing Hoobs boot

### ISSUE THREAD

**Issue by jermg77** [hoobs-org/HOOBS#873]
Been running HOOBS for months on a RPi model B. I was poking where I should not have been with regards to using N to update Node.js... stupid move, and I broke something. This is what I'm seeing upon attempting start HOOBS via ssh:

Looking like I need to reinstall the correct version of Node.js in the correct location? Any pushes in the right direction would be appreciated.

hoobs@hoobs:~ $ hoobs
innerError { Error: Cannot find module '../build/Debug/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19) code: 'MODULE_NOT_FOUND' }
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)

**Comment by mkellsy** [comment]
N changes the location of Node and it screws with the way Debian installs Node.

This command should get you up and running.
`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by jermg77** [comment]
Bingo... that did it... Thanks!
