### ISSUE TITLE
HOOBS stuck on yellow loading screen 

### ISSUE THREAD

**Issue by fizulnizam** [hoobs-org/HOOBS#887]
Hi there. My installation of HOOBS version 3.2.9 running on Raspberry Pi Zero W is now stuck at the yellow loading screen after me updating the node version using Terminal. When I ssh into the Pi and run hoobs, it says 

`innerError { Error: Cannot find module '../build/Debug/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) code: 'MODULE_NOT_FOUND' }
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)`

Now I regret trying to update the node.. Can anyone please help me solve this? :(

**Comment by askovi** [comment]
`npm uninstall -g @hoobs/hoobs`
then
`npm install -g --unsafe-perm @hoobs/hoobs`

**Comment by fizulnizam** [comment]
Thank you, now I am able to log into HOOBS, but when I try to start the service, I run into this problem in the log:

`07/11/2020, 20:31:08 Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/hapCrypto.js:80:35)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:499:39)
    at HAPServer._this._handlePairVerify (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:463:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
07/11/2020, 20:31:09 Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/hapCrypto.js:80:35)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:499:39)
    at HAPServer._this._handlePairVerify (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:463:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
07/11/2020, 20:31:09 Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/hapCrypto.js:80:35)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:499:39)
    at HAPServer._this._handlePairVerify (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:463:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
07/11/2020, 20:31:09 [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
07/11/2020, 20:31:09 [Google Smart Home] To continue using Google Home, please update the homebridge-gsh plugin ASAP.
07/11/2020, 20:31:09 Got SIGTERM, shutting down Bridge...
07/11/2020, 20:31:09 Error: send ECANCELED 224.0.0.251:5353
    at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
07/11/2020, 20:31:09 Error: send ECANCELED 224.0.0.251:5353
    at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)`

What should I do..

**Comment by askovi** [comment]
See here: https://github.com/hoobs-org/HOOBS/issues/649

**Comment by fizulnizam** [comment]
Thank you, that solved it for me!
