### ISSUE TITLE
HOOBS Web interface not reachable

### ISSUE THREAD

**Issue by freddair** [hoobs-org/HOOBS#903]
**Description**
I have 3 HOOBS instances. Each for a different Home. 1 runs on RPi 3B+, 2 run on RPi zero. 
After Updating the Fritz-Platform plugin, hoops service stopped. I updated to hoobs 3.2.10 but it did not help. I then tried to update node.js to latest, with the result that I could not reach the web interface any more. I then installed hoops again with `wget -q -O - http://bit.ly/get-hoobs | sudo bash -` and it went through, but I still cannot reach the web interface. 

**Version**
3.2.10

**Did you upgrade**
Yes

**Pervious version**
3.2.9

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
No

**What device are you using?**
Please let us know the device you are running HOOBS on.
HOOBS SD Card image

**Comment by askovi** [comment]
Please post your logs.
Here are the instructions to retrieve the logs:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, type this command: sudo hoobs service log

**Comment by freddair** [comment]
Thanks for the instruction, here's the log which is endlessly repeating itself with only increasing process id numbers:

```
hoobs.service: Found left-over process 7940 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 7973 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 8007 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 8091 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
hoobs.service: Found left-over process 8146 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started HOOBS.
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1300:21)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
[HOOBS] Stopping server.
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 195.
Stopped HOOBS.
```

**Comment by askovi** [comment]
Run these commands in order via SSH:

sudo systemctl disable nginx

sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node

sudo reboot

**Comment by freddair** [comment]
okay, it said this:
```
hoobs@hoobszero:~ $ sudo systemctl disable nginx
Failed to disable unit: Unit file nginx.service does not exist.
hoobs@hoobszero:~ $ 
hoobs@hoobszero:~ $ sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/node
hoobs@hoobszero:~ $ 
hoobs@hoobszero:~ $ sudo reboot
```

after that, one pi zero is up and reachable again, the other one seems to be running in the log, but web interface not reachable:

```
hoobs@hoobszero:~ $ sudo hoobs service log
Started HOOBS.
HOOBS listening on port 80.
Loaded plugin 'homebridge-dummy'
[2020-11-15 11:13:23] Registering accessory 'homebridge-dummy.DummySwitch'
Loaded plugin 'homebridge-fritz-platform'
[2020-11-15 11:13:41] Registering platform 'homebridge-fritz-platform.FritzPlatform'
Loaded plugin 'homebridge-nello'
[2020-11-15 11:13:44] Registering platform 'homebridge-nello.NelloPlatform'
Loaded plugin 'homebridge-weather-plus'
[2020-11-15 11:14:02] Registering platform 'homebridge-weather-plus.WeatherPlus'
Loaded plugin 'homebridge-xiaomi-fan'
[2020-11-15 11:14:08] Registering platform 'homebridge-xiaomi-fan.xiaomifan'
Loading 4 platforms...
[WeatherPlus] Initializing WeatherPlus platform...
[WeatherPlus] Adding station with weather service OpenWeatherMap named 'Draußen'
Initializing platform accessory 'Draußen'...
[NelloPlatform] Initializing NelloPlatform platform...
[xiaomifan] Initializing xiaomifan platform...
[FritzPlatform] Initializing FritzPlatform platform...
Loading 1 accessories...
[Dummy] Initializing DummySwitch accessory...
[NelloPlatform] Configuring accessory with location ID 105d621e-f942-48be-8a1b-4b8e29ce0ef3.
[NelloPlatform] Cached accessories loaded.
[NelloPlatform] START Request: GET https://public-api.nello.io/v1/locations/
[NelloPlatform] Not signed in, requesting sign-in
[xiaomifan] Init - initializing devices
[xiaomifan] [Ralfs Ventilator] Init - got fan configuration, initializing device with name: Ralfs Ventilator
Bridge is running on port 51826.
[NelloPlatform] COMPLETE Request: GET https://public-api.nello.io/v1/locations/
External port pool ran out of ports. Fallback to random assign.
[NelloPlatform] Connecting to webhook relay service
Herthastraße 4, Berlin Camera is running on port 33025.
Please add [Herthastraße 4, Berlin Camera] manually in Home app. Setup Code: 031-45-154
[NelloPlatform] Connected to webhook backend, requesting webhook
[NelloPlatform] Updating webhook for door with ID 105d621e-f942-48be-8a1b-4b8e29ce0ef3 to https://nello.alexdev.de/callback/7639dbdc48e9cdd4baf42494aa50ae79e283b5cd071893d672f489e1f426674e.
[NelloPlatform] START Request: PUT https://public-api.nello.io/v1/locations/105d621e-f942-48be-8a1b-4b8e29ce0ef3/webhook/
[NelloPlatform] COMPLETE Request: PUT https://public-api.nello.io/v1/locations/105d621e-f942-48be-8a1b-4b8e29ce0ef3/webhook/
```

...whereas the pi 3b+ is still neither reachable and nor running:

```
hoobs@hoobs:~ $ sudo hoobs service log
Started HOOBS.
HOOBS listening on port 80.
Loaded plugin 'homebridge-dummy'
[11/15/2020, 11:12:06 AM] Registering accessory 'homebridge-dummy.DummySwitch'
Loaded plugin 'homebridge-fritz-platform'
[11/15/2020, 11:12:07 AM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
Error loading plugin "homebridge-nello"
Error: Cannot find module 'request'
Require stack:
- /home/hoobs/.hoobs/node_modules/homebridge-nello/dist/lib/APIClient.js
- /home/hoobs/.hoobs/node_modules/homebridge-nello/dist/NelloPlatform.js
- /home/hoobs/.hoobs/node_modules/homebridge-nello/dist/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-nello/dist/lib/APIClient.js:7:35)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-nello/dist/NelloPlatform.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
Loaded plugin 'homebridge-nello'
Loaded plugin 'homebridge-rpi'
[11/15/2020, 11:12:08 AM] Registering platform 'homebridge-rpi.Lib'
[11/15/2020, 11:12:08 AM] Registering platform 'homebridge-rpi.RPi'
Loaded plugin 'homebridge-webos-tv'
[11/15/2020, 11:12:08 AM] Registering platform 'homebridge-webos-tv.webostv'
Loaded plugin 'homebridge-xiaomi-fan'
[11/15/2020, 11:12:10 AM] Registering platform 'homebridge-xiaomi-fan.xiaomifan'
Loaded plugin 'homebridge-xiaomi-roborock-vacuum'
[11/15/2020, 11:12:10 AM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
Loading 6 platforms...
Error loading platform requested in your config.json at position 1
Error: The requested platform 'netatmo' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by ollieslats** [comment]
same issue for me, I change router address and hoobs just keeps looking for the pull in on restart web interface not reachable.

hope for a fix soon have a great day,
