### ISSUE TITLE
Node update to 14.15.1

### ISSUE THREAD

**Issue by Tesla-P100FX** [hoobs-org/HOOBS#914]
**Description**
The ring plug in is  having issues on the standard current node.js installed on Hoobs 3.2.10.  It no longer connects to ring stream servers.    people ho have upgraded to node 14.15.1 say it resolves the issue. Looking for an upgrade to a current Node. 

**Version**
3.2.10

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.
Chamberlan
PureCool
Harmony
Homeseer
Ring 
Wemo

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
Out install script can install Node 14 for you
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```

**Comment by marvelousmo** [comment]
> Our install script can install Node 14 for you
> 
> ```
> wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
> ```

after doing so my hoobs webinterface doesn't show anymore! I can only connect via ssh with terminal. Whats wrong?

**Comment by marvelousmo** [comment]
Ask differently: How can I go back? Sorry, I am quite a newbie..

**Comment by marvelousmo** [comment]
Error: The module '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
hoobs.service: Main process exited, code=exited, status=1/FAILURE
hoobs.service: Failed with result 'exit-code'.
hoobs.service: Service RestartSec=3s expired, scheduling restart.
hoobs.service: Scheduled restart job, restart counter is at 111.
Stopped HOOBS.
Started HOOBS.
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/api.js
- /usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js
- /usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js
- /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/index.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/scripts/loader.js',
    '/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs'
  ]
}
/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

**Comment by mkellsy** [comment]
You can access the terminal via ssh.

On Mac or Linux terminal
```
ssh hoobs@hoobs.local
```

The password is hoobsadmin

On Windows you need to use Putty

Once logged in run these commands
```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm  @hoobs/hoobs
```

This will trigger a rebuild.

**Comment by marvelousmo** [comment]
Thank you!

**Comment by mastrigt** [comment]
Same problem, same error here. Thank you Tesla-P100FX, your commands solved it!

**Comment by Tesla-P100FX** [comment]
Just so everyone knows Ring 💍 is having a major outage this morning IOS ring app not streaming

**Comment by leehord** [comment]
> Just so everyone knows Ring 💍 is having a major outage this morning IOS ring app not streaming

Would this also affect simply installing the Ring plugin? When I install the Ring plugin it kills the bridge service.

> 25/11/2020, 16:34:06 Plugin "homebridge-ring" installed.
25/11/2020, 16:34:06 Got SIGINT, shutting down Bridge...
25/11/2020, 16:34:10 Loaded plugin 'homebridge-pihole'
25/11/2020, 16:34:10 [11/25/2020, 4:34:10 PM] Registering accessory 'homebridge-pihole.Pihole'
25/11/2020, 16:34:10 Error loading plugin "homebridge-ring"
25/11/2020, 16:34:10 TypeError: Cannot assign to read only property 'toString' of object '#<Object>'
    at Object.<anonymous> (/private/var/root/.hoobs/node_modules/ip/lib/ip.js:63:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/private/var/root/.hoobs/node_modules/stun/src/node_modules/attributes/stun-address-attribute.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/private/var/root/.hoobs/node_modules/stun/src/node_modules/lib/attributes.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
25/11/2020, 16:34:10 Loaded plugin 'homebridge-ring'
25/11/2020, 16:34:10 Error loading plugin "homebridge-vieramatic"
25/11/2020, 16:34:10 TypeError: Cannot assign to read only property 'toString' of object '#<Cancel>'
    at Object.<anonymous> (/private/var/root/.hoobs/node_modules/homebridge-vieramatic/node_modules/axios/lib/cancel/Cancel.js:13:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/private/var/root/.hoobs/node_modules/homebridge-vieramatic/node_modules/axios/lib/axios.js:40:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/private/var/root/.hoobs/node_modules/homebridge-vieramatic/node_modules/axios/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
25/11/2020, 16:34:10 Loaded plugin 'homebridge-vieramatic'
25/11/2020, 16:34:10 Loading 2 platforms...
25/11/2020, 16:34:10 Error loading platform requested in your config.json at position 1
25/11/2020, 16:34:10 Error: The requested platform 'PanasonicVieraTV' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
25/11/2020, 16:34:10 Got SIGTERM, shutting down Bridge...

**Comment by shellyman** [comment]
I also have this problem, unfortunately the sudo command under shh does not work for me either
hoobs@hoobs:~ $ sudo npm uninstall -g @hoobs/hoobs
sudo: npm: command not found

**Comment by mkellsy** [comment]
You node install is hosed.
This might recover Node and NPM for you
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts
```
