### ISSUE TITLE
HOOBS 3.3.1 Service name is already in use on the network

### ISSUE THREAD

**Issue by mariusstrom** [hoobs-org/HOOBS#938]
**Description**
When starting HOOBS Bridge, an error appears in the log:
```log
11/30/2020, 3:36:08 PM Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
11/30/2020, 3:36:08 PM Got SIGTERM, shutting down Bridge...
```

**Version**
HOOBS 3.3.1
Node 14.15.1
Raspbian buster 5.4.72-v7l+

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Previous version**
from 3.2.9, also upgraded node from 12.x to 14.x

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
homebridge-hue
homebridge-keylights
homebridge-nest
homebridge-purpleair-sensor
homebridge-xbox-tv

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

```json
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYH96D",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "[MASKED]",
        "latitude": "[MASKED]",
        "longitude": "[MASKED]"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "[MASKED]",
        "username": "[MASKED]"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "PurpleAirSensor",
            "plugin_map": {
                "plugin_name": "homebridge-purpleair-sensor"
            },
            "conversion": "None",
            "name": "PurpleAir Outdoor Sensor",
            "sensor": 76605,
            "averages": "realtime",
            "updateIntervalSecs": 600
        }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "name": "Nest",
            "access_token": "[MASKED]",
            "options": [
                "HomeAway.Disable",
                "Thermostat.Eco.Disable",
                "Thermostat.Fan.Disable",
                "Thermostate.SeparateBuiltInHumiditySensor.Enable"
            ]
        },
        {
            "platform": "Hue",
            "name": "Hue",
            "users": {
                "[MASKED]": "[MASKED]"
            },
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "sensors": false,
            "anyOn": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": false,
            "groups": false,
            "group0": false,
            "hueDimmerRepeat": false,
            "lights": true,
            "rooms": false
        },
        {
            "platform": "ElgatoKeyLights",
            "plugin_map": {
                "plugin_name": "homebridge-keylights"
            },
            "name": "Elgato Key Lights",
            "switchOnDurationMs": 100,
            "powerOnBehavior": 1,
            "powerOnBrightness": 20,
            "powerOnTemperature": 4695,
            "switchOffDurationMs": 300,
            "colorChangeDurationMs": 100
        },
        {
            "platform": "XboxTv",
            "plugin_map": {
                "plugin_name": "homebridge-xbox-tv"
            },
            "devices": [
                {
                    "name": "Xbox One",
                    "host": "[MASKED]",
                    "xboxliveid": "[MASKED]",
                    "refreshInterval": 5,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Dashboard",
                            "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                            "type": "HOME_SCREEN"
                        },
                        {
                            "name": "YouTube",
                            "reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Netflix",
                            "reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Amazon Prime",
                            "reference": "AmazonVideo.AmazonVideoUK_pwbj9vvecjh7j!App",
                            "type": "APPLICATION"
                        }
                    ],
                    "manufacturer": "Microsoft",
                    "modelName": "Xbox One X",
                    "serialNumber": "[MASKED]",
                    "firmwareRevision": "Firmware Revision"
                }
            ]
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
11/30/2020, 3:36:07 PM Loaded plugin 'homebridge-hue'
11/30/2020, 3:36:08 PM [11/30/2020, 3:36:07 PM] Registering platform 'homebridge-hue.Hue'
11/30/2020, 3:36:08 PM Loaded plugin 'homebridge-keylights'
11/30/2020, 3:36:08 PM [11/30/2020, 3:36:08 PM] Registering platform 'homebridge-keylights.ElgatoKeyLights'
11/30/2020, 3:36:08 PM Loaded plugin 'homebridge-nest'
11/30/2020, 3:36:08 PM [11/30/2020, 3:36:08 PM] Registering platform 'homebridge-nest.Nest'
11/30/2020, 3:36:08 PM Loaded plugin 'homebridge-purpleair-sensor'
11/30/2020, 3:36:08 PM [11/30/2020, 3:36:08 PM] Registering accessory 'homebridge-purpleair-sensor.PurpleAirSensor'
11/30/2020, 3:36:08 PM Loaded plugin 'homebridge-xbox-tv'
11/30/2020, 3:36:08 PM [11/30/2020, 3:36:08 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
11/30/2020, 3:36:08 PM Loading 4 platforms...
11/30/2020, 3:36:08 PM [Nest] Initializing Nest platform...
11/30/2020, 3:36:08 PM [Hue] Initializing Hue platform...
11/30/2020, 3:36:08 PM [Hue] config.json: warning: plugin_map: ignoring unknown key
11/30/2020, 3:36:08 PM [Hue] homebridge-hue v0.12.3, node v14.15.1, homebridge v1.1.6
11/30/2020, 3:36:08 PM [Elgato Key Lights] Initializing ElgatoKeyLights platform...
11/30/2020, 3:36:08 PM [XboxTv] Initializing XboxTv platform...
11/30/2020, 3:36:08 PM Loading 1 accessories...
11/30/2020, 3:36:08 PM [PurpleAir Outdoor Sensor] Initializing PurpleAirSensor accessory...
11/30/2020, 3:36:08 PM [PurpleAir Outdoor Sensor] Initializing PurpleAirSensor PurpleAir Outdoor Sensor 76605 update every 600000 ms using realtime averages and None conversion
11/30/2020, 3:36:08 PM [Elgato Key Lights] Loading accessory from cache: Elgato Key Light 6F41
11/30/2020, 3:36:08 PM [Nest] Fetching Nest devices.
11/30/2020, 3:36:08 PM External port pool ran out of ports. Fallback to random assign.
11/30/2020, 3:36:08 PM Xbox One is running on port 44957.
11/30/2020, 3:36:08 PM Please add [Xbox One] manually in Home app. Setup Code: [MASKED]
11/30/2020, 3:36:08 PM Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
11/30/2020, 3:36:08 PM Got SIGTERM, shutting down Bridge...
11/30/2020, 3:36:09 PM [Hue] searching bridges and gateways
11/30/2020, 3:36:11 PM [Hue] goodbye
```

**Comment by mkellsy** [comment]
Do you have multiple HOOBS or Homebridge devices? You may need to regenerate the username and change the bridge name in the bridge settings.

**Comment by mariusstrom** [comment]
Nope, just the one device. I've regenerated the username and changed the bridge name ("Service Name" under Configuration -> Apple Home, just to make sure we're talking about the same thing) and the error persists.

**Comment by askovi** [comment]
Try doing Reset Connection from the top right menu -> help then rescan the new QR code on the dashboard.

**Comment by mariusstrom** [comment]
@askovi no joy, did Reset Connection (which removed the persist directory) and tried to start which resulted in the same errors in the logs.

**Comment by askovi** [comment]
Have you tried rebooting from the top right menu?

**Comment by mariusstrom** [comment]
@askovi ... yes, the system has been power cycled many times in the course of debugging this. :)

**Comment by mariusstrom** [comment]
Surgery has started and I've removed all plugins and Bridge is back up. Adding plugins one-by-one, and when I re-add the homebridge-xbox-tv plugin things go sideways... so good news is I have a repro!

**Comment by mariusstrom** [comment]
Ok, all prior plugins up and fully operational (phew!) and only the homebridge-xbox-tv plugin causes this issue. Any reason why the homebridge-xbox-tv can cause the the bridge to go belly up?

**Comment by mkellsy** [comment]
I see. The plugin is making a separate bridge for the XBox. It looks like it is running on port 44957. I also don't see anything in the config for renaming it.

Good news is we have a target plugin for testing.
