### ISSUE TITLE
ETIMEDOUT while connecting on HOOBS Homebridge

### ISSUE THREAD

**Issue by wavi-web** [hoobs-org/HOOBS#974]
**Description**
At startup the plugin should connect to Homeseer4 through the json url. For Homeseer3 it works just fine, but Homeseer4 gives a ETIMEDOUT error. The HOOBS service stops. 
The json url give correct reponse when entered in al browser. Plugin developer says the problem is in de HOOBS domain. 

**Expected behavoir**
Connect to Homeseer3 or Homeseer4 json url.

**Plugin name**
Homebridge-HomeSeer4.

**Please report the issue to the plugin developer**
https://github.com/jvmahon/Homebridge-HomeSeer4/issues/

**Version**
3.3.1.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x ] Yes, but HS4 connection never worked, problem sustains since several updates. 
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.
N/A.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [x ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY4KP1",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "BE",
        "postal_code": "3900"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "6E:02:81:EA:0D:D1"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "HomeSeer",
            "plugin_map": {
                "plugin_name": "homebridge-homeseer4"
            },
            "name": "HomeSeer",
            "host": "http://192.168.1.10",
            "ASCIIport": 11000,
            "login": "hoobs",
            "password": "homebridge",
            "Lightbulbs": [
                799,
                800
            ]
        }
    ]
}```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
18-12-2020 14:37:18 [HomeSeer] Initializing HomeSeer platform...18-12-2020 14:37:18 [HomeSeer] Start18-12-2020 14:37:19 [HomeSeer] End18-12-2020 14:37:19 [HomeSeer] Checking Configuration Data18-12-2020 14:37:19 Creating HomeKit devices from HomeSeer data.18-12-2020 14:37:19 Initializing platform accessory 'JowiHue Prikspot 1'...18-12-2020 14:37:19 Initializing platform accessory 'JowiHue Prikspot 2'...18-12-2020 14:37:19 [HomeSeer] Host for ASCII Interface set to: 192.168.1.10 at port 1100018-12-2020 14:37:19 Bridge is running on port 51826.18-12-2020 14:37:19 [HomeSeer] Successfully connected to ASCII Control Interface of HomeSeer.18-12-2020 14:37:19 [HomeSeer] Sent Authorization Data18-12-2020 14:37:19 [HomeSeer] Successfully authorized Telnet port18-12-2020 14:45:17 [HomeSeer] * Warning * - Unable to connect to HomeSeer ASCII Port: 11000. Fatal error.18-12-2020 14:45:17 [HomeSeer] To enable ASCII Port, see WIKI "Enable the HomeSeer ASCII Commands Interface Port" entry18-12-2020 14:45:17 [HomeSeer] * Warning * - ASCII Port closed - Critical Failure!. Restart system if failure continues.18-12-2020 14:45:47 [HomeSeer] Attempting to re-start ASCII Port Interface, Attempt: 218-12-2020 14:46:05 Got SIGINT, shutting down Bridge...18-12-2020 14:46:10 Loaded plugin 'homebridge-homeseer4'18-12-2020 14:46:10 homebridge API version: 2.618-12-2020 14:46:10 [12/18/2020, 6:46:10 AM] Registering platform 'homebridge-homeseer4.HomeSeer'18-12-2020 14:46:10 Loading 1 platforms...18-12-2020 14:46:10 [HomeSeer] Initializing HomeSeer platform...18-12-2020 14:46:10 [HomeSeer] Start18-12-2020 14:46:42 (node:22435) UnhandledPromiseRejectionWarning: FetchError: request to http://hoobs:homebridge@192.168.1.10/JSON?request=getstatus failed, reason: connect ETIMEDOUT 192.168.1.10:8018-12-2020 14:46:42 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)18-12-2020 14:46:42 at ClientRequest.emit (events.js:310:20)18-12-2020 14:46:42 at Socket.socketErrorListener (_http_client.js:426:9)18-12-2020 14:46:42 at Socket.emit (events.js:310:20)18-12-2020 14:46:42 at emitErrorNT (internal/streams/destroy.js:92:8)18-12-2020 14:46:42 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)18-12-2020 14:46:42 at processTicksAndRejections (internal/process/task_queues.js:84:21)18-12-2020 14:46:42 (node:22435) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)18-12-2020 14:46:42 (node:22435) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Additional context**

**Comment by wavi-web** [comment]
I really hope someone can help me. The reason I bought HOOBS is the community and support....
