### ISSUE TITLE
GSH not working

### ISSUE THREAD

**Issue by Mdonci** [hoobs-org/HOOBS#997]
**Description**
I set up the system with my custom Raspberry Pi install, the system seems to be working, but I can't link the Google Assistant app to the Homebridge

**Expected behavoir**
There should be a connection between Hoobs and Google Assistant

**Plugin name**
Google Assistant + Homebridge skill

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

**Version**
3.3.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
This is running on a Raspberry Pi, img from Hoobs' website

**Post your config**

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYF5M0",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "HU",
        "postal_code": "1097"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "C9:45:14:F6:87:62"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "AlexaPlayer",
            "plugin_map": {
                "plugin_name": "homebridge-alexa-player"
            }
        },
        {
            "platform": "Alexa",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "name": "Alexa",
            "routines": true,
            "blind": true,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "username": "dvdmanco",
            "password": "Chop[[per4",
            "pin": "031-45-154"
        },
        {
            "platform": "google-smarthome",
            "plugin_map": {
                "plugin_name": "homebridge-gsh"
            },
            "name": "Google Smart Home",
            "notice": "Keep your token a secret!",
            "token": "",
            "debug": true
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
1/1/2021, 5:48:48 PM HOOBS listening on port 80.
1/1/2021, 5:49:37 PM Loaded plugin 'homebridge-alexa'
1/1/2021, 5:49:38 PM [1/1/2021, 5:49:37 PM] Registering platform 'homebridge-alexa.Alexa'
1/1/2021, 5:49:39 PM Loaded plugin 'homebridge-alexa-player'
1/1/2021, 5:49:39 PM [1/1/2021, 5:49:39 PM] Registering platform 'homebridge-alexa-player.AlexaPlayer'
1/1/2021, 5:49:40 PM Loaded plugin 'homebridge-gsh'
1/1/2021, 5:49:40 PM Loading 3 platforms...
1/1/2021, 5:49:40 PM [1/1/2021, 5:49:40 PM] Registering platform 'homebridge-gsh.google-smarthome'
1/1/2021, 5:49:40 PM [AlexaPlayer] Initializing AlexaPlayer platform...
1/1/2021, 5:49:40 PM [AlexaPlayer] Running homebridge-alexa-player-v0.4.1 with homebridge-v1.1.6 on node-v14.15.1.
1/1/2021, 5:49:41 PM [AlexaPlayer] Error: Configuration error: config should NOT have additional properties
    at AlexaPlatformPlugin.validateConfig (/home/hoobs/.hoobs/node_modules/homebridge-alexa-player/lib/alexaPlatformPlugin.js:105:19)
    at new AlexaPlatformPlugin (/home/hoobs/.hoobs/node_modules/homebridge-alexa-player/lib/alexaPlatformPlugin.js:41:22)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
1/1/2021, 5:49:41 PM [Alexa] Initializing Alexa platform...
1/1/2021, 5:49:41 PM [Alexa] homebridge-alexa v0.5.22, node v14.15.1, homebridge v1.1.6
1/1/2021, 5:49:41 PM Initializing platform accessory 'Alexa'...
1/1/2021, 5:49:41 PM [Google Smart Home] Initializing google-smarthome platform...
1/1/2021, 5:49:54 PM Bridge is running on port 51826.
1/1/2021, 5:49:56 PM [Google Smart Home] Waiting 15 seconds before starting instance discovery...
1/1/2021, 5:49:57 PM [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
1/1/2021, 5:50:02 PM [Alexa] alexaDiscovery - returned 1 devices
1/1/2021, 5:50:11 PM 2021-01-01T16:50:11.168Z hapNodeJSClient Starting Homebridge instance discovery
1/1/2021, 5:50:11 PM 2021-01-01T16:50:11.294Z hapNodeJSClient HAP Device discovered HOOBS 09FE
1/1/2021, 5:50:11 PM 2021-01-01T16:50:11.307Z hapNodeJSClient HAP Device address HOOBS 09FE ->  {
1/1/2021, 5:50:11 PM host: '192.168.1.78',
1/1/2021, 5:50:11 PM port: 51826,
1/1/2021, 5:50:11 PM url: 'XXXXX',
1/1/2021, 5:50:11 PM deviceID: 'XXXXX',
1/1/2021, 5:50:11 PM txt: {
1/1/2021, 5:50:11 PM md: 'HOOBS',
1/1/2021, 5:50:11 PM pv: '1.1',
1/1/2021, 5:50:11 PM id: 'XXXXX',
1/1/2021, 5:50:11 PM 'c#': '4',
1/1/2021, 5:50:11 PM 's#': '1',
1/1/2021, 5:50:11 PM ff: '0',
1/1/2021, 5:50:11 PM ci: '2',
1/1/2021, 5:50:11 PM sf: '0',
1/1/2021, 5:50:11 PM sh: '5E5GVQ=='
1/1/2021, 5:50:11 PM }
1/1/2021, 5:50:11 PM }
1/1/2021, 5:50:11 PM 2021-01-01T16:50:11.602Z hapNodeJSClient HAP Device discovered Philips hue - 11C860
1/1/2021, 5:50:11 PM 2021-01-01T16:50:11.616Z hapNodeJSClient HAP Device address Philips hue - 11C860 ->  {
1/1/2021, 5:50:11 PM host: '192.168.1.69',
1/1/2021, 5:50:11 PM port: 8080,
1/1/2021, 5:50:11 PM url: 'http://192.168.1.69:8080',
1/1/2021, 5:50:11 PM deviceID: 'D5:B4:90:61:3B:D8',
1/1/2021, 5:50:11 PM txt: {
1/1/2021, 5:50:11 PM 'c#': '6',
1/1/2021, 5:50:11 PM ff: '1',
1/1/2021, 5:50:11 PM id: 'D5:B4:90:61:3B:D8',
1/1/2021, 5:50:11 PM md: 'BSB002',
1/1/2021, 5:50:11 PM pv: '1.1',
1/1/2021, 5:50:11 PM sf: '0',
1/1/2021, 5:50:11 PM 's#': '29',
1/1/2021, 5:50:11 PM ci: '2'
1/1/2021, 5:50:11 PM }
1/1/2021, 5:50:11 PM }
1/1/2021, 5:50:11 PM 2021-01-01T16:50:11.912Z hapNodeJSClient HAP Discover failed BSB002 -> http://192.168.1.69:8080 invalid PIN or homebridge is not running in insecure mode with -I
1/1/2021, 5:50:11 PM 2021-01-01T16:50:11.989Z hapNodeJSClient Homebridge instance discovered HOOBS with 2 accessories
1/1/2021, 5:50:21 PM 2021-01-01T16:50:21.204Z hapNodeJSClient Ready
1/1/2021, 5:50:21 PM [Google Smart Home] Finished instance discovery
1/1/2021, 5:50:36 PM [Google Smart Home] Sending Sync Request
1/1/2021, 5:52:23 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:23 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "7180197023611178016"
    }
  ],
  "requestId": "7180197023611178016"
}
1/1/2021, 5:52:23 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:24 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:24 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "12850857241160318114"
    }
  ],
  "requestId": "12850857241160318114"
}
1/1/2021, 5:52:24 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:25 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:25 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "3811772094577291240"
    }
  ],
  "requestId": "3811772094577291240"
}
1/1/2021, 5:52:25 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:26 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:26 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "7215290624768534672"
    }
  ],
  "requestId": "7215290624768534672"
}
1/1/2021, 5:52:26 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:26 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:26 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "12050959708847472609"
    }
  ],
  "requestId": "12050959708847472609"
}
1/1/2021, 5:52:26 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:27 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:27 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "10890211396517452994"
    }
  ],
  "requestId": "10890211396517452994"
}
1/1/2021, 5:52:27 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:28 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:28 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "9249024176817452662"
    }
  ],
  "requestId": "9249024176817452662"
}
1/1/2021, 5:52:28 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:29 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:29 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "10787163272452621757"
    }
  ],
  "requestId": "10787163272452621757"
}
1/1/2021, 5:52:29 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:30 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:30 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "13330901967145700146"
    }
  ],
  "requestId": "13330901967145700146"
}
1/1/2021, 5:52:30 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:31 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:31 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "8940786934086532151"
    }
  ],
  "requestId": "8940786934086532151"
}
1/1/2021, 5:52:31 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:32 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:32 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "16644073430530868572"
    }
  ],
  "requestId": "16644073430530868572"
}
1/1/2021, 5:52:32 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:33 PM [Google Smart Home] Received SYNC intent
1/1/2021, 5:52:33 PM [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "15652588854616530035"
    }
  ],
  "requestId": "15652588854616530035"
}
1/1/2021, 5:52:33 PM [Google Smart Home] No supported devices found. See https://git.io/JfuHW
1/1/2021, 5:52:33 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:34 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:35 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:36 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:36 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:37 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:38 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:39 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:40 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:41 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:42 PM [Google Smart Home] Sending full post-sync state report
1/1/2021, 5:52:43 PM [Google Smart Home] Sending full post-sync state report
```

**Additional context**

**Comment by askovi** [comment]
Google Home seems to be linked just fine according to your logs. However you have no devices to expose to it. HOOBS can only expose other devices you linked through HOOBS via other plugins to Google Home.

**Comment by icodetheworld** [comment]
I'm having Smitch devices in my google home. these devices are mostly light bulbs, I"m still getting the same issue here also
